### ISSUE TITLE
发现个问题 bottomNav active

### ISSUE THREAD

**Issue by peirancao** [museui/muse-ui#10]
当 value 的值来自 data 没问题

改成 computed 就不 active 了

**Comment by myronliu347** [comment]
对这个 active 被废弃了，使用 value

**Comment by peirancao** [comment]
用的就是 value 在 data 里定义没问题 在 computed里 就不行了。。

**Comment by myronliu347** [comment]
就是开始的时候必须有个默认值啊

**Comment by myronliu347** [comment]
现在不定义在data里的不会被watch

**Comment by myronliu347** [comment]
我也想向你问个问题，最近准备整官网，不知道怎么样会好看点。。

**Comment by peirancao** [comment]
@myronliu347 这类官网基本都差不多 可以多参考下其它类似官网（不过感觉 体验都不太好） 个人感觉 这类官网 要 界面简洁 内容为主 体验友好

**Comment by peirancao** [comment]
大体结构都差不多 主页 介绍  + 导航菜单  简洁美观就好  关键是文档 界面 要体验好  😄

**Comment by peirancao** [comment]
看到主页 可以引起我想看文档的冲动 看到文档就决定使用它 嘿嘿。。

**Comment by peirancao** [comment]
找到原因了 是我的 computed 返回的值不是 Number 类型的 转换了下可以了。。
