### ISSUE TITLE
loadMore 移动端  下拉刷新报错

### ISSUE THREAD

**Issue by likaixuan** [museui/muse-ui#1006]
报错如下:
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>
 ```
在官方文档demo页上切到手机预览，也会报错，不能禁止 touch-action: none;  这样会造成 容器无法滚动

**Comment by zangxx66** [comment]
已更新3.0.0-rc5，下拉刷新还是会报错`Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

**Comment by weiyunpeng** [comment]
3.0.1版本，报错：RefreshControl.js?e8c2:135 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by weiyunpeng** [comment]
解决方法：
this.handlePrevent = function (event) {
        if (_this.draging && _this.y > 0) null;
      };

将event.preventDefault()改为null

**Comment by weizhanzhan** [comment]
> 解决方法：
> this.handlePrevent = function (event) {
> if (_this.draging && _this.y > 0) null;
> };
> 
> 将event.preventDefault()改为null

你这个是加在哪的
