### ISSUE TITLE
建议alert这样的弹窗能不能实现多个实例（不知道表述的真不正确）

### ISSUE THREAD

**Issue by AprilLemon** [museui/muse-ui#1017]
如题，就是类似element这样的，几次alert就弹几次窗口。

**Comment by myronliu347** [comment]
看看这个插件， 是否可以解决你的问题
https://github.com/museui/muse-ui-message

**Comment by AprilLemon** [comment]
@myronliu347  谢谢作者哈。已down下来，把我自己写的插件替换下。
