### ISSUE TITLE
[Bug] mu-list-item的active-class属性受$router.replace事件影响

### ISSUE THREAD

**Issue by yrfandrew** [museui/muse-ui#1028]
```html
<template>
  <mu-list :value="selected">
    <mu-list-item active-class"selected" :to="{ name: 'aa' }" value="abc">
      <mu-list-item-title>ABC</mu-list-item-title>
    </mu-list-item>
  </mu-list>
</template>
<script>
export default {
  name: 'test',
  data () {
    return {
      selected: 'abc'
    }
  }
}
</script>
``` 

执行语句 `this.$router.replace({ name: this.$route.name, params: { page: page } })` 后，标签 `<a class="mu-item-wrapper" />` 缺少了 `router-link-exact-active selected` 样式，变成了非选中状态。

**Comment by myronliu347** [comment]
可否编写一个简单在线示例呢 http://jsfiddle.net/
方便我解决这个问题

**Comment by yrfandrew** [comment]
很抱歉，我还不会用 http://jsfiddle.net/ 写 vue 项目 demo。
所以录制了一段屏幕操作...
![gif](http://p4zwrzcg2.bkt.clouddn.com/person/screencast-localhost-8080-2018.06.29-09-31-16.gif)

**Comment by myronliu347** [comment]
这个并非是组件本身的问题，而是路由匹配的不对，所以才没有相应的样式添加
https://jsfiddle.net/8xrk1n9f/1013/
https://router.vuejs.org/zh/api/#active-class
录屏里我看不到 url的变化， 和你的router 的配置代码
