### ISSUE TITLE
[Bug] mu-dialog 组件叠加的问题

### ISSUE THREAD

**Issue by yrfandrew** [museui/muse-ui#1031]
先上一段代码

```html
<!-- List -->
<template>
<div>
  <router-link :to="{ name: 'Detail', params: { id: '1' } }">1</router-link>
  <router-link :to="{ name: 'Detail', params: { id: '2' } }">2</router-link>
</div>
</template>

<!-- Detail -->
<template>
<div>
  <router-view />
  <confirm keyId='DELETE' />
</div>
</template>
```
代码中 `confirm` 即为 `mu-dialog` 组件。
由 `List` 通过链接进入 `Detail`。
用不同的id进入 `Detail` ，并唤起 `confirm` 组件，会发现 `mu-dialog` 组件出现叠加。

**Comment by myronliu347** [comment]
请给出具体的唤起confirm的逻辑

**Comment by yrfandrew** [comment]
操作流程：
从 `List` 点击链接进入 `Detail` --> 在 `Detail` 点击按钮唤起 `confirm` 组件 --> 关闭 `confirm` 组件 --> 回到 `List` ，点击另一个链接进入 `Detail` --> 在 `Detail` 点击按钮唤起 `confirm` 组件

在最后一个步骤时，可以发现出现下图的情况：
![image](https://user-images.githubusercontent.com/4082323/42074579-768f4136-7b9f-11e8-9942-2952281d586b.png)

**Comment by myronliu347** [comment]
这样的描述，我没法定位问题的。， 提供下 `confirm` 和 `detail` 的源码

**Comment by myronliu347** [comment]
直接在最外层使用的话可以设置下 `append-body`
```html
<mu-dialog :append-body="false">
</mu-dialog>
```

另外快捷弹窗可以使用 插件
https://github.com/museui/muse-ui-message
