### ISSUE TITLE
有适用于ios的类mu-select组件吗

### ISSUE THREAD

**Issue by Jarvis-zhuang** [museui/muse-ui#1042]
在ios上readonly属性会失效,但是我看了3.0好像没有mu-select的优秀替换方案
想请问一下作者当时是怎么看待这个问题的,有啥解决办法吗?

**Comment by Jarvis-zhuang** [comment]
之前2.0的时候 用mu-dropDown-menu,用得太爽了.现在3.0一时不知道怎们办了

**Comment by myronliu347** [comment]
Menu 组件了解一下
https://muse-ui.org/#/zh-CN/menu
