### ISSUE TITLE
[Feature] 为 mu-atuo-complete 增加 slot，方便自定义结果popover的内容

### ISSUE THREAD

**Issue by yrfandrew** [museui/muse-ui#1046]
建议为 `mu-atuo-complete` 增加 slot，方便自定义结果popover的内容。如下图的展现...

![screenshot-mail google com-2018 07 05-12-10-16](https://user-images.githubusercontent.com/4082323/42302332-ea7ef878-804c-11e8-9c95-e757cdf77b92.png)

**Comment by myronliu347** [comment]
现在有的哦， 可以参考官网搜索框的定制
https://github.com/museui/muse-ui/blob/master/docs/src/components/search.js
