### ISSUE TITLE
找不到组件mu-container mu-loadmore, 

### ISSUE THREAD

**Issue by enotsl** [museui/muse-ui#1048]
[Vue warn]: Unknown custom element: <mu-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[Vue warn]: Unknown custom element: <mu-load-more> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

已全局安装使用，node_modules\muse-ui\src 里没有container 和loadmore 文件夹， 但是重新安装后还是没有

**Comment by myronliu347** [comment]
注意muse-ui 的版本，现在是有的

**Comment by svygh123** [comment]
现在确实没有，请问怎么解决？

**Comment by My-Zzw** [comment]
有些插件或者组件有 mu-container。比如插件Grid。把他引入，Grid 里面有 mu-container
