### ISSUE TITLE
1049BUG验证未解决

### ISSUE THREAD

**Issue by 7040210** [museui/muse-ui#1052]
<mu-date-input type="dateTime"/>组件，在操作的时候，选择完日期就会触发验证，此时应该不触发验证，因为还要选择时间，但是在选择完时间后，又没触发验证，造成提示了一个错误的验证信息，并且无法去除。

**Comment by myronliu347** [comment]
现在选择完成之后会触发验证的哦

**Comment by 7040210** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

重新测试发现问题依旧，附件是我录制的一个操作过程。你验证下，感谢！

    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    


                


    在2018年7月10日 12:56，myron<notifications@github.com> 写道： 


Closed #1052.
