### ISSUE TITLE
mu-button如何添加点击事件

### ISSUE THREAD

**Issue by qfwfqf** [museui/muse-ui#1053]
`<mu-appbar style="width: 100%;" color="primary">
    <mu-button icon slot="left" v-if="back" event="goBack">
      <mu-icon value="arrow_back_ios"></mu-icon>
      <span>返回</span>
    </mu-button>
    <span>{{title}}</span>
  </mu-appbar>`

mu-button的点击事件如何添加？根据文档说明加个值为String/Array的event属性？

**Comment by myronliu347** [comment]
@click=""

**Comment by zhangyj1992** [comment]
电脑键盘回车时，会触发两次click事件
