### ISSUE TITLE
mu-date-input 的 change 事件 ,每选择一次日期就会累加触发

### ISSUE THREAD

**Issue by ligoudan1991** [museui/muse-ui#1056]
<mu-date-input v-model="testDate" @change ="testDateChange"></mu-date-input>
change 事件和input事件 每选择一次日期就会累加触发

**Comment by myronliu347** [comment]
逻辑是这样的，每次选择日期之后会触发 
change事件和
input事件 ， 

input事件是为了兼容 `v-model`的使用

**Comment by ligoudan1991** [comment]
@myronliu347 可能是我没有描述清楚,是这样的,比如:在选择4次日期之后,在第5次,我绑定的testDateChange 会执行5次,

**Comment by ligoudan1991** [comment]
我把源码中 DateInput.js中的 this.$emit('change', value);  改成 this.$emit('change1', value); 就能正常使用;

**Comment by myronliu347** [comment]
下次bug，记得写下在线的demo， 这样方便定位问题，

**Comment by myronliu347** [comment]
fixed: rc.6
