### ISSUE TITLE
mu-icon不显示

### ISSUE THREAD

**Issue by andyComeOn** [museui/muse-ui#1062]
官网上给的demo <mu-icon value="close"></mu-icon> ，添加到代码中是不能显示出来icon，只是回以斜体的方式显示出来。

**Comment by myronliu347** [comment]
需要引入字体图标的样式， 国内cdn 在这里
<link rel="stylesheet" href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css">

github 仓库在这https://github.com/google/material-design-icons
