### ISSUE TITLE
using "SnackBar" in opened "Bottom Sheet" dialog cause overlay disappear

### ISSUE THREAD

**Issue by AaaCabbage** [museui/muse-ui#1063]
See below example and click `open bottom sheet` -> click `star item` -> click dialog `ok` button
[jdfiddle](https://jsfiddle.net/AaaCabbage/hr5pn286)

**Comment by myronliu347** [comment]
Thanks, I will fixed, please wait...

**Comment by myronliu347** [comment]
fixed: rc.6
https://jsfiddle.net/hr5pn286/5/
