### ISSUE TITLE
Date inpurt 的value-formate

### ISSUE THREAD

**Issue by Zone-F** [museui/muse-ui#1065]
value-formate=“yyyy-MM-dd”这样子绑定格式后，被绑定的值就乱码了
`      <mu-date-input  icon="today" label="开始日期" v-model="form.begDate" type="date" label-float full-width value-format="yyyy—MM-dd"></mu-date-input>
`

**Comment by myronliu347** [comment]
YYYY-MM-DD
日期格式参照这个来 
https://github.com/iamkun/dayjs
