### ISSUE TITLE
mu-bottom-navigation 数据双向绑定的时候，动态改变value，mu-bottom-navigation没有跟着选中

### ISSUE THREAD

**Issue by 547377507** [museui/muse-ui#1067]
mu-bottom-navigation 数据双向绑定的时候，动态改变value，mu-bottom-navigation没有跟着选中
或者说我在页面上进行路由跳转的时候，如何设置mu-bottom-navigation项动态active，路由改变后，并没有改变？

**Comment by myronliu347** [comment]
fixed: in https://github.com/museui/muse-ui/pull/1014/commits/486c65260839c04bd247b39a07b5a85f4c9ad294
