### ISSUE TITLE
请问mu-bottom-nav-item中怎么使用第三方ICON呢？

### ISSUE THREAD

**Issue by qdchenyixuan** [museui/muse-ui#1073]
Google ICON中有一个需要的图标没有，感谢作者大大！

**Comment by myronliu347** [comment]
首先引入你需要的icon资源

然后需要使用icon的部分， 添加 `:` 前缀, 像这样

```html
 <mu-icon size="36" value=":mudocs-icon-custom-github"></mu-icon>
```

**Comment by qdchenyixuan** [comment]
再次感谢，报一个文档的小错误：https://muse-ui.org/#/zh-CN/date-input  中“不同的显示方式”演示代码第四行多写了一遍ICON
