### ISSUE TITLE
2.0版本mu-picker，修改slots里的values时会报错

### ISSUE THREAD

**Issue by queee03** [museui/muse-ui#1074]
需要用到mu-picker做地址联动，联动过程中需要修改slots里对应对象里的values，但是一旦修改会报以下错误。但我的组件中并没有引入props。
> Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

**Comment by myronliu347** [comment]
可否提供一下使用的代码

**Comment by queee03** [comment]
HTML部分
> <mu-picker :slots="addressSlots" :values="address" :visible-item-count="5" @change="addressChange" />

JS关键部分
> 
> let obj={
>     "110000": "某某市",
>     "120000": "某市",
>     ……
> };
> export default {
>     data () {
>       return {
>         addressSlots: [
>           {
>             width: '100%',
>             textAlign: 'right',
>             values: ['北京','天津']
>           }, 
>           {
>             width: '100%',
>             textAlign: 'left',
>             values: []
>           }
>         ],
>         address: [],
>       }
>     },
>     methods: {
>       addressChange(value, index){
>         switch (index) {
>           case 0:
>             let arr=[];
>             //以obj作为原始数据，对arr做处理，得到arr=["某某市","某市"];
>             ……
>             this.addressSlots[1].values = arr //运行此句时报上述错误
>             break
>           case 1:
>             ……
>             break
>         }
>       }
>     }
>   }
> }
