### ISSUE TITLE
表单验证的时候，多层数据验证失败。

### ISSUE THREAD

**Issue by heikaimu** [museui/muse-ui#1077]
比如我的form:{name: xxx,  family: {father: xx, mather: xxx}}  我在一个form里面同时有这3个表单，分别写上规则。 如果我的:model="form", 我只有name这个验证生效了, 如果我写的是:model="form.family",  那fater和mater生效了，name又没生效，是我写法错了吗，这个该怎么写才能满足我的需求，新手不太懂

**Comment by myronliu347** [comment]
fixed: 3.0.0-rc.6 

```
prop="family.father"
```
