### ISSUE TITLE
CDN 模式用不了插件

### ISSUE THREAD

**Issue by zhouxianjun** [museui/muse-ui#1078]
RT：使用CND加载 一个插件都用不了(不使用webpack等其他打包工具)；
```
requirejs(['vue2', 'muse', 'axios', 'muse-toast'], function (Vue, Muse, axios, MuseToast) {
        Vue.use(Muse);
        Vue.use(MuseToast);
        new Vue({
            el: '#app',
            data: {
                
            },
            mounted () {
                this.$toast.message('hello world');
            },
            methods: {
               
            }
        })
    });
```
不报错，但页面上只有一个<div></div>其他啥都没。
![image](https://user-images.githubusercontent.com/5254523/42935314-ebdc0550-8b7b-11e8-9c32-f867ee42b300.png)

**Comment by myronliu347** [comment]
CDN
<link  rel="stylesheet" href="https://unpkg.com/muse-ui-message/dist/muse-ui-message.all.css"/>
<script src="https://unpkg.com/muse-ui-message/dist/muse-ui-message.js"></script>
