### ISSUE TITLE
移动端选项卡延迟

### ISSUE THREAD

**Issue by mxue12138** [museui/muse-ui#1081]
大神您好，现在是这样的一个问题：我用的muse-ui的选项卡，点击不同的选项卡显示不同的组件，在pc端没问题，但是在移动端点击选项卡会有延迟，导致点击过快的话会无法切换，只能再点击一下才能切换过去，请问怎么解决啊？

**Comment by mymaizi** [comment]
的确不理想。。。跳转也会出现卡顿

**Comment by mxue12138** [comment]
那楼上那位你解决了吗？我试过好几种办法也解决不了，能解决的就没动画效果，有动画效果就卡顿。。。

**Comment by mxue12138** [comment]
我怀疑是因为移动端相对于click事件有300ms的点击延迟导致的？

**Comment by myronliu347** [comment]
fastclick 加了么

**Comment by mxue12138** [comment]
早就加了，npm i fastclick，我安装的时候就加上了，但是还是延迟、卡顿。
