### ISSUE TITLE
关闭mu-drawer之后笼罩层无法隐藏

### ISSUE THREAD

**Issue by zangxx66** [museui/muse-ui#1084]
尚不明确是什么原因造成的，控制台没报错，暂时用监听去处理了
`watch:{
    open:function(){
      if(!this.open){
        const dom = document.querySelector('.mu-overlay')
        dom.style.position = 'inherit'
      }
    }
  }`

**Comment by myronliu347** [comment]
提供下出错的在线示例哦

**Comment by myronliu347** [comment]
fixed: in rc.7
