### ISSUE TITLE
mu-date-input 的change事件，取不到v-model绑定的值

### ISSUE THREAD

**Issue by liu874396180** [museui/muse-ui#1085]
`<mu-date-input v-model="dataObj.policyHolder.birthday" @change="fastChange(dataObj.policyHolder.birthday)" label="" container="bottomSheet" label-float full-width name=""></mu-date-input>
            </mu-list-item>`
`fastChange(res){console.log(res)}----------->undefined`

**Comment by myronliu347** [comment]
fixed: in rc.7
