### ISSUE TITLE
mu-tootip和mu-dialog同时出现时bug

### ISSUE THREAD

**Issue by chutzstudio** [museui/muse-ui#1086]
具体表现为，点击带有tooltip的按钮，打开一个对话框。对话框背景在接近完成transition的时候消失，并在控制台报错：

[Vue warn]: Error in nextTick: "TypeError: Cannot set property 'color' of null"
vue.esm.js?efeb:1741 TypeError: Cannot set property 'color' of null
    at Object.changeOverlayStyle (muse-ui.esm.js?6857:2766)
    at eval (muse-ui.esm.js?6857:2702)
    at Array.eval (vue.esm.js?efeb:1837)
    at flushCallbacks (vue.esm.js?efeb:1758)

以下代码片段可以正常执行，取消注释加上tooltip后会产生报错。

`<mu-container class="btn-ctn">
            
                <mu-button fab color="primary" @click="openDialog=true">
                    <mu-icon value="add"></mu-icon>
                </mu-button>
            
        </mu-container>
        <mu-dialog title="新建用户" width="360" :open="openDialog">
            表单位置
            <mu-button slot="actions" flat color="primary">取消</mu-button>
            <mu-button slot="actions" flat color="primary">提交</mu-button>
        </mu-dialog>`

**Comment by adtkcn** [comment]
挤挤；
Toast插件和mu-dialog同时出现也有这问题，在Toast被移除是会报错Cannot set property 'color' of null"，并且会把mu-dialog的背景遮罩移除

**Comment by myronliu347** [comment]
fixed: in rc.7
