### ISSUE TITLE
using 'Tooltip' and 'Dialog' together cause overlay disappear

### ISSUE THREAD

**Issue by AaaCabbage** [museui/muse-ui#1087]
see below example [jsfiddle](https://jsfiddle.net/AaaCabbage/aubm8x5t/)
In console will print `Cannot set property 'color' of null"` err, I think because 'tooltip' will trigger `overlay.$destroy()` function, but 'dialog' instance still alive. 
I'm trying to fix that but not work :-(
btw, I like this project, It help me a lot! Thanks for you efforts!

**Comment by myronliu347** [comment]
fixed: in rc.7
