### ISSUE TITLE
mu-date-input表单验证中不会实时监测

### ISSUE THREAD

**Issue by yang131323** [museui/muse-ui#1088]
mu-date-input放在表单中，使用表单验证时不能实时更新验证结果，如：表单内容我全部不填写，表单所有内容弹出validate中设置的message，但是mu-date-input添加内容进去message不会实时消失？这个组件设置时的一个缺陷还是我的验证方式错了： validate: （ val）=> !!val?

**Comment by myronliu347** [comment]
fixed: in rc.7
