### ISSUE TITLE
mu-load-more组件报错

### ISSUE THREAD

**Issue by mxue12138** [museui/muse-ui#1089]
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
handlePrevent @ muse-ui.esm.js?6857:11188

下拉刷新偶尔会报这个错，对页面没有任何影响，但是会阻止某些js的执行，会导致页面在移动端app的某些js无法执行，暂不知道原因，求教下

**Comment by myronliu347** [comment]
这里只是阻止了原生滚动， 具体阻止那些js执行，希望能提供详细点信息

**Comment by mxue12138** [comment]
我把源代码或者页面发给你可以吗？你直接运行就可以看到了。

我这个是写完以后打包成移动app，他阻止的是监听安卓返回按钮的js，只要一报错，手机app按返回键就会直接退出应用，而不是返回上一页

**Comment by myronliu347** [comment]
fixed: in rc.7
