### ISSUE TITLE
mu-select 在api版本<=23的情况下会出现错误

### ISSUE THREAD

**Issue by mymaizi** [museui/muse-ui#1091]
`TypeError: undefined is not a function at static/js/vendor.33955dbd7df786af14b3.js:12
 TypeError: Cannot read property 'scrollWidth' of undefined at static/js/vendor.33955dbd7df786af14b3.js:12`

以上错误是在模拟器下通过HBuilder打包进行测试出现的。
不知道博主是否发现？？？

**Comment by myronliu347** [comment]
fixed
