### ISSUE TITLE
type script 声明报错 没找到vue PluginObject

### ISSUE THREAD

**Issue by CXY037** [museui/muse-ui#1094]

**Comment by myronliu347** [comment]
需要依赖vue2.5以上版本才有 PluginObject

**Comment by CXY037** [comment]
Invalid module name in augmentation. Module 'muse-ui/lib/theme/colors' resolves to an untyped module at '/home/wwwroot/vuecli/matchmobile/node_modules/muse-ui/lib/theme/colors.js', which cannot be augmented.
     8 | }
     9 | 
  > 10 | declare module 'muse-ui/lib/theme/colors' {
       |                ^
    11 |   export default MuseUI.Colors;
    12 | }

**Comment by CXY037** [comment]
其他都ok了升级了cli rc9

**Comment by CXY037** [comment]
I change the index.d.ts 
declare module 'muse-ui/theme' {
  export default MuseUI.theme;
}

declare module 'muse-ui/theme/colors' {
  export default MuseUI.Colors;
}
it works well

**Comment by myronliu347** [comment]
// index.d.ts
```typescript
export * from './muse-ui';

import * as MuseUI from './muse-ui';
export default MuseUI;

declare module 'muse-ui/lib/theme' {
  import * as MuseUI from './muse-ui';
  export default MuseUI.theme;
}

declare module 'muse-ui/lib/theme/colors' {
  import * as MuseUI from './muse-ui';
  export default MuseUI.Colors;
}

```

**Comment by myronliu347** [comment]
近期会发这个更新

**Comment by CXY037** [comment]
@myronliu347 ok
