### ISSUE TITLE
slide-picker 滑动选择器的值怎么设置编号

### ISSUE THREAD

**Issue by jlcool** [museui/muse-ui#1095]
选择后一般用编号id赋值，没看到这个功能，请添加

**Comment by Necroogre** [comment]
+1, 像select一样，一般item是key-value的对象

**Comment by myronliu347** [comment]
每个slot.values可以这样 [{text: 'label1', id: '1'},{text: 'label1', id: '1'}] ,  然后选中的值 [{text:'label1'., id: '1'}] 返回的是整个item 对象
