### ISSUE TITLE
loadMore 下拉刷新：在安卓手机上第一次会卡在半路，第二次才会触发刷新【bug】

### ISSUE THREAD

**Issue by liu874396180** [museui/muse-ui#1096]
loadMore 下拉刷新：在安卓手机的h5页面上第一次会卡在半路（上不来下不去）松开手不会自动返回上去，需要第二次触发一次下拉才会回去，第二次才会触发刷新并自动返回上去。

**Comment by huangying100** [comment]
我也出现这种情况，页面打开后，反复操作都是这样
