### ISSUE TITLE
Invalid module name in augmentation

### ISSUE THREAD

**Issue by BengBu-YueZhang** [museui/muse-ui#1099]
Invalid module name in augmentation. Module 'muse-ui/lib/theme' resolves to an untyped module at '/Users/zhangyue/Documents/VueTypescript/my-project/node_modules/muse-ui/lib/theme/index.js', which cannot be augmented.

Invalid module name in augmentation. Module 'muse-ui/lib/theme/colors' resolves to an untyped module at '/Users/zhangyue/Documents/VueTypescript/my-project/node_modules/muse-ui/lib/theme/colors.js', which cannot be augmented.

```
// 官方的描述文件
export * from './muse-ui';

import * as MuseUI from './muse-ui';
export default MuseUI;

declare module 'muse-ui/lib/theme' {
  export default MuseUI.theme;
}

declare module 'muse-ui/lib/theme/colors' {
  export default MuseUI.Colors;
}
```

我找到了这个解释，https://stackoverflow.com/questions/42693836/typescript-custom-declaration-files-for-untyped-npm-modules

**Comment by myronliu347** [comment]
fixed: in rc.7
