### ISSUE TITLE
如何使用switch组件

### ISSUE THREAD

**Issue by wuzhiming** [museui/muse-ui#110]
如何使用switch组件，在import 组件之后，并没有看到switch组件
![image](https://cloud.githubusercontent.com/assets/6093737/20738699/e8012f62-b6ef-11e6-9809-3581a535cff7.png)

**Comment by myronliu347** [comment]
switch是关键字，变量名变成 _switch， 使用可以看[文档](https://museui.github.io/#/switch)中的示例代码
