### ISSUE TITLE
mu-button==>tag 貌似无效。不知道是bug还是我使用错误

### ISSUE THREAD

**Issue by mymaizi** [museui/muse-ui#1100]
` <mu-ripple class="mu-ripple-m m-1">
                <mu-button flat :ripple="false" tag="div">
                    <mu-flex align-items="center" direction="column" style="position:fixed">
                        <mu-flex><mu-icon value="iso" size="30"></mu-icon></mu-flex>
                        <mu-flex>我是按钮</mu-flex>
                    </mu-flex>
                </mu-button>
            </mu-ripple>`

`.mu-ripple-m {
  position: relative;
  width: 86px;
  height: 86px;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  margin-right: 8px;
  background-color: #fff;
  border-radius: 4px;
}.mu-ripple-m.m-1 {
  background-color: #f74359;
  color: #fff;
}`
button最终还是渲染成了button并没有改变成div，如果正常button标签属性应该被渲染成div不知道我理解错没有？？？？

**Comment by myronliu347** [comment]
这个tag只在 设置了to之后有效哦

**Comment by mymaizi** [comment]
哟西，了解，话说文档没有这么写，博主有空整理去更新下哦，幸苦了
