### ISSUE TITLE
muse-ui.org at Firefox unable to open 

### ISSUE THREAD

**Issue by a-wing** [museui/muse-ui#1102]
- Chromium normal
- Firefox unable to open

**Comment by myronliu347** [comment]
![image](https://user-images.githubusercontent.com/7897937/43434658-3f68d9f0-94af-11e8-9b19-0bd840ae9f99.png)

**Comment by a-wing** [comment]
![image](https://user-images.githubusercontent.com/18189138/43434891-38e72ba8-94b0-11e8-945d-42ea578e3be7.png)
