### ISSUE TITLE
选择dark主题字体颜色不变化

### ISSUE THREAD

**Issue by weeChanc** [museui/muse-ui#1106]
```
dependencies": {
    "animate.css": "^3.6.1",
    "axios": "^0.18.0",
    "element-ui": "^2.2.1",
    "muse-ui": "^3.0.0-rc.6",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1"
  }
```
```
<mu-container>
    <mu-flex align-items="center" style="padding-bottom: 8px;">
      <span style="margin-right: 16px;">Label Position:</span>
      <mu-radio v-model="labelPosition" style="margin-right: 16px;" value="top" label="Top"></mu-radio>
      <mu-radio v-model="labelPosition" style="margin-right: 16px;" value="left" label="Left"></mu-radio>
      <mu-radio v-model="labelPosition" style="margin-right: 16px;" value="right" label="Right"></mu-radio>
    </mu-flex>
  </mu-container>

```
比如上述代码中，radio显示label中的字体，颜色是黑色的而不是白色的

**Comment by rocka** [comment]
文档中的例子是这样的

```js
import theme from 'muse-ui/lib/theme';
theme.add('teal', {
  primary: '#009688',
  secondary: '#ff4081',
  success: '#4caf50',
  warning: '#ffeb3b',
}, 'light');

theme.use('teal');
```

然而实测从亮色主题换到暗色主题的时候好多地方颜色都不会变，甚至一些组件的颜色变成了默认的蓝色。

正确的姿势是

```js
import MuseUI from 'muse-ui'

MuseUI.theme.add('custom', {
  primary: '#009688',
  secondary: '#ff4081'
}, 'dark').use('custom');
```

## 可能的解释

可能是作用域的问题？单独 `import theme from 'muse-ui/lib/theme'` 的时候实际上创建了一个新的实例，而不是引用全局的主题实例，这导致 theme 中只有默认的两项：

https://github.com/museui/muse-ui/blob/70f149e49829d5e5a7de5fefe5606105b8e637a0/src/theme/index.js#L6-L8

而在 MuseUI 初始化注册所有组件的时候，内部会调用

https://github.com/museui/muse-ui/blob/70f149e49829d5e5a7de5fefe5606105b8e637a0/src/theme/index.js#L26-L30

来添加组件的的特定主题。

在然后 `use()` 一个主题的时候，会从 `themes` 数组中取出所有的主题，并生成一个 `<style>` 标签

https://github.com/museui/muse-ui/blob/70f149e49829d5e5a7de5fefe5606105b8e637a0/src/theme/index.js#L40-L44

所以只能更换 body 的颜色以及背景色，还有部分组件的主题色 ...

**Comment by myronliu347** [comment]
附加可能出现这个问题的示例：
首先是否使用 `theme.use('dark')` 这个默认的黑色主题
其次，是否在自己的样式文件给 radio更改过文字颜色
