### ISSUE TITLE
text-field无法支持监听键盘按钮信息，比如enter按钮

### ISSUE THREAD

**Issue by wuzhiming** [museui/muse-ui#111]
text-field无法支持监听键盘按钮信息，比如enter按钮

例如
<input @keyup.enter="submit">

**Comment by myronliu347** [comment]
@keyup.native.enter, 请注意vue2.0的事件改动

**Comment by wuzhiming** [comment]
<input @keyup.enter="submit">
这个写法就是2.0vue文档里看到的
 http://cn.vuejs.org/v2/guide/events.html#按键修饰符

**Comment by myronliu347** [comment]
组件上监听元素事件需要.native修饰符 [用-v-on-监听原生事件-改变](https://cn.vuejs.org/v2/guide/migration.html#用-v-on-监听原生事件-改变)
