### ISSUE TITLE
Error while using the script

### ISSUE THREAD

**Issue by zapping** [museui/muse-ui#1112]
Hi,
 Can you please take a look at the screencap and let me know the issue in running the script.

Thank you.
![museui](https://user-images.githubusercontent.com/4123026/43783568-8f1165c4-9a51-11e8-86ce-f024aec5d2df.PNG)

**Comment by mymaizi** [comment]
It is recommended to create a project through VUE-CLI for testing.

**Comment by zapping** [comment]
Actually I am trying to integrate your UI to a legacy .net application. Hence CLI is not an option that I can use. Unfortunately will have to go with the CDN include of the required libraries.

**Comment by mymaizi** [comment]
`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/muse-ui/dist/muse-ui.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <link rel="stylesheet" href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
    <script src="https://unpkg.com/muse-ui/dist/muse-ui.js"></script>
<style>
.flex-wrapper {
  width: 100%;
  height: 56px;
  margin-top: 8px;
}
.flex-demo {
  width: 200px;
  height: 32px;
  background-color: #e0e0e0;
  text-align: center;
  line-height: 32px;
  margin-left: 8px;
}
.flex-wrapper:first-child {
  margin-top: 0;
}
.flex-demo:first-child {
  margin-left: 0;
}
</style>
</head>

<body>
    <div id="app">
    	<div style="width: 100%; background: #fff; padding: 8px;">
  <mu-flex class="flex-wrapper" justify-content="start">
    <mu-flex class="flex-demo" justify-content="center" >left</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="center">
    <mu-flex class="flex-demo" justify-content="center" >center</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="end">
    <mu-flex class="flex-demo" justify-content="center" >right</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" align-items="center">
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
  </mu-flex>
  <mu-container class="button-wrapper">
  <mu-button color="primary">Primary---{{name}}</mu-button>
  <mu-button color="secondary">Secondary</mu-button>
  <mu-button color="success">Success</mu-button>
  <mu-button color="warning">Warning</mu-button>
  <mu-button color="info">Info</mu-button>
  <mu-button color="error">Error</mu-button>
  <mu-button disabled>disabled</mu-button>
<mu-container>
</div>
    </div>
    <script>
        
        new Vue({
            el: '#app',
            data:{
            	name:"maizi"
            }
        })
    </script>
</body>

</html>`

**Comment by mymaizi** [comment]
> <!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/muse-ui/dist/muse-ui.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <link rel="stylesheet" href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
    <script src="https://unpkg.com/muse-ui/dist/muse-ui.js"></script>
<style>
.flex-wrapper {
  width: 100%;
  height: 56px;
  margin-top: 8px;
}
.flex-demo {
  width: 200px;
  height: 32px;
  background-color: #e0e0e0;
  text-align: center;
  line-height: 32px;
  margin-left: 8px;
}
.flex-wrapper:first-child {
  margin-top: 0;
}
.flex-demo:first-child {
  margin-left: 0;
}
</style>
</head>

<body>
    <div id="app">
    	<div style="width: 100%; background: #fff; padding: 8px;">
  <mu-flex class="flex-wrapper" justify-content="start">
    <mu-flex class="flex-demo" justify-content="center" >left</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="center">
    <mu-flex class="flex-demo" justify-content="center" >center</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="end">
    <mu-flex class="flex-demo" justify-content="center" >right</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" align-items="center">
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
  </mu-flex>
  <mu-container class="button-wrapper">
  <mu-button color="primary">Primary---{{name}}</mu-button>
  <mu-button color="secondary">Secondary</mu-button>
  <mu-button color="success">Success</mu-button>
  <mu-button color="warning">Warning</mu-button>
  <mu-button color="info">Info</mu-button>
  <mu-button color="error">Error</mu-button>
  <mu-button disabled>disabled</mu-button>
<mu-container>
</div>
    </div>
    <script>
        
        new Vue({
            el: '#app',
            data:{
            	name:"maizi"
            }
        })
    </script>
</body>

</html>

**Comment by mymaizi** [comment]
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/muse-ui/dist/muse-ui.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <link rel="stylesheet" href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
    <script src="https://unpkg.com/muse-ui/dist/muse-ui.js"></script>
<style>
.flex-wrapper {
  width: 100%;
  height: 56px;
  margin-top: 8px;
}
.flex-demo {
  width: 200px;
  height: 32px;
  background-color: #e0e0e0;
  text-align: center;
  line-height: 32px;
  margin-left: 8px;
}
.flex-wrapper:first-child {
  margin-top: 0;
}
.flex-demo:first-child {
  margin-left: 0;
}
</style>
</head>

<body>
    <div id="app">
    	<div style="width: 100%; background: #fff; padding: 8px;">
  <mu-flex class="flex-wrapper" justify-content="start">
    <mu-flex class="flex-demo" justify-content="center" >left</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="center">
    <mu-flex class="flex-demo" justify-content="center" >center</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="end">
    <mu-flex class="flex-demo" justify-content="center" >right</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" align-items="center">
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
  </mu-flex>
  <mu-container class="button-wrapper">
  <mu-button color="primary">Primary---{{name}}</mu-button>
  <mu-button color="secondary">Secondary</mu-button>
  <mu-button color="success">Success</mu-button>
  <mu-button color="warning">Warning</mu-button>
  <mu-button color="info">Info</mu-button>
  <mu-button color="error">Error</mu-button>
  <mu-button disabled>disabled</mu-button>
<mu-container>
</div>
    </div>
    <script>
        
        new Vue({
            el: '#app',
            data:{
            	name:"maizi"
            }
        })
    </script>
</body>

</html>

**Comment by mymaizi** [comment]
`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/muse-ui/dist/muse-ui.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <link rel="stylesheet" href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
    <script src="https://unpkg.com/muse-ui/dist/muse-ui.js"></script>

</head>

<body>
    <div id="app">
    	<div style="width: 100%; background: #fff; padding: 8px;">
  <mu-flex class="flex-wrapper" justify-content="start">
    <mu-flex class="flex-demo" justify-content="center" >left</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="center">
    <mu-flex class="flex-demo" justify-content="center" >center</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" justify-content="end">
    <mu-flex class="flex-demo" justify-content="center" >right</mu-flex>
  </mu-flex>
  <mu-flex class="flex-wrapper" align-items="center">
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
    <mu-flex class="flex-demo" justify-content="center" fill>fill</mu-flex>
  </mu-flex>
  <mu-container class="button-wrapper">
  <mu-button color="primary">Primary---{{name}}</mu-button>
  <mu-button color="secondary">Secondary</mu-button>
  <mu-button color="success">Success</mu-button>
  <mu-button color="warning">Warning</mu-button>
  <mu-button color="info">Info</mu-button>
  <mu-button color="error">Error</mu-button>
  <mu-button disabled>disabled</mu-button>
<mu-container>
</div>
    </div>
    <script>
        
        new Vue({
            el: '#app',
            data:{
            	name:"maizi"
            }
        })
    </script>
</body>

</html>`

**Comment by zapping** [comment]
Tried commenting the line you have mentioned but still the same issue exists.
![museui_tf](https://user-images.githubusercontent.com/4123026/43841153-ff4907fa-9b11-11e8-93b2-8991d961990e.PNG)

**Comment by mymaizi** [comment]
`<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="https://unpkg.com/muse-ui/dist/muse-ui.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
	<link rel="stylesheet" href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.css">
	<maizi src="https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.js"></maizi >
	<maizi src="https://unpkg.com/muse-ui/dist/muse-ui.js"></maizi >
</head>

<body>
	<div id="app">
		<mu-container class="button-wrapper">
		  <mu-button color="primary">Primary</mu-button>
		  <mu-button color="secondary">Secondary</mu-button>
		  <mu-button color="success">Success</mu-button>
		  <mu-button color="warning">Warning</mu-button>
		  <mu-button color="info">Info</mu-button>
		  <mu-button color="error">Error</mu-button>
		  <mu-button disabled>disabled</mu-button>
		<mu-container>
	</div>
</body>
	<maizi >
		new Vue({
		  el: '#app'
		});
	</maizi >
</html>`

**Comment by zapping** [comment]
Thank you that fixed it. I guess I was using the wrong vue CDN. 
![museui_sl](https://user-images.githubusercontent.com/4123026/43878441-b165f688-9b8e-11e8-831c-4dbbfba18696.PNG)
