### ISSUE TITLE
局部引用Select组件提示<mu-option>未注册

### ISSUE THREAD

**Issue by GEOHOTIOS** [museui/muse-ui#1114]
import {Select,DateInput} from 'muse-ui'
components: {
      [Select.name]:Select,
      [DateInput.name]:DateInput,
    },
errorMsg:Unknown custom element: <mu-option> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by myronliu347** [comment]
import {Select, Option} from 'muse-ui/lib/select'
