### ISSUE TITLE
表单验证必填非空，对Boolean类型 0 验证失败

### ISSUE THREAD

**Issue by happylai** [museui/muse-ui#1116]
官网实例：
 usernameRules: [
        { validate: (val) => !!val, message: '必须填写用户名'},
        { validate: (val) => val.length >= 3, message: '用户名长度大于3'}
 ],
(!!0) //false
(!!'0')//true

**Comment by myronliu347** [comment]
官网是只是做一个简单的例子，表单验证函数可以参考这个项目
https://www.npmjs.com/package/validator
