### ISSUE TITLE
啥时候能够出一个单独依赖的组件的 可以不用全部引入

### ISSUE THREAD

**Issue by zhangli254804018** [museui/muse-ui#1119]

**Comment by zhangli254804018** [comment]
很久没用了 刚看已经更新 赞一个

import Vue from 'vue';
import 'muse-ui/lib/styles/base.less';
import { Button, Select } from 'muse-ui';
import 'muse-ui/lib/styles/theme.less';

Vue.use(Button);
Vue.use(Select);

**Comment by nian1123** [comment]
有尝试过吗，能用吗？
