### ISSUE TITLE
mu-pagination 的 page-count 属性使用之后出现如下警告 求解答 

### ISSUE THREAD

**Issue by WX60666** [museui/muse-ui#1121]
<mu-pagination @change="pagerChange" raised :total="orderTotal" :page-count="4" :current.sync="current"></mu-pagination>

![image](https://user-images.githubusercontent.com/17688082/43944673-5690d82a-9cb2-11e8-9856-0c85c1e0448f.png)

**Comment by myronliu347** [comment]
page-count 只能是奇数哦 5， 7 ，9
