### ISSUE TITLE
浏览器窗口较矮时，可滚动的对话框滚动内容显示区域过小或超出对话框

### ISSUE THREAD

**Issue by zxl409774878** [museui/muse-ui#1128]
可滚动的对话框与窗口的上下间距似乎是固定的，当窗口较矮（比如窗口化浏览器），滚动区域会变得很小难以操作。若窗口进一步缩小（比如手机横屏）mu-dialog-body的max-height属性会消失，滚动区域的内容就会超出对话框显示。
使用的版本是3.0.0-rc.7

**Comment by myronliu347** [comment]
请给出出错截图和在线的demo 模拟出错情况

**Comment by zxl409774878** [comment]
以官网的例子为例，使用Chrome浏览器

手机横屏模拟：
![0](https://user-images.githubusercontent.com/35023776/44145695-2f0045f0-a0bf-11e8-8f5e-df5678e8441b.jpg)

窗口较低时：
![1](https://user-images.githubusercontent.com/35023776/44145772-8272b0ba-a0bf-11e8-8713-925dac6ac03c.jpg)

手机实机截屏（iPhone7 iOS11）：
![2](https://user-images.githubusercontent.com/35023776/44145925-f0385db6-a0bf-11e8-9bb4-8aeb09e90cb5.PNG)

**Comment by myronliu347** [comment]
fixed: 3.0.0
<mu-dialog scrollable :padding="20"></mu-dialog> // 缩短顶部和底部的距离
