### ISSUE TITLE
如果Loading插件下层有拖拽动作，在loading的情况下可以拖拽

### ISSUE THREAD

**Issue by jlcool** [museui/muse-ui#1131]
应该取消事件的默认动作，preventDefault？

**Comment by myronliu347** [comment]
loading是遮盖到元素上的，除非你的拖拽时间监听在元素外层，那样的情况没需要在loading时禁止拖拽效果

**Comment by myronliu347** [comment]
loading是遮盖到元素上的，除非你的拖拽时间监听在元素外层，那样的情况没需要在loading时禁止拖拽效果

**Comment by jlcool** [comment]
因为对整个body拖拽了
