### ISSUE TITLE
一些小小的建议

### ISSUE THREAD

**Issue by ShowHide** [museui/muse-ui#1144]
建议增加图片上传，左滑删除针对移动端的组件，感觉虽然muse-ui说是移动端组件，但还是掺杂了好多pc的ui组件，这样就感觉好乱，而且像input和select一些组件感觉更适用于pc，一直想用muse-ui做移动端项目，但由于这些原因就一直在观望，希望作者能考虑下

**Comment by myronliu347** [comment]
额，目前是以pc为主的哦， 后续会出移动端的解决方案，select input这些会对应调整

**Comment by ShowHide** [comment]
@myronliu347 好的，感谢
