### ISSUE TITLE
Unknown custom element: <mu-fade-transition> & <mu-circular-progress> while using muse-ui-loading

### ISSUE THREAD

**Issue by Illyrix** [museui/muse-ui#1146]
I have installed muse-ui and muse-ui-loading, and used them in Vue such like:
    
    import Vue from 'vue'
    import MuseUI from 'muse-ui'
    import MuseUILoading from 'muse-ui-loading'

    import 'muse-ui/dist/muse-ui.css'
    import 'material-icons/iconfont/material-icons.scss'
    import 'muse-ui-loading/dist/muse-ui-loading.css'

    Vue.use(MuseUI)
    Vue.use(MuseUILoading)

then applied loading on a button:

    <mu-button color="gray" v-loading="isListening" @click="isListening = !isListening" icon small>
          <mu-icon value="keyboard"></mu-icon>
    </mu-button>

which reports  
`[Vue warn]: Unknown custom element: <mu-circular-progress> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`  
and  
`[Vue warn]: Unknown custom element: <mu-fade-transition> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`  
after clicking.

I noticed that muse-ui-loading have [dependencies](https://github.com/museui/muse-ui-loading#dependencies-muse-ui) includes `mu-circle-progress` and `mu-fade-transition`, which are not in npm repository.  
So how to install these two plugins(or dependencies) into my project? muse-ui has the version `3.0.0-rc.6` and muse-ui-loading does `0.2.0`.

**Comment by myronliu347** [comment]
retry 
```
yarn add muse-ui
```

**Comment by Illyrix** [comment]
@myronliu347 no use, same errors

**Comment by myronliu347** [comment]
vue 2.5.0 +

**Comment by tinyAdapter** [comment]
same problem here (using muse-ui-message, got Unknown custom element: <mu-dialog> and <mu-button>)

**Comment by myronliu347** [comment]
借鉴 https://github.com/museui/muse-docs/blob/master/src/main.js  全局引入 + 插件

**Comment by stillyu** [comment]
有同样的问题
vue版本2.5.17
museui版本3.0.1

**Comment by IvanLi-CN** [comment]
同楼上，上面的方法也无法解决。
vue版本2.5.17
museui版本3.0.1

**Comment by wxf4150** [comment]
也是上面的问题。不能用啊。
直接装的最新版本
vue@2.5.21
muse-ui@3.0.1

**Comment by michael8908** [comment]
一样的问题，Unknown custom element: <mu-fade-transition> 和 Unknown custom element: <mu-circular-progress>。实在是搞不定了。

**Comment by michael8908** [comment]
一样的问题：
Unknown custom element: mu-circular-progress
Unknown custom element: mu-fade-transition
实在是搞不定了。

**Comment by kenberkeley** [comment]
My temporary solution: 

```js
import Vue from 'vue'

// fix: Unknown custom element: mu-circular-progress
import 'muse-ui/lib/styles/base.less'
import {
  /* https://muse-ui.org/#/en-US/usage#import-on-demand */
  Progress
} from 'muse-ui'
Vue.use(Progress)
import 'muse-ui/lib/styles/theme.less'

// fix: Unknown custom element: mu-fade-transition
import { FadeTransition } from 'muse-ui/src/internal/transitions'
Vue.component('mu-fade-transition', FadeTransition)

// https://github.com/museui/muse-ui-loading#usage
import 'muse-ui-loading/dist/muse-ui-loading.css'
import MuseUILoading from 'muse-ui-loading'
Vue.use(MuseUILoading)
```
