### ISSUE TITLE
ListItemAction toggle-icon class missing

### ISSUE THREAD

**Issue by ludmiloff** [museui/muse-ui#1147]
Hello,
The toggle-icon class for ListItemAction element is missing.
On documentation site there is a nice arrow animation when collapsing/open a sublist. The same cannot be reproduced on jsfiddle.net demo nor my local project.

I'd suggest to put 
```
.toggle-icon {
  color: rgba(0,0,0,.54);
  -webkit-transition: -webkit-transform .3s cubic-bezier(.23,1,.32,1);
  transition: -webkit-transform .3s cubic-bezier(.23,1,.32,1);
  transition: transform .3s cubic-bezier(.23,1,.32,1);
  transition: transform .3s cubic-bezier(.23,1,.32,1),-webkit-transform .3s cubic-bezier(.23,1,.32,1);
}

.mu-item__open .toggle-icon {
  transform: rotate(180deg);
}

/* copied from documentation site */
```

somewhere, ideally src/styles/components/list.less

**Comment by myronliu347** [comment]
There is no toggle icon， It is a custom style

**Comment by ludmiloff** [comment]
Adding as a part of library css and providing a consistent feedback on toggle user action would be highly appreciated, please.
