### ISSUE TITLE
Is Icon lib supports "outline" style?

### ISSUE THREAD

**Issue by Penggggg** [museui/muse-ui#1148]
Is Icon lib supports "outline" style?

[Material Icons](https://material.io/tools/icons/?style=outline) supports "outline" style.
But when i code, it seens doesn't work as I want.
```
<mu-bottom-nav-item
       title="首页"
       icon="home_outline"
       value="home"
/>
```

**Comment by myronliu347** [comment]
Muse-UI not provide icons, please try `outline_home`

**Comment by myronliu347** [comment]
please search in https://github.com/google/material-design-icons
