### ISSUE TITLE
Vue完全导入: Vue.use(MuseUI);提示参数不匹配,MuseUI is not defined

### ISSUE THREAD

**Issue by azhengyongqin** [museui/muse-ui#1149]
### 按照完整引入的方法引入MusUI
> 在WebStrom中就提示参数不匹配

![f gywb4yis 8h392g3twymw](https://user-images.githubusercontent.com/18138282/44454143-4ec3e400-a62d-11e8-8ad6-9173922e2262.png)
![y0 oh q nrwv9b6 msv gg](https://user-images.githubusercontent.com/18138282/44454272-a6fae600-a62d-11e8-8f70-2e78cf26888c.png)

### 确定npm 已经安装完成
> chorem上打印日志:

![w iq 5fm ljgu 1 fyt](https://user-images.githubusercontent.com/18138282/44454366-e295b000-a62d-11e8-9c3c-cae785f1990a.png)

**Comment by myronliu347** [comment]
首先vue要在 2.5.0+ 
让后检查muse-ui是否安装3.0+ 版本
