### ISSUE TITLE
text-field组件的label属性在设置了label-float，在form表单中label的位置偏移

### ISSUE THREAD

**Issue by cunjif** [museui/muse-ui#1152]
`<mu-form ref="loginForm" :model="loginform" class="login-form" label-position="right">
        <mu-form-item label="用户名" help-text="已注册的邮箱/手机号码" prop="username" :rules="userRules">
          <mu-text-field v-model="loginform.username" prop="username" label="用户名" label-float full-width></mu-text-field>
        </mu-form-item>
        <mu-form-item label="密码" htlp-text="密码" prop="password" :rules="passwordRules">
          <mu-text-field type="password" v-model="loginform.password" prop="password" label="密码" label-float full-width></mu-text-field>
        </mu-form-item>
</mu-form>`
&nbsp;&nbsp;text-field组件未获得focus时，label标签出现在输入横线的下方，获得focus时上移到输入横线中，应该是label的位置计算出现了小小的偏差。

**Comment by myronliu347** [comment]
需要label-float 时，将此属性，设置在`mu-form-item` 上
```html
<mu-form-item label="日期" label-float help-text="帮助文字" prop="username" :rules="usernameRules">
      <mu-date-input v-model="validateForm.username" prop="username"></mu-date-input>
    </mu-form-item>
```

**Comment by 308787520huanhuan** [comment]
> 需要label-float 时，将此属性，设置在`mu-form-item` 上
> 
> ```
> <mu-form-item label="日期" label-float help-text="帮助文字" prop="username" :rules="usernameRules">
>       <mu-date-input v-model="validateForm.username" prop="username"></mu-date-input>
>     </mu-form-item>
> ```

这个时候给mu-form-item设置color属性 不生效是怎么回事
![image](https://user-images.githubusercontent.com/3348828/56846065-ca80d980-68fc-11e9-91da-98ccc86efbcc.png)
![image](https://user-images.githubusercontent.com/3348828/56846069-d371ab00-68fc-11e9-9ff5-3709f68f5b5d.png)

**Comment by 308787520huanhuan** [comment]
如果把color设置在text-field上面 又有问题
![image](https://user-images.githubusercontent.com/3348828/56846073-f308d380-68fc-11e9-9839-f0579a3b956c.png)
![image](https://user-images.githubusercontent.com/3348828/56846075-fac87800-68fc-11e9-8e58-2cfd1a831280.png)
