### ISSUE TITLE
官网挂了！！！

### ISSUE THREAD

**Issue by yanzhenyu** [museui/muse-ui#1154]

**Comment by tvChan** [comment]
[muse-ui](https://muse-ui.org/#/zh-CN)很正常啊

**Comment by yanzhenyu** [comment]
![image](https://user-images.githubusercontent.com/11738089/44570119-53180a80-a7af-11e8-8072-f7dbe18c420b.png)
@tvChan

**Comment by tvChan** [comment]
@yanzhenyu 什么地址。我这正常呢
