### ISSUE TITLE
Message 弹框插件使用问题

### ISSUE THREAD

**Issue by menglin0302** [museui/muse-ui#1157]
主要代码如下：

> main.js:

` import Vue from 'vue'`
`import Vue from 'vue'`
`import axios from 'axios'`
`import VueAxios from 'vue-axios'`
`import MuseUI from 'muse-ui'`
`Vue.use(MuseUI)`
`import 'muse-ui/dist/muse-ui.css'`
`import theme from 'muse-ui/lib/theme'`
`theme.use('dark')`
`import Toast from 'muse-ui-toast'`
`Vue.use(Toast)`
`import 'muse-ui-message/dist/muse-ui-message.css'`
`import Message from 'muse-ui-message'`
`Vue.use(Message)`

>  test.vue:

`this.$confirm('确定要删除？', '提示', { `
`          type: 'warning'`
`        }).then(({ result }) => {`
`          if (result) {`
`            var index = this.tds[data.rowIndex][data.colIndex].indexOf(data.key);`
`            if (index > -1) {`
`              this.tds[data.rowIndex][data.colIndex].splice(index, 1);`
`            }`
`          }`
`        });`

> 报错信息:

**vue.esm.js?22f2:591 [Vue warn]: Unknown custom element: <mu-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.**

(found in <Root>)
.....
...
..

**Comment by myronliu347** [comment]
#1146
