### ISSUE TITLE
插件npm安装后无法找到（muse-ui-toast，muse-ui-message）

### ISSUE THREAD

**Issue by jianlis** [museui/muse-ui#1159]
![image](https://user-images.githubusercontent.com/20299159/44706590-b0c09580-aad4-11e8-899f-91f2f7e6de52.png)
![image](https://user-images.githubusercontent.com/20299159/44706600-b9b16700-aad4-11e8-8600-b416a65d470b.png)
这些包安装过了，node_modules中也有，就是在引入的时候一直提示引用不到。
![image](https://user-images.githubusercontent.com/20299159/44706654-e9f90580-aad4-11e8-805d-a1002b893512.png)

**Comment by myronliu347** [comment]
TS是定义了的哦
