### ISSUE TITLE
mu-bottom-nav 问题

### ISSUE THREAD

**Issue by zhenliGitHub** [museui/muse-ui#1161]
请看图片  如果加了 to  就会为选中状态
![1535443965 1](https://user-images.githubusercontent.com/28820070/44709952-90490900-aadd-11e8-8faa-680f31b1de17.jpg)
![1535443992 1](https://user-images.githubusercontent.com/28820070/44709954-90490900-aadd-11e8-9fdd-b3535f4fe7b0.jpg)

**Comment by geshansuiyue** [comment]
+1

**Comment by myronliu347** [comment]
fixed in 3.0.1
