### ISSUE TITLE
tabs highlight width render error when resize

### ISSUE THREAD

**Issue by wanghaiwei** [museui/muse-ui#1162]
![image](https://user-images.githubusercontent.com/13343271/44755106-469d0480-ab57-11e8-9056-67e82706b28f.png)

**Comment by myronliu347** [comment]
暂时无法监控元素的宽度变化，需要在宽度变化时手动调用 $forceUpdate 方法刷新组件

**Comment by wanghaiwei** [comment]
可以引入vue-resize来监听吗？

**Comment by myronliu347** [comment]
resize-observer-polyfill 
可以使用这个库进行监听

**Comment by wanghaiwei** [comment]
谢谢
