### ISSUE TITLE
 mu-dialog在iphone4上设置scrollable后，不能触发滚动事件

### ISSUE THREAD

**Issue by zhangyj1992** [museui/muse-ui#1171]
mu-dialog在iphone4上设置scrollable后，不能触发滚动事件，现在只测试有iphone4，其他不清楚

**Comment by lcysgsg** [comment]
5s 同样碰到了

**Comment by z521436** [comment]
啥情况 我在ipad上也遇到了

**Comment by myronliu347** [comment]
具体情况呢，是无法滚动，还是无法监听到事件

**Comment by zhangyj1992** [comment]
无法滚动，但其他行为可以比如点击，所以可以排除遮罩问题

**Comment by zhangyj1992** [comment]
无法滚动，但其他行为可以比如点击，所以可以排除遮罩问题

**Comment by myronliu347** [comment]
应该是body-scroll-lock 这个依赖导致的问题

**Comment by zhangyj1992** [comment]
如何修改？还是要等您发布版本，近期我这边产品要上线

**Comment by zhangyj1992** [comment]
如何修改？还是要等您发布版本，近期我这边产品要上线

**Comment by myronliu347** [comment]
fixed in 3.0.1

<mu-dialog :lock-scroll="false" /> 可选择关闭锁定全局滚动
