### ISSUE TITLE
electron-vue 插件无法使用

### ISSUE THREAD

**Issue by phpjishu** [museui/muse-ui#1172]
electron-vue 插件无法使用

 [Vuewarn]: Unknown custom element: <mu-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)
warn @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:589
createElm @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:5566
patch @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:6128
Vue._update @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:2658
updateComponent @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:2786
get @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:3140
Watcher @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:3129
mountComponent @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:2793
Vue.$mount @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:7997
Vue._init @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:4638
VueComponent @ D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:4796
(anonymous) @ D:\WebStorm\vueele\node_modules\muse-ui-message\dist\muse-ui-message.common.js:212
Message @ D:\WebStorm\vueele\node_modules\muse-ui-message\dist\muse-ui-message.common.js:211
Message.(anonymous function) @ D:\WebStorm\vueele\node_modules\muse-ui-message\dist\muse-ui-message.common.js:266
alert @ App.vue?234e:15
click @ App.vue?e7ed:16
invoker @ vue.esm.js?a026:2027
Vue.$emit @ vue.esm.js?a026:2538
handleClick @ D:\WebStorm\vueele\node_modules\muse-ui\dist\muse-ui.common.js:1221
invoker @ vue.esm.js?a026:2027
Vue.$emit @ vue.esm.js?a026:2538
handleClick @ D:\WebStorm\vueele\node_modules\muse-ui\dist\muse-ui.common.js:1875
invoker @ vue.esm.js?a026:2027
fn._withTask.fn._withTask @ vue.esm.js?a026:1826
D:\WebStorm\vueele\node_modules\vue\dist\vue.runtime.common.js:589 [Vue warn]: Unknown custom element: <mu-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)`

`import Vue from 'vue'
import axios from 'axios'

import App from './App'
import router from './router'
import store from './store'
import MuseUi from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
import Message from 'muse-ui-message'
import 'muse-ui-message/dist/muse-ui-message.css'

if (!process.env.IS_WEB) Vue.use(require('vue-electron'))
Vue.http = Vue.prototype.$http = axios
Vue.config.productionTip = false
Vue.use(MuseUi)
Vue.use(Message)

/* eslint-disable no-new */
new Vue({
  components: {App},
  router,
  store,
  template: '<App/>'
}).$mount('#app')`
`<template>
    <div id="app">
        <mu-button class="demo-button" color="primary" @click="alert()">Alert</mu-button>
        <mu-button class="demo-button" color="secondary" @click="confirm()">Confirm</mu-button>
        <mu-button class="demo-button" color="teal" @click="prompt()">Prompt</mu-button>
        <router-view></router-view>
    </div>
</template>

<script>
    export default {
        name: 'vueelectron',
        methods: {
            alert() {
                this.$alert('Hello World', '提示', {
                    okLabel: '知道了'
                }).then(() => {
                    this.$toast.message('提示信息');
                });
            },
            confirm() {
                this.$confirm('确定要删除？', '提示', {
                    type: 'warning'
                }).then(({result}) => {
                    if (result) {
                        this.$toast.message('点击了确定');
                    } else {
                        this.$toast.message('点击了取消');
                    }
                });
            },
            prompt() {
                this.$prompt('请输入邮箱', '提示', {
                    validator(value) {
                        return {
                            valid: /[\w!#$%&'*+/=?^_`{|}~-]+(?:\.[\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\w](?:[\w-]*[\w])?\.)+[\w](?:[\w-]*[\w])?/.test(value),
                            message: '请输入正确邮箱格式'
                        }
                    }
                }).then(({result, value}) => {
                    if (result) {
                        this.$toast.message('你输入的邮箱：' + value);
                    } else {
                        this.$toast.message('点击了取消');
                    }
                });
            }
        }
    }
</script>

<style>
    /* CSS */
</style>`

**Comment by myronliu347** [comment]
请检查 Vue 和 muse-ui的版本
muse-ui 支持 vue 2.50+ 版本
```javascript
MuseUI.version // 查看版本号
Vue.verseion // 查看版本号

```
