### ISSUE TITLE
Toast组件能否增加垂直居中的属性，top和bottom在手机端显示不太友好

### ISSUE THREAD

**Issue by zwind007** [museui/muse-ui#1174]
试过覆盖样式，但在手机屏幕上弹出动画有些bug
`.mu-snackbar {
    left: 50%;
    top: 50%;
    transform: translate3d(-50%, -50%, 0);
    display: flex;
    justify-content: center;
  }

  @media screen and (max-width: 600PX) {
    .mu-snackbar {
      width: auto;
      max-width: 80%;
      min-width: 50%;
    }
  }`

**Comment by myronliu347** [comment]
只能覆盖样式哦，toast的目前的风格不太适合居中弹出
