### ISSUE TITLE
data table展开行能否改为一个按钮触发, rowclick 留给用户其他的操作

### ISSUE THREAD

**Issue by gloooe** [museui/muse-ui#1175]
我用v-if 做了(以下内容默认显示不完整)
                 <template v-if="extendopen" slot="expand" slot-scope="prop">
                        <div style="padding: 24px;">this is expand row, name {{prop.row.name}}</div>
                    </template>

这样虽然可以,但有bug,因为没有屏蔽掉 rowclick ,或讲rowclick 用到别的事件

**Comment by myronliu347** [comment]
可以哦
![image](https://user-images.githubusercontent.com/7897937/45249264-48817780-b350-11e8-8238-6f9021f6a1b3.png)
auto-expand 设置为 false

然后使用 expand-row-index.sync 控制展开行

**Comment by gloooe** [comment]
老大 能给个例子吗?没琢磨出来 怎么用
