### ISSUE TITLE
iOS全屏Dialog滚动到底部会触发滚动穿透

### ISSUE THREAD

**Issue by zangxx66** [museui/muse-ui#1179]
开启scrollable之后，在iOS上滚动到底部会触发滚动穿透 ，这时滚动的对象就变成弹窗遮盖的部分了

**Comment by myronliu347** [comment]
ios这种情况确实会存在，似乎没法处理，overflow：hidden之后还是会滚动，或者你有什么好的建议，欢迎pr

**Comment by nongzhenli** [comment]
> ios这种情况确实会存在，似乎没法处理，overflow：hidden之后还是会滚动，或者你有什么好的建议，欢迎pr

overflow：hidden 在ios上会发生失效！通过动态添加一个class 
`.lock-position {
    position: fixed;
    width: 100%;
    height: 100%;
    overflow: hidden;
}`
可是实现！但是需要 在一些弹框组件单独处理！比如  

> Dialog 、Bottom Sheet、Popover....

一类的弹框组件，是否可以添加 change event 呢？ 方便统一处理~ @myronliu347
