### ISSUE TITLE
demo在iOS 8.1 + Chrome 47.0.2526.107样式出现问题

### ISSUE THREAD

**Issue by paraself** [museui/muse-ui#118]
![img_0252](https://cloud.githubusercontent.com/assets/2179686/20780300/e1fd0a4e-b7b4-11e6-8634-1346cc32efc9.png)
![img_0253](https://cloud.githubusercontent.com/assets/2179686/20780301/e2386f8a-b7b4-11e6-8b47-f51797462768.png)
![img_0251](https://cloud.githubusercontent.com/assets/2179686/20780303/e2740cac-b7b4-11e6-8946-55b84226db11.png)
在系统自带的safari 下存在同样的问题。
系统已翻墙。

**Comment by myronliu347** [comment]
是我的环境的autoPrfixer配置的问题，会尽快修复

**Comment by paraself** [comment]
好的 期待！

**Comment by myronliu347** [comment]
已经修复
