### ISSUE TITLE
Bottom Navigation 怎样使用自定义图标呢？

### ISSUE THREAD

**Issue by zhangzhi93** [museui/muse-ui#1188]
<mu-bottom-nav-item title="Favorites"
      icon="&#xf0122;">
      <mu-icon size="36"
        value=":mudocs-icon-custom-pie"
        color="green"></mu-icon>
</mu-bottom-nav-item>
mu-bottom-nav-item 不接受子标签，icon属性只是一个字符串，自定义图标怎样设置呢？建议不要强绑定material-icons，icon可以传类名

**Comment by lgs442874490** [comment]
icon=":iconfont icon-ziyuan"  这样就可以用外部图标了 我用的是iconfont
