### ISSUE TITLE
DataTable中使用自定义表头,排序功能无效,自己写排序的话,column对象都无法获取,这完全就是个BUG,希望作者能修复,或者给出自定义排序的demo

### ISSUE THREAD

**Issue by jshintrc** [museui/muse-ui#1189]
DataTable中使用自定义表头,排序功能无效,自己写排序的话,column对象都无法获取,这完全就是个BUG,希望作者能修复,或者给出自定义排序的demo

**Comment by myronliu347** [comment]
自定义可以获取columns 
![image](https://user-images.githubusercontent.com/7897937/45915466-b74ded00-be87-11e8-8327-bea9b409d4c9.png)
