### ISSUE TITLE
vee-validate for validation part

### ISSUE THREAD

**Issue by alphaelf** [museui/muse-ui#119]
how can i use [vee-validate](http://vee-validate.logaretm.com/) as validator?
it need to use input element

**Comment by myronliu347** [comment]
You can use [vue-validator](https://github.com/kazupon/vue-validator)

**Comment by alphaelf** [comment]
thank for reply. but if you research about vee-validate you see it's strategy is better and more usable.
and some thing about your suggest is the component is alpha version for vue v2 and no doc for it.
you can use vee in your core of ui component as part of your package. it become wonderful.
anyway, how can i use vee-validate in your components?
if i wrong about your suggest please clear me.
and good luck my dear.

**Comment by throrin19** [comment]
@alphaelf I test vee-validate with muse-ui and this is the basic requirement to attach textFields with errors :  

```
<mu-text-field data-vv-name="email" label="Email" fullWidth labelFloat v-validate data-vv-rules="required|email" :errorText="errors.first('email')"/>
```

**Comment by throrin19** [comment]
After more tests, vee-validate works fine with the "on the fly" validation. If I launch the all form validating on submit, vee-validate return errors on my components : https://github.com/logaretm/vee-validate/issues/118
