### ISSUE TITLE
如何让一个textfield中的文字居中

### ISSUE THREAD

**Issue by wupei1024** [museui/muse-ui#1195]
加了style发现加不到input上面，用css结果你生成的 input没有hash匹配不上。

**Comment by wupei1024** [comment]
![image](https://user-images.githubusercontent.com/5860283/46138810-7edf5200-c27f-11e8-803e-e1ef8ce291c2.png)

**Comment by myronliu347** [comment]
不要使用scoped scoped css无法修改组件内部的样式
