### ISSUE TITLE
messasge 插件中图标样式问题

### ISSUE THREAD

**Issue by date-convert** [museui/muse-ui#1199]
this.$confirm('确定要删除？', '提示', {
					type: 'warning'
				}).then(({
					result
				}) => {
					if(result) {
						this.$toast.message('点击了确定');
					} else {
						this.$toast.message('点击了取消');
					}
				});
使用该方法会出现 type：warning的图标不显示，显示的是图标的text文字

**Comment by myronliu347** [comment]
没有引入material 图标库 

https://github.com/google/material-design-icons
