### ISSUE TITLE
为什么php过来的json数据不能解析

### ISSUE THREAD

**Issue by nbslr** [museui/muse-ui#120]
import Vue from 'vue'

import App from './App'
import Login from './components/Login'

import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css' // 加载样式
Vue.use(MuseUI)

import VueResource from 'vue-resource';
Vue.use(VueResource);
Vue.http.options.emulateJSON = true;
/* eslint-disable no-new */
new Vue({
  el: '#app',
  data:{ islogin:1,
         currentView:Login,
		 gridData:'',
		 apiUrl: 'http://localhost:80/t.php'
	   },
	methods: {
		getCustomers: function() {
			this.$http.get(this.apiUrl).then((response) => {
					this.$set('gridData', response.data)
				})
				.catch(function(response) {
					console.log(response)
				})
		}
	},	   
  created: function(){
       
		this.getCustomers()
		}
})
-----------------------------
php过来的json数据  {data:[{"id":"2"}]}
--------------------------------------
错误显示：
can't assign to properties of (new String("gridData")): not an object

**Comment by stevieyu** [comment]
$this 用漏了个参数吧

**Comment by nbslr** [comment]
什么参数

**Comment by myronliu347** [comment]
看官网文档， [vm-set](https://cn.vuejs.org/v2/api/#vm-set)， 你这里可以不用$set ，直接 `this.gridData = response.data` 就可以了
