### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by aeasringnar** [museui/muse-ui#1202]
vue发起请求时报一下错误：Redirect from 'https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/MaterialIcons-Regular.woff2' to 'https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/MaterialIcons-Regular.woff2' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8090' is therefore not allowed access.
请问muse-ui后端是否允许跨域

**Comment by myronliu347** [comment]
下载这个地址上的icons放在本地把， https://github.com/google/material-design-icons
