### ISSUE TITLE
mu-bottom-nav有bug，要点击2次才能改变状态

### ISSUE THREAD

**Issue by msxg** [museui/muse-ui#1204]
示例代码：
`
<mu-bottom-nav :value="bottomNav" @change="handleChange">
           <mu-bottom-nav-item to="/" value="home" title="首页" icon="home"/>
            <mu-bottom-nav-item to="/publish" value="publish" title="发布" icon="note_add"/>
            <mu-bottom-nav-item to="/person" value="person" title="我的" icon="person"/>
        </mu-bottom-nav>
`
`
methods:{
    handleChange(val){
      this.$store.commit('changeNav', val);
    }
  },
  computed:{
    bottomNav(){
      return this.$store.state.bottomNav
    }
  }
`

加了to属性后有问题。多次点击切换后，item的状态就不对了，需要点击两次，第一次页面会切换到to指定的页面，第二次点击当前item才会变成高亮状态。

麻烦看下是否有这个问题。

**Comment by myronliu347** [comment]
这里有些原因是因为在路由跳转的过程会影响到状态的更新，所以这里的处理情况建议改到，跳转之后再实时更改状态
