### ISSUE TITLE
mu-text-field 没有  focus 方法

### ISSUE THREAD

**Issue by hoythan** [museui/muse-ui#1207]
版本
^3.0.1
使用
```
<mu-text-field ref="test" />

this.$refs.test.focus()
error this.$refs.test.focus is not a function
```

**Comment by hoythan** [comment]
> 用id dom 操作

直接找到input 进行 focus 也不行，class 等没有添加上去

**Comment by jlcool** [comment]
> > 用id dom 操作
> 
> 直接找到input 进行 focus 也不行，class 等没有添加上去

我直接设置个id就可以操作了，不知道你怎么操作的

**Comment by hoythan** [comment]
看源码应该用的是handleFocus 而不是 focus

**Comment by hoythan** [comment]
handleFocus 绑定在input的 focus 事件上
所以应该用
this.$refs.textField.$el.getElementsByTagName("input")[0].focus()

**Comment by hoythan** [comment]
[feat](https://github.com/museui/muse-ui/pull/1211)

**Comment by jlcool** [comment]
<mu-text-field v-model="searchInfo"  type="search" id="txtSearch">
        </mu-text-field>
document.getElementById("txtSearch")
