### ISSUE TITLE
appbar里title位置不居中

### ISSUE THREAD

**Issue by LaiXuechao** [museui/muse-ui#121]
设置居中效果，如果隐藏一个按钮，title位置会跑偏，能不能给left,right设置一个固定宽度或者可以自定义宽度，如图：
![image](https://cloud.githubusercontent.com/assets/22734724/20821078/ae5138ac-b87a-11e6-90c9-f4b53a99f2db.png)

**Comment by myronliu347** [comment]
material design中的title就是布局中的，所以我这里也more也不是居中的，我觉得你可以使用slot自定义title然后通过position:absolute 居中
