### ISSUE TITLE
mu-text-field text field event behavior is not matching the document

### ISSUE THREAD

**Issue by rong4188** [museui/muse-ui#1218]
Hi,

I just found that mu-text-field text field event behavior is not matching the document. In document https://muse-ui.org/#/text-field-events it says the text field event is change, but I just can't make it work by using @change="onChange". Instead, I use @input="onInput" which works fine.

I am just not sure if this is an document issue or the incorrect behavior.

Thanks

**Comment by myronliu347** [comment]
Form Components default have  onInput
