### ISSUE TITLE
请教MuseUI组件字体、大小等如何实现自适应多尺寸设备

### ISSUE THREAD

**Issue by arthurzhang87** [museui/muse-ui#122]
请问如何实现MuseUI各组件在不同尺寸分辨率下的字体、大小等自适应？
相关组件均使用的默认字体，若需要修改字体如何进行（考虑到组件内部构成由多HTML DOM构成，如Flat Button只有labelClass的设置，可以调整label字体大小，但对应的icon大小如何设置）呢？

**Comment by myronliu347** [comment]
组件的样式、字体大小等都是根据material design设计文档来的，并不推荐修改，如果需要修改可以采用直接覆盖样式的方式
