### ISSUE TITLE
icon失效，只出现文字

### ISSUE THREAD

**Issue by HIKALU-Z** [museui/muse-ui#123]
用vue-cli构建项目后，使用npm安装。
按照官方的使用说明，做了一个appbar.
但是貌似icon不出现，出现的是文字，也没有提示报错。
![image](https://cloud.githubusercontent.com/assets/14190574/20825256/edfbc8d2-b89d-11e6-8e1f-02c8bb6c2424.png)
错误效果如图，是我哪里做的不对么？
不好意思，是个新手，麻烦知道的人告知我问题在哪？

**Comment by HIKALU-Z** [comment]
我还引入了bootstrap 和这个冲突么？

**Comment by HIKALU-Z** [comment]
不好意思，怪我自己没引入
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
我以为用组件的方式加载，就不需要引入这两个文件了。

**Comment by wishma2013** [comment]
遇到同样的问题！
