### ISSUE TITLE
mu-text-field类型问题

### ISSUE THREAD

**Issue by wakeupfive** [museui/muse-ui#1231]
<mu-text-field v-model="articleName" placeholder="Please input......" full-width></mu-text-field>
控制台一直输出Invalid prop: type check failed for prop "gutter". Expected Boolean, got Number.
这个是做了类型控制吗

**Comment by myronliu347** [comment]
没有这个参数， 只有 row组建才有gutter 参数，应该是其他代码使用上有问题
