### ISSUE TITLE
mu-load-more组件 @load函数没有执行😂

### ISSUE THREAD

**Issue by cunjif** [museui/muse-ui#1232]
mu-load-more组件的问题，之前测试的时候没有问题，@load事件下滑底部后可以执行，加载到数据。

但是在重启开发服务器，重新编译之后就失效了，在下滑到底端后，@load事件没有被执行，一脸懵逼ing。

>html部分
```
...
<div class="hide-scrollbar" ref="scrollWidget" v-show="!!db && !!db.data">
                <mu-load-more @refresh="refreshMore" :refreshing="refreshing" :loading="loading" @load="loadMore" 
                  loading-text="正在拼命加载中..." class="informs-loadmore">
                    <mu-list class="informs-list" textline="three-line">
                        <template v-for="(item, idx) in db.data">
...
```
>load函数
```
methods: {
    // 下滑加载数据
    loadMore() {
      console.log("test if run");
      if (this.loading) return;
      const tabidx = this.tabidx;
      this.loading = true;
      let resp = this.loadData({ tabidx }).then(data => {
        this.loading = false;
        if (data == 200);
```

**Comment by Piscen** [comment]
遇到同样问题

**Comment by myronliu347** [comment]
父元素上需要设置 `overflow: auto` 这样才能正确的找到滚动条奥

**Comment by myronliu347** [comment]
后期会考虑与better-scroll 结合

**Comment by LJYes** [comment]
css一定要加上，才能调`load`方法！
`.demo-loadmore-wrap {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
    }

    .demo-loadmore-content {
        flex: 1;
        overflow: auto;
        -webkit-overflow-scrolling: touch;
    }`
`demo-loadmore-wrap` 要加 `display: flex;`;
`.demo-loadmore-content` 要加 `flex: 1;`
