### ISSUE TITLE
data-picker :should-disable-date="allowedDates"     禁用多个日期怎么传递参数

### ISSUE THREAD

**Issue by vxy1142296352** [museui/muse-ui#1236]
<mu-container>
  <mu-flex wrap="wrap">
    <mu-paper :z-depth="1" class="demo-date-picker">
      <mu-date-picker  :should-disable-date="allowedDates" :date.sync="date3"></mu-date-picker>
    </mu-paper>
  </mu-flex>
</mu-container>   :should-disable-date="allowedDates"     禁用多个日期怎么传递参数

**Comment by myronliu347** [comment]
```javascript
export default {
  methods: {
    allowedDates (date) {
      return date.getDate() % 2 === 0
    }
  }
}
```
