### ISSUE TITLE
 Date Picker Scoped Slots里面几个参数怎么传

### ISSUE THREAD

**Issue by vxy1142296352** [museui/muse-ui#1238]
< mu-date-picker>
< template slot="day" slot-scope="{ selected, date, disabled, now}">
< div class="mu-day-button-bg">1</div>
< div class="mu-day-button-content">
< span class="mu-day-button-text">{{date.getDate()}}</span>
< span class="day-dot" v-if="date.getDate() % 3 === 0"></span>
<  /div>
<  /template>
<   /mu-date-picker>   
slot-scope="{ selected, date, disabled, now}"这几个参数怎么传

**Comment by myronliu347** [comment]
这些参数，是组件内部传递的哦,提供给需要应用的时候使用，

**Comment by vxy1142296352** [comment]
那个要具体怎么使用,能给个简单示例吗
