### ISSUE TITLE
Invalid self-closing tag 的问题

### ISSUE THREAD

**Issue by cmzz** [museui/muse-ui#124]
`Invalid self-closing tag: <mu-text-field hintText="Full Width" fullWidth />. This will be treated as the starting tag only in HTML5. Use <mu-text-field></mu-text-field> instead.`

使用的 webpack

**Comment by myronliu347** [comment]
vue-loader的版本不对吧

**Comment by cmzz** [comment]
@myronliu347  我的配置 "vue-loader": "^8.3.0"

**Comment by myronliu347** [comment]
muse ui是基于vue2.0，vue-loader现在需要对应vue的版本，你这个版本有点低了
