### ISSUE TITLE
muse-ui Form-Components not work in low IOS system 

### ISSUE THREAD

**Issue by Penggggg** [museui/muse-ui#1240]
muse-ui Form-Components（input/radio） not work in low IOS system. It can not be tab or click.
muse-ui的表单组件（input/radio等等）在低版本的IOS系统上，无法点击和运行。

- IOS 8 
- IOS 9

Muse-Ui supported IOS system above which version?
Muse-Ui最低支持哪个版本的系统呢？谢谢

Is it possible to fix it or do some compatibility work?
有可能修复或者通过什么办法做兼容呢？

tips: i add es6 polyfill.js but is not working as well.
备注：我加上了 es6 js polyfill，但依然无效

**Comment by myronliu347** [comment]
找不到报错信息，目前官网上的demo也无法定位这个问题，
个人判断：

没有绑定`v-model` 导致状态没有更新，
