### ISSUE TITLE
date-picker有个需求，日期翻页的时候禁用日期会失效

### ISSUE THREAD

**Issue by lazycms** [museui/muse-ui#1242]
![image](https://user-images.githubusercontent.com/4734975/48473898-68438900-e834-11e8-85ec-bedf23fda52f.png)
我的限制日期是个跨月的数组，翻页这个判断就失效了 ，请问有什么办法处理这个吗

**Comment by myronliu347** [comment]
请提供示例的demo， 正常翻页之后是不会失败的哦
