### ISSUE TITLE
vue cli 3.0 创建的项目 完全引入muse ui  在组件中无法使用this.$alert方法

### ISSUE THREAD

**Issue by Lneedy** [museui/muse-ui#1245]
import Vue from 'vue'
import App from './App.vue'
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
Vue.use(MuseUI)

error:
MessagesPage.vue?9b6f:122 Uncaught TypeError: this.$alert is not a function
    at VueComponent.alert (MessagesPage.vue?9b6f:125)
    at invoker (vue.runtime.esm.js?2b0e:2023)
    at HTMLDivElement.fn._withTask.fn._withTask (vue.runtime.esm.js?2b0e:1822)

json:
{
  "name": "vue-dog",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "muse-ui": "^3.0.1",
    "vue": "^2.5.17"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.5",
    "@vue/cli-plugin-eslint": "^3.0.5",
    "@vue/cli-service": "^3.0.5",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.8.0",
    "eslint-plugin-vue": "^5.0.0-0",
    "node-sass": "^4.10.0",
    "sass-loader": "^7.0.1",
    "vue-template-compiler": "^2.5.17"
  }
}

**Comment by myronliu347** [comment]
this.$alert 函数在 `muse-ui-message` 插件中嗑
https://muse-ui.org/#/zh-CN/message
