### ISSUE TITLE
muse-pagination 文档中样式错误

### ISSUE THREAD

**Issue by IWANABETHATGUY** [museui/muse-ui#1249]
![image](https://user-images.githubusercontent.com/17974631/48878701-88ca9f00-ee43-11e8-9d4e-0ffca0efcabf.png)
看了开发者模式是markdown中通用样式`magin-bottom:16px`，错误引用，删去后正常，可能需要覆盖其他的样式解决
![image](https://user-images.githubusercontent.com/17974631/48878731-a8fa5e00-ee43-11e8-9a47-7ac6a508e948.png)

**Comment by myronliu347** [comment]
fixed
