### ISSUE TITLE
mu-flex如果按需引用应该怎么设置？

### ISSUE THREAD

**Issue by tongwudi** [museui/muse-ui#1252]
import 'muse-ui/lib/styles/base.less';
import {Pagination} from 'muse-ui';
import 'muse-ui/lib/styles/theme.less';
Vue.use(Pagination);

在引用以下代码的时候会报**mu-flex没有注册**

\<mu-flex justify-content="center" style="margin: 32px 0;">\
    \<mu-pagination raised :total="1000" :current.sync="current"></mu-pagination>\
  \</mu-flex>

请问mu-flex如果按需引用应该怎么设置呢？

**Comment by myronliu347** [comment]
import { Grid } from 'muse-ui'
Vue.use(Grid);
