### ISSUE TITLE
mu-bottom-navigation底部组件添加自己的icon的问题

### ISSUE THREAD

**Issue by YuFy1314** [museui/muse-ui#1255]
```
<mu-bottom-nav-item value="movies" title="Movies" icon="ondemand_video"></mu-bottom-nav-item>
```
这个标签里面难道不可以包自己的标签么, 我想在底部导航中用自己的icon, 怎么做? @myronliu347

**Comment by Hlianfa** [comment]
自己加
`<mu-bottom-nav class="bottom-nav" :value.sync="shift">
      <mu-bottom-nav-item
        :class="icon"
      ></mu-bottom-nav-item>
    </mu-bottom-nav>` 
icon就是自己的图标，bottom-nav效果很好，但是拓展太差，很难受

**Comment by myronliu347** [comment]
icon=":fa fa-home" 
+ `:` 前缀使用外部（非material-design-icons）icon

**Comment by YuFy1314** [comment]
> 自己加
> `<mu-bottom-nav class="bottom-nav" :value.sync="shift"> <mu-bottom-nav-item :class="icon" ></mu-bottom-nav-item> </mu-bottom-nav>`
> icon就是自己的图标，bottom-nav效果很好，但是拓展太差，很难受

对, 确实扩展很差, 后来我自己写的, 下载了阿里icon的fonts, 很好用

**Comment by YuFy1314** [comment]
> icon=":fa fa-home"
> 
> * `:` 前缀使用外部（非material-design-icons）icon

好的, 有时间试一下

**Comment by machaosuper** [comment]
用slot插槽解决这个问题不好吗？
