### ISSUE TITLE
mu-form-item-label css

### ISSUE THREAD

**Issue by ChinaSor** [museui/muse-ui#1256]
我想在.vue组件中定制 表单输入框label的样式，但是无法在创建表单时指定css名称，也无法通过 `.mu-form-item-label` 选中label,请问有什么办法吗?
`<div class="mu-form-item-label">姓名:</div>`

**Comment by myronliu347** [comment]
你可以使用 form item 的 `label` slot

```html
 <mu-form-item prop="switch">
    <span slot="label">label</span>
 </mu-form-item>
```
