### ISSUE TITLE
手机火狐浏览器访问Muse-ui官网图标不显示

### ISSUE THREAD

**Issue by parabeyond008** [museui/muse-ui#1257]
自己本地搭建Muse-ui，电脑firefox浏览器显示图标正常，手机firefox浏览器访问图标不显示。
手机firefox 访问 https://muse-ui.org/#/zh-CN/bottom-navigation 图标也不显示

**Comment by myronliu347** [comment]
对material icons 的支持问题，可以使用一些方法解决的
https://material.io/icons
