### ISSUE TITLE
Filter autocomplete problem

### ISSUE THREAD

**Issue by fesnt** [museui/muse-ui#126]
Hello, I was experimenting and found a problem with the autocomplete filter. If i go to your demo https://museui.github.io/#/autoComplete on the filter section and digit "Mango" and then click on the word "Mango", it completes with the word "Apple" insted of "Mango". No matter how you filter, if you click on the first item it will always completes with "Apple".

Am I doing something wrong?

Many thanks!

**Comment by myronliu347** [comment]
Yes, This seems to be a problem, I need some time to fix 
Thanks

**Comment by myronliu347** [comment]
I fixed, please update

**Comment by fesnt** [comment]
Thank you very much!
