### ISSUE TITLE
2.0版本中的mu-list-item 在3.0中不支持自定义标签的递归了。希望解决

### ISSUE THREAD

**Issue by 80163916** [museui/muse-ui#1264]
<template>
  <mu-list-item :title="data.title" :toggleNested="!!data.childrens" :open="false" :to="data.path">
    <mu-icon :slot="data.iconSlot" :value="data.icon"></mu-icon>
    <MyListItem v-for="childItem in data.childrens"
                :style="{'text-indent': ccount + 'em'}"
                :count="ccount"
                :data="childItem"
                :key="childItem.title"
                :slot="childItem.itemSlot">
    </MyListItem>
  </mu-list-item>
</template>

自定义的MyListItem标签中使用<mu-list-item>递归，这段代码在3.0中不支持了。希望能够更新支持或者有类似的解决方案。

**Comment by myronliu347** [comment]
支持的，mu-list-item 依然支持nested slot 可以使用
