### ISSUE TITLE
表格组件无法自适应宽度

### ISSUE THREAD

**Issue by charleslo1** [museui/muse-ui#1273]
表格组件在父容器或浏览器宽度变宽的时候可以自适应，但在变窄的时候还是会保留之前的宽度导致表格溢出容器，看了代码好像是容器宽度变化时会自动设置 mu-table-header、mu-body-header 的宽度，但不知道为什么要这样做？目前是重写了 mu-table-header、mu-body-header 的样式解决了这个问题：

```
.mu-table-header,
.mu-body-header {
    width: auto !important;
}
```

**Comment by myronliu347** [comment]
这里是需要的吗，当列数过多时是需要移除的，然后横向滚动的，列数少的请空袭阿是可以自动适应的
