### ISSUE TITLE
如果解决在typescript中出现的$toast提示没定义问题

### ISSUE THREAD

**Issue by aohanhe** [museui/muse-ui#1276]
[我在vue-cli3中使用toast组件，引入后，编译时会报以下错误，但是是否要正常执行的。
`Property '$toast' does not exist on type 'HelloWorld'.
    13 |
    14 |   onClick () {
  > 15 |     this.$toast.message({
       |          ^
    16 |       message: '你好'
    17 |     })
    18 |   }`

我已经做了正确的引入，我需要怎么样才可以解决这个问题。谢了
`import Vue from 'vue'
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
import Toast from 'muse-ui-toast'

Vue.use(MuseUI)
Vue.use(Toast)`

**Comment by coldpc** [comment]
可以生命.d.ts文件

// ComponentOptions 声明于 types/options.d.ts 之中
declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    myOption?: string
  }
}

文档地址：
https://cn.vuejs.org/v2/guide/typescript.html

**Comment by myronliu347** [comment]
toast默认是有声明文件的奥，不知道是不是ts版本的原因

**Comment by myronliu347** [comment]
https://github.com/museui/muse-ui-toast
如果发现问题可以在这个项目里pr
