### ISSUE TITLE
请问 如果我想只引入Muse-UI的插件 可以吗

### ISSUE THREAD

**Issue by TheColdVoid** [museui/muse-ui#1277]
我想只引入Muse-UI的插件（比如Toast Message），但是不想引入UI库本身，那么我只import Muse-UI的Toast和Message插件 可以吗？

**Comment by myronliu347** [comment]
dist 下面有连个问题进
*.all.js
*.all.css

**Comment by TheColdVoid** [comment]
啥意思，没太听懂，求大佬解答。谢谢

**Comment by TheColdVoid** [comment]
是必须要import进来这两个文件吗
