### ISSUE TITLE
Ripple effect doesn't work in Firefox

### ISSUE THREAD

**Issue by sqal** [museui/muse-ui#128]
I have installed latest version of Firefox@50.0.2, os - Windows 10 and I don't see the ripple effect when clicking on the button or any other element that uses this effect. Any idea what may be causing this?

**Comment by linxiaowu66** [comment]
Hi, @sqal
I also installed the Firefox@50.0.2,  but i don`t find your issue. can you check your environment again?

![image](https://cloud.githubusercontent.com/assets/13563876/20965976/29d3daac-bcb3-11e6-8b58-06a84261eac8.png)

**Comment by linxiaowu66** [comment]
@myronliu347 

 Can you check this issue.  I indeed find the ripple effect is not work except the left navigation sidebar.

**Comment by myronliu347** [comment]
Problem in js, I'll repair as soon as possible, a little busy recently, so update slow...

**Comment by linxiaowu66** [comment]
@myronliu347 
you can assign some bugs to me. I will do my best to solve them even though I am not familiar with all components. Thus you can take it easy.

**Comment by myronliu347** [comment]
This a strange question，Can`t listen button mousedown event in firefox, I can't solve .

**Comment by sqal** [comment]
@myronliu347 Please check this answer http://stackoverflow.com/a/40975362/1451859 You can solve it by adding events manually to the parent element of TouchRipple component. Here's my code which I modified a little bit for my own use https://gist.github.com/sqal/6c8d4d859897b2adc091426857fdc14c

**Comment by myronliu347** [comment]
I try ....
