### ISSUE TITLE
引用了cdn的vue就会报错

### ISSUE THREAD

**Issue by lifetin** [museui/muse-ui#1280]
把vue放在index.html中,通过cdn加载, 然后在开发环境会报错  
![44](https://user-images.githubusercontent.com/10474968/50441276-e6677500-0934-11e9-8a6c-ed26830bb2b2.png)
![11](https://user-images.githubusercontent.com/10474968/50441292-0008bc80-0935-11e9-909e-535cab339e8c.png)
![33](https://user-images.githubusercontent.com/10474968/50441293-0008bc80-0935-11e9-98c8-c26d23130fbd.png)

**Comment by leonafricain** [comment]
Que dalle

**Comment by myronliu347** [comment]
不是cdn 的问题，而是说vue在开发环境中的vue引入是否正确，我们的官网上的demo在jsffidle里运行就是使用的cdn 的资源
https://muse-ui.org/#/zh-CN/bottom-navigation
需要你检测下这个cdn上的vue的具体问题
