### ISSUE TITLE
v3.0.1官网版本 Message弹框组件问题

### ISSUE THREAD

**Issue by ziyi2** [museui/muse-ui#1289]
![image](https://user-images.githubusercontent.com/13852687/50681723-7305e780-1047-11e9-8d2e-cd3730437dd6.png)

连续按回车键Enter会不断的弹出新的重复的提示框。

**Comment by cdll** [comment]
这个估计是因为你页面焦点还停留在Modal下层的Button上, 回车和空格都能持续触发Button的Click的

**Comment by ziyi2** [comment]
意思是这个不需要解决么，比如我点击了按钮，然后弹出了提示框，那么我就不能按回车去触发 知道了 按钮么，是不是聚焦一下比较好

**Comment by ziyi2** [comment]
> 这个估计是因为你页面焦点还停留在Modal下层的Button上, 回车和空格都能持续触发Button的Click的

意思是这个不需要解决么，比如我点击了按钮，然后弹出了提示框，那么我就不能按回车去触发 知道了 按钮么，是不是聚焦一下比较好

**Comment by myronliu347** [comment]
恩恩，确实是个问题，
