### ISSUE TITLE
全屏loading组件

### ISSUE THREAD

**Issue by yufengkz** [museui/muse-ui#1293]
muse-ui-loading.esm.js?d4ea:117 Uncaught TypeError: Cannot read property '$el' of null at eval (muse-ui-loading.esm.js?d4ea:117)
loading.$el.parentNode && loading.$el.parentNode.removeChild(loading.$el); 这行代码报错，页面切换太快就会出现这个问题，但是我把定时器注掉以后就没有这个问题了，小白不懂事什么原因。麻烦帮我看下。

**Comment by myronliu347** [comment]
如果把loading全屏的代码写在某一个组件中，需要将在这个组件被移除的时候将定时器去掉，因为的你的loading绑定在 `this` 上，被移除的时候 `this` 对象不存在了，所以会报错
