### ISSUE TITLE
mu-button组件的textColor属性问题

### ISSUE THREAD

**Issue by cdll** [museui/muse-ui#1294]
-----
museUI: v3.0.1
vuejs: v2.5.22
browser: Chrome 71.0
-----
貌似``mu-button``组件的``textColor``没有作用在内部的``.mu-button-wrapper``中, 虽然可以再自定义内部``.mu-button-wrapper``的样式解决, 但组件内部是否考虑修复下. 感谢!

**Comment by myronliu347** [comment]
不需要作用到`mu-button-wrapper` 上的，color 属性默认会 'inherit' ，所以在button最外层标签上设置就好了
