### ISSUE TITLE
切换主题后部分组件的颜色没有变化

### ISSUE THREAD

**Issue by Ice-Hazymoon** [museui/muse-ui#1298]
使用的默认主题`light`，切换到`dark`以后Dialog的背景颜色还是白色，里面的样式没有变化，也没有自己设置过样式，文档里确是正常的，自己本地就出现这种问题，Checkbox也遇到过这样的情况

**Comment by obtus** [comment]
我用mu-card也遇到了同样的情况.

**Comment by myronliu347** [comment]
组件的import 要放到theme.use 的前面，
