### ISSUE TITLE
关于字体的引用问题

### ISSUE THREAD

**Issue by challengeYY** [museui/muse-ui#1306]
[![snipaste20190227_145800.jpg](https://i.loli.net/2019/02/27/5c76355c616fa.jpg)](https://i.loli.net/2019/02/27/5c76355c616fa.jpg)

作为vue新手，从网上找不到怎么替换成本地的方法。
googleapi在国内是被墙的，必须替换成其他的。
暂时只能将ui库换成其他的试试，这个字体的问题无法解决，只能放弃。
请教老手，这个替换的方法，万分感谢。解决这问题能为国内用户提供很大方便。

**Comment by myronliu347** [comment]
Robot 字体
```bash
npm install typeface-roboto --save
```
```js
import 'typeface-roboto'
```

**Comment by myronliu347** [comment]
图标

https://github.com/google/material-design-icons
