### ISSUE TITLE
list

### ISSUE THREAD

**Issue by elisangelacarla** [museui/muse-ui#131]
Good Morning,
I need to click on the button, the subitems in the list are closed. The open property must be set to false. However when setting the property on the button onclick the list remains open. Is there an example of how I can solve it?

Regards,
Elisangela

**Comment by elisangelacarla** [comment]
Can anyone help me with example of how to change the list open property in button onclick?

**Comment by myronliu347** [comment]
Good Morning, Can you give me some code as a reference, I don't quite understand what you mean

**Comment by myronliu347** [comment]
ListItem have `click` event

**Comment by elisangelacarla** [comment]
I need to run the onlick event from listitem on another button. In other words, the same event triggered by the itemclick will have to be triggered when clicking another component (button). thanks

**Comment by elisangelacarla** [comment]
<div id="sideNav">
    <ul>
      <mu-list :value="8" @change="handleChange">

        <mu-list-item :value="2" title="Compras">
            <mu-icon slot="left" value="shopping_basket"/>
        </mu-list-item>
        <mu-list-item :value="3" title="Faturamento">
          <mu-icon slot="left" value="insert_chart"/>
        </mu-list-item>
        <mu-list-item :value="4" title="Financeiro">
          <mu-icon slot="left" value="attach_money"/>
        </mu-list-item>
        <mu-list-item :value="5" title="Manutenção">
          <mu-icon slot="left" value="account_box"/>
          <mu-badge content="10" class="demo-icon-badge" circle secondary></mu-badge>
        </mu-list-item>

       <mu-list-item  :value="6" title="teste 2" toggleNested :open="abre" >
          <mu-icon slot="left" value="dns"/>
          <mu-list-item :value="7"  title="Ficha Técnica"  id="id" slot="nested" ></mu-list-item>
        </mu-list-item>

        <mu-list-item  :value="6" title="teste" toggleNested :open="abre">
          <mu-icon slot="left" value="dns"/>
          <mu-list-item :value="7"  title="Ficha Técnica"  id="id" slot="nested" ></mu-list-item>
        </mu-list-item>
     
        <mu-list-item :value="6" title="Manufatura" toggleNested :open="abre" >
          <mu-icon slot="left" value="dns"/>
          <mu-list-item id="um" :value="7" title="Ficha Técnica"  slot="nested" ></mu-list-item>
        </mu-list-item>
       
      </mu-list>
    </ul> 
  </div> 
This is my list

**Comment by elisangelacarla** [comment]
<mu-raised-button class="demo-raised-button"  icon="format_list_bulleted"@click="clikitemlist()"/>
, this is my button, I need in the onclik of my button the event of the click of the itemlist to be triggered

**Comment by elisangelacarla** [comment]
Methods () {
  Clikitemlist: function () {

     Here I need to call the click event of the item list
  }
}

**Comment by myronliu347** [comment]
you can look here [demo](https://jsfiddle.net/6ycjb9z1/)

**Comment by elisangelacarla** [comment]
Worked, thank you.

**Comment by elisangelacarla** [comment]
thank you for help. works.
