### ISSUE TITLE
Button英文自动大写BUG

### ISSUE THREAD

**Issue by favouriter** [museui/muse-ui#1315]
<mu-button @click="changeTheme('dark')">dark</mu-button>
  <mu-button @click="changeTheme('light')">light</mu-button>
  <mu-button @click="changeTheme('teal')">teal</mu-button>
  <mu-button @click="changeTheme('carbon')">carbon</mu-button>

显示的英文单词全部变成大写，这是为什么

**Comment by favouriter** [comment]
DARK, LIGHT, TEAL, CARBON

**Comment by myronliu347** [comment]
material design 规定button全部都要大写
