### ISSUE TITLE
muse-ui在ios9浏览器不兼容

### ISSUE THREAD

**Issue by HoraceYu** [museui/muse-ui#1320]
vue-cli3开发使用muse-ui，在ios9手机浏览器中一片空白。然后用模拟器查看了下，发现报错。
“Unexpected keyword 'const'. Const declarations are not supported in strict mode.”
然后一查是在muse-ui的js里面有es6的语法。而cli3使用的babel.config.js，又不会做include写法....然后就不支持ios9了

**Comment by myronliu347** [comment]
这个是环境的问题

**Comment by myronliu347** [comment]
应该是引用了src目录下的东西吧
