### ISSUE TITLE
mu-date-input 点击年份popover自动关闭（autoclose）

### ISSUE THREAD

**Issue by vivayue** [museui/muse-ui#1327]
![image](https://user-images.githubusercontent.com/11346163/54822440-e252b580-4cdf-11e9-87e7-18ff9e66f28f.png)
muse-UI 3.0.1和3.0.2都存在此问题

**Comment by vivayue** [comment]
不好意思，是我这边依赖没安装全的问题

**Comment by carller0302** [comment]
什么依赖，我也遇到这个问题

**Comment by carller0302** [comment]
> 不好意思，是我这边依赖没安装全的问题

什么依赖，我也遇到这个问题

**Comment by localvar** [comment]
> 不好意思，是我这边依赖没安装全的问题

我也遇到同样的问题，麻烦告知是什么依赖，谢谢

**Comment by chi1010860** [comment]
請問這個問題怎麼解決，感謝

**Comment by vivayue** [comment]
重新安装mu-ui依赖即可

**Comment by localvar** [comment]
> 重新安装mu-ui依赖即可

我使用的是CDN方式，实在不知道依赖缺的是哪个

**Comment by Sun79** [comment]
在src/DateInput/DateInput.js文件256行后新增一行阻止click事件冒泡就没问题了。
```js
on: {
  close: this.closePicker,
  click: e => { e.stopPropagation() }
}
```
