### ISSUE TITLE
Pagination 的 bug 

### ISSUE THREAD

**Issue by chenzhenjia** [museui/muse-ui#133]
@linxiaowu66
`
    {{users.totalElements}}<br>
    {{current}}<br>
    {{users.size}}<br>
    <mu-pagination :total="users.totalElements" :current="current" :defaultPageSize="3"
                   :pageSize="users.size"></mu-pagination>
`
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1fagw4bbd65j20o207smx7.jpg)

:total 里面 里面应该是总数，而不是一共多少页，文档有错误描述，

看了一下源代码，pagination.vue 里面的代码已经改了，我用的是 2.0.0-alpha.11 不知道为什么 mu-pagination 还是有bug

**Comment by linxiaowu66** [comment]
@chenzhenjia  

你指的分页的bug是上图中显示的页码不全是吗？

我最新修改的代码在0.11版本上还没有，所以需要等下一个版本看看是否有修复，
文档的话我立马更新。

多谢。。。

**Comment by linxiaowu66** [comment]
![image](https://cloud.githubusercontent.com/assets/13563876/20918433/f2be5c40-bbd1-11e6-82a3-b19adf88d7e4.png)

![image](https://cloud.githubusercontent.com/assets/13563876/20918442/fce341ae-bbd1-11e6-80d9-6cee0b8c59b9.png)

新版本没有这个问题哈，所以等等新版本发布哈，实在不好意思了 @chenzhenjia

**Comment by chenzhenjia** [comment]
恩
