### ISSUE TITLE
请问什么时候支持vue3？在vur3环境下没有波纹效果

### ISSUE THREAD

**Issue by zjh4473** [museui/muse-ui#1338]
如题，什么时候会支持vue3？

**Comment by nszbf** [comment]
@zjh4473  vue3？？？？？？

**Comment by zjh4473** [comment]
@nszbf 可能是我阐述不正确。我的vue-V显示的是3.5.3

**Comment by nszbf** [comment]
@zjh4473  那是vue-cli3，那跟你用的啥框架没关系

**Comment by zjh4473** [comment]
@nszbf 但是我确实试了好久都搞不定这个。。不知道为什么波纹就是无效。
