### ISSUE TITLE
怎样修改flatbutton的字体大小宽度这些样式？

### ISSUE THREAD

**Issue by whatya** [museui/muse-ui#134]
重写class样式只是宽度和字体颜色有效，其他样式不起作用

**Comment by myronliu347** [comment]
可以了利用`labelClass` 这个属性，加一些额外的字体样式，宽度这些 :class 绑定样式即可

**Comment by CHEN-DONG** [comment]
能具体举个例子么 我怎么绑定了 还是不好用 改不了字体大小

**Comment by arnoldgithub** [comment]
我有相同的情況，就是綁定了後，沒有反應。
我用的 code 是:

`<template>
	<mu-flat-button label="Default" class="demo-flat-button" :labelClass="myLabelClass"/>
</template>

<script>
computed: {
	myLabelClass() {
		return 'my-label-class'
	}
}
</script>

<style>
.my-label-class {
	font-style: x-large;
}
</style>`
