### ISSUE TITLE
Vue完全导入MuseUI，提示MuseUI is not defined

### ISSUE THREAD

**Issue by HscongDrect** [museui/muse-ui#1341]
这是引入的依赖：
![image](https://user-images.githubusercontent.com/19298348/55545851-b3393c80-5700-11e9-918a-ffe16c788f75.png)
导入方式：
![image](https://user-images.githubusercontent.com/19298348/55545921-da900980-5700-11e9-8fba-4d0faa42af45.png)
报错：
![image](https://user-images.githubusercontent.com/19298348/55545954-e976bc00-5700-11e9-89ba-135482f1d279.png)

单独导入组件是可以的

**Comment by HscongDrect** [comment]
问题解决了，是因为我加了按需导入的代码没注释掉
![image](https://user-images.githubusercontent.com/19298348/55547558-20020600-5704-11e9-99a7-03ced7b2af67.png)
注释掉就好了
![image](https://user-images.githubusercontent.com/19298348/55547587-314b1280-5704-11e9-80b5-add80949ba23.png)

**Comment by Yakima-Teng** [comment]
这是啥场景，你都配置了支持按需导入为啥还要改成整体导入？
