### ISSUE TITLE
2.0.0-alpha.11 的 mu-select-field bug

### ISSUE THREAD

**Issue by chenzhenjia** [museui/muse-ui#136]
```
<mu-select-field value="-1" label="选择框" fullWidth @change="change">  
  <mu-menu-item v-for="d, index in data" :value="d.id" :title="d.title"/>  
</mu-select-field>  
```
结果是这样的:
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1fahztwyv70g20wc06wjsq.gif)
但是加上一行 `<mu-menu-item value="-1" title="请选择"/>` 就可以选择上去。
```
<mu-select-field value="-1" label="选择框" fullWidth @change="change">  
  <mu-menu-item value="-1" title="请选择"/>  
  <mu-menu-item v-for="d, index in data" :value="d.id" :title="d.title"/>  
</mu-select-field>  
```

**Comment by myronliu347** [comment]
提示内容可以使用`hintText`

**Comment by chenzhenjia** [comment]
@myronliu347 我要说明的不是提示内容 ，而是 item 选择后不会更新到框上的bug。加上一个写死的 item 则可以更新。

**Comment by chenzhenjia** [comment]
@myronliu347 我又发现一个新的bug ，同样是 mu-select-field 的，使用 :errorText 后bug
![](http://ww1.sinaimg.cn/large/65e4f1e6gw1fai8w48m1pg20wk09gtce.gif)
同样选择后不会出现在框上

**Comment by myronliu347** [comment]
我已经修复这个bug，请更新
