### ISSUE TITLE
drawer 中的open参数有问题

### ISSUE THREAD

**Issue by nbslr** [museui/muse-ui#137]
[Vue warn]: Invalid prop: type check failed for prop "open". Expected Boolean, got Function. 
(found in component <mu-drawer>)
---------------------------------------------------
 
<mu-drawer :open="open" :docked="docked" @close="toggle()">
      <mu-list @itemClick="docked ? '' : toggle()">

        <mu-list-item title="Menu Item 1"/>
        <mu-list-item title="Menu Item 2"/>
        <mu-list-item title="Menu Item 3"/>

        <mu-list-item v-if="docked" @click.native="open = false" title="Close"/>
      </mu-list>
    </mu-drawer>
 data () {
    return {
	  open: false,
      docked: true
    }
  },
 methods: {
toggle (flag) {
      this.open = !this.open
      this.docked = !flag
    }
}

**Comment by timeswind** [comment]
你会不会写了个名字叫open的function在methods里

**Comment by myronliu347** [comment]
请在 [jsfiddle](https://jsfiddle.net/)里给出demo，现在目测原因应该是你在methods里写了个open的 function

**Comment by nbslr** [comment]
里面，存在open函数，重复了，现在可以了，谢谢
