### ISSUE TITLE
textField上提示文字的问题

### ISSUE THREAD

**Issue by autopanda** [museui/muse-ui#139]
如果在单行的textField里面用鼠标左键按住**提示文字和浮动标签**(div.mu-text-field-hint, div.mu-text-field-label)这个范围的话，focus会变成false，但是松开鼠标左键之后，focus会变回true。这样会使得点击**提示文字和浮动标签**区域会再播放一次hr.mu-text-field-focus-line的伸缩动画。

win10 1607/54.0.2840.99 m/2.0.0-alpha.11

![](https://cloud.githubusercontent.com/assets/21982034/20955324/5fc1937e-bc7d-11e6-97fd-e3246edb6215.png)

**Comment by myronliu347** [comment]
我会尽快修复

**Comment by myronliu347** [comment]
已修复，请更新下
