### ISSUE TITLE
Toast弹出动画没有，消失动画是有的

### ISSUE THREAD

**Issue by caodahui** [museui/muse-ui#1391]
Toast弹出动画没有，消失动画是有的

**Comment by caodahui** [comment]
问题已经找到，与 #1322 问题一样，是vue版本导致的transitions动画，需要加上appear: true属性、
解决方案：lib/internal/transitions.js：加上 context.data.props['appear'] = true

**Comment by gabrielxvx** [comment]
加了还是不行
