### ISSUE TITLE
Unknown custom element

### ISSUE THREAD

**Issue by hellinnocence** [museui/muse-ui#14]
Unknown custom element: <mu-appbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
Vue 2.0
用 npm install muse-ui -S

**Comment by myronliu347** [comment]
我还没发布，这个名字只是占个位

**Comment by hellinnocence** [comment]
赶紧发布体验一下

**Comment by myronliu347** [comment]
文档还差一些，写完了就准备发布了

**Comment by BubblyPoker** [comment]
等不及了，等不及了，等不及了，说三遍了>_>
