### ISSUE TITLE
js 报错

### ISSUE THREAD

**Issue by cmzz** [museui/muse-ui#141]
错误:
> Uncaught TypeError: hook.Vue.util.classify is not a function
> TypeError: hook.Vue.util.classify is not a function(…)
> Uncaught TypeError: Cannot read property 'reload' of null

安装: 
`import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
Vue.use(MuseUI)`

使用:
`      <mu-text-field label="手机号" v-model="user.mobile" labelFloat/><br/>
      <mu-text-field label="登录密码" v-model="user.password" type="password" labelFloat/><br/>
      <mu-raised-button :disabled="disabled" v-bind:label="loginButtonTitle" class="demo-raised-button" primary/>`

问题：
页面表单的效果出来了， 但是js出问题

**Comment by myronliu347** [comment]
可以在 [jsfiddle](https://jsfiddle.net/) 里写下么，这里好调试
资源可用

https://unpkg.com/muse-ui/dist/muse-ui.js
https://unpkg.com/muse-ui/dist/muse-ui.css
