### ISSUE TITLE
[Checkbox] 无法自定义颜色，希望能加个checked的prop自定义开关

### ISSUE THREAD

**Issue by timeswind** [museui/muse-ui#142]
用redux和vuex不能直接用v-model经行数据绑定，希望能加个checked的prop自定义开关

**Comment by myronliu347** [comment]
跟vuex处理方式一样

```html
<mu-checkbox :value="value" @input="changeValue" />
```

至于自定义颜色，这个代码我早就提交了，只不过最近入职太忙，还有些内容没有完成没法版本，会在周末或者下周一发下一个版本
