### ISSUE TITLE
Get the multi-selected item in table component?

### ISSUE THREAD

**Issue by chenyiqiao** [museui/muse-ui#145]
When switch the `multiSelectable` prop in table component to true, I can multi-select items,which is pretty nice.But the items selected saved in the `tbody` components's data field `selectedRows` can be really confusing.

 In `tr` component:

```js
let uuid = 1;

export default {
  // ...
  data () {
    return {
      hover: false,
      rowId: 'tr-' + uuid++
    }
  }
}

```

What's the point of `uuid`? In my opinion, It's straightforward if i can transfer a variable as `tr`'s prop, the variable here can be a index of the selected rows of data, or id that specify this row of data. Whatever it is, it   should serve as the rowId, siginifies the items that i've chosen.

For exmaple, say i can write a template like this:

```html
<mu-thead>
  <mu-tr>
    <mu-th>name</mu-th>
  </mu-tr>
</mu-thead>
<mu-tbody>
  <mu-tr v-for="(role, idx) in roles" :rowId="role.id">
    <mu-td>{{role.name}}</mu-td>
  </mu-tr>
</mu-tbody>
```

and my list of data : 

```js
var data = [
  {
     id: 'a',name:'Arnold'
  },
  {
    id: 'b', name: 'Bernard'
  },
  {
    id: 'd', name: 'Dolores'
  }
]
```

When i choose the first two of them,i want the `selectedRows` to be :

```
['a', 'b']
```

rather than 

```
['tr-213', 'tr-214']
```

In this case, I can get `['a', 'b']` in `tbody` as `selectedRows`,which i can pickup and use right away.

**Comment by myronliu347** [comment]
The rowId in internal use only, You get selectRows is row index

**Comment by myronliu347** [comment]
Use uuid, because the tr index will change in some cases

**Comment by chenyiqiao** [comment]
firstly, the tr in thead also has a rowId so that the first tr in tbody has a rowId of `tr-2`, which is wrong. 

Secondly, say i have a lot of tables in it my SPA, when i navigate from page to page,as several tables appears, the rowId just add up as if a table has a lot a lot of rows,unless i refresh the page. Maybe all of the `tr`s share the uuid and that's incorrect. As for this,you can check [Table](https://museui.github.io/#/table), when you select rows in the second table, the `rowId` actually starts from `tr-7`.

**Comment by myronliu347** [comment]
太长了，有道翻译不准确，我就打中文了。
yes, 必须保证 rowId 唯一, 至于为什么不用rowIndex,因为在某些操作如排序这些，或者删除某行是，rowIndex是会发生变化的，这样的话可能导致一些错误。现在的版本在外部是获取不到rowId的，只能拿到选择行的index.
