### ISSUE TITLE
appbar中 将text-filed组件分发到slot=“default”中，在手机上无法正常显示input内容

### ISSUE THREAD

**Issue by jaweii** [museui/muse-ui#147]
如题

是在手机上

不是在chrome中调成手机窗口

是不是bug？

**Comment by myronliu347** [comment]
请给个demo [jsfiddle](https://jsfiddle.net/)

**Comment by jaweii** [comment]
@myronliu347 https://jsfiddle.net/ufuLsu79/5/
在手机上才会出现！

**Comment by myronliu347** [comment]
手机型号也给我下我，这里似乎没有这个问题
。

**Comment by jaweii** [comment]
iphone se的
