### ISSUE TITLE
为啥全局安装没法使用

### ISSUE THREAD

**Issue by bajian** [museui/muse-ui#155]
任何muse组件都没法用，比如报错：
vue.common.js?c736:519
[Vue warn]: Error when rendering component <mu-text-field>: 
vue.common.js?c736:2961
Uncaught TypeError: e._h is not a function

安装过程
1、vue init webpack my-project 然后安装对应依赖，vue可以跑起来，Ready. Detected Vue 2.1.5.
2、npm install --save muse-ui 提示缺少peerDependency keycode
3、全局安装
```
import Vue from 'vue'
import App from './App'

import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
Vue.use(MuseUI)

```

4、App.vue 直接用
<mu-text-field icon="search" class="appbar-search-field"  slot="right" hintText="请输入搜索内容"/>

然后就报错了。。。我安装上keycode2.1.7也没用，我感觉没啥问题啊？捣鼓了一下午未果

电脑windows8.1

  "dependencies": {
    "muse-ui": "^2.0.0-beta.1",
    "vue": "^2.1.0",
    "keycode": "^2.1.7"
  },

**Comment by linxiaowu66** [comment]
能否将你的代码上传到github上 我帮你看看

**Comment by bajian** [comment]
https://github.com/bajian/musetest
 上传到这个了，麻烦帮我看下，谢谢！

**Comment by javaSwing** [comment]
楼主，我也是这个问题，是不是你们发布到NPM上的程序有问题啊！
![image](https://cloud.githubusercontent.com/assets/7713463/21141988/f9203f5a-c17a-11e6-8460-27ad715272e0.png)

**Comment by myronliu347** [comment]
2.1是有这个问题，需要使用最新的vue-loader重新打包，晚上网速不好，明早重发版本，抱歉了

**Comment by myronliu347** [comment]
已经重发了版本，请更新
