### ISSUE TITLE
Refresh Control 组件直接用官方上例子copy到项目上不起效

### ISSUE THREAD

**Issue by KeithMo0425** [museui/muse-ui#156]
我直接用官网上的例子代码copy到项目上，没有任何改变，但不起效。拖动的动画效果没有用，导致没有触发事件

**Comment by KeithMo0425** [comment]
我用的是beta.1版本，那位大神能帮我解答下

**Comment by myronliu347** [comment]
请给在 [jsfiddle](https://jsfiddle.net/) 上写个demo
资源可用

https://unpkg.com/muse-ui/dist/muse-ui.js
https://unpkg.com/muse-ui/dist/muse-ui.css

https://unpkg.com/vue

**Comment by KeithMo0425** [comment]
我找到影响的原因，是因为我把整个项目的px 转 rem导致的。请问这有办法解决吗？

**Comment by myronliu347** [comment]
给我点时间，rem我不是特别熟

**Comment by myronliu347** [comment]
scroller没有指定对，https://jsfiddle.net/fgLftsjg/1/ 我改了下，你看看

**Comment by F-loat** [comment]
嗯，示例没问题了，Vue2中是应该使用this.$refs.scroller.$el对吧，实际应用中scroller的高度不定的话怎么绑定，不设置或者手动设置为window都无效
https://jsfiddle.net/Float_/fgLftsjg/2/

**Comment by F-loat** [comment]
按照现在的计算方式，如果scroller为默认值window的话，好像是不能正确判断是否滚动到了底部的，希望能改善一下，我先用别的办法解决下吧
``` javascript
    if (this.loading) return
    const scroller = this.scroller
    let h = scroller.scrollHeight - scroller.scrollTop - 5
    let sh = scroller.offsetHeight
     if (h <= sh) {
       this.$emit('load')
     }
```
