### ISSUE TITLE
更新到beta.2 有报错

### ISSUE THREAD

**Issue by bigezhang** [museui/muse-ui#160]
升级到beta.2 后有若干组件报错
[Vue warn]: Error when rendering component <mu-appbar>: 
[Vue warn]: Error when rendering component <mu-flexbox>:

**Comment by myronliu347** [comment]
这次用了vue2.1*打包因为低版本打包的文件，在2.1+上不能跑，你可以尝试更新下你的vue，
似乎是vue-loader更新后出现的问题
