### ISSUE TITLE
mu-select-field这个控件如何才能做到点击下拉时加载数据呢？

### ISSUE THREAD

**Issue by mythbobo** [museui/muse-ui#164]
这个组件只有input跟change事件。。而且事件都跟item有关，如果我现在需要点击下拉再异步加载数据应该如何做呢？
另有一个问题，DatePicker组件能不能增加一个inline属性，直接显示在页面上。现在都是弹出来选择。。而且好像状态是用的v-if来控制,我想用样式修改都不行。。

**Comment by myronliu347** [comment]
selectField目前不支持下拉异步加载数据，datePicker是弹出显示，你想要的应该是calendar，如果只是出现的话，只需要让输入框focus即可。
最近事情有点多，所以回复晚了，实在抱歉。
