### ISSUE TITLE
由2.0.0-beta.1升级2.0.0-beta.2后，flex-box出错

### ISSUE THREAD

**Issue by arthurzhang87** [museui/muse-ui#167]
如题，升级后，原来使用的flex-box出现错误。经查，flex-box相关的vue文件并无变化 ，请问出错的原因可能在哪里。
![default](https://cloud.githubusercontent.com/assets/21171005/21300006/b755efba-c5db-11e6-8062-e9c3fac957ff.png)

**Comment by linxiaowu66** [comment]
你可以参考这个issue的回答：https://github.com/museui/muse-ui/issues/160

应该是vue-loader的问题 尝试更新一下vue的版本

**Comment by arthurzhang87** [comment]
@linxiaowu66 经检查，已经是最新的vue及vue-loader。作者的意思可能是他用的vue-loader版本比较低，高版本的vue-loader加载vue组件时出错了。我暂时使用2.0.0-beta.1版本，等作者使用高版本vue-loader重新打包后再升级。

**Comment by myronliu347** [comment]
升级到beta2之后，需要使用2.1+的版本的vue,
之前就是有人说beta.1在vue2.1+的版本上用不了，我才重新打包发的beta.2
