### ISSUE TITLE
安卓手机无法显示icon

### ISSUE THREAD

**Issue by nextdooroldwang** [museui/muse-ui#169]
如题，crome模拟和ios真机显示效果都正常，但是安卓的手机所有icon都不显示，请问是什么情况？

**Comment by linxiaowu66** [comment]
你的icon是使用内置的还是直接从谷歌的CDN下载下来的？

**Comment by nextdooroldwang** [comment]
@linxiaowu66 `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`
直接引用的

**Comment by myronliu347** [comment]
有些手机浏览器上对一部分链接会拦截，还是推荐下载下来使用
