### ISSUE TITLE
大赞alpha上线！refresh control和ripple效果有冲突

### ISSUE THREAD

**Issue by beeplin** [museui/muse-ui#17]
在手机上过了一遍doc demo，别的都没什么问题，很赞。只是refresh control在下拉都不时候，被按中的条目也会出water ripple效果，看起来很怪。

**Comment by myronliu347** [comment]
很多地方，没有仔细的使用和调整，所以先发个alpha 版本试试水，然后再改

**Comment by beeplin** [comment]
嗯，起点已经相当高了。大家一起试用，一起捉bug。我发现你这个是desktop和mobile通吃的ui框架啊，一个人要干掉element和mint两家的节奏，哈哈。
为啥上来就是2.0.0 alpha呢？

**Comment by myronliu347** [comment]
大部分内容是仿 material-ui 的，跟大牛们的作品还是有差距的, 2.0主要是跟随 vue 的版本号

**Comment by lqixv** [comment]
恭喜恭喜。。。。。。。。。。
