### ISSUE TITLE
需求: 警告提示框等辅助组件

### ISSUE THREAD

**Issue by cmzz** [museui/muse-ui#170]
考虑增加警告提示框等辅助组件

可参考:
https://www.iviewui.com/components/alert
https://www.iviewui.com/components/message

**Comment by myronliu347** [comment]
可以放在2.1版本内加上

**Comment by xiaobebe** [comment]
这个加上了么。。同需求

**Comment by myronliu347** [comment]
https://www.muse-ui.org/#/zh-CN/alert
