### ISSUE TITLE
引入muse ui 使用部分组件报错

### ISSUE THREAD

**Issue by syun0216** [museui/muse-ui#171]
![2016-12-21 9 29 35](https://cloud.githubusercontent.com/assets/18444325/21374227/2d31c670-c760-11e6-88b5-762995e64750.png)

求解答

**Comment by myronliu347** [comment]
请给出vue 和museui的版本

**Comment by syun0216** [comment]
"vue": "^2.1.0",
"muse-ui": "^2.0.0-beta.3",

**Comment by bigezhang** [comment]
"vue": "^2.1.3",
"muse-ui": "^2.0.0-beta.3",
"vue-loader": "^10.0.1",
遇到同样的问题，请问下应该选择哪个版本？
ps: 之前 muse-ui 使用alpha.10 版本一切正常

**Comment by myronliu347** [comment]
vue的版本需要更新，我只是升级了一下vue-loader 发现之后版本好像有问题

**Comment by syun0216** [comment]
"vue": "^2.1.6",
"vue-template-compiler": "^2.1.6",
更新就可以用了，谢谢！
