### ISSUE TITLE
日期框最大时间bug

### ISSUE THREAD

**Issue by mengyubo** [museui/muse-ui#172]
设置了最大时间如果是2016-12-01，但是今天的时间是2016-12-21，这个时候如果点击确定按钮，选择的时间是今天的时间2016-12-21，超过了最大时间2016-12-01

建议，如果控件的当前时间也要参照最大最小时间进行设置

**Comment by myronliu347** [comment]
多谢，我会尽快处理

**Comment by linxiaowu66** [comment]
问题已经修复。 参考PR173

**Comment by myronliu347** [comment]
#173
