### ISSUE TITLE
Dialog弹框在PC上显示模糊

### ISSUE THREAD

**Issue by xiangle** [museui/muse-ui#176]
删除CSS动画后显示清晰，可是这样居中就没有了
也可能是我的高分屏兼容性问题，没有测试过其它设备

**Comment by myronliu347** [comment]
能截图么 ？

**Comment by xiangle** [comment]
![a](https://cloud.githubusercontent.com/assets/23191144/21418034/813ceb4c-c859-11e6-8c85-107b06cf2003.png)
![b](https://cloud.githubusercontent.com/assets/23191144/21418038/9209a168-c859-11e6-9524-802410e02155.png)

**Comment by myronliu347** [comment]
ok, 那这个问题就跟  #174  这个解决方式一样，我最近会重构下这个组件，你可以关注这个issue #174
