### ISSUE TITLE
iconButton 按钮第一次进来2次点击才触发

### ISSUE THREAD

**Issue by HopeFE** [museui/muse-ui#179]
1.首页的
![image](https://cloud.githubusercontent.com/assets/22955719/21419296/c3019e58-c861-11e6-95c6-60a29a4f1e03.png)这个 iconButton 在手机模式下 ，第一次进来需要点2次，才能触发点击事件。 

2.建议作者 将material-icon换一个CDN，谷歌的比较卡
推荐bootcdn
`//cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css"`

3. 首页快速使用 这段代码
`import appbar from 'muse-components/appbar'`
应该是appBar吧，src下没appbar这个目录

**Comment by myronliu347** [comment]
1. 点击问题是，fastclick 和vue配合使用的时候用冲突; 正在想办法修复
2. cdn可以考虑替换，这个是个不错的建议
3. 这个名称被改过了，我马上修改

**Comment by HopeFE** [comment]
VUX里面也是用的fastclick好像还没有这个问题

**Comment by myronliu347** [comment]
Vux是vue1.0的，这种情况只在ios上出现，最近准备再底层用tap事件换掉click

**Comment by AK35** [comment]
这个问题修复了吗？  好像目前还是有这个问题呢 移动端无法使用 fastclick

**Comment by AK35** [comment]
iconButton.vue   中 这个方法导致的需要点2次  ，注释所说的BUG我暂时没遇到过  是不是可以用其他方法解决注释中的问题？

 handleStop (event) {
      event.stopPropagation() // 防止list中使用导致波纹点击重复
    }

**Comment by myronliu347** [comment]
@AK35 多谢提醒，我会及时修复
