### ISSUE TITLE
selectField控件下拉内容有时候无法显示问题

### ISSUE THREAD

**Issue by mengyubo** [museui/muse-ui#180]
每次刷新浏览器，20次大概有1次会出现此问题，点击selectField的输入框后，如果界面有滚动条，浏览器会滚动到顶部

界面最好放两个selectfield进行测试，第一个好使，可能第二个就不好使了（下拉面板无内容，f12查看，div会显示一下，然后立刻隐藏，并且div里面无dom）

**Comment by myronliu347** [comment]
请在 [jsfiddle](https://jsfiddle.net/) 上写个demo， 
资源
https://unpkg.com/vue
https://unpkg.com/muse-ui/dist/muse-ui.js
https://unpkg.com/muse-ui/dist/muse-ui.css

**Comment by mengyubo** [comment]
我在你们官网上面试过好几次了，用谷歌浏览器，selectField组件，你多刷新几次，每次都把所有的下拉都点一遍，总会有一个点不出来的，复现频率比较高，急需解决啊

**Comment by myronliu347** [comment]
好的，我试下

**Comment by myronliu347** [comment]
反复试过了很多次，确实没有重现

**Comment by mengyubo** [comment]
我这里很容易重现，或者我重现后怎么联系你看下？

**Comment by myronliu347** [comment]
录屏，什么都可以吧

**Comment by hrbzcj** [comment]
@myronliu347 我也遇到了这个问题，以下是录屏地址：
[百度云录屏](https://pan.baidu.com/s/1bo9pAhh)
