### ISSUE TITLE
为什么iphone6中的safari浏览器中浏览存在问题

### ISSUE THREAD

**Issue by nbslr** [museui/muse-ui#181]
电脑中网页访问正常
![qq 20161223103844](https://cloud.githubusercontent.com/assets/23208889/21446041/3e8e6ac0-c8fc-11e6-98e4-209c594d07a5.png)
safari浏览器中浏览
![921186359855530358](https://cloud.githubusercontent.com/assets/23208889/21446017/0f778b2c-c8fc-11e6-99cd-c9e2bdaca9ee.jpg)

**Comment by myronliu347** [comment]
写个demo吧 [jsfiddle](https://jsfiddle.net/)

http://unpkg.com/muse-ui/dist/muse-ui.js
http://unpkg.com/muse-ui/dist/muse-ui.css

http://unpkg.com/vue
