### ISSUE TITLE
vue-cli 创建的项目中会出现undefined

### ISSUE THREAD

**Issue by shuaiho** [museui/muse-ui#184]
版本
vue-cli:2.6.0
vue:2.1.0
![muse-ui-bug](https://cloud.githubusercontent.com/assets/2002360/21470844/2c911a4a-cad5-11e6-962e-ebae2cdca75b.png)

**Comment by myronliu347** [comment]
最好贴下App.vue的代码，看下是如何使用的

**Comment by shuaiho** [comment]
@myronliu347 感谢您的回复
创建的命令: vue init webpack demo 
只修改了这两个文件
main.js
![main js](https://cloud.githubusercontent.com/assets/2002360/21478675/ae989f3c-cb88-11e6-962c-15d9a5a8a884.png)
app.vue
![app vue](https://cloud.githubusercontent.com/assets/2002360/21478677/b16e8d3e-cb88-11e6-90da-9894d744e429.png)

**Comment by shuaiho** [comment]
@myronliu347 
我的vue-cli版本是2.6.0之前时，是能正常使用，昨天升级到2.6.0后就无法正常显示了。
之前的是哪个版本也忘记了

**Comment by didilinkin** [comment]
## 我也是发现这个问题,当添加`import 'muse-ui/dist/muse-ui.css'`时，就会报错

```
                                                                                                  
ERROR in ./~/css-loader?sourceMap!./~/style-loader!./~/css-loader!./~/muse-ui/dist/muse-ui.css    
Module build failed: Unknown word (5:1)                                                           
                                                                                                  
  3 | // load the styles                                                                          
  4 | var content = require("!!./../../css-loader/index.js!./muse-ui.css");                       
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];                       
    | ^                                                                                           
  6 | // add the styles to the DOM                                                                
  7 | var update = require("!./../../style-loader/addStyles.js")(content, {});                    
  8 | if(content.locals) module.exports = content.locals;                                         
                                                                                                  
 @ ./~/muse-ui/dist/muse-ui.css 4:14-136                                                          
                                                                                                  
ERROR in ./~/muse-ui/dist/muse-ui.css                                                             
Module build failed: Error                                                                        
```

### vue-cli版本为@2.6.0

目前解决方法是在html文件那里引用css和js文件

`<link rel="stylesheet" href="./static/css/muse-ui.css">`
`<script type="text/javascript" src="./static/js/muse-ui.js"></script>`

**Comment by myronliu347** [comment]
我先升级下看看

**Comment by Sandon** [comment]
遇到了同样undefined的问题，vue@2.1.7，webpack@1.14.0.

main.js
`import Vue from 'vue/dist/vue.js'
import App from './App.vue'
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
Vue.use(MuseUI)

console.log(MuseUI)
Vue.component(MuseUI.datePicker.name, MuseUI.datePicker)
Vue.component(MuseUI.textField.name, MuseUI.textField)
Vue.component(MuseUI.appBar.name, MuseUI.appBar)

var vm = new Vue({
  el: '#app',
  render: h => h(App)
})`

App.vue
`<template>
  <div id="content">
    <mu-appbar title="Title">
      <mu-icon-button icon='menu' slot="left"></mu-icon-button>
      <mu-icon-button icon='expand_more' slot="right"></mu-icon-button>
    </mu-appbar>
    <mu-text-field v-model="value"></mu-text-field>
    
  </div>
</template>

<script>
export default {
  data () {
    return {
      value: 'hello'
    }
  },
  components:{
  }
}
</script>

<style>
</style>`

结果是：
![image](https://cloud.githubusercontent.com/assets/1669301/21480409/afed8de8-cb97-11e6-8895-121e7e27c5b2.png)

**Comment by myronliu347** [comment]
解决方案，使用vue@2.1.5版本  目前这个是稳定版，没有什么明显的bug

```bash
npm install vue@2.1.5 --save 

npm install vue-template-compiler --save-dev
```

**Comment by myronliu347** [comment]
首先是实在是抱歉，对于 vue 2.1.0 / 2.1.7 版本出现这种问题，目前我还未找出原因，目前检测到的是需要使用最新 vue-template-compiler 来重新编译所有的组件, 但是2.1.7版本中muse的有些组件无法正常运行。

从vue 2.0.x版本开始，对于muse组件很少改动，对于vue升级之后的问题我也很无语，最近事情比较多，所以修复和维护的工作大部分都放在了周末完成。所以如果回复晚了，请谅解，谢谢！
