### ISSUE TITLE
How to create MuList 

### ISSUE THREAD

**Issue by roslaneshellanoo** [museui/muse-ui#188]
I want MuList to be closed by default.
Tried various options without success

**Comment by myronliu347** [comment]
what is MuList?

**Comment by roslaneshellanoo** [comment]
This is the accordion inside list component.
https://museui.github.io/#/list

By default it's in the opened state. How to create make this element to be closed by default?
![screen shot 2016-12-28 at 10 10 39](https://cloud.githubusercontent.com/assets/20886073/21517232/f508a5b2-cce5-11e6-88fa-1401f2f00bcf.png)

**Comment by myronliu347** [comment]
![image](https://cloud.githubusercontent.com/assets/7897937/21517607/54528c92-cd1b-11e6-8615-7fb53255ab8f.png)

`open` set  false
