### ISSUE TITLE
建议snackbar和toast借鉴mintui的实现方法

### ISSUE THREAD

**Issue by beeplin** [museui/muse-ui#19]
对于snackbar和toast这样的组件，我感觉mintui的处理比较合理，就是不需要写到< template>里，不隶属于某个组件内部，只是用一个Toast()函数呼出。参见 [http://mint-ui.github.io/docs/#!/zh-cn2/toast](http://mint-ui.github.io/docs/#!/zh-cn2/toast)

另外，各种dialog其实最好也做成只靠dialog()函数呼出的独立js组件，函数返回promise来处理用户在diaolog中的输入操作。这样的话就省去了手工定义各种close事件处理函数的麻烦。参见 [http://mint-ui.github.io/docs/#!/zh-cn2/message-box](http://mint-ui.github.io/docs/#!/zh-cn2/message-box)

如果考虑到有时候dialog需要搞些slot来定制UI，最好也能提供纯函数版的另一个dialog组件。我自己的经验是，绝大部分时候只需要函数呼出的dialog和toast，这样使得< template>和js代码都很简洁。

**Comment by myronliu347** [comment]
后期会开发一些快捷操作的api，目前还是已组件为主

**Comment by shmy** [comment]
nice

**Comment by myronliu347** [comment]
@beeplin  Hi, 这个问题我想了很久，一个 SPA 程序里，所有的视图里的数据都需要经过 `vuex` 的控制，所以呢，我的解决方案是在 `App.vue` 写好 `snackbar` 和 `toast` 组件，显示数据在全局内配置 `state` 和 `mutations`, `action`,其它组件都可以使用全局内的 `action` 控制显示和隐藏 `snackbar` / `toast`

后面我会给出一个demo项目

**Comment by beeplin** [comment]
嗯对于使用vuex的项目来说这是个好方法。不使用vuex的项目也可以类似的在根组件上引入toast然后在需要时使用this.$root.toast（xxx）。

不过其实繁琐的地方在于必须手动控制toast的显示和隐藏，不像mintui那样就是一个干干净净的函数并带有promise。可能比较难以两全吧。

**Comment by myronliu347** [comment]
@jaweii  放到2.1版本里了，准备2月份再写

**Comment by HZZformGD** [comment]
@jaweii  现在是2.1 版本了 好像没有 之前说的全局方法， 我这几天想把之前的elementui替换成MUSE-UI（讲实话，我觉得museui ！！！好好看 赏心悦目的感觉）   然后发现 之前elementui  弹窗 之类的 是有一个全局方法的。  后来翻遍museui 的文档好像没有 一个全局方法 就像  @beeplin 所提的一样 如果有这样的一个方法  我觉得会更简便的。   看了下 之前说2月份~ 现在已经7月份了 好期待有这个功能。

**Comment by jaweii** [comment]
@HZZformGD 你爱错人了

**Comment by HZZformGD** [comment]
@jaweii  哈哈哈哈 我的锅我的锅

**Comment by HZZformGD** [comment]
@myronliu347 现在是2.1 版本了 好像没有 之前说的全局方法， 我这几天想把之前的elementui替换成MUSE-UI（讲实话，我觉得museui ！！！好好看 赏心悦目的感觉） 然后发现 之前elementui 弹窗 之类的 是有一个全局方法的。 后来翻遍museui 的文档好像没有 一个全局方法 就像 @beeplin  所提的一样 如果有这样的一个方法 我觉得会更简便的。 看了下 之前说2月份~ 现在已经7月份了 好期待有这个功能。

**Comment by sobriver** [comment]
@Zeus-Iqd 我如果只在JS中写，怎么封装。比如我要在axios的拦截器里面统一处理所有的错误，弹出错误信息，怎么弄
