### ISSUE TITLE
TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by peirancao** [museui/muse-ui#190]
vue 2.1.7
muse-ui 2.0.0-beta.3

**Comment by peirancao** [comment]
紧急！！！求修复 项目马上要交工了。。

**Comment by myronliu347** [comment]
建议先把vue退回2.1.5 版本， 2.1.7vue动过核心代码，有些bug, 我最近正在修复一些问题

**Comment by myronliu347** [comment]
#183  关注这个，我修复好会回复，抱歉了，其实我也是被坑了
