### ISSUE TITLE
用npm装不上muse-ui

### ISSUE THREAD

**Issue by blingbling-bin** [museui/muse-ui#192]
难产了。。。。

**Comment by myronliu347** [comment]
报错还是 ?

**Comment by blingbling-bin** [comment]
@myronliu347 

帮忙看看，谢谢，错误信息：
blingbling-bindeMacBook-Pro:HandanApp blingbling_bin$ npm install muse-ui
loadDep:vue-popup-mixin - | |#############################--------------------------------------------------------------------------------------------------------------|
^C
blingbling-bindeMacBook-Pro:HandanApp blingbling_bin$ npm install muse-ui
npm WARN install Couldn't install optional dependency: shasum check failed for /var/folders/cb/jxc0_9d10s9_dktpb6ctpc3h0000gn/T/npm-2255-55093a8c/registry.npmjs.org/echarts/-/echarts-3.3.2.tgz
npm WARN install Expected: 06f42a47d213248d45fe585719ec8940fdc610aa
npm WARN install Actual:   15d774ea69fff9c1c135382414ebff6db1ad6fff
npm WARN install From:     https://registry.npmjs.org/echarts/-/echarts-3.3.2.tgz
npm WARN EPACKAGEJSON handan@1.0.0 No description
npm WARN EPACKAGEJSON handan@1.0.0 No repository field.

**Comment by myronliu347** [comment]
先升级加vue在安装muse-ui, 以后muse只支持vue2.1.5以上版本

```
npm install vue muse-ui --save
```

**Comment by blingbling-bin** [comment]
@myronliu347 
就是一直停在loadDep:vue-popup-mixin 装不下去了。。。
blingbling-bindeMacBook-Pro:HandanApp blingbling_bin$ npm install vue muse-ui --save
loadDep:vue-popup-mixin - - |#############################--------------------------------------------------------------------------------------------------------------|

**Comment by myronliu347** [comment]
你可以分开

```
npm install vue 
npm install muse-ui
```
