### ISSUE TITLE
【table】在表格里怎么正确地维护选中的Index？

### ISSUE THREAD

**Issue by chenyiqiao** [museui/muse-ui#196]
我在`table`上监听`rowSelection`事件，拿到一个包含index的数组。全选的时候没问题，会把所有的index收进来，但是在取消全选的时候不会清空这个数组。版本是`2.0.0-alpha-.11`

**Comment by myronliu347** [comment]
Happy new year !!!

这个地方确实是个bug，我需要修改，多谢你的提醒哦，哈哈！
