### ISSUE TITLE
DatePicker设置maxDate为当前日期时，绑定‘’YYYY-MM-DD‘’格式日期会报错

### ISSUE THREAD

**Issue by javaMumu** [museui/muse-ui#199]
我需要经最大日期设置为当前日期，但是传入函数生成的YYYY-MM-DD格式字符串，会报错
 Invalid prop: type check failed for prop "maxDate". Expected Date, got Number. 
固定输入则不会报错，我该如何设置maxDate属性?

**Comment by myronliu347** [comment]
<mu-date-picker hintText="竖屏模式选择" maxDate="2017-01-02"/>

**Comment by myronliu347** [comment]
<mu-date-picker hintText="竖屏模式选择" maxDate="2017-01-02"/>

**Comment by myronliu347** [comment]
抱歉昨晚网速太差

**Comment by myronliu347** [comment]
请给出了jsfiddle 上的demo

https://unpkg.com/muse-ui/dist/muse-ui.js
https://unpkg.com/muse-ui/dist/muse-ui.css

**Comment by qianduangaoshou** [comment]
@javaMumu  问题最后你是怎样解决的？
