### ISSUE TITLE
开发进度如何了？正在选型，想用这个框架

### ISSUE THREAD

**Issue by lqixv** [museui/muse-ui#2]

**Comment by myronliu347** [comment]
还剩下表单部分的组件未开发，最后需要整体看看，还有哪些地方需要改进

**Comment by peirancao** [comment]
等待中...

**Comment by tigerui** [comment]
顶

**Comment by superpig2046** [comment]
非常期待～

**Comment by beeplin** [comment]
公司项目刚刚正式决定迁移到vue2了，这周末就迁移，正在做新的UI组件库选型。muse来得及不？来不及我们就只好先用mint了。。。:((

**Comment by myronliu347** [comment]
来不及了，开发完了也不能直接发正式版, 如果坚持material 风格可以试下这个 [vue-material](https://github.com/marcosmoura/vue-material)

**Comment by beeplin** [comment]
嗯，vue-material还是组件有点少。那就只能mint，加上一些ripple组件，一些手写css。。。。

加油加油！等你搞好了我忽悠大家再迁移到muse，哈哈哈

**Comment by peirancao** [comment]
正在使用中 等发布了 再更新吧。。

**Comment by myronliu347** [comment]
组件基本都写完了，接下来要处理不同主题和样式， 打包文件， 最后做一次api的小需改，整理官网和文档就好啦

**Comment by lqixv** [comment]
先出个文档吧

**Comment by myronliu347** [comment]
正在整呢,官网即将到来，距离发布不远啦
<img width="1273" alt="muse-ui" src="https://cloud.githubusercontent.com/assets/7897937/19731649/b8a0abd8-9bd0-11e6-887d-45c835284937.png">

**Comment by hellinnocence** [comment]
好期待！！！

**Comment by BubblyPoker** [comment]
大大，还要多久呀？等不及了

**Comment by myronliu347** [comment]
还有几个组件文档没有，这个月应该会发布 `alpha` 版

**Comment by myronliu347** [comment]
[Muse UI](https://museui.github.io/) 文档基本补全，最后整理下主题这些就可以发布啦

**Comment by myronliu347** [comment]
已发布 `alpha` 版 , [Muse UI](https://museui.github.io) 文档基本补全， 主题的会在一周内补全文档和使用。
