### ISSUE TITLE
How to change theme with switch component?

### ISSUE THREAD

**Issue by roslaneshellanoo** [museui/muse-ui#200]
I tried something like this:

`<mu-switch @change="changeTheme('dark')" label="默认为 true"  class="demo-switch" /><br/>`

![screen shot 2017-01-02 at 12 05 32](https://cloud.githubusercontent.com/assets/20886073/21587337/d1e11482-d0e3-11e6-8aa1-7a68a54d42cc.png)

but thats working only with one way.....means thats its changing the theme only to 'dark'

**Comment by roslaneshellanoo** [comment]
Figured it out!

` 
<template>
    <div>

        <mu-switch
                @change="checkTheme"
                label="Change Theme"
                v-model="theme_checked"
                   class="demo-switch"
           />
  
    </div>
</template>

<script>

    import light from '!raw-loader!muse-ui/dist/theme-default.css'
    import dark from '!raw-loader!muse-ui/dist/theme-dark.css'

    export default {
        data() {
            return {
                theme: 'dark',
                themes: {
                    light,
                    dark
                },
                theme_checked: false
            }
        },

        methods: {

            getThemeStyle: function () {
                const themeId = 'muse-theme';
                let styleEl = document.getElementById(themeId);
                if (styleEl) return styleEl
                styleEl = document.createElement('style');
                styleEl.id = themeId;
                document.body.appendChild(styleEl);
                return styleEl
            },

            changeTheme: function (theme) {
                this.theme = theme;
                const styleEl = this.getThemeStyle();
                styleEl.innerHTML = this.themes[theme] || '';
                console.log(styleEl)
            },

            checkTheme: function() {
                if(this.theme_checked === true) {
                    this.changeTheme('light')
                } else {
                    this.changeTheme('dark')
                }
            }


        },

    }
</script>


`

**Comment by roslaneshellanoo** [comment]
**Figured it out!**

```
<template>
    <div>

        <mu-switch
                @change="checkTheme"
                label="Change Theme"
                v-model="theme_checked"
                   class="demo-switch"
           />
  
    </div>
</template>

<script>

    import light from '!raw-loader!muse-ui/dist/theme-default.css'
    import dark from '!raw-loader!muse-ui/dist/theme-dark.css'

    export default {
        data() {
            return {
                theme: 'dark',
                themes: {
                    light,
                    dark
                },
                theme_checked: false
            }
        },

        methods: {

            getThemeStyle: function () {
                const themeId = 'muse-theme';
                let styleEl = document.getElementById(themeId);
                if (styleEl) return styleEl
                styleEl = document.createElement('style');
                styleEl.id = themeId;
                document.body.appendChild(styleEl);
                return styleEl
            },

            changeTheme: function (theme) {
                this.theme = theme;
                const styleEl = this.getThemeStyle();
                styleEl.innerHTML = this.themes[theme] || '';
                console.log(styleEl)
            },

            checkTheme: function() {
                if(this.theme_checked === true) {
                    this.changeTheme('light')
                } else {
                    this.changeTheme('dark')
                }
            }


        },

    }
</script>
```

**Comment by myronliu347** [comment]
Please check whether the style is inserted
