### ISSUE TITLE
textFiled组件怎么在输入框右边放置个按钮？

### ISSUE THREAD

**Issue by jaweii** [museui/muse-ui#201]
就像验证码输入框，右边有一个获取验证码按钮

但是我尝试在mu-text-field中放入mu-flat-button，是无效的

在mu-text-field中放置任何元素都会导致mu-text-field无效

所以怎么实现在输入框右边放置个按钮？

**Comment by myronliu347** [comment]
可以重开，作为一个新的功能，我会在下个版本加上哦
