### ISSUE TITLE
pagination计算属性覆写

### ISSUE THREAD

**Issue by kukujbb** [museui/muse-ui#202]
![1483441348 1](https://cloud.githubusercontent.com/assets/20284294/21605937/373f0a1a-d1e7-11e6-998d-f09bdd7b0d01.png)

**Comment by linxiaowu66** [comment]
@kukujbb  能否贴出你的代码？

**Comment by kukujbb** [comment]
@linxiaowu66  仅在vue-cli创建的项目下使用pagination

![image](https://cloud.githubusercontent.com/assets/20284294/21629869/0116554e-d267-11e6-84dd-18902908a689.png)

**Comment by linxiaowu66** [comment]
@kukujbb  已经修复， 在PR#202，多谢。

**Comment by myronliu347** [comment]
#205
