### ISSUE TITLE
低版本的webview显示material icons的问题

### ISSUE THREAD

**Issue by daduXu** [museui/muse-ui#204]
在版本低的webview中，使用名称带有下划线的图标时，显示不正确，位置也会变乱。
请问有解决的办法吗？在低版本中如何正常使用material icons图标呢。

**Comment by myronliu347** [comment]
请截图，然后请给出webview的版本

**Comment by daduXu** [comment]
WebView 33.0.0.0



zhaoxu028@sina.com
 
发件人： myron
发送时间： 2017-01-04 09:59
收件人： museui/muse-ui
抄送： Jensen.zhao; Manual
主题： Re: [museui/muse-ui] 低版本的webview显示material icons的问题 (#204)
请截图，然后请给出webview的版本

**Comment by daduXu** [comment]
[
![image](https://cloud.githubusercontent.com/assets/11400444/21630369/78619b6e-d26b-11e6-96a6-11af4ae612d9.png)
](url)

**Comment by myronliu347** [comment]
是appbar上的突变没有对齐么 ？

**Comment by daduXu** [comment]
图标设定不识别，比如icon里使用chevron_left，就不显示，使用不带下划线的，例如settings就正常显示
<mu-icon-button icon="chevron_left"  />
<mu-icon-button icon="settings"  />

**Comment by daduXu** [comment]
`<mu-icon-button icon="settings"  />`   `<mu-icon-button icon="chevron_left"/>`

**Comment by muyunz** [comment]
可以參考這個 issue :
https://github.com/google/material-design-lite/issues/1375

所以如果碰到有带下划线的可以用另一個代替：
![2017-01-04 5 10 38](https://cloud.githubusercontent.com/assets/4878855/21637230/f636b5f8-d2a0-11e6-90dd-e0265cbd9dcd.png)

**Comment by myronliu347** [comment]
楼上的办法太赞了，
可以去这个网站找图标的两种使用方式 https://material.io/icons/

**Comment by daduXu** [comment]
![image](https://cloud.githubusercontent.com/assets/11400444/21666604/b24a281a-d32d-11e6-81c7-0217f8813a21.png)
这是什么情况？我用的不对？`<mu-bottom-nav-item value="gift" title="Gift" icon="&#xE86A;"/>`

**Comment by muyunz** [comment]
@daduXu 
如果是直接寫在單組件的 `<template>`，或是組件裡面的屬性 `template: '...'` 的話，就會出現這問題，
因為被直接當成了 `普通字符串` 來處理，而不是 `Unicode 字符`，所以得先解析好再傳。

如果本來就有引用 `jQuery` 的話就簡單很多：
```javascript
template: `
    <mu-icon :value="decodeHtmlEntities('&#xE86A;')"></mu-icon>
`,
methods: {
    decodeHtmlEntities(str) {
        return $('div').html(str).text()
    }
},
```

沒有的話就自己寫一個來處理，這裡找到一個別人寫的：
[simongong/decodeEntities.js](https://gist.github.com/simongong/00f223537e9df5faba3f3b97ee180b7e)
