### ISSUE TITLE
目前只支持import，对commonjs的require支持不好

### ISSUE THREAD

**Issue by beeplin** [museui/muse-ui#21]
如果使用require，只能写成 `MuseUI = (require 'muse-ui').default`，因为包内部使用`export default`导出模块的，转化为commonjs需要加一个恶心的default。

解决方法：包内部导出的时候不用`export default xxx`，而用commonjs的 `module.exports = xxx`。这样，在babel和webpack的默认设置下，既支持es6语法，又支持commonjs的require语法。

**Comment by myronliu347** [comment]
已修复 2.0.0-alpha.3
