### ISSUE TITLE
table组件在fixedHeader的情况下

### ISSUE THREAD

**Issue by CurtisCBS** [museui/muse-ui#211]
# 问题描述
因为业务需要，table组件的table-layout需要为auto，即不写死table cell的宽度。所以重写了以下样式

`.mu-table{
  table-layout: auto;
}`

但当table-header固定在顶部的时候，变成了

`<div>
            <table>
                <thead></thead>
            </table>
        </div>
        <div>
            <table>
                <tbody></tbody>
            </table>
        </div>`

即thead和tbody没办法在同一个<table>内，导致自动计算宽度的时候有差异。
# 反馈
是否有其他的方法能实现table-cell的宽度根据内容自适应且thead固定在顶部

**Comment by CurtisCBS** [comment]
没有提供根据单元内容计算宽度的属性吗？

**Comment by myronliu347** [comment]
不设置宽度就是根据单元格内容扩展的啊

**Comment by Hanruis** [comment]
@CurtisCBS fixHeader 的特性，可以不需要用到 mu-table 的 fixHeader ，用 css 就可以实现，参考 [codepen](https://codepen.io/anon/pen/dzJzpR)

另外 @myronliu347 mu-table 的 fixHeader 是否也可以参考上面的，用 css 实现，而不用实际分离 header 出来。
