### ISSUE TITLE
使用时，自动发起异常GET请求

### ISSUE THREAD

**Issue by nelsonnick** [museui/muse-ui#212]
我使用muse-ui 2.0.0-rc.1版本编写了一个小程序，每次进入程序时，发现程序自动发起了一个GET请求，请求的地址如下：http://rlogs.youdao.com/rlog.php?_npid=deskdict&_ncat=event&_ncoo=1594705812.8801322&_nssn=NULL&_nver=1.2.0&_ntms=1483677871368&_nhrf=first-touch&/=NULL&keyfrom=dict_huaci。
能不能解释下这是为啥？

**Comment by myronliu347** [comment]
网址打不开。。。。

**Comment by myronliu347** [comment]
muse-ui里没有任何请求....
