### ISSUE TITLE
关于ripple效果在X5内核浏览器中的问题

### ISSUE THREAD

**Issue by ChaoYuLeo** [museui/muse-ui#214]
发现ripple效果在X5内核浏览器上表现不佳。甚至只是页面中有此效果的元素，即使未触发也影响页面表现，特别是滑动时迟缓、卡顿。

**所以是否可以考虑给一些有ripple效果的组件增加一个降级的prop选项。**

**Comment by myronliu347** [comment]
在下一个版本可以点击的组件都会加上一个 disabledRipple 的 属性，用于关掉波纹效果

**Comment by myronliu347** [comment]
ListItem上已经有disableRipple属性，用于关闭波纹效果，另外我还需要具体的信息，比如说是安卓那个版本的x5内核

**Comment by ChaoYuLeo** [comment]
系统为安卓5.1.1 LMY47V，微信为最新版。
