### ISSUE TITLE
怎么设置 text field 自动 focus

### ISSUE THREAD

**Issue by altjz** [museui/muse-ui#219]
API  只提供了设置 focus 的 class 还有 focus 与 blur 的事件绑定，但是没有设置 focus 的方法。

例如：按下了某个按钮，用 v-show 显示一个 textfield，怎么能把这个 textfield 自动设置为 focus 的状态呢？

**Comment by linxiaowu66** [comment]
Hi  你可以试一下原生的HTML5的这个属性：

`autofocus`

比如:(非VUE代码)

```
<form>
  First name: <input type="text" name="fname" autofocus><br>
  Last name: <input type="text" name="lname"><br>
  <input type="submit">
</form
```

**Comment by myronliu347** [comment]
给出一些hack的办法

```html
<template>
   <mu-text-field ref="text" />
</template>
<script>
export default {
    methods: {
         setFocus() {
             const el = this.$refs.text.$el
             el.querySelector('input').focus()
         }
    }
}
</script>
```

**Comment by altjz** [comment]
@myronliu347 非常感谢，原来可以这么用。

**Comment by wenzhixin** [comment]
```js
this.$refs. text.$refs.input.focus()
```

**Comment by skobeo** [comment]
Implementing setFocus method to a multi text field does nothing
`setFocus () {
        const el = this.$refs.usermessage.$el
        el.querySelector('textarea').focus() // or input vs textarea do the same
      },`
And then when call setFocus(), ie. on open event, text field is not focused. And no error in console

**Comment by messikiller** [comment]
网页端可以实现，移动端貌似不行啊，手机端还有没有什么好办法？

**Comment by bafuka** [comment]
> 给出一些hack的办法
> 
> ```
> <template>
>    <mu-text-field ref="text" />
> </template>
> <script>
> export default {
>     methods: {
>          setFocus() {
>              const el = this.$refs.text.$el
>              el.querySelector('input').focus()
>          }
>     }
> }
> </script>
> ```

非常感谢。
