### ISSUE TITLE
table组件，当允许全选并进行全选后，这时取消下面部分部分选择，这时全选按钮应该被自动取消

### ISSUE THREAD

**Issue by lqixv** [museui/muse-ui#22]
table组件，当允许全选并进行全选后，这时取消下面部分部分选择，这时全选按钮应该被自动取消。同样，当全部的行都被选择后，是不是全选按钮应该被自动勾选？

**Comment by stevieyu** [comment]
这个个人觉得应该自己处理，并不是所有的地方都需要全选以及自动勾选那种

**Comment by myronliu347** [comment]
[已修复](https://github.com/museui/muse-ui/commit/ebcfb7190cc75102663841c24de890250953a364)
