### ISSUE TITLE
table组件在tr只剩下1个时，无法触发rowSelection事件

### ISSUE THREAD

**Issue by a62527776a** [museui/muse-ui#220]

**Comment by a62527776a** [comment]
还有貌似table的第1项@rowSelection返回的下标是1 第二项返回的下标是0

**Comment by myronliu347** [comment]
后面这个是正常的 ，index是从0开始算了

**Comment by myronliu347** [comment]
第一个问题，我要检查下

**Comment by a62527776a** [comment]
谢谢

**Comment by myronliu347** [comment]
#240 问题解决同这个一直，星期一发rc.3版本修复

**Comment by efanng** [comment]
最新的2.0.0好像仍然有这个问题

**Comment by efanng** [comment]
想到一个办法，当items的length为一时就启用multiSelectable
`computed:{
            multiSelectable:function(){
                return this.items.length==1
            }
        },`

**Comment by myronliu347** [comment]
麻烦重新开个issue，这个关掉了有时候会忘记
