### ISSUE TITLE
Pagination的pageSizeChange触发时机问题

### ISSUE THREAD

**Issue by mengyubo** [museui/muse-ui#223]
当我使用了pageSizeOptions 设置为['15', '20', '30', '40']而不是['10', '20', '30', '40']的时候，pageSizeChange事件在初始化的时候会被触发，当我设置了defaultPageSize为15的时候，还是会触发pageSizeChange事件

是不是应该是defaultPageSize为pageSizeOptions 中的一个的时候，就不应该触发该事件

**Comment by myronliu347** [comment]
稍后 @linxiaowu66  会给你回复

**Comment by mengyubo** [comment]
刚发现了问题原因，是actualPageSize设置的字符串类型问题，vue的watch机制监测的是字符串‘10’和数字10的比较，而示例里面给的是字符串，所以每次都会触发，还有组件内部的代码给的默认值也是字符串，建议都改为数字

**Comment by linxiaowu66** [comment]
@mengyubo 
defaultPageSize只在组件初始化的时候才会生效，而且它和pageSizeOptions一起使用的时候会默认去使用pageSizeOptions ，不大清楚你的使用场景，能否再详细一点。

另外你说的字符串类型和数字倒是一个问题，我会修改掉，多谢

**Comment by myronliu347** [comment]
最近会发rc.3版本解决这个问题
