### ISSUE TITLE
这个框架主要针对PC端吧？ 还有没找到搜索框的ui组件

### ISSUE THREAD

**Issue by YYmmlin** [museui/muse-ui#225]
这个框架主要针对PC端吧？
跟pc端的ui框架像
手机端的话，那还缺很多UI组件
 ！！！还有没找到搜索框的ui组件

**Comment by myronliu347** [comment]
search组件后续会加上，目前是没有的，现有的很多组件都可以在mobile上使用啊

**Comment by YYmmlin** [comment]
好，加油啊~
