### ISSUE TITLE
menu的宽度设置问题

### ISSUE THREAD

**Issue by mengyubo** [museui/muse-ui#227]
< mu-paper class="demo-menu" >
   < mu-menu desktop :width="256" >
       < mu-menu-item title="Open" afterText="Cmd + O" />
       < mu-menu-item title="Paste in place" afterText="Shift + V" />
       < mu-menu-item title="Research" afterText="Opt + Shift + Cmd + I" />
   < /mu-menu>
 < /mu-paper>
 .demo-menu {
   display: inline-block;
   margin: 16px 32px 16px 0;
 }

好像设置的宽度都不管用？

**Comment by myronliu347** [comment]
`autoWidth` 这个参数需要设置成false，才能自定义宽度

**Comment by mengyubo** [comment]
OK 谢谢
