### ISSUE TITLE
推荐看看 material2 的ui 有些功能可以做成他那样那么全面

### ISSUE THREAD

**Issue by stevieyu** [museui/muse-ui#23]
之前用过angular 官方出的 material2， 虽然人家在alpha版，组件少，不过他的一个组件的功能做的很完善，可惜就是组件更新慢，有过想法做一个界面跟他一样的vue2版的material2，就是缺点实力。

附上地址 https://github.com/angular/material2

**Comment by myronliu347** [comment]
请问那些组件的功能不够完善呢？我会在在近期改进

**Comment by stevieyu** [comment]
input 缺少 required 这个参数，必填时 label 后面会有个 *

**Comment by stevieyu** [comment]
![image](https://cloud.githubusercontent.com/assets/8325201/20251720/6e402818-aa56-11e6-9300-76253c4e28f9.png)
示例的tooltip位置不太对吧，应该居中才对

**Comment by stevieyu** [comment]
多行文本 这光标位置不太对吧
![image](https://cloud.githubusercontent.com/assets/8325201/20251775/f62cc6dc-aa56-11e6-97be-17856df3a536.png)

**Comment by myronliu347** [comment]
收到，我已经在修复啦

**Comment by myronliu347** [comment]
上面提到的问题，我都在新版中修复了，这个 issue 我就不关了，有问题还可以在这边提，我会尽快修复

**Comment by stevieyu** [comment]
![image](https://cloud.githubusercontent.com/assets/8325201/20290611/1300ef84-ab1c-11e6-9eec-41ade6da5148.png)
这个占位文字不能选中才对吧

**Comment by stevieyu** [comment]
![image](https://cloud.githubusercontent.com/assets/8325201/20290765/0e17ed00-ab1d-11e6-985b-796534e2c3dd.png)
![image](https://cloud.githubusercontent.com/assets/8325201/20290772/16f1de9a-ab1d-11e6-88ef-4131b44bbc24.png)
tooltip left 的右边中间对齐，right 的左边没有中间对齐

**Comment by stevieyu** [comment]
建议 flexbox 的布局用这个会更好一点
http://flexboxgrid.com/

**Comment by stevieyu** [comment]
Progress 是不是少了个 circle 有没有组件添加计划那些？

**Comment by myronliu347** [comment]
tooltip，确实还需要修改，
栅格布局这块需要再考虑下，
progress circle 这个功能现在现在只实现了 indeterminate 模式，并未开放出来，svg 动画在安卓上会闪， 这个组件会在后期开发， 2.0.0版本中的组件固定就这些，后续版本升级会加入其它组件

**Comment by myronliu347** [comment]
tooltip和提示文字的问题已修复

**Comment by stevieyu** [comment]
select 的 item1 选不了 
![image](https://cloud.githubusercontent.com/assets/8325201/20336582/426adbb4-ac06-11e6-96b4-1d7e4093e48c.png)

**Comment by myronliu347** [comment]
已修复, 晚些发版本

**Comment by Eliooooo** [comment]
![image](https://cloud.githubusercontent.com/assets/16299018/20415147/70266f66-ad71-11e6-8221-6e64f82fcbb4.png)

单击官网DEMO里的[View Dialog]弹出的Dialog按钮有不明蓝色样式，在任意位置点击后，这个蓝色的样式就消失了。用的是Chrome浏览器 54.0.2840.99 m (64-bit) 

// 我看到有提bug的issue我也直接在这里发了

**Comment by stevieyu** [comment]
docs 里table 的高度设为 auto 时，下面的排版错位
![image](https://cloud.githubusercontent.com/assets/8325201/20457074/5a4274da-aebe-11e6-9179-58605ab040c1.png)

**Comment by myronliu347** [comment]
文档里输入框设置么？周末一直没法重现这个场景， 方面写个 [jsfiddle](https://jsfiddle.net) 么？

资源可以用
https://unpkg.com/muse-ui@2.0.0-alpha.8/dist/muse-ui.js
https://unpkg.com/muse-ui@2.0.0-alpha.8/dist/muse-ui.css

**Comment by stevieyu** [comment]
![kapture 2016-11-21 at 13 04 53](https://cloud.githubusercontent.com/assets/8325201/20471254/22d01268-afeb-11e6-93a3-9efdae119d77.gif)

**Comment by myronliu347** [comment]
找了好几台windows的电脑，都没有发现这个问题，
请问你那里可以找到原因么？

**Comment by stevieyu** [comment]
我系统是mac 10.12 浏览器是最新的 chrome canary

**Comment by myronliu347** [comment]
没有就行，真的非常感谢你给我提出了这么多的建议

**Comment by stevieyu** [comment]
![image](https://cloud.githubusercontent.com/assets/8325201/20740877/7cab94ac-b701-11e6-9781-d45ae06d8fdf.png)
input 能不能加个眼睛那样的东西

**Comment by myronliu347** [comment]
ok，我会在近期加上

**Comment by stevieyu** [comment]
picker 增加鼠标滚动的吧，尽管在移动设备用得比较多，但是支持pc不是更好

**Comment by myronliu347** [comment]
@stevieyu  应该不用，pc上不需要使用picker这种选择的了呀

**Comment by stevieyu** [comment]
做年月份筛选时用得到，然后pc的地址选择，如果不采用select，用这个picker也是可以的

**Comment by timeswind** [comment]
www.iviewui.com,
这个vue 的ui 库很精致，组建的功能也全面，就是现在不支持2.0

**Comment by myronliu347** [comment]
@timeswind iview的2.0应该会跟element差不多， 主要是精力和时间问题，我一直在慢慢完善这个项目

**Comment by myronliu347** [comment]
@stevieyu 我先关掉了，这个太长了，每次加载好久，以后有问题开新的就好
