### ISSUE TITLE
Clicking on a mu-list-item with defined href causes page to reload

### ISSUE THREAD

**Issue by pipejesus** [museui/muse-ui#231]
Vue version: latest
Muse-ui version: latest

I'm using `vue-router` and trying to put some links in the `<mu-list>` 

All item entered like this:

`<mu-list-item href="mypath"></mu-list-item>`

cause the page to refresh instead of using the vue-router. Could you help me out a bit?

**Comment by myronliu347** [comment]
you can use  router `hash` model

```html
<mu-list-item href="#/mypath"></mu-list-item>
```

or listener click event

```html

<mu-list-item @click="go()"></mu-list-item>

<script>
export default {
   methods: {
        go () {
           this.$router.push('/mypath')
        }
   }
}
</script>
```

**Comment by pipejesus** [comment]
yep, that's what i currently do, thank you @myronliu347
