### ISSUE TITLE
making "ripple" work in Firefox by changing <button> to <span> ?

### ISSUE THREAD

**Issue by pipejesus** [museui/muse-ui#233]
Hi guys, i know this might seem simplistic but what do you think about making the ripple effect work on buttons in Firefox simply by changing the `abstractButton.js`line to

`return h(this.href ? 'a' : this.containerElement ? this.containerElement : 'span', {`

so that it produces 'span' elements instead of 'button' elements? From what i've read `<button>` should not contain any child elements (as stated in W3C specifications) so maybe we could stick to the rules here and get the ripple working?

I've found the wonderful answer by @sqal here: https://github.com/museui/muse-ui/issues/128 but i'm too of a novice to wrap my head around it all yet.

I've tested all the kinds of buttons and everything seems to be almost right but after such change these issues would have to be dealt with:

1. `.mu-flat-button-wrapper` has to have `height:100%` added (similar to `.mu-raised-button-wrapper`)

2. The `vertical-align` of the span-buttons would have to be set to `middle` in order to match the allignement with text next to it

3. the `<input type="file">` inside such a button needs to have top margin corrected

**Comment by myronliu347** [comment]
`vertical-align` ,   I think you can adjust the layout to control the position of the button

others，I will  fixed in next version

My English is very poor, I am very sorry

**Comment by myronliu347** [comment]
#128

**Comment by pipejesus** [comment]
Great :-) I've made those changes for my purpose and everything displays fine so far (i've been using buttons heavily in a project). Here they are: https://github.com/pipejesus/muse-ui

**Comment by myronliu347** [comment]
o, Thank you for your support！
