### ISSUE TITLE
请问能不能取消按钮点击的动画？日期控件在安卓卡顿。

### ISSUE THREAD

**Issue by bairdweng** [museui/muse-ui#234]
感觉按钮在点击的时候都会产生动画，如果这时候滑动的话，动画会卡注。另外在安卓手机(魅族pro6安卓6.0)，日期控件弹出的时候，卡顿挺严重的，能不能给个设置，取消所有不必要的动画。非常感谢,UI做得非常漂亮，实在不想放弃这个UI框架。

**Comment by myronliu347** [comment]
考虑下改变这个dialog的弹出的动画方案，尝试改为fade，或者滑动更为轻量的实现方式

**Comment by myronliu347** [comment]
动画方案已经改动，另外关于波纹效果可以在全局配置关闭, 星期一发rc.3版本，然后按照下面更改代码即可

全组件加载时
```javascript

import MuseUI from 'muse-ui'
MuseUI.config({
     disableTouchRipple: true,
     disableFocusRipple: true
})
```

单组件加载时

```javascript
import config from 'muse-ui/src/config'

config({
     disableTouchRipple: true,
     disableFocusRipple: true
})
```

**Comment by bairdweng** [comment]
好的，非常感谢！

**Comment by bairdweng** [comment]
新版本的日期控件没有居中，其它都正常，取消水波纹之后安卓也不卡顿了。
<img width="466" alt="09795a8f-dd2c-4c52-9bda-3c027f6c391b" src="https://cloud.githubusercontent.com/assets/8598304/21971003/77f162e2-dbe7-11e6-8c54-9627233a5594.png">

**Comment by bairdweng** [comment]
![simulator screen shot 2017 1 16 5 00 06](https://cloud.githubusercontent.com/assets/8598304/21976596/9819fe82-dc0d-11e6-9b26-9fd378aa263a.png)
5s中直接往右边偏移了。

**Comment by myronliu347** [comment]
ok，我近期看看

**Comment by bairdweng** [comment]
好的，幸苦了。
