### ISSUE TITLE
请问input的类型是tel的时候在iOS下没有小数点如何解决？

### ISSUE THREAD

**Issue by bairdweng** [museui/muse-ui#235]
input的类型是tel的时候在iOS下没有小数点，请问各位应该如何解决？非常感谢。

**Comment by myronliu347** [comment]
tel类型只是在提交表单时候会加验证而已，可以使用text，然后自己验证电话号码

**Comment by bairdweng** [comment]
用text的话感觉体验不太好，我是想强制让用户输入加小数点的数字，使用tel类型的时候，安卓是有小数点的，iOS没有，原生是有一个带小数点的数字键盘，input类型好像没法调用，看了微信的小程序应该是自定义的。能不能也自定义一个类似这样的，或者提供下思路，谢谢。
<img width="1100" alt="9bbacf34-5a65-479f-9c87-c596e8da7fe5" src="https://cloud.githubusercontent.com/assets/8598304/21971284/165d2d1a-dbea-11e6-82ee-992af3705af5.png">
微信小程序，最右边是原生的。
![untitled 2](https://cloud.githubusercontent.com/assets/8598304/21971417/6ad15686-dbeb-11e6-9b7c-b4de8e7394a4.png)

**Comment by myronliu347** [comment]
tel类型不需要 `.` 你可以试下 number 类型
