### ISSUE TITLE
为什么我重新下载了新版的muse ui 原来的代码就出现问题了？

### ISSUE THREAD

**Issue by nbslr** [museui/muse-ui#237]
![qq 20170113091946](https://cloud.githubusercontent.com/assets/23208889/21915008/ef210372-d971-11e6-8fa0-70ed5a28b413.png)
![qq 20170113092012](https://cloud.githubusercontent.com/assets/23208889/21915009/ef252f06-d971-11e6-9d48-ba345be438f8.png)

**Comment by myronliu347** [comment]
目前支持vue2.1.6及以上版本

**Comment by nbslr** [comment]
我的环境用vue-cli搞的，那如何升级vue呢

**Comment by myronliu347** [comment]
```bash
npm install vue --save
npm install vue-template-compiler --save-dev
```

**Comment by nbslr** [comment]
我重新初始化目录，下载了vue等，现在出现这个问题，请教
You are running Vue in development mode.

**Comment by myronliu347** [comment]
请给出全部的报错截图
