### ISSUE TITLE
circular-progress的样式问题

### ISSUE THREAD

**Issue by mengyubo** [museui/muse-ui#238]
当circular-progress控件的父元素是overflow auto的时候，进度条的动画会让父元素的滚动条不断的闪现，原因是因为 里面的方形div旋转的时候 将父元素撑开

建议修改为：
.mu-circular-progress {
    display: inline-block;
    position: relative;
    overflow: hidden;
}

**Comment by myronliu347** [comment]
可以采纳，多谢
