### ISSUE TITLE
tooltip问题

### ISSUE THREAD

**Issue by mengyubo** [museui/muse-ui#239]
当浏览器窗口从其他标签或者其他应用切换过来的时候，将鼠标移动到table上面的th上，这个时候，tooltip会出现一个巨大的灰色的圆形阴影，建议修改

**Comment by mengyubo** [comment]
一定要用alt tab去切换才可以复现，我用的是谷歌浏览器最新版

**Comment by myronliu347** [comment]
周末我检查下就修改
