### ISSUE TITLE
Dawer 中的 Menu 组件 在切换路由后 宽度会从280px 变成 84px

### ISSUE THREAD

**Issue by peirancao** [museui/muse-ui#24]
而且 menu item 的 ripple 会影响 overfly 动画效果

**Comment by myronliu347** [comment]
请给出运行的环境

**Comment by myronliu347** [comment]
是给出的demo会有这个问题吗？

**Comment by myronliu347** [comment]
大致看了下， 问题有如下几点：
1. 切换路由后 overlay仍存在；
2. menu 组件的宽度有问题

menu 组件会自动计算宽度的，所以在drawer上使用时应该这么设置

```html
<mu-menu :autoWidth="false" width="100%">
//...
</mu-menu>
```

严格来来说menu只能配合popover做弹出式菜单，在drawer中应该使用 list 和 listItem

上述两个问题稍后会提交代码， 近期发布新版本修复
