### ISSUE TITLE
文档的自定义主题不太友好啊，不知道怎么下手

### ISSUE THREAD

**Issue by jaweii** [museui/muse-ui#242]
> 目前只支持 less, 黑色的主题配置 dark.less
dark.less是自己创建，还是已经存在了自己修改呢
创建或者修改，是在什么路径呢
小白一枚 求教

**Comment by myronliu347** [comment]
dark.less地址  https://github.com/museui/muse-ui/blob/master/src/styles/themes/dark.less

简单说就是，定义类颜色相关的变量，只需要修改这些变量就可以定义一个自己的主题,
muse ui 内置 light, dark, carbon, teal 四种主题

**Comment by lingyunzhu** [comment]
@myronliu347 只能在muse-ui的源码里面改颜色吗？请问我如何在自己的工程里改颜色？

**Comment by yutiansut** [comment]
css呀

**Comment by yutiansut** [comment]
你把他的css复制出来,然后在main.js里引入你的css的路径

**Comment by yutiansut** [comment]
@lingyunzhu @myronliu347
