### ISSUE TITLE
需求：Pagination移动端体验不佳

### ISSUE THREAD

**Issue by Cyrilszq** [museui/muse-ui#246]
Pagination组件没有做到响应式，移动端页数太多时变成这样了
![screenshot from 2017-01-16 20-00-14](https://cloud.githubusercontent.com/assets/17585588/21982265/8057f222-dc26-11e6-8b30-f6095d3bd999.png)
请问有什么好的解决办法？

希望有选项可以配置最多显示出来的分页按钮数，或者当出现一行不够时能折行显示

**Comment by myronliu347** [comment]
这个组件设计的就是给pc端用的，好像没有移动端用分页的，大部分基本都是infineScroll

**Comment by hrbzcj** [comment]
加上  style="flex-wrap:wrap;"
