### ISSUE TITLE
图标不支持安卓，以及对日历组件的一点建议

### ISSUE THREAD

**Issue by hlpszy** [museui/muse-ui#247]
如题。。。
如图
![image](https://cloud.githubusercontent.com/assets/18546928/21983005/f2c7b538-dc29-11e6-9868-60343fe757a2.png)

日历的话，请给一个事件可以唤起日历，我现在有个需求就是右上角会有个日历图标，点击后选择日期，随后获取列表。
现在的日历很难做到，要修改才能达到这个需求（很蛋疼）。
另外赞一个

**Comment by myronliu347** [comment]
图标是可以下载下来引入的 https://github.com/google/material-design-icons/tree/master/iconfont
之前给的地址有些手机上会拦截

**Comment by myronliu347** [comment]
这样的话日历组件应该独立出来

**Comment by Eric-ss** [comment]
如果要用Bottom  Navigation安卓端上就变这样，只有加的图标才显示，而且没效果，这个如何解决，@myronliu347
![1](https://cloud.githubusercontent.com/assets/22341907/23200348/d7a04908-f90e-11e6-80fe-cc59922f5b55.jpg)

**Comment by myronliu347** [comment]
@Eric-ss 请给出具体的代码，或者在线的demo

**Comment by Eric-ss** [comment]
对比了一下另外一个demo 发现加了这个就正常了
<link href="http://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css" rel="stylesheet">

官方文档只加这2个好像不起作用
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

**Comment by Eric-ss** [comment]
对比了一下另外一个demo，发现加了这个就正常了
`<link href="http://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css" rel="stylesheet">`
只引入官方说的那两个好像不起作用
` <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">`
` <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">`

**Comment by smoook** [comment]
Bottom Navigation 不重写样式的情况下 怎么固定在底部呢

**Comment by myronliu347** [comment]
@smoook 要加样式的哦，这个组件是没有定位的

**Comment by smoook** [comment]
请问下 在main.js `中引入字体文件为啥不生效呢 **import './assets/font-icons/style.css';**
还有就是在index.html中引入静态字体问价也不生效**<link rel="stylesheet" href="./static/font-icons/style.css">**

**Comment by myronliu347** [comment]
这是哪里的字体 ？

**Comment by smoook** [comment]
我在你的museui的项目里找到的 字体文件

**Comment by myronliu347** [comment]
重复 https://github.com/museui/muse-ui/issues/369，
字体有问题的可以重开一个issues, @smoook
