### ISSUE TITLE
Refresh Control中的container如果不添加position: relative;在列表中间下拉的时候refresh icon也会出现

### ISSUE THREAD

**Issue by BubblyPoker** [museui/muse-ui#25]
Refresh Control中的container如果不添加position: relative;在列表中间下拉的时候refresh icon也会出现，

可以在官网上试一下，在cdt里把container的position勾掉，不管列表滚动条是否在顶部，下拉的时候都会出现refresh icon，同时会触发refresh事件。

我觉得有必要在官网上说明一下需要加上position:relative; 菜鸟弄了半天才找到这个原因

**Comment by myronliu347** [comment]
[已修改](https://github.com/museui/muse-ui/commit/c5b510580934113fe2b64b8ee4ab3c6f27ed88e3)
