### ISSUE TITLE
SCSS support?

### ISSUE THREAD

**Issue by 7brend7** [museui/muse-ui#251]
Hello,

Is is possible to add SCSS support e.g. into another branch with further support (thinking about forking...)?

IMHO - LESS is not so flexible and popular as SCSS now (e.g. bootrstap which switched to SCSS). I have also SCSS everywhere in my projects so I don't know how to merge it.

**Comment by myronliu347** [comment]
If you don't need a custom theme, you can need not consider this,

The custom theme  only support Less

**Comment by Macavity** [comment]
Many people might have the need for different themes because their corporate identity doesn't match the available themes.
No need to support scss though, i think it would suffice to provide a small tutorial on how to build a custom theme file with vue.

**Comment by 7brend7** [comment]
What I propose is to have possibility to use SASS(SCSS) prepocessor instead of LESS.
It's not related to themes at all; in muse-ui there are LESS styles inside *.vue templates.

In truth, I don't like LESS and currently I'm thinking how to integrate muse-ui into my sass project (one of solutions is to use minified css with all styles, but I prefer to import only those components what I need).

So, I will spend some time to rewrite all styles to SCSS.

**Comment by Macavity** [comment]
Why? You can overwrite the styles generated from less with sass without the need to rewrite the original component. Vue compiles both to css anyway.

**Comment by myronliu347** [comment]
I can give a theme.css, your writing style to cover it

**Comment by 7brend7** [comment]
After some investigation I realized how I can import components (because the main purpose was - to use theme variables and - to import only those components what I need).
So, @Macavity - I guess, you are right, I think I can import base.less, some-component.js and even my *.scss files into js and build all with webpack.
Little-bit strange for me because I've never used css import in javascript.
