### ISSUE TITLE
Pagination组件BUG及建议。

### ISSUE THREAD

**Issue by aaron0713** [museui/muse-ui#252]
测试数据130条。
1）10/页：点下一页的时候，从第4页会瞬间跳到13页。
2）当前为第一页的时候，更改 10/页 为 40/页 会出现两个 第4页
3）更改 40/页 为 30/页，会漏掉 第4页，显示页码为 1、2、3、5
建议：
增加总页数显示Lable

**Comment by myronliu347** [comment]
最近找时间看下，会立即修复的，多谢

**Comment by linxiaowu66** [comment]
Hi @aaron0713 
1) 我没有复现第一个问题
后面两个问题我会立马修复

**Comment by linxiaowu66** [comment]
Hi @aaron0713 
感谢你的反馈，已经修复该问题。原因是我在更新页数列表的时候没有提前更新页面总数造成的，现在已经更改顺序了。[PR 255](https://github.com/museui/muse-ui/pull/255)

**Comment by linxiaowu66** [comment]
@aaron0713 至于你的建议感觉有点多余，因为总页数都是在页码列表中就可以看到的，也就是最后一项，所以感觉没必要，@myrouliu347 你觉得呢？

**Comment by aaron0713** [comment]
@linxiaowu66 描述错误，应该是显示总条数。不好意思

**Comment by linxiaowu66** [comment]
@aaron0713 嗯  也可以的 我就将其做为一个可选的label吧 稍后版本加上

**Comment by myronliu347** [comment]
Fixed in 2.0.0-rc.5
