### ISSUE TITLE
布局不支持iphone5 ios9 么，几乎乱掉

### ISSUE THREAD

**Issue by lry210** [museui/muse-ui#257]
现在用的iphone5布局很多乱的，你们写这种css不用考虑下兼容性：
![image](https://cloud.githubusercontent.com/assets/12726826/22141934/3f2f3ab0-df2f-11e6-99a0-c209d129ea14.png)
现在更新最新版本vue会报错，同时更新了最新版本的vue也是一样，都升级不了

**Comment by lry210** [comment]
![image](https://cloud.githubusercontent.com/assets/12726826/22142419/279d419c-df31-11e6-89c2-580e1cd111b6.png)

**Comment by myronliu347** [comment]
请出示你的muse的版本，我们的css都是会有autoPrefixer的，你这个版本应该是之前版本的问题，至于vue的升级，目前需要同时升 vue vue-template-compiler

```bash
npm install vue --save
npm install vue-template-compiler
```

最后，麻烦您升级下muse, 目前muse-ui只支持vue2.1.6及以上版本

```bash
npm install muse-ui --save
```
