### ISSUE TITLE
想知道下你这个跟vue-material有什么不一样的吗？

### ISSUE THREAD

**Issue by mjiong** [museui/muse-ui#258]
在github里看到 vue-material 这个，然后想咨询下。

**Comment by myronliu347** [comment]
这两个都是基于material design 风格的设计（此类风格的设计的ui还有很多），相较于vue-material， muse-ui 提供的组件更为丰富，在很多组件实现上，这两者有很大的差别，所以api也完全不同，
最后vue-material对于主题的处理是比muse-ui 好很多，muse-ui目前只支持使用less自定义主题风格

**Comment by mjiong** [comment]
谢谢你的解答。很喜欢你的这个UI框架呢。希望你可以一直维护下去。
