### ISSUE TITLE
有计划增加表单验证吗

### ISSUE THREAD

**Issue by zq99299** [museui/muse-ui#261]
有计划增加表单验证吗？

**Comment by myronliu347** [comment]
可以使用官方全家桶 https://github.com/vuejs/vue-validator

**Comment by Hanruis** [comment]
vue-validator 已经不是 vue 官方的组件了。重点的是，它还没有完成对 vue2.0 的支持。请问 muse-ui 有推荐的表单验证的最佳实践 or 库么。
