### ISSUE TITLE
English OK/Cancel buttons for Date Picker

### ISSUE THREAD

**Issue by cmosguy** [museui/muse-ui#265]
Hey there,

I am trying to use the Date Picker, OK/Cancel buttons in English?

![image](https://cloud.githubusercontent.com/assets/1676382/22375574/81f88268-e45f-11e6-97ff-949fc736dc85.png)

**Comment by myronliu347** [comment]
You can set `okLabel` and  `cancelLabel` , Like this：

```html
 <mu-date-picker okLabel="Ok" cancelLabel="Cancel"/>
```

**Comment by cmosguy** [comment]
Hey @myronliu347 thanks for the help!  Yeah I finally figured it out before you replied. Thanks for the quick response.  This project is great!
