### ISSUE TITLE
align datepicker and select field

### ISSUE THREAD

**Issue by cmosguy** [museui/muse-ui#266]
Hey!

Do you know how to align the select field and datepicker?  I cannot figure out how to make the styling work so they look aligned.

![image](https://cloud.githubusercontent.com/assets/1676382/22412787/ee123f3a-e666-11e6-991c-55529c8aebad.png)

Thanks!

**Comment by myronliu347** [comment]
Please write a simple demo in [jsfiddle](https://jsfiddle.net/)

You can use :
https://unpkg.com/vue/dist/vue.min.js
https://unpkg.com/muse-ui/dist/muse-ui.js
https://unpkg.com/muse-ui/dist/muse-ui.css

**Comment by cmosguy** [comment]
@myronliu347 

I went ahead and created a fiddle here:
https://jsfiddle.net/asklein/bL9hjhw3/

You can see when I put the select field next to the date of bith the styling lines do not match up.  Please advise.

Many thanks!

**Comment by myronliu347** [comment]
I change the demo, you can look 

https://jsfiddle.net/bL9hjhw3/1/

I'm sorry to reply you so late， just after the Spring Festival holiday

**Comment by cmosguy** [comment]
@myronliu347 thanks for your feedback.  the problem is when I actually implement those updates on my site it does not actually fix the problem and react the same way as it does in this js fiddle....  Anyways, thanks for your time, much appreciated!
