### ISSUE TITLE
Text field with Google Place API template

### ISSUE THREAD

**Issue by cmosguy** [museui/muse-ui#267]
Hey @myronliu347 ,

I was trying to use your text fields with this other project.  Is there a way to merge the inputs so I can use your field styling along with this logic: 

https://github.com/xkjyeah/vue-google-maps/blob/vue2/examples/basic-autocomplete.html

If you have an easy way to combine these two field inputs I would be super interested.

Many thanks!
Adam

**Comment by myronliu347** [comment]
Please give me some time, I need to know the vue-google-maps

**Comment by cmosguy** [comment]
@myronliu347 Thanks for your help here!

**Comment by myronliu347** [comment]
I can`t change the `vue-google-maps`, but I think you can change  autocomplete style in https://github.com/xkjyeah/vue-google-maps/blob/vue2/src/components/autocomplete.vue
