### ISSUE TITLE
Vee-Validate problem

### ISSUE THREAD

**Issue by throrin19** [museui/muse-ui#268]
Hi,
I have a big problem with the vee-validate validator.

If I try to validate this field in a form :

```vue
<mu-text-field data-vv-name="email" label="Email" fullWidth labelFloat v-validate data-vv-rules="required|email" :errorText="errors.first('email')"/>
<mu-select-field label="Profession" fullWidth labelFloat data-vv-name="job" v-validate data-vv-rules="required" :errorText="errors.first('job')">
   <mu-menu-item value="1" title="Agriculteur"/>
   <mu-menu-item value="2" title="Chomeur"/>
   <mu-menu-item value="3" title="Développeur"/>
   <mu-menu-item value="4" title="Docteur"/>
   <mu-menu-item value="5" title="Super Héro"/>
   <mu-menu-item value="6" title="Maman"/>
</mu-select-field>
```

- In the "on the fly" validation (on keypress, focus/unfocus, ...) On the input/select, the validation works fine
- If I call the method `this.$validator.validateAll()` to manually validate my form (like a submit click), all inputs are in error.

After research I see this differents issues :

- https://github.com/logaretm/vee-validate/issues/118
- https://github.com/museui/muse-ui/issues/119

How to fix the problem with Vee-validate ? The usage of vue-validator is not a correct option.

Thanks

**Comment by throrin19** [comment]
Ok, after research I find the problem.

Basically, vee-validate get the `value` attribute of form component. In the case of muse-ui, the form element value is setted in the `inputValue` data field.

Hopefully, vee-validate as an attribute to indicate the correct field :

```
data-vv-value-path="inputValue"
```

And now it works fine. I think you shuld add this information in the textField part in the documentation.

**Comment by myronliu347** [comment]
ok, I save the issue, after , I will add faq

**Comment by myronliu347** [comment]
Thank you very much, in fact, I don't know about `vee-validate`
