### ISSUE TITLE
Module not found: Error

### ISSUE THREAD

**Issue by oscarnevarezleal** [museui/muse-ui#269]
I had setup my Muse-ui project according to the documentation.
Whenever I try to build using webpack I got this error:

`    ERROR in ./~/muse-ui/src/appBar/index.js
    Module not found: Error: Can't resolve './appBar' in 'C:\muse-ui-example\node_modules\muse-    ui\src\appBar'
    @ ./~/muse-ui/src/appBar/index.js 7:14-33
    @ ./app/src/main.js
`

_webpack.config.js_
`
var path = require('path');

module.exports = {
    entry: './app/src/main.js',
    module: {
        loaders: [
            // ...
            {
                test: /muse-ui.src.*?js$/,
                loader: 'babel-loader'
            },
            {
                test: /muse-ui.src.*?less/,
                use: [
                    'style-loader',
                    {loader: 'css-loader', options: {importLoaders: 1}},
                    'less-loader'
                ]
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            },
            {
                test: /\.vue$/,
                use: ['vue-loader']
            }
        ]
    },
    resolve: {
        alias: {
            "muse-components": "muse-ui/src",
            "app-components": path.resolve(__dirname, 'app/components').toString()
        }
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'public/js').toString()
    }
};
`

Probably not related in any way with the project per se, but still any help would be appreciated.

**Comment by myronliu347** [comment]
Please show you code on use

**Comment by myronliu347** [comment]
webpack config
```javascript
{
resolve: {
    extensions: ['', '.js', '.vue', '.json', '.less'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      'vue$': 'vue/dist/vue.common.js',
      'muse-components': 'muse-ui/src'
    }
  },
  resolveLoader: {
    fallback: [path.join(__dirname, '../node_modules')]
  }
}
```

**Comment by myronliu347** [comment]
I close the first, if still have questions, please reopen.

**Comment by oscarnevarezleal** [comment]
I forgot to mark it as complete, thank you.
