### ISSUE TITLE
it does't work?

### ISSUE THREAD

**Issue by itaotao** [museui/muse-ui#27]
-----main.js----
`
import Vue from 'vue'

import MuseUI from 'muse-ui'

import 'muse-ui/dist/muse-ui.css'
import App from './App'
Vue.use(MuseUI)
/* eslint-disable no-new */
new Vue({
  el: '#app',
      data: {
        columns:['id','name','age'],
        tableData: [
          {id:1, name:"John",age:"20"},
          {id:2, name:"Jane",age:"24"},
          {id:3, name:"Susan",age:"16"},
          {id:4, name:"Chris",age:"55"},
          {id:5, name:"Dan",age:"40"}
        ],
        options: {
          // see the options API
        }
      } ,
  render: h => h(App)
})
`

App.vue:
`
<template>
  <div id="app">
    aaaaaaaaa
  <mu-bottom-nav :value="bottomNav" shift @change="handleChange">
    <mu-bottom-nav-item value="movies" title="Movies" icon="ondemand_video"/>
    <mu-bottom-nav-item value="music" title="Music" icon="music_note"/>
    <mu-bottom-nav-item value="books" title="Books" icon="books"/>
    <mu-bottom-nav-item value="pictures" title="Pictures" icon="photo"/>
  </mu-bottom-nav>
  </div>
</template>

<script>
export default {

  data () {
    return {
      bottomNav: 'movies'
    }
  },
  methods: {
    handleChange (val) {
      this.bottomNav = val
    }
  }
}
</script>
`
why  it does't work ?

**Comment by myronliu347** [comment]
额，请提供 template里的内容

**Comment by itaotao** [comment]
```
<template>
  <div id="app">

  <mu-bottom-nav :value="bottomNav" shift @change="handleChange">
    <mu-bottom-nav-item value="movies" title="Movies" icon="ondemand_video"/>
    <mu-bottom-nav-item value="music" title="Music" icon="music_note"/>
    <mu-bottom-nav-item value="books" title="Books" icon="books"/>
    <mu-bottom-nav-item value="pictures" title="Pictures" icon="photo"/>
  </mu-bottom-nav>
  </div>
</template>
```

**Comment by myronliu347** [comment]
刚刚新建了一个demo项目试了下，的确是没有问题的，
请问你这是是报错还是？

**Comment by myronliu347** [comment]
我给出我的

**main.js**

```javascript
import Vue from 'vue'
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
import App from './App'
Vue.use(MuseUI)
/* eslint-disable no-new */
new Vue({
  el: '#app',
  template: '<App/>',
  components: { App }
})
```

**App.vue**

```javascript
<template>
 <mu-bottom-nav :value="bottomNav" shift @change="handleChange">
    <mu-bottom-nav-item value="movies" title="Movies" icon="ondemand_video"/>
    <mu-bottom-nav-item value="music" title="Music" icon="music_note"/>
    <mu-bottom-nav-item value="books" title="Books" icon="books"/>
    <mu-bottom-nav-item value="pictures" title="Pictures" icon="photo"/>
</mu-bottom-nav>
</template>
<script>
export default {
  data () {
    return {
      bottomNav: 'movies'
    }
  },
  methods: {
    handleChange (val) {
      this.bottomNav = val
    }
  }
}
</script>
```

```index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>muse-demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no,minimal-ui">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>

```

**Comment by itaotao** [comment]
页面是空白的 没报错 是对Vue的版本有要求吗 或者其他的原因

**Comment by myronliu347** [comment]
vue 2.0以上

**Comment by itaotao** [comment]
我是用vue-cli创建的项目 页面代码直接复制你的

**Comment by myronliu347** [comment]
我刚刚也是vue-cli创建的项目

**Comment by myronliu347** [comment]
你看下你的控制台，是否打包没有成功
