### ISSUE TITLE
请提供各组件获取focus的方法

### ISSUE THREAD

**Issue by jaweii** [museui/muse-ui#272]
比如，让页面打开后，raised button就处于focus状态

**Comment by myronliu347** [comment]
keyboardFocused 参数

https://jsfiddle.net/m1w7ku0y/2/

**Comment by jaweii** [comment]
谢谢 可以了

文档里没写这个属性啊，只有event里有个keyboardFouce，而不是keyboard-focused,并且keyboardFouce写上去无效

建议在文档上写清楚这个属性。。。
