### ISSUE TITLE
新版vue-cli引入列表组件，报无依赖的错误

### ISSUE THREAD

**Issue by 569835014** [museui/muse-ui#278]
These dependencies were not found in node_modules:

* ../internal/abstractButton
* ../iconButton
* ../utils
其他组件没问题，用到列表组件的时候出错

**Comment by myronliu347** [comment]
请给出，使用代码，和报错信息

**Comment by 569835014** [comment]
上面就是报错信息，
 import Appbar from 'muse-ui/src/appBar/appBar'
  import List from 'muse-ui/src/list/list.vue'
  import ListItem from 'muse-ui/src/list/listItem.vue'
代码就是这个 Appbar 已经成功引入，ListItem 这个报错

These dependencies were not found in node_modules
../internal/abstractButton
../iconButton
../utils

**Comment by myronliu347** [comment]
webpack配置呢 ？

**Comment by 569835014** [comment]
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var eslintFriendlyFormatter = require('eslint-friendly-formatter')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    modules: [
      resolve('src'),
      resolve('node_modules')
    ],
    alias: {
      'vue$': 'vue/dist/vue.common.js',
      'src': resolve('src'),
      'assets': resolve('src/assets'),
      'components': resolve('src/components'),
      
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /muse-ui.src.*?js$/,
        loader: 'babel'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}

**Comment by myronliu347** [comment]
我用vue-cli重新new了项目，使用了和你一样的配置并没有问题，搜索下是有是有

../internal/abstractButton
../iconButton
../utils

这些文件，如果没有可以尝试重装

```
npm install muse-ui --save
```

**Comment by 569835014** [comment]
```javascript
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var eslintFriendlyFormatter = require('eslint-friendly-formatter')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    modules: [
      resolve('src'),
      resolve('node_modules')
    ],
    alias: {
      'vue$': 'vue/dist/vue.common.js',
      'src': resolve('src'),
      'assets': resolve('src/assets'),
      'components': resolve('src/components'),
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /muse-ui.src.*?js$/,
        loader: 'babel'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}

```

**Comment by 569835014** [comment]
![image](https://cloud.githubusercontent.com/assets/13517450/22641227/c0b99d6e-ec90-11e6-888f-aed39c2f9dd5.png)
![image](https://cloud.githubusercontent.com/assets/13517450/22641233/c819728c-ec90-11e6-8007-54f631a7d4b7.png)

**Comment by 569835014** [comment]
文件是有的，点击可以跳过去.但是用的时候就会报错，我也没改过webpack配置

**Comment by myronliu347** [comment]
实在模拟不出来这种情况，你把项目打个包发到我邮箱 myronliu347@gmail.com , 我看看，关键性代码可以删掉

**Comment by myronliu347** [comment]
问题有以下几点，

1. 首先 webpack 2配置

```javascript
{
 test: /muse-ui.src.?js$/,
  loader: 'babel-loader' // webpack2不能省略 ‘loader’
}
```

2. 单组件使用时需要安装less-loader

```bash
npm install less less-loader --save-dev
```

3. 单组件使用时， 有部分组件依赖 keycode

```bash
npm install keycode --save
```
