### ISSUE TITLE
似乎官网在手机打开所有图标都不显示，即使翻过墙

### ISSUE THREAD

**Issue by ccwq** [museui/muse-ui#280]
在pc的chrome(>50)一切正常，但是貌似只支持pc，移动端我测过几个浏览器，所有图标均不能正常显示

**Comment by myronliu347** [comment]
https://material.io/icons/,有些移动浏览器需要使用第二种方案加载，material icon
<i class="material-icons">stars</i>
<i class="material-icons">&#xE8D0;</i>

**Comment by ccwq** [comment]
已经解决了，看源码发现museui可以这样使用。最后我使用国内的图标库了。这么好的功能竟然没有体现在api里。
![image](https://cloud.githubusercontent.com/assets/3853416/22679089/79f48768-ed3a-11e6-80ab-9eb1b1874857.png)

**Comment by myronliu347** [comment]
不推荐，毕竟这种写法还是怪怪的

**Comment by xianzhi0520** [comment]
不翻墙官网的图标都显示文字
我有解决方法
我把图标库弄成本地的
写了一个css引导加载本地字体
 webpack也会自动打包进去
希望我这个方法 你能使用
