### ISSUE TITLE
关于分页Pagination无法拆分table

### ISSUE THREAD

**Issue by yutiansut** [museui/muse-ui#282]
我看到了分页里面
 data () {
    return {
      total: 50,
      current: 1
    }

我现在是用axios动态查询 会返回一个response.data  这个长度不定
我在method里面写了
```vue.js
     querybyname(message){
        let val='name='+message
        console.log(val)
         axios.get('http://localhost:3000/apis/querytitlebyName?'+val)
            .then( response => {
              this.items= response.data;
              this.total =this.items.length;
              })
          .catch(function (error) {
            console.log(error);
            });
```
然而是可以控制页数了,可是并没有真的分页...
![image](https://cloud.githubusercontent.com/assets/11537812/22685834/d67371bc-ed5c-11e6-8b8e-540b1167563b.png)
![image](https://cloud.githubusercontent.com/assets/11537812/22685843/dfcc4f90-ed5c-11e6-9e3e-98e5c253691a.png)
他依旧是被table压下去了

**Comment by yutiansut** [comment]
![image](https://cloud.githubusercontent.com/assets/11537812/22686095/cad59834-ed5d-11e6-87b2-ef2b17bfabb1.png)
目前唯一的办法只有限制table的高度,分页+table似乎无法用

**Comment by myronliu347** [comment]
分页功能，是需要前后端配合的，前端只提供显示，而真正的数据分页是后台完成的

**Comment by yutiansut** [comment]
就是说 我的每次分页的按钮都会发送ajax请求?  首先查询完了以后 会用10/页还是20/页去加载10条,然后点击1,2,3,4,5这些分页按钮的时候再去加载更多吗?

**Comment by yutiansut** [comment]
我目前是一次性查完了用vue-for直接循环到mu-table里面去

**Comment by myronliu347** [comment]
是的，实际的分页查询是后台处理的
