### ISSUE TITLE
使用组件icon失效

### ISSUE THREAD

**Issue by guanbiao33** [museui/muse-ui#286]
按照全局加载的方法引入，但是使用组件的时候icon不显示，是我姿势不对？应该怎么使用？
![git](https://cloud.githubusercontent.com/assets/16236310/22727992/955a8ca0-ee16-11e6-8697-56a2a18e083e.png)

**Comment by 569835014** [comment]
翻墙了吗

**Comment by guanbiao33** [comment]
没有

**Comment by myronliu347** [comment]
和这个重复 #123
