### ISSUE TITLE
MUSEUI Text Field 的EVENTS

### ISSUE THREAD

**Issue by yutiansut** [museui/muse-ui#287]
muse-ui 的text field 的events 怎么用呀
好比如我想做的是一个注册界面

我怎么样才能把我注册时文本框的value在method的里面拿到手呢?
```
focus	
输入框获取焦点时触发
blur	
输入框失去焦点时触发
input	
value 发生改变触发的事件，传入新的value, (value)
change	
用户输入时触发事件，传入输入框的 value
```
这是文档里面的 
```html
<mu-text-field label="账户" hintText="请输入用户名" v-model="valuex" type="password" labelFloat/><br/>
<mu-text-field label="密码" hintText="请输入密码" type="password" labelFloat/><br/>
<mu-raised-button label="注册" @click="**reg(name,password)**"/>
```
这个是我的代码,我不是很清楚怎么样才能拿到那个value,谢谢

**Comment by yutiansut** [comment]
![image](https://cloud.githubusercontent.com/assets/11537812/22733157/bc2b4a30-ee2b-11e6-8fcc-2e84368df875.png)
从后台可以看到 那个input和change都是实时触发的,没搞清楚这个怎么拿来用
难道是我点注册的时候 getELementbyId().value 这种原生js的方法去弄吗？

**Comment by myronliu347** [comment]
```javascript
<template>
<mu-text-field :value="value" @input="handleInput">
</template>
<script>
export default {
    data () {
         return {
             value: ''
         }
    },
   methods: {
        handleInput (value) {
           this.value = value
        }
   }
}
</script>
```
这些事件触发之后，第一个参数就是当前的value，
focus 和blur第一个参数是event，

**Comment by yutiansut** [comment]
那如果是两个input框呢?  我目前还是在用document.getelementbyclassname().value

**Comment by myronliu347** [comment]
一样，事件监听函数的第一个参数就是当前input的value

**Comment by myronliu347** [comment]
你也可以使用 `v-model`

**Comment by yutiansut** [comment]
我试试哈 谢谢啦
ps. museui有没有打算封装一点charts的部分,基于d3.js这些?

**Comment by myronliu347** [comment]
暂时没有，目前echart或者chart.js都是比较好的方案，也都有对应的vue插件
