### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by John0x** [museui/muse-ui#288]
Hey, the demo application (https://museui.github.io/#/bottomNav) is lagging for me, like really extreme. After clicking some buttons and switching around pages. Almost all components are lagging, especially tooltips and the bottom navigation.

Is it caused by my environment or is it a common issue?

**Comment by myronliu347** [comment]
What you see is the shift mode？

**Comment by John0x** [comment]
@myronliu347 what do you mean by the shift mode?
I'm using the newest chrome canary build on a desktop machine.

**Comment by myronliu347** [comment]
BottomNav shift mode will be caton in android, Other component normal

**Comment by John0x** [comment]
Then no, it wasn't in shift mode.
I'm using the newest chrome canary build on a desktop machine.
