### ISSUE TITLE
A typo in App Bar README_EN.md

### ISSUE THREAD

**Issue by gamtiq** [museui/muse-ui#289]
There is the following typo in [App Bar README_EN.md](https://github.com/museui/muse-ui/blob/master/src-docs/views/components/appbar/README_EN.md):
> which can be placed logo, *navagation* menu, search box or some buttons.

Also there are typos in description of properties of [Date Picker](https://github.com/museui/muse-ui/blob/master/src-docs/views/components/datePicker/en.js#L16):
> time format object, it should need following *attribue*
> *whther* it is completed automatically or not
> to *determin* which day is the first day
> to *determin* the disable date with function
> the *lable* of date picker
> the style of *lable* when the input box
> *whther* the date picker is disabled or not

**Comment by linxiaowu66** [comment]
@gamtiq 
  Thanks for your comments, I will fixed them just now.

**Comment by linxiaowu66** [comment]
Hi, @gamtiq 
 has fix this issue at [PR290](https://github.com/museui/muse-ui/pull/290)
