### ISSUE TITLE
<mu-menu-item>不可以添加点击事件

### ISSUE THREAD

**Issue by WispYs** [museui/muse-ui#29]
正在看文档的List信息列表，遇见了一个问题
`<mu-menu-item title="删除" @click="removeList(index)"/>`点击事件失效，但是换成`<mu-list-item title="删除" @click="removeList(index)"/>`就可以了，但是失去了iconMenu 组件的效果

**Comment by myronliu347** [comment]
嗯，你先使用 `.native` 监听点击，下个版本我会把 `menuItem` 的点击事件加上

```html
<mu-menu-item title="删除" @click.native="removeList(index)"/>
```
