### ISSUE TITLE
请问文本输入框如何绑定submit事件呢？How to bind submit event on TextField component?

### ISSUE THREAD

**Issue by paraself** [museui/muse-ui#291]
如题

**Comment by myronliu347** [comment]
submit事件不是应该在form上监听么 ？

**Comment by myronliu347** [comment]
组件内目前没有submit组件，不过也有hack的方案

```html
<template>
<mu-text-field ref="textField"/>
</template>
<script>
export default {
    mounted () {
        const input = this.$refs.textField.$el.querySelector('input');
        input.addEventListener('submit', function () {
        })
    }
}
</script>
```

**Comment by paraself** [comment]
哦哦，不好意思，我刚开始接触网页开发，我的意思就是说想在用文本框输入完的时候，检测用户按下回车的这个事件。您上面的例子应该就是我想要的，我试一下，谢谢啦。

**Comment by myronliu347** [comment]
<template>
<mu-text-field ref="textField"/>
</template>
<script>
export default {
    mounted () {
        const input = this.$refs.textField.$el.querySelector('input');
        input.addEventListener('keyup', function (event) {
                if (event.keyCode === 13) {
                      // TODO
                }
        })
    }
}
</script>

**Comment by myronliu347** [comment]
```html
<template>
<mu-text-field ref="textField"/>
</template>
<script>
export default {
    mounted () {
        const input = this.$refs.textField.$el.querySelector('input');
        input.addEventListener('keyup', function (event) { 
              if (event.keyCode === 13) { 
                // TODO 
              } 
        }) 
    } 
} 
</script>
```

**Comment by yutiansut** [comment]
也可以用 v-on:keyup.enter=''这样把

**Comment by paraself** [comment]
@yutiansut 直接在mu-textfield 上用v-on:keyup没用。。。试了作者给的这个方法是可以的，感谢！

**Comment by folse** [comment]
@myronliu347 为什么不让 TextField 支持 v-on:keyup.enter='' 呢？
