### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by John0x** [museui/muse-ui#292]
Hello, is this library intended to be SSR friendly/compatible?

**Comment by myronliu347** [comment]
We have not tested SSR support,

**Comment by John0x** [comment]
Will it ever be testes for SSR oficially?

**Comment by myronliu347** [comment]
In the near future.

**Comment by shimarulin** [comment]
Hi! After simple monkey patching (see https://github.com/shimarulin/muse-ui/tree/muse-ui-ssr) Muse UI can be compatible to SSR. @myronliu347 some changes can be smell bad, but it works)))

**Comment by myronliu347** [comment]
Can  you give me a pull request ?
