### ISSUE TITLE
use router-link in a button

### ISSUE THREAD

**Issue by shayneo** [museui/muse-ui#294]
I am trying to use a `router-link` from vue-router to navigate to a route with a `mu-flat-button`

I've tried wrapping the `router-link` in the button, like so

```
<mu-flat-button label="Sign In"><router-link to="/"></router-link></mu-flat-button>
```

**Comment by yutiansut** [comment]
<router-link to="/"><mu-flat-button label="Sign In"></mu-flat-button></router-link>
this will be ok

**Comment by shayneo** [comment]
I tried using your example, but it would not work. I think the problem is that the button is inside of an `mu-appbar`

**Comment by Tim86** [comment]
Trigger the link with `router.push('/')` in the button click event might work for you. Haven't tried it myself yet.

**Comment by shayneo** [comment]
thanks @Tim86 that's actually the same solution that I ended up going with. I figured I'd report, as this is probably a common use case.

**Comment by Tim86** [comment]
Good thinking @shayneo

**Comment by myronliu347** [comment]
If router mode is  `hash`, you can use `href` , I will support `router-link` ,repeat #39
