### ISSUE TITLE
Icon Button怎么禁用点击一次之后，按下空格和回车键会触发点击事件

### ISSUE THREAD

**Issue by altjz** [museui/muse-ui#298]
发现了一个问题，如果点击了一个 Button 之后再按下回车和空格，就会触发点击事件。请问怎么把这个键盘触发事件禁用呢？
我找到了一个 css 的解决方式[How to remove focus around buttons on click](http://stackoverflow.com/questions/19053181/how-to-remove-focus-around-buttons-on-click)
但是试用并没有用，然后查看源代码，看到有 abstractButton 里面有这个 `disableKeyboardFocus` ，尝试设为了 true 也没任何效果。
请问有没有什么解决方法呢？

之前也问过类似的问题(设置自动 focus)，最后是用了 hack 的方式解决，建议在每个组件提供Focus 的设置呢？因为这个情况遇到还挺多的。

**Comment by myronliu347** [comment]
多谢提出问题，我会尽快修复
