### ISSUE TITLE
mu-picker组件在做地区3级联动时出现以下错误。

### ISSUE THREAD

**Issue by bairdweng** [museui/muse-ui#300]
第一级在滚动的时候，获取value，然后改变第二级的数据，在使用demo例子的时候是正常的，但只要随意改变第二级的值，就会出现以下错误。
![2ccd6004-1e5f-40f0-80dd-b0db297a8b22](https://cloud.githubusercontent.com/assets/8598304/22926384/4b39ba6c-f2e7-11e6-913f-06575491db12.png)
![c335e427-f2f3-4b1c-9c78-798e8970e61c](https://cloud.githubusercontent.com/assets/8598304/22926388/52017f60-f2e7-11e6-8b9c-e0765f2a3bd1.png)
做3级联动的时候需要改变2级，3级的数据，可以正常实现，但是会抱截图错误，请问如何解决，尝试过计算属性，同样还是报错，谢谢！

**Comment by myronliu347** [comment]
请给出一个在线的demo，https://jsfiddle.net

**Comment by bairdweng** [comment]
在线的demo不知道怎么给啊，其实这个bug很容易重现。

![2017-02-15 10 09 07](https://cloud.githubusercontent.com/assets/8598304/22958010/4818962a-f367-11e6-9e5b-e2bbcb9fdc6d.png)

**Comment by bairdweng** [comment]
不知道怎么给在线demo啊，其实这个bug很容易重现。
![ebb9425e-f450-4096-b992-51ffebab8379](https://cloud.githubusercontent.com/assets/8598304/22958097/c9ffd98c-f367-11e6-8393-96fd5839f610.png)

**Comment by guohuadeng** [comment]
三级联动选地址太常见了，能不能像vux的xaddress一样做成个三级联动选地址组件，这个很常用，谢谢

**Comment by bairdweng** [comment]
@guohuadeng 自带的组件就可以实现，就是会报错，暂时不影响使用。
![2017-02-16 5 23 33](https://cloud.githubusercontent.com/assets/8598304/23015111/9ced2d4a-f46c-11e6-9a23-3723eeb407a8.png)

**Comment by myronliu347** [comment]
我需要点时间调试下这个问题，近期会改好

**Comment by bairdweng** [comment]
最近发现是我的写法有问题，我把mu-picker封装成组件，传入控件默认显示的值的时，同时把这个值赋值给内部控件，由于Vue props传参时，子组件不能更改这个值，所以报错了。用另外一个变量接受这个默认值，控件回调之后更新错误消失了。
![ae27b04d-d743-4ea0-9a3b-0dac2a1b4f4d](https://cloud.githubusercontent.com/assets/8598304/23392338/e5278e32-fdb5-11e6-81d0-ef3b9d6a9da5.png)
。

**Comment by myronliu347** [comment]
我昨天仔细调试过，的确没有问题，所以我把它关掉了

**Comment by jjjachyty** [comment]
同楼上一样，联动更换数组报Vue warn 能使用
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value" 
(found in <PickerSlot>)

**Comment by 546200350** [comment]
@bairdweng  请问三级城市选择怎么做呢？？ 不会哦，，，

**Comment by 546200350** [comment]
@bairdweng 已解决
