### ISSUE TITLE
Gridlist Col property not working

### ISSUE THREAD

**Issue by adityaism** [museui/muse-ui#304]
Can someone help me why gridlist `:cols` property not working properly. When I set more than 2 to property the list shows 1 column and when it is set to 1 the list shows 2 columns in a row.[https://museui.github.io/?lang=en#/gridList]

Code snippet below-
`  <div class="gridlist-demo-container">
			  	<mu-grid-list class="gridlist-demo">
			    <mu-sub-header>Progress</mu-sub-header>
			    <mu-grid-tile v-for="item in progress.items" titlePosition="top" actionPosition="right" :rows="1" :cols="1">
			      
			      <span slot="title">{{item.name}}</span>
			      <span slot="subTitle"><b>{{item.percentage}}%</b></span>
			      <mu-icon-button icon="info" slot="action"/>
			    </mu-grid-tile>
			  	</mu-grid-list>
			  </div>`

**Comment by myronliu347** [comment]
Please write in https://jsfiddle.net/,  Thanks

**Comment by adityaism** [comment]
@myronliu347  here it is https://jsfiddle.net/6jLsrpcm/

**Comment by myronliu347** [comment]
I updated, look here https://jsfiddle.net/6jLsrpcm/1/
