### ISSUE TITLE
Tab组件，能否实现类似 vux 的左滑右滑功能

### ISSUE THREAD

**Issue by guohuadeng** [museui/muse-ui#307]
手指拨动page可以更换tab，这个是现在主流应用的标配了，能否实现？
像vux有这个功能，不过muse好看太多，所以希望muse-ui能加上此功能。
谢谢！
===参考===
vux-ui
https://vux.li/demos/v2/?x-page=v2-doc-home#/component/tab

**Comment by myronliu347** [comment]
#97
