### ISSUE TITLE
Tabs 组件 tabLightStyle 计算错误

### ISSUE THREAD

**Issue by wenzhixin** [museui/muse-ui#309]
[jsfiddle](https://jsfiddle.net/wenyi/odngmpg5/2/)，重现步骤：
1. 点击两次 **是否完成**
2. 切换 tab 即可看到

![image](https://cloud.githubusercontent.com/assets/2117018/23098120/0ea15388-f681-11e6-95b4-8da61e3f6e01.png)

**Comment by myronliu347** [comment]
嗯，确实有问题，给我点时间修复
