### ISSUE TITLE
又发现了俩问题，appbar和badge的

### ISSUE THREAD

**Issue by BubblyPoker** [museui/muse-ui#31]
1. appbar的title文字未居中，建议增加参数设置居中，或者直接设为居中，因为很多时候title都是居中显示的

2. badge的color参数失效，看了源码`background-color`拼写错误，写成了`backgroud-color`，导致无法改变背景

会一直跟进的...

**Comment by myronliu347** [comment]
fix in [2.0.0-alpha.5](https://github.com/museui/muse-ui/tree/2.0.0-alpha.5), 
appbar title在material design就不是居中显示的,需要居中的话可以利用`slot`

```html
<mu-appbar>
    <div style="text-align:center">Title </div>
</mu-appbar>
```
