### ISSUE TITLE
我的项目在import  并  use 后  得到这个错误   

### ISSUE THREAD

**Issue by jiahua1** [museui/muse-ui#311]
![52803b29-041a-4577-a565-631c11d32ae5](https://cloud.githubusercontent.com/assets/11866846/23100803/4c97f0be-f6c4-11e6-86ac-4a6cdcc15d20.png)

**Comment by myronliu347** [comment]
请给出具体的使用代码，和 Vue版本 muse-ui版本

**Comment by myronliu347** [comment]
请给出详细信息后重开

**Comment by jiahua1** [comment]
<img width="762" alt="mainjs" src="https://cloud.githubusercontent.com/assets/11866846/23102377/11439ce2-f6e3-11e6-81f7-c00eb7cf2610.png">这是main.js

**Comment by jiahua1** [comment]
<img width="684" alt="c3af93c1-6360-4ef1-9993-f87ce993e7cf" src="https://cloud.githubusercontent.com/assets/11866846/23102394/2e3296fa-f6e3-11e6-85a1-31fd461db3f3.png">
<img width="274" alt="62fa588b-f248-484f-95d8-f125afe9572f" src="https://cloud.githubusercontent.com/assets/11866846/23102395/30bafd2c-f6e3-11e6-8937-8bdd26f302fc.png">
<img width="378" alt="b4896706-1ff0-4c53-af58-eb06e8b5b7ca" src="https://cloud.githubusercontent.com/assets/11866846/23102396/32c486c4-f6e3-11e6-8c6e-c1074b5fa04c.png">
<img width="472" alt="8494a84f-070d-4fc8-9adc-166a8da65942" src="https://cloud.githubusercontent.com/assets/11866846/23102397/3800bea0-f6e3-11e6-9477-9abfe9915979.png">一个vue 引了三个文件

**Comment by jiahua1** [comment]
<img width="490" alt="93d456b7-51af-4b52-8e46-6e90040772ee" src="https://cloud.githubusercontent.com/assets/11866846/23102400/531063c6-f6e3-11e6-85f4-17e0e2e47008.png">
这是我的依赖版本

**Comment by myronliu347** [comment]
示例Vue里似乎没有实现render函数

**Comment by jiahua1** [comment]
文档使用里没有要求使用render函数啊
![3255a6fd-5a48-4869-b5c2-2455ab1343bf](https://cloud.githubusercontent.com/assets/11866846/23109248/4a922af8-f752-11e6-8226-7dc70d8db2ae.png)

**Comment by jiahua1** [comment]
？

**Comment by myronliu347** [comment]
Vue 情动的时候需要实现render

**Comment by jiahua1** [comment]
<img width="606" alt="43d35f04-35cd-4453-8886-5df4adc0be7b" src="https://cloud.githubusercontent.com/assets/11866846/23110892/9946aa18-f75f-11e6-9162-b449f9c1195f.png">
这是我的main.js    提示找不到app    是应该写在这里吗？    我把你的框架yarn add 下来    使用文档你应该也把render写进去吧？   我不是太理解。并且我看了文档app应该是jsx类似标签的东西.谢谢。

**Comment by myronliu347** [comment]
这个是vue基础里面的， 一般起步只到 .use 方法使用

**Comment by myronliu347** [comment]
这边的APP组件需要大写， h(App)

**Comment by jiahua1** [comment]
页面渲染时 我还是得到这个错误
![a5efb124-a762-4875-825d-839f4cdc84df](https://cloud.githubusercontent.com/assets/11866846/23111772/e33a0e5c-f765-11e6-8de2-872061866e04.png)

**Comment by jiahua1** [comment]
<img width="448" alt="4f66e5cf-b467-486c-80b4-925885eb6da0" src="https://cloud.githubusercontent.com/assets/11866846/23111821/21bdde56-f766-11e6-82df-ef0dff845cf8.png">
这是我的main.js

**Comment by jiahua1** [comment]
?

**Comment by jiahua1** [comment]
？。。
