### ISSUE TITLE
引入mobileTearSheet报错

### ISSUE THREAD

**Issue by le0zh0u** [museui/muse-ui#312]
我想使用SubHeader，其中用到了mobileTearSheet，在示例代码中使用了相对目录引入：import mobileTearSheet from '../../../components/mobileTearSheet'，但是报错了，是需要自己建这个vue文件吗？还是import的路径错误？

**Comment by myronliu347** [comment]
这个不在源码里，是demo网站中独立的组件

**Comment by le0zh0u** [comment]
这个组件是什么方便透露一下吗

**Comment by myronliu347** [comment]
就是一个ui框，底部有个波浪线的这种，没有实际意义
