### ISSUE TITLE
table组件如果横向很长，会出现bug，文字重叠

### ISSUE THREAD

**Issue by d87904488** [museui/muse-ui#316]
![qq 20170223001238](https://cloud.githubusercontent.com/assets/18729228/23220398/dd981f9a-f95c-11e6-95e3-5b0459fe88a6.png)
如上图，文字重叠在了一起，如果以后能自定义，每列的宽度就好了

**Comment by myronliu347** [comment]
每一列的宽度是可以自定义的mu-td这个组件可以混入其它样式和属性
