### ISSUE TITLE
我的主题切换功能使用姿势对吗？

### ISSUE THREAD

**Issue by H2rmone** [museui/muse-ui#320]
![image](https://cloud.githubusercontent.com/assets/18731042/23286493/dba07acc-fa72-11e6-8730-b3562431faca.png)
![image](https://cloud.githubusercontent.com/assets/18731042/23286498/ecc36396-fa72-11e6-8bf7-2b5313f2097b.png)
![image](https://cloud.githubusercontent.com/assets/18731042/23286514/046e4966-fa73-11e6-8654-8c3f6af235ab.png)

上述是我的代码，dev后点击增加的style里面内容为
![image](https://cloud.githubusercontent.com/assets/18731042/23286528/2d7708d4-fa73-11e6-9241-06495b728ebf.png)

**Comment by myronliu347** [comment]
上面的代码我在主题切换的部分有提供，下面这个是要做动态替换么 ？
