### ISSUE TITLE
请问如何区分多个dialog呢？ 

### ISSUE THREAD

**Issue by jiahua1** [museui/muse-ui#321]
<img width="562" alt="64ee1c76-50cf-4bee-b0b0-ac89c3679d36" src="https://cloud.githubusercontent.com/assets/11866846/23302468/c69c52fc-fac9-11e6-9f8a-824e3df0f92c.png">

这是引用的地方

<img width="186" alt="f124cda0-b309-4b73-9af8-22ce4ad1a72b" src="https://cloud.githubusercontent.com/assets/11866846/23302292/215a3372-fac9-11e6-9f4f-103fb67e01c9.png">

这是Data绑定。

我期望提供多个 ：open 绑定的props值  如 dialog: false,    dialoga: false,  dialogb: false,
但是并没有起作用。。

**Comment by jiahua1** [comment]
???

**Comment by jiahua1** [comment]
比如有多个地方   需要唤起不同内容弹窗

**Comment by jsxyhdy** [comment]
@jiahua1 不同的mu-dialog的:open绑定到不同的属性上。

**Comment by wenzhixin** [comment]
https://jsfiddle.net/wenyi/odngmpg5/5/

**Comment by jiahua1** [comment]
我想过这样实现。但这样实现并不优雅，如果有很多弹窗我要定义很多的data

**Comment by jiahua1** [comment]
我希望通过在js 中   直接调用   类似于   window.alert('text');

**Comment by jiahua1** [comment]
那样的话我就必须在父组件中做一个事件中心，也不是很优雅，，有更好的解决办法吗？

**Comment by zhoucumt** [comment]
![image](https://cloud.githubusercontent.com/assets/6021846/23339950/cc55dd2c-fc67-11e6-8189-f3fde3857b62.png)
我也很想问这个问题，比如页面上同时有两个甚至多个简单的使用中的button需要点击，然后弹出弹窗，这个时候怎么做？每个mu-raised-button怎么区分到底是触发的哪一个浮层呢？

**Comment by myronliu347** [comment]
其实也有一些别的方案，例如像这样
https://jsfiddle.net/wenyi/odngmpg5/5/
使用这种类似枚举的做法只是为了更加规范（1，2，3这种不容易让人明白），当然你可以直接使用字符串

**Comment by jiahua1** [comment]
我觉得这并不是 好的实现，我期望在js中调用多个，类似于   this.setPopup('popupa')

**Comment by wenzhixin** [comment]
目前的做法是在 App.vue 中添加全局的 dialog，然后使用全局事件的方式，调用：
```js
eventHub.$emit('alert', 'xxx')
```

**Comment by jiahua1** [comment]
对就是在父组件中放一个事件中心   然后在调用地方触发事件

**Comment by wenzhixin** [comment]
或者可以考虑扩展 Vue 的方法，如：
```js
Vue.prototype.$alert = ...
Vue.prototype.$confirm = ...
Vue.prototype.$prompt = ...
Vue.prototype.$toast = ...
```
然后在所有组件就可以直接使用
```
this.$alert('xxx')
```
不知道作者有没有考虑过这种实现方式。

**Comment by jiahua1** [comment]
这个弹窗是如何实现的？Vue.prototype.$alert = ...

**Comment by jiahua1** [comment]
可以辛苦给个事例吗    在 jsfiddle

**Comment by myronliu347** [comment]
怎么说呢，如果使用vuex的方案的话建议在顶层组件控制不同dialog的弹出，内部使用公用的action调用，如果不适用vuex，可以考虑协议个单独的弹窗的库。不建议直接对vue扩展，

**Comment by jsxyhdy** [comment]
用vuex做一个全局状态控制文本框的显示和内容，我觉得很优雅啊。
在vuex store里面建立一个dialog模块，专门用于管理全局对话框的数据和事件操作，在需要的时候commit就好了。this.$store.commit('showdialog', msg) 这样的调用方式和windows.alert()有什么区别么？
我觉得这样很优雅，显示，数据，事件都分离了。

**Comment by jiahua1** [comment]
@wenzhixin     https://jsfiddle.net/wenyi/odngmpg5/5/     这种方式实现不了。  没有提供@close="dialoga = false"

**Comment by wenzhixin** [comment]
@jiahua1 不懂你说的是什么意思

**Comment by jiahua1** [comment]
@close   dialog组件里没有定义

**Comment by jiahua1** [comment]
<img width="649" alt="d3c466d8-296e-4401-a8ee-03a105fb7152" src="https://cloud.githubusercontent.com/assets/11866846/23413306/3a3f6ffe-fe13-11e6-9b02-757b486bfa94.png">

**Comment by jiahua1** [comment]
还是不能区分多个弹窗

**Comment by myronliu347** [comment]
https://jsfiddle.net/odngmpg5/7/
看这个 上次写了好像没保存就发了。。。
