### ISSUE TITLE
mu-text-field could not draw 1-lined textarea

### ISSUE THREAD

**Issue by alexey2baranov** [museui/muse-ui#331]
hello! 
```html
<mu-text-field multiLine :rows="1" :rowsMax="5" v-model="model.question" />
```
draws 2-lined input but should draw 1-lined

**Comment by shijiansu** [comment]
I think it is possible that when the row = 1, the (height > minHeight) and (height < maxHeight) causes the issue.
Source Code: <https://github.com/museui/muse-ui/blob/master/src/textField/enhancedTextarea.vue>
````javascript
let minHeight = pd + pt + lineHeight * this.rows
      let maxHeight = pd + pt + lineHeight * (this.rowsMax || 0)
      let height = hiddenEl.scrollHeight
      element.style.height = (height < minHeight ? minHeight : height > maxHeight && maxHeight > 0 ? maxHeight : height) + 'px'
````

**Comment by myronliu347** [comment]
Sorry, I forgot!
I will check, after reply

**Comment by alexey2baranov** [comment]
I updated muse-ui to  2.0.1 
now i see single-line text area but it has very big height exactly like two lined textarea. As result i have single line textarea which hold screen place as previous bugged two lines textarea. And no free screen performance 

I'm very confusing is this a correct layout for text component. How can we get it exactly single-line initial height? As I can understand this is because muse-ui.css min-height is for two lined textarea
```css
.mu-text-field {
    min-height: 48px; 
}
```

**Comment by myronliu347** [comment]
This is the minimum height of the textField, you can set `inputClass` to change height

```html
<template>
<div>
  <mu-text-field hintText="多行文本输入，默认 3行，最大6行" inputClass="custom-input" multiLine :rows="1" :rowsMax="6"/><br/>
</div>
</template>
<style>
.custom-input{
  font-size: 36px
}
</style>

```

**Comment by alexey2baranov** [comment]
@myronliu347 
:rows="1" not works up today/ do you plan to fix it in future?
