### ISSUE TITLE
feature request: mu-text-field @keyup

### ISSUE THREAD

**Issue by alexey2baranov** [museui/muse-ui#332]
hello! 

We would like to have another  @keyup event in mu-text-field. It can be very helpful to implement Ctrl+Enter to send message behavior

Thanks

**Comment by lcnju** [comment]
hi，you may be use `.native` to implement the event linstener
```
<mu-text-field v-on:keyup.ctrl.enter.native="search"/>
```
see the vue document [here](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components)

**Comment by alexey2baranov** [comment]
I will try. Thank you!
