### ISSUE TITLE
生产如何配置，才能像你将封装ui库生成一个单独的js文件，在html直接引入运行

### ISSUE THREAD

**Issue by yezhiyong2017** [museui/muse-ui#333]
我用的是vue.cli  "webpack": "^2.2.1",

**Comment by myronliu347** [comment]
不太懂，你是封装自己的UI库 ？

**Comment by myronliu347** [comment]
```javascript
```
output: {
    path: path.resolve(__dirname, '../dist'),
    filename: 'muse-ui.js',
    library: 'MuseUI',   // 输出js库名
    libraryTarget: 'umd'
  },
  externals: {
    vue: {                             // 依赖的库配置外链
      root: 'Vue',
      commonjs2: 'vue',
      amd: 'vue',
      commonjs: 'vue'
    }
  },
```
```
