### ISSUE TITLE
请问Muse UI如何适配移动设备retina屏幕？

### ISSUE THREAD

**Issue by paraself** [museui/muse-ui#334]
在移动设备上试了下muse ui 发现没有适配retina屏幕，请问这部分功能目前muse有计划加入么？
![wechatimg12](https://cloud.githubusercontent.com/assets/2179686/23575497/30ecb38c-00c8-11e7-91c2-435fe951173a.jpeg)

**Comment by paraself** [comment]
但是用移动设备看了下museui.github.io，发现是正常的，请问是不是需要哪里设置一下？

**Comment by myronliu347** [comment]
viewport没有配置 html里需要加上
