### ISSUE TITLE
Dialog的阴影会闪烁

### ISSUE THREAD

**Issue by paraself** [museui/muse-ui#336]
![dialog flicker](https://cloud.githubusercontent.com/assets/2179686/23587953/a08631a4-01f0-11e7-838f-7b07b3300427.gif)

在Chrome上Dialog的阴影会闪烁，在Safari下就不会，请问这个是bug么？

**Comment by myronliu347** [comment]
周末看了下确实有这个问题，不过最近太忙了，可能没时间改

**Comment by myronliu347** [comment]
已修改，但没有在发布版本，近期会更新

**Comment by lufeng4828** [comment]
我更新到2.0.1版本，chrome浏览器下发现这个问题还存在，请问这个bug还没有修复么？

**Comment by myronliu347** [comment]
现在已经不会了呀

**Comment by lufeng4828** [comment]
看了下，是缓存没有更新，谢了！奇怪了，平时chrome debug模式不会缓存的，今儿怎么缓存那么久
