### ISSUE TITLE
在firefox下图标都无法显示，chrome正常。

### ISSUE THREAD

**Issue by dongshimou** [museui/muse-ui#337]
![1](https://cloud.githubusercontent.com/assets/9100799/23594058/be8cb4fa-0251-11e7-9abd-b822777f6bb3.png)
![2](https://cloud.githubusercontent.com/assets/9100799/23594059/be94c5e6-0251-11e7-95ce-99b85d7a35b5.png)

我要做什么修改呢？

**Comment by myronliu347** [comment]
首先先要确定是否是icon文件没有下载下来，
https://material.io/icons/ 这里有icon的使用说明
