### ISSUE TITLE
Select Field 完全不能用

### ISSUE THREAD

**Issue by JavaCS3** [museui/muse-ui#338]
Vue 2.2.1
Muse 2.0.0.rc5

    <div id="app">
        <mu-select-field v-model="game2" multiple label="选择多个">
            <mu-menu-item value="1" title="阴阳师" />
            <mu-menu-item value="2" title="影之刃" />
            <mu-menu-item value="3" title="天下HD" />
            <mu-menu-item value="4" title="穿越火线" />
            <mu-menu-item value="5" title="英雄联盟" />
            <mu-menu-item value="6" title="王者荣耀" />
        </mu-select-field>
    </div>

    <script>
        Vue.use(MuseUI);
        var vm = new Vue({
            el: '#app',
            data: {
                game2: ['1']
            }
        });
    </script>

![shot](https://cloud.githubusercontent.com/assets/4168698/23595693/db9f36a0-025e-11e7-9820-808c6502cbfb.gif)

**Comment by mokaikai** [comment]
https://jsfiddle.net/cxmokai/Ls42v2se/2/
确实有这个问题

**Comment by JavaCS3** [comment]
这个bug太严重了，不应该出现在rc版本里面

**Comment by myronliu347** [comment]
https://jsfiddle.net/Ls42v2se/4/

**Comment by JavaCS3** [comment]
@myronliu347 
文档写错了啊！！！

![image](https://cloud.githubusercontent.com/assets/4168698/23601414/4c182fc8-0286-11e7-978d-55d4d2d7adfe.png)

**Comment by myronliu347** [comment]
不是， html 和 .vue文件中的使用区别， 我的demo都是在.vue文件中写的，所以尽量简洁

**Comment by JavaCS3** [comment]
怪不得，我还不太会Webpack，ES6，太Fancy了
