### ISSUE TITLE
Text Field 组件可以当作form表单来用吗？

### ISSUE THREAD

**Issue by jinyahuan** [museui/muse-ui#339]
因为发现Text `Field没有‘name’等属性，试了下` :name="XXX" 和 :attr="name='XXX'"也不行。

**Comment by lvxiaoshu** [comment]
应该可以的,你可以试试

**Comment by myronliu347** [comment]
嗯，这个确实被我删掉了，请问是要在那种清空下使用name呢 ？有必要的话可以在所有元素里加上

**Comment by jinyahuan** [comment]
主要还是要把‘Text Field’当作form表单的input来用，因为缺乏name属性所以无法正确发送参数请求。现在只能用隐藏域来双向绑定‘Text Field’的value来实现这种效果，比较麻烦。。。
