### ISSUE TITLE
appbar 多增加几个右边按钮，会导致title为空。

### ISSUE THREAD

**Issue by gofmt** [museui/muse-ui#34]

**Comment by myronliu347** [comment]
fix in [2.0.0-alpha.5](https://github.com/museui/muse-ui/tree/2.0.0-alpha.5)

**Comment by gofmt** [comment]
OK,经过alpha.6测试,并没有解决这个问题.

    <mu-appbar :zDepth="0" :title=Test">
      <mu-icon-button @click="toggleSidebar" icon='menu' slot="left"/>
      <mu-icon-button icon='apps' slot="right"/>
      <mu-icon-button @click="toggleMessagePopover" ref="messagepopover" icon='notifications' slot="right"/>
      <mu-icon-button @click="toggleUserPopover" ref="userpopover" icon="account_circle" slot="right" tooltip="用户" tooltipPosition="bottom-left"/>
    </mu-appbar>

**Comment by myronliu347** [comment]
title 是 string, 所以这里应该是

```html
<mu-appbar :zDepth="0" title="Test">
</mu-appbar>
```

**Comment by gofmt** [comment]
这个是我在线修改的笔误,实际上是有双引号的.

**Comment by gofmt** [comment]
测试发现 mu-appbar-title  的文字是空的.并不是溢出导致的.

**Comment by myronliu347** [comment]
不是双引号的问题 `:title="Test"` 这么写是绑定的 vm里的Test属性

**Comment by gofmt** [comment]
OK,不增加冒号,同样是空内容.

**Comment by gofmt** [comment]
<div class="mu-appbar"><div class="left"><button type="button" tabindex="0" class="mu-icon-button" style="user-select: none; outline: none; cursor: pointer; -webkit-appearance: none;"><div><div class="mu-ripple-wrapper"></div> <i aria-hidden="true" class="mu-icon material-icons menu" style="font-size: 24px; width: 24px; height: 24px;">menu</i> </div></button></div> <div class="mu-appbar-title">   </div> <div class="right"><button type="button" tabindex="0" class="mu-icon-button" style="user-select: none; outline: none; cursor: pointer; -webkit-appearance: none;"><div><div class="mu-ripple-wrapper"></div> <i aria-hidden="true" class="mu-icon material-icons apps" style="font-size: 24px; width: 24px; height: 24px;">apps</i> </div></button><button type="button" tabindex="0" class="mu-icon-button" style="user-select: none; outline: none; cursor: pointer; -webkit-appearance: none;"><div><div class="mu-ripple-wrapper"></div> <i aria-hidden="true" class="mu-icon material-icons notifications" style="font-size: 24px; width: 24px; height: 24px;">notifications</i> </div></button><button type="button" tabindex="0" class="mu-icon-button" style="user-select: none; outline: none; cursor: pointer; -webkit-appearance: none;"><div><div class="mu-ripple-wrapper"></div> <i aria-hidden="true" class="mu-icon material-icons account_circle" style="font-size: 24px; width: 24px; height: 24px;">account_circle</i> <div class="mu-tooltip" style="right: 0px; top: 36px; transform: translate(0px, 14px);"><div class="mu-tooltip-ripple" style="left: 100%; top: 0px; width: 0px; height: 0px;"></div> <span class="mu-tooltip-label">用户</span></div></div></button></div></div>

这是渲染后的结果.

**Comment by myronliu347** [comment]
```html
<mu-appbar :zDepth="0" title="Test">
    <mu-icon-button icon='menu' slot="left"/>
    <mu-icon-button icon='apps' slot="right"/>
    Test22
    <mu-icon-button ref="messagepopover" icon='notifications' slot="right"/>
    <mu-icon-button ref="userpopover" icon="account_circle" slot="right" tooltip="用户" tooltipPosition="bottom-left"/>
  </mu-appbar>
```

vue 编译的时候，把文本节点也算在slot 里面了
