### ISSUE TITLE
muse-ui引入使用总是失败，提示module 没找到组件

### ISSUE THREAD

**Issue by zhou1178539345** [museui/muse-ui#341]

**Comment by myronliu347** [comment]
请给出muse-ui和vue的版本，然后给出使用的代码

**Comment by zhou1178539345** [comment]
![qq 20170307103234](https://cloud.githubusercontent.com/assets/18715564/23639267/bfb0ff8c-0321-11e7-9d5d-2485d2469ec7.png)
![qq 20170307103237](https://cloud.githubusercontent.com/assets/18715564/23639264/bf2d72f2-0321-11e7-8931-cfaa5c9ab8c6.png)
![qq 20170307103239](https://cloud.githubusercontent.com/assets/18715564/23639265/bf68efee-0321-11e7-98ca-9f92261a01a4.png)
![qq 20170307103354](https://cloud.githubusercontent.com/assets/18715564/23639266/bfa7bed6-0321-11e7-9e94-339246ac8f00.jpg)
![qq 20170307103227](https://cloud.githubusercontent.com/assets/18715564/23639268/bfe560a6-0321-11e7-9c18-ca25ffe9ea0d.png)

**Comment by zhou1178539345** [comment]
哥们儿，给解决一下啊

**Comment by myronliu347** [comment]
muse-components这个没有配置，所以找不到，你已经全局安装了muse,就不用这么写，
muse-components相关的删掉就行

**Comment by zhou1178539345** [comment]
谢了，昨天解决了
