### ISSUE TITLE
怎么自定义主题啊...新手刚入手,谢谢!

### ISSUE THREAD

**Issue by dmlzj** [museui/muse-ui#342]
`@import "muse-ui/less/vars.less"; // 默认基础的变量

// 修改基础变量

@primaryColor: @lightBlue700;
@darkerPrimaryColor: @lightBlue700;
@lighterPrimaryColor: @grey600;
@accentColor: @pinkA200;
@darkerAccentColor: @pinkA400;
@lighterAccentColor: @pinkA100;

@textColor: @fullWhite;
@secondaryTextColor: fade(@fullWhite, 70%);
@alternateTextColor: #303030;
@borderColor: fade(@fullWhite, 30%);
@disabledColor: fade(@fullWhite, 30%);

// background
@backgroundColor: #303030;
@statusBarBackgroundColor: @fullBlack;
@appbarBackgroundColor: @grey900;
@dialogBackgroundColor: #424242; // dialogs or cards

// icon
@activeIconColor: fade(@fullWhite, 100%);
@inActiveIconColor: fade(@fullWhite, 50%);

@import "muse-ui/less/theme-vars.less";  // 默认组件变量

// 修改组件变量
@avatarBackgroundColor: lighten(@alternateTextColor, 26%);
@datePickerHeaderColor: fade(@fullWhite, 12%);
@timePickerHeaderColor: fade(@fullWhite, 12%);
@timePickerClockCircleColor: fade(@fullWhite, 12%);
@avatarBackgroundColor: lighten(@alternateTextColor, 26%);
@chipColor: lighten(@alternateTextColor, 12%);
@floatButtonDisabledColor: lighten(@alternateTextColor, 12%);

@tableRowHoverBackgroundColor: fade(@textColor, 10%);
@tableRowSelectedBackgroundColor: fade(@textColor, 5%);

@import "muse-ui/less/theme.less"; // 主题相关的样式`
这些代码要在哪里运行啊?还是直接改已有的样式名称为新的样式名称,然后再改里面的颜色....

**Comment by myronliu347** [comment]
新建一个less文件， 可以看下这个主题的定义
https://github.com/museui/muse-ui/blob/master/src/styles/themes/dark.less

**Comment by smoook** [comment]
关于自定义主题请问：
1.按你所说的引入https://github.com/museui/muse-ui/blob/master/src/styles/themes/dark.less 这个文件根本就不行，因为这个文件里面有很多依赖的less，然后我把整个styles文件夹加在我的项目里也还是不行，真的很头疼
2.你所说的引入是在main.js里直接import，还是在App.vue里@import呢 这两种方法我都试过了 可还是不起作用

**Comment by myronliu347** [comment]
不用引入这个，我是说参考这个自定义主题写

**Comment by youzime** [comment]
我也想问这个写好的自定义的less文件是放在哪个目录下的

**Comment by myronliu347** [comment]
https://github.com/museui/muse-ui/blob/master/src/styles/themes/dark.less
源码里的路径

**Comment by bwqgithub** [comment]
@myronliu347  为什么我修改了dark.less文件无效呢，刚刚用vue不太明白。已经安装了 less loader。
