### ISSUE TITLE
安卓5.1 ios8.2 不兼容 不能正常显示

### ISSUE THREAD

**Issue by jaweii** [museui/muse-ui#343]
这只是我找身边的两个朋友测试的结果，我用阿里的MQC H5测试，发现安卓低版本设备的支持率很低

兼容性比我想象中低太多了。。。

想请问下这个ui最低支持安卓和ios什么版本？

如何向下兼容？

**Comment by JavaCS3** [comment]
作者貌似有个移动端专用的框架
https://github.com/myronliu347/vue-carbon

**Comment by jaweii** [comment]
我记得muse-ui就是vue-carbon的升级，vue-carbon相当于不维护了

**Comment by jaweii** [comment]
@myronliu347 老大为什么还没回复？急啊！我该怎么解决。。。

**Comment by myronliu347** [comment]
能先给个截图么，我看下具体情况

**Comment by jaweii** [comment]
正常情况是这样的：
![1](https://cloud.githubusercontent.com/assets/22613580/23839334/4b4aaba0-07d8-11e7-9873-22d3f3229675.gif)
在ios8.2系统是这样的：
![2](https://cloud.githubusercontent.com/assets/22613580/23839342/58e081ea-07d8-11e7-8512-1047e6194d0c.jpg)
安卓5.1则是空白

**Comment by myronliu347** [comment]
动画没动，还是输入文字 ？

**Comment by jaweii** [comment]
首先是动画效果没了，我查了很久好像是因为ios8.x版本对-webkit-animation属性支持有兼容问题，因为svg的动画也没了
另外ios8.x不兼容就是muse-ui组件交互效果没了，比如点击按钮没有任何反应，不会有波纹，不会触发事件
另外安卓低版本不兼容就是页面无法打开，控制台报错

**Comment by myronliu347** [comment]
这个问题，需要实际调试下，值安卓低版本上报错，这个问题，请给出具体的报错信息

**Comment by jaweii** [comment]
如图
![console](https://cloud.githubusercontent.com/assets/22613580/23885656/9bc31450-08af-11e7-9cf7-59c47a9f138d.png)

**Comment by jaweii** [comment]
如图：
![console](https://cloud.githubusercontent.com/assets/22613580/23885686/d16cf8d2-08af-11e7-8e83-d21c062c9b14.png)

**Comment by myronliu347** [comment]
使用textField报错的么 ？
