### ISSUE TITLE
所有弹出类控件在移动端都有滚动穿透问题

### ISSUE THREAD

**Issue by hearain** [museui/muse-ui#344]
比如Drawer,dialog,bottomsheet等都存在滚动穿透的问题，当滚动弹层，底层容器也会随之滚动，即使存在遮罩层也会有这个问题，甚至会出现遮罩曾断裂的问题（底层容器被滑动到上面内容，但遮罩仍然在下面）
其中DatePicker和TimePicker在弹出时会导致一瞬间的页面下滑的情况。
官方demo中就存在这个问题，iOS和Android平台下都存在该问题

在弹出上面加上Text Field 点击输入当键盘出来后因为滚动穿透会导致遮罩断裂
![image](https://cloud.githubusercontent.com/assets/9176349/23739192/33e0b1ec-04d8-11e7-9d57-22311021bd9c.png)

**Comment by myronliu347** [comment]
已锁定滚动条，弹出时不再滚动

**Comment by lany44** [comment]
我今天也遇到这个问题了，版本是 2.0.2
移动端 iphone 6 wx webview
官网 pop-up 下方出现可重现

**Comment by 1008611** [comment]
用微信浏览器打开 http://www.muse-ui.org/#/dialog  还是存在滚动穿透的问题。
