### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by guanbiao33** [museui/muse-ui#345]
icon=“alarm-check”
显示效果如图，是不是哪里错了，还有就是对照icon列表好多icon都用不了，可不可以给个版本对照。
![qq 20170310110029](https://cloud.githubusercontent.com/assets/16236310/23780285/e02dab28-0580-11e7-86e3-a7bf5da857b8.png)

**Comment by jjjachyty** [comment]
icon=“alarm-check”  换成icon=“alarm_check”

**Comment by JavaCS3** [comment]
他的文档写好多都不对~

**Comment by jjjachyty** [comment]
是有些不是很完美的地方 开源的需要有更多的人参与进来维护才行

**Comment by myronliu347** [comment]
https://material.io/icons/
icon 的使用看这里，官方文档

**Comment by myronliu347** [comment]
实在是精力有限，最近加班又比较猛
