### ISSUE TITLE
2.0.0-rc.5颜色深浅等级不生效

### ISSUE THREAD

**Issue by jjjachyty** [museui/muse-ui#346]
使用2.0.0-rc.5,在使用颜色深浅的时候不生效，使用red teal 这种可以，不可以使用redA700 pink50调节深浅

  <mu-card-title class="redA700"  title="xx" subTitle="xxx"/>  红色不生效

  <mu-card-title class="red"  title="xx" subTitle="xxx"/>  红色生效

**Comment by myronliu347** [comment]
可以给个具体的例子么，是在组件中使用不生效么 ？

**Comment by myronliu347** [comment]
我先关掉了，请提供具体的demo后重开

**Comment by jjjachyty** [comment]
class="teal" 生效  class="teal100" 不能渲染颜色

**Comment by myronliu347** [comment]
没有这个样式啊

**Comment by jjjachyty** [comment]
不能使用 teal100 或者 tealA100 这种变量 直接替代颜色样式嚒？

**Comment by myronliu347** [comment]
不行，只有设置颜色的地方可以填写这些颜色变量，或者在less文件中引入颜色变量
