### ISSUE TITLE
TextField type=Number的时候可以输入字母e 并且显示 hintText

### ISSUE THREAD

**Issue by jjjachyty** [museui/muse-ui#347]

**Comment by myronliu347** [comment]
这个type number 的处理是浏览器处理的，能输入字母e，我想大致是科学计数法的问题，先标哥bug吧，我稍后处理

**Comment by myronliu347** [comment]
已修改，但没有在发布版本，近期会更新

**Comment by jaweii** [comment]
@myronliu347 老大 你这个修改造成了另一个bug

我应用本来没问题的，muse重装后，数字输入框组件就出问题了，于是看了下官网，又搜到了这里，所以我觉得应该是这次更新造成的bug

之前的textField组件的input类型是number，现在设置成type=number后，源码里还是type=text，这样的话手机输入法默认就不是数字键盘了

另外经我调试，发现textField有v-model时，textField的type=number是无效的，就是任何字符都能输入，删除v-model才能限制为数字输入

**Comment by jaweii** [comment]
这样就造成v-model绑定的数据类型不是number型，于是我的js逻辑又因为类型不是number报错了

**Comment by jaweii** [comment]
老大 改回来吧。。。
e不影响什么的。。。

**Comment by myronliu347** [comment]
你用number类型可以直接写v-model.number

**Comment by jaweii** [comment]
v-model.number是啥语法。。
我怎么搜不到 文档里也没有

**Comment by jaweii** [comment]
@myronliu347 然而我用v-moedel.number ，textField依然可以输入任何字符

**Comment by jaweii** [comment]
@myronliu347 用v-model.number textField依然可以输入任意字符，除非第一个字符是数字

**Comment by jaweii** [comment]
我说的不只是那一个问题。。

**Comment by jaweii** [comment]
@myronliu347 

我反馈的这个问题会不会解决啊？会的话我等着更新，不会的话回复下，我想其他办法。。。

**Comment by myronliu347** [comment]
会的，稍等
