### ISSUE TITLE
Auto Complete 控件在未弹出提示框的时候一直按回车会触发Select事件

### ISSUE THREAD

**Issue by JavaCS3** [museui/muse-ui#348]
JQuery 的都不会 http://jqueryui.com/autocomplete/#multiple

## 浮现代码
https://jsfiddle.net/javacs3/snq0car2/3/

## 步骤
![shot](https://cloud.githubusercontent.com/assets/4168698/23821001/7098f3ee-0661-11e7-8205-acf3ed06133a.gif)

**Comment by myronliu347** [comment]
已记录bug..

**Comment by jjjachyty** [comment]
用filter过滤方法的时候 如果改变datasource 则进入死循环
