### ISSUE TITLE
2.0.0-rc.5 mu-text-field 错误样式 与官网demo不一致

### ISSUE THREAD

**Issue by jjjachyty** [museui/muse-ui#349]
<mu-text-field fullWidth class="orange--text"   **errorText="passwdErr"** hintTextClass="gray--text" @change="vaildPasswd" hintText="1-16位密码" v-model="passwd" type="password" :maxLength="16" icon="lock"/><br/>

生成的错误样式 .error {
    background-color: #f44336 !important;
    border-color: #f44336 !important;
}
导致整个mu-text-field 全是红色，而不是只有底线红色

￼

![1](https://cloud.githubusercontent.com/assets/7439418/23822575/de50588c-0689-11e7-96d8-e62deec5a18b.png)

￼

**Comment by myronliu347** [comment]
能在jsfiddle上模拟下么，我并没有写着两行样式，这个.error的样式也不是全局的
