### ISSUE TITLE
SelectField

### ISSUE THREAD

**Issue by bairdweng** [museui/muse-ui#350]
selectField在电脑页面偶尔点击无法弹出，然后直接滚动到最底部。官网那个例子可以重现，测试机器是macpro，chrome。

**Comment by cyanolive** [comment]
同样遇到过这个问题，特别是selectField在加载时不显示，然后通过v-if控制后期加载的时候更明显（更容易触发这个bug），我在dropDownMenu里移除了menu里的v-if="openMenu"，貌似得到了一点点改善，但还是偶尔会出现，不知道是真的有用还是心理作用，也没太弄懂这个v-if的存在意义。应该openMenu为false时上层的popup已关闭？

**Comment by myronliu347** [comment]
我找找看，稍等

**Comment by myronliu347** [comment]
找到问题了，这个加上那个自动focus影响的，晚点我提交代码

**Comment by myronliu347** [comment]
已修改，但没有在发布版本，近期会更新
