### ISSUE TITLE
打开Dialog时屏幕如果有垂直滚动条，滚动条会消失，后面的内容会有一个小偏移

### ISSUE THREAD

**Issue by cyanolive** [museui/muse-ui#354]
是否可以做成后面的内容仍然显示滚动条但是不能滚动，这样就不会有一个视觉上的小偏移了

**Comment by myronliu347** [comment]
设置了overflow:hidden,所以没有滚动条，但是偏移的问题，之前好像没有

**Comment by cyanolive** [comment]
我的页面是自适应的，页面滚动条的消失会导致宽度重新计算，所以会有一个小的偏移，尝试取消overflow:hidden，后面的页面变得可以滚动了，更怪异，看起来要再增加个禁止滚动的逻辑？

**Comment by myronliu347** [comment]
overflow:hidden是最高效的，如果你有其它的方案可以提pr，之前我有试过用阻止事件冒泡的方式阻止滚动，但是，当你的弹出框中有滚动条的时候，滚动事件是会冒泡的
