### ISSUE TITLE
Drop Down Menu中如何获取title？？？

### ISSUE THREAD

**Issue by kukujbb** [museui/muse-ui#356]
因为我想要将确定的title发给后台，而不是value，是否有比较简单的方式呢？

**Comment by cyanolive** [comment]
做个value到title的映射呗，顺手还能使用v-for简化items的书写

**Comment by myronliu347** [comment]
@cyanolive  这种做法是推荐的

**Comment by myronliu347** [comment]
我可以在change的时候把title传过去

**Comment by kukujbb** [comment]
@cyanolive 不是很理解
