### ISSUE TITLE
Auto Complete插件的dataSource为null的时候后台报错，可否处理一下

### ISSUE THREAD

**Issue by jjjachyty** [museui/muse-ui#357]
我想通过Auto Complete输入的时候动态显示数据，当未查到数据的时候js报错，可否对dataSource位null 处理一下，另外希望Auto Complete 能同时支持 value text的过滤搜索 和 双显示，选择弹出内容的时候 显示text 值为value

**Comment by jjjachyty** [comment]
使用 filter 动态改变 dataSource的时候 会进入死循环

**Comment by myronliu347** [comment]
这个重复了，#348，
