### ISSUE TITLE
加了FastClick之后的bug。

### ISSUE THREAD

**Issue by bairdweng** [museui/muse-ui#358]
mu-icon-menu，mu-icon-menu在加了FastClick之后需要点击两次按钮才能触发事件，求解决方案？

**Comment by bairdweng** [comment]
补充下
![e0345ae5-63df-45cc-93a1-b0aa5d4ad3b4](https://cloud.githubusercontent.com/assets/8598304/23985111/27c76bc8-0a58-11e7-9c73-44dd72550dd3.png)
有个过渡方法分享下，让FastClick在头部以下生效。
![dcb318ea-86e2-4422-82e1-a43c6e498aa4](https://cloud.githubusercontent.com/assets/8598304/23985147/5f9ffa42-0a58-11e7-8f1d-c231e8f0007e.png)

**Comment by myronliu347** [comment]
最近刚修复这个问题，请等候更新

**Comment by bairdweng** [comment]
好的，幸苦了。
