### ISSUE TITLE
Is there a way to dynamically update the open status in the mu-list-item with toggleNested?

### ISSUE THREAD

**Issue by shijiansu** [museui/muse-ui#361]
Hi,

Thank you for the amazing Vue UI components! I have a question about how to dynamically update the open status in the mu-list-item with toggleNested. I want to hide the other opening menu items when I click the menu item. I try to use the @toggleNested or @click at the mu-list-item, to update the props.open, or data.nestedOpen. But even I have changed their value to false, it cannot hide the menu item. The props.open works for the first time only. Any idea about this? It would be great if there are some examples to show how to use the event handler at the mu-list-item. Thank you.

**Comment by shijiansu** [comment]
I think my problem solved... I use the @toggleNested, and below are some sample code.
````javascript
if(this.$refs.itself.nestedOpen){
......
  this.$refs.others.handleToggleNested()
......
}
````
Please let me know if you have better idea, thank you.

**Comment by myronliu347** [comment]
You can look demo https://jsfiddle.net/6ycjb9z1/1/

**Comment by shijiansu** [comment]
Thank you. I found the reason and the way to solve it. It is because when we toggle the item, the data of toggleNested change, but the props open is not. When I change the open again, but in the watch, it found the oldVal is the same as the val, so it does not update the data toggleNested but just return. So in this case, what I did is simply sync the props open in the @toggleNested, which is at that time being, the data toggleNested had updated.
恩, 我看了一下你的例子, 那个是好的, 但是不完全符合我现在的问题, 不过还是谢谢你. 我的问题是要改变其他的item, 不是改变被点击的item. 现在我的问题也解决了, 回头再看一下能不能用你的方式, 或找到更好的办法.
谢谢!
