### ISSUE TITLE
如何动态绑定数据到属性中

### ISSUE THREAD

**Issue by Shaman05** [museui/muse-ui#362]
如图：
![image](https://cloud.githubusercontent.com/assets/951756/24092859/f010e592-0d8b-11e7-832a-a48773499ab1.png)
求教：我要绑定 name 值，输出到 label 属性中，该怎么绑定？

**Comment by Shaman05** [comment]
我现在是去掉 label 属性，把 name 输出到标签里面，能显示值，但是图标位置就在左边了
![image](https://cloud.githubusercontent.com/assets/951756/24093360/685c106a-0d8e-11e7-8960-44d1c1fb2d7d.png)

**Comment by paraself** [comment]
... lable="name" ...

data () {
}

**Comment by Shaman05** [comment]
你确定这样可以？ 不会直接输出 name 字符串？

**Comment by Shaman05** [comment]
@paraself 你确定这样可以？不会直接输出name字符串？

**Comment by Shaman05** [comment]
换了一种方式：
![image](https://cloud.githubusercontent.com/assets/951756/24093808/aebbd106-0d90-11e7-89f0-9a2e62f63279.png)
组件嵌套输出了，把icon放按钮里面输出了

**Comment by Shaman05** [comment]
应该多尝试下的  >_<

**Comment by paraself** [comment]
你看文档嘛，完全没必要这样嵌套，文档写的很清楚的
```html
<mu-raised-button 
  class="demo-raised-button" 
  label="文字在前面" 
  labelPosition="before" 
  icon="folder" 
  secondary
/>
```
label 绑定按钮上的文字
labelPosition控制图标和文字的前后关系嘛

**Comment by Shaman05** [comment]
@paraself  汗！绑定数据是基本的，文档我也看过，如果这样能行，我就不会提这个低级问题了。

**Comment by paraself** [comment]
好吧，鉴于您表述问题的方法，我还真的是没有get到你问题的点...

**Comment by myronliu347** [comment]
https://jsfiddle.net/ 写个在线demo吧，然后说清楚你要把什么数据绑定到label,我也没有get到你的问题

**Comment by Shaman05** [comment]
或许我表达真有问题？
![image](https://cloud.githubusercontent.com/assets/951756/24181683/93e50010-0ef7-11e7-8fb4-aad545951503.png)

**Comment by Shaman05** [comment]
好吧，原来是用冒号来绑值

**Comment by paraself** [comment]
> 汗！绑定数据是基本的，文档我也看过，如果这样能行，我就不会提这个低级问题了。
你连vuejs的冒号绑定都不知道，居然还说看过文档，居然还说绑定数据是基本的。
看来这还真是个低级问题。

**Comment by Shaman05** [comment]
嗯

**Comment by Shaman05** [comment]
回看到了模板语法缩写了，是我看文档不仔细，感谢！

**Comment by myronliu347** [comment]
为了世界和平，我还是先关掉了
