### ISSUE TITLE
关于TextField某些空白处鼠标指针变为(单击)手势的问题

### ISSUE THREAD

**Issue by shijiansu** [museui/muse-ui#364]
将鼠标移至下图的"标签文字"时, 鼠标箭头指针变为(单击)手势, 但点击后并无什么特别.
![image](https://cloud.githubusercontent.com/assets/21063434/24134123/050239e0-0e3d-11e7-9b70-c0bf491b31a9.png)

该问题同样发现在TextField的下划线下面一点点的位置.

可以在<https://museui.github.io/#/textField>模拟出结果.

问题, 不知道这个是不是Bug还是有特定的需求实现. 因为用户使用起来有点疑惑, (单击)手势一般出现在超链接或者按钮上面, 但现在也在这个组件的空白处出现.

谢谢!

**Comment by myronliu347** [comment]
嗯嗯，多谢提醒，我改一下

**Comment by shijiansu** [comment]
不客气! 劳烦你了, 等手上项目有空后会尝试帮忙该项目改Bug或其他.

**Comment by shijiansu** [comment]
刚刚稍微看了一下, 手势是这个CSS引起的. 
.mu-text-field-content里面的cursor: pointer

**Comment by myronliu347** [comment]
是的，我昨天改了

**Comment by shijiansu** [comment]
好的, 谢谢了!
