### ISSUE TITLE
关于mu-text-field multiLine中的rowsMax属性

### ISSUE THREAD

**Issue by shijiansu** [museui/muse-ui#368]
根据Demo网上<https://museui.github.io/#/textField>的例子, 
````
<mu-text-field hintText="多行文本输入，默认 3行，最大6行" multiLine :rows="3" :rowsMax="6"/>
````
里面有配置:rowsMax="6", 但尝试过是可以输入多于6行的.
![image](https://cloud.githubusercontent.com/assets/21063434/24138542/892659fc-0e53-11e7-8057-748706fb9831.png)

我查看源代码<https://github.com/museui/muse-ui/blob/master/src/textField/enhancedTextarea.vue>, 发现rowsMax只是使用在计算let maxHeight上面, 本身并没绑定textarea的属性. 

这个rowsMax, 有计划会限制最大行数吗? 还是会像maxLength那样会触发事件交由开发人员各自处理呢?

谢谢!

**Comment by myronliu347** [comment]
这个是指超过6行就不会自动扩展高度了，不是只能输入6行

**Comment by shijiansu** [comment]
谢谢抽空回答! 恩, 明白了, 就是页面中最多显示6行没尽管用户还可以继续输入下去. 所以这里暂时不能限制最大行数, 输入可以通过maxLength触发@textOverflow去做逻辑.
