### ISSUE TITLE
能不能在DatePicker里增加一些props, slot和按钮的回调，这样可以结合DatePicker做一些信息的展示

### ISSUE THREAD

**Issue by paraself** [museui/muse-ui#369]
![1](https://cloud.githubusercontent.com/assets/2179686/24150730/8c56e2da-0e81-11e7-9e91-f1f10959fcfc.png)

![circle23](https://cloud.githubusercontent.com/assets/2179686/24151690/6f9ba542-0e84-11e7-9e07-eddd50862d11.gif)

目前用jQuery改了好多，但是改的很难受，如果能集成一些基本的信息展示的功能就再好不过了。
比如，提供回调方法，根据日期可以设置每个日期的颜色。提供slot来设置不同颜色的legend。等。

**Comment by myronliu347** [comment]
目前并不打算这么，感觉会跟本来的样式/操作冲突

**Comment by paraself** [comment]
好的，或者是，新增一个Calendar类型的组件？
像这种的
https://fullcalendar.io/

**Comment by myronliu347** [comment]
这个倒是可
