### ISSUE TITLE
关于SelectField通过键盘向下选择高亮时候的问题

### ISSUE THREAD

**Issue by shijiansu** [museui/muse-ui#371]
浏览器: Chrome

![image](https://cloud.githubusercontent.com/assets/21063434/24185127/808e3bca-0f0c-11e7-84a0-3b088571a2f7.png)
鼠标选择高亮时, 是浅灰色的.通过键盘向下选择高亮时候的问题, 那个深灰色的部分一直没有完全展开. 例子可以看Demo官网<https://museui.github.io/#/selectField>, 两者的行为不同, 不知道这里有没有问题, 

现在可以同时出现两个高亮, 并且按下enter是选取键盘高亮的,
![image](https://cloud.githubusercontent.com/assets/21063434/24185263/322defa6-0f0d-11e7-8819-521fad372236.png)

有个小建议. 参考其他Vue的select组件(例如<http://monterail.github.io/vue-multiselect/>), 可以考虑将鼠标高亮和键盘高亮统一起来, 并且鼠标左键和键盘enter都是只是选取当前唯一高亮选项.

**Comment by myronliu347** [comment]
这个列表的focus的样式是根据规范来的

**Comment by shijiansu** [comment]
可否分享规范的URL? 在https://material.io上面查找没有找到. 所以你所参考的规范, 也是可以允许同时两个Item高亮的?

**Comment by myronliu347** [comment]
这是两个状态，一个focus，一个hover

**Comment by shijiansu** [comment]
谢谢你的回复! 恩, 明白, 昨天看到一个另外的material Vue框架也是类似实现.
