### ISSUE TITLE
Grid栅格布局在手机环境不会触发width设定

### ISSUE THREAD

**Issue by ZzMark** [museui/muse-ui#375]
使用文档中的例子，在浏览器上直接调整宽度可以触发，但是开发模式中的手机模拟就不能触发，手机端也是同样，电脑浏览器Chrome57，手机端相同，node 6.9.5，npm 4.4.1，muse-ui rc5，vue 2.2.4，

app.vue

    <template>
      <div>
        <mu-row gutter>
          <mu-col width="100" tablet="50" desktop="33">col-100<br/>tablet-50<br/>desktop-33</mu-col>
          <mu-col width="100" tablet="50" desktop="33">col-100<br/>tablet-50<br/>desktop-33</mu-col>
          </mu-row>
      </div>
    </template>

main.js

    import Vue from 'vue'
    import App from './App.vue'
    import MuseUI from 'muse-ui'
    import 'muse-ui/dist/muse-ui.css'

    Vue.use(MuseUI)

    new Vue({
      el: '#app',
      render: h => h(App)
    })

**Comment by shijiansu** [comment]
我在Chrome中调至下图是可以的.
![image](https://cloud.githubusercontent.com/assets/21063434/24255909/bb2526a2-1021-11e7-9e0b-a58e52a78cbb.png)
但是我用的是Chrome Version 56

**Comment by ZzMark** [comment]
![qq 20170323234930](https://cloud.githubusercontent.com/assets/23636931/24256525/60ebfac4-1023-11e7-82d8-cfa5e020e37c.png)
但是我自己抄出来就不能用，难道是我缺少了什么东西

**Comment by ZzMark** [comment]
是我缺少了头部声明，感谢帮助

**Comment by wxkj001** [comment]
@ZzMark 能详细说一下怎么解决的吗，我也出现了同样的问题

**Comment by RunningV** [comment]
为什么不能自定义gutter的宽的？没法用啊这组件
