### ISSUE TITLE
建议对话框的快捷键功能是可选的，或者放到show阶段和close阶段处理

### ISSUE THREAD

**Issue by Potato2009** [museui/muse-ui#377]
如题由于按键绑定在mounted阶段就触发了，导致无法单独绑定esc按键，建议放到show阶段和close阶段处理或者提供选项可以关闭该功能

**Comment by cjz9032** [comment]
在@close中 `if(e.keyChar==='esc') return `

**Comment by Potato2009** [comment]
不是要禁用esc功能， 而是在mounted阶段就把esc按键这个事件给绑定了，建议加命名空间或者， 在show阶段绑更好
