### ISSUE TITLE
Popup中一些问题

### ISSUE THREAD

**Issue by cjz9032** [museui/muse-ui#378]
~/src/internal/popup/ 

1. ESC按键事件未正确处理.e.x.当同时存在一个dialog和drawer.他们都会监听到ESC.
是否应当在popManager中处理,将事件发送给对应的modal?

2. 禁止/允许滚动在showOverlay,closeOverlay其中.
那么如果有些modal不存在Overlay的情况,滚动是否就不禁止了,或者说现在所有modal必须有Overlay?

3. 还有把现在popManager中changeOverlayStyle, showOverlay, hideOverlay等方法放到Overlay其中实现,popManager加以装饰会不会更好?

4. overlay和model的zIndex现在是通过控制执行(zIndex++)顺序控制,改成computed会不会正常点?

5. Overlay中几个style样式放到单独的object中.
那么changeOverlayStyle写成`_.extendOwn(this.myStyle, style)`更简洁点.
不知道object能不能验证类型.官方文档只看到有一个default

6. util中keyCode方法.实际上获取到的是keyChar,而不是keyCode.
...

BTW:~/src-doc/app.vue中传open要3层(app> appNavDrawer> drawer)传下去,然后又要emit再3层传上来,学了几天Vue看到这里有点害怕..有没好点的方案?

**Comment by myronliu347** [comment]
1. 这个确实是个问题，我会处理的额，
2. 可以设置overlay = false 关闭overlay，现在默认是全部都有
3. overlay只有一个，这部分的代码优化你可以给个pr哦，
4. 待定，没太懂你的意思
5. 我可以自己写个工具还是，属于代码优化吧，目前功能没有问题
6. 现在keycode库局势吧code转成容易理解char
BTW: 这里没有使用vuex做状态管理，所以只能一级一级向下传，用来vuex会方便很多 https://vuex.vuejs.org/
