### ISSUE TITLE
Infinite Scroll 的高度100%的时候，在浏览器上无法使用

### ISSUE THREAD

**Issue by tingrun919** [museui/muse-ui#380]
如题

**Comment by myronliu347** [comment]
请给出具体的demo,模拟出错情况https://jsfiddle.net/

**Comment by tingrun919** [comment]
https://jsfiddle.net/fgLftsjg/3/
实际上我想实现Infinite Scroll铺满屏幕的效果，高度100%的话明显不行，有什么建议吗？

**Comment by myronliu347** [comment]
https://jsfiddle.net/fgLftsjg/4/,使用上的问题

**Comment by tingrun919** [comment]
当Infinite Scroll是子组件的时候真的无法使用。。。

**Comment by myronliu347** [comment]
这根子组件没关系，子组件的时候this.$el，并不是滚动元素

**Comment by xianzhi0520** [comment]
这个问题我也遇到了 不能用百分比 只能用固定宽度

**Comment by decadego** [comment]
height 为 100% 时，需要设置 body 的 height 才能触发 loadMore：
```
html, body {
  height: 100%;
}
```

这时如果浏览器出现两个纵向滚动条，把 div #app 的 margin-top 去掉：
```
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  /*margin-top: 60px;*/
}
```
