### ISSUE TITLE
drawer 的show， hide事件触发依赖docked属性

### ISSUE THREAD

**Issue by Potato2009** [museui/muse-ui#381]
` if (!this.docked) this.$emit(this.open ? 'show' : 'hide')`
但我这边有个drawer不要遮罩，现在如果docked设为true， 连show事件也不会触发

**Comment by myronliu347** [comment]
之前好像是docked模式下对show事件处理会引发一些bug我才这么处理的，不过这并不影响使用啊，show和hide事件只是跟动画相关

**Comment by Potato2009** [comment]
mu-dialog我是放在全局一直没有销毁， 所以能对dialog做变更的，只有show和hide这2个回调，比如加载数据啥的。现在事件触发不了

**Comment by myronliu347** [comment]
fixed
