### ISSUE TITLE
日期控件当前月份无法返回到上个月

### ISSUE THREAD

**Issue by bairdweng** [museui/muse-ui#385]
点击官网的日期控件就可以重现这个bug。当前是2017年3月份，返回上个月是无效的。麻烦修复下这个bug。

**Comment by myronliu347** [comment]
多谢啦，这个bug隐藏的比较深嘿嘿

**Comment by dsonghui** [comment]
我也遇到这个问题， 好奇怪哦， 昨天还好的。
