### ISSUE TITLE
建议: 存在href的组件,请支持vue-router

### ISSUE THREAD

**Issue by gofmt** [museui/muse-ui#39]
```<router-link />``` 
本身有一些特殊能力,如果放弃,比较郁闷.

**Comment by myronliu347** [comment]
router-link 现在还没法和组件配合使用，我需要研究下源码，看能不能提个pr

**Comment by wh469012917** [comment]
部分是可以和router配合使用的，比如在List组件上，但是这样用的话会导致item高亮失效。而且，建议高亮换一种形式实现，不然每次都要考虑怎样让list的value和item的value一样，这是个麻烦事

**Comment by chenyiqiao** [comment]
@myronliu347  那文档的左边list栏的导航是怎么做的？ 看了下不是用href些写的

**Comment by wh469012917** [comment]
@chenyiqiao 直接用a链接包裹，然后给a链接写死href，使用route-link会有问题的

**Comment by chenyiqiao** [comment]
@wh469012917 @myronliu347   `listItem` 可以把 router-link 写在`slot=title`里面，不过选中的css效果没有了，而且选中的区域太小了。其他的组件很多不能直接写在slot里面。至于写a链接是不可能的。。因为整个页面会重绘，而且不用命名路由是不可能的。应该可以通过修改组件的slot的位置来把router-link写在slot里面。

**Comment by nextdooroldwang** [comment]
@myronliu347 Bottom Navigation 组件也存在这个问题，没办法配合vue-router使用，再加上组件是通过@change来监听的，导致重复点击同一个菜单，没法正确的路由跳转。

**Comment by shijunti19** [comment]
是不是又这样的问题，我一个url定义了/user如果要要改成/weixin/user因为没使用vue-router我必须整个项目一个个改链接

**Comment by shijunti19** [comment]
@myronliu347 我觉得似乎用不下去了，这个href使用后，点击任何连接都是刷新网页的

**Comment by wh469012917** [comment]
@shijunti19 给a链接的href属性写死，加一个#号即可实现route的功能，虽然写法有点不合适，但毕竟是个折中的办法

**Comment by shijunti19** [comment]
@wh469012917 恩，估计也只能这样了，如果页面刷新，那用vue2没任何意义了，还不如php，这项目的痛点啊！不解决的话，真郁闷了

**Comment by myronliu347** [comment]
@wh469012917 ， 使用history模式的话确实有这个问题，如果对seo要求不高，可以监听点击事件，调用`$router.push` 跳转

**Comment by DaxChen** [comment]
請問有沒有可能像是 material-ui 那樣支援一個 `containerElement` 來放 `<router-link/>` 呢？可能透過slot和一些props之類的？

material-ui 的範例可以看這篇 http://stackoverflow.com/questions/32106513/material-ui-menu-using-routes/34507786#34507786

**Comment by shijunti19** [comment]
参考vux就行，他也更新到vue2了

**Comment by myronliu347** [comment]
已添加支持，可以直接使用`router-link`的属性，设置 `to` 属性之后会被渲染成 `router-link` 组件
http://www.muse-ui.org/#/flatButton
```html
<mu-raised-button label="Get Started" to="/install" class="mu-banner-button"/>
```
