### ISSUE TITLE
Dialog组件里面使用SelectField后的bug

### ISSUE THREAD

**Issue by asd136912** [museui/muse-ui#390]
在dialog里面点击selectfield会使dialog下层的maskView（背景色）失效
关掉SelectField可以恢复

**Comment by myronliu347** [comment]
请给出一个在线的demo模拟出错情景， https://jsfiddle.net/

**Comment by asd136912** [comment]
没有找到cdn 先贴一段代码可以吗
  <mu-raised-button label="dialog" @click="open"/>
  <mu-dialog :open="dialog" title="Dialog" @close="close">
    <mu-select-field v-model="game" label="选择">
    <mu-menu-item value="1" title="阴阳师"/>
    <mu-menu-item value="2" title="影之刃"/>
  </mu-select-field>
    <mu-flat-button slot="actions" @click="close" primary label="取消"/>
    <mu-flat-button slot="actions" primary @click="close" label="确定"/>
  </mu-dialog>

**Comment by asd136912** [comment]
没有找到cdn 先贴一段代码可以吗
  <mu-dialog :open="dialog" title="Dialog" @close="close">
  <mu-select-field v-model="game1" :labelFocusClass="['label-foucs']" label="选择你喜欢的游戏">
    <mu-menu-item v-for="text,index in list" :key="index" :value="index" :title="text" />
  </mu-select-field>
  </mu-dialog>

**Comment by myronliu347** [comment]
https://unpkg.com/vue@2.2.6/dist/vue.min.js
https://unpkg.com/muse-ui/dist/muse-ui.js
https://unpkg.com/muse-ui/dist/muse-ui.css

**Comment by asd136912** [comment]
没有找到cdn 先贴一段代码可以吗

`
  <mu-dialog :open="dialog" title="Dialog" @close="close">
  <mu-select-field v-model="game" label="选择">
    <mu-menu-item value="1" title="阴阳师"/>
    <mu-menu-item value="2" title="影之刃"/>
  </mu-select-field>
  </mu-select-field>
  <mu-flat-button slot="actions" @click="close" primary label="取消"/>
  <mu-flat-button slot="actions" primary @click="close" label="确定"/>
  </mu-dialog>
`

**Comment by asd136912** [comment]
`    opacity: 0.4;
    background-color: rgb(0, 0, 0);
    position: fixed;
    z-index: 20141273` 
这是打开了dialog没打开selectfiled的overlay
`    opacity: 0.01;
    background-color: rgb(0, 0, 0);
    position: fixed;
    z-index: 20141317;` 
这个是打开了selectfield的overlay 
透明度改变了 所以放在dialog后面的背景色也变了
我这边暂时先用了important把透明度锁定在0.4 层级锁定在dialog下层了
`  .mu-overlay {
    opacity: 0.4 !important;
    z-index: 20141265 !important;
  }`
