### ISSUE TITLE
MuRadio nativeValue, value propTypes only String?

### ISSUE THREAD

**Issue by lubomir-chatoryiskyi** [museui/muse-ui#392]
Hi!
PropTypes of nativeValue, value are set as String and when I try to set another type like Number, Boolean I got Vue warning "Invalid prop...". Sometimes it's hard and boring to convert data type into String. Maybe it is reasonable to set them as an Array [String, Number, Boolean]?
PS: The same with checkboxes and another components maybe.
Regards

**Comment by myronliu347** [comment]
NO, Value must be String, Because value  is String in HTML
