### ISSUE TITLE
针对mu-select-field一个建议

### ISSUE THREAD

**Issue by Potato2009** [museui/muse-ui#393]
使用mu-select-field时，需要远程加载选项。发现，当选项更新默认值没变的情况下， mu-select-field没有重新渲染。现在的做法是，watch 选项数据改变时， 强制将value置空，然后重新设置value

**Comment by tsunamilx** [comment]
另外，多选时，是不是显示checkbox的框对用户更加友好一点

**Comment by Muyv** [comment]
+1

**Comment by myronliu347** [comment]
fixed https://www.muse-ui.org/#/zh-CN/select
