### ISSUE TITLE
webpack 编译报错

### ISSUE THREAD

**Issue by ElderJames** [museui/muse-ui#394]
你好！！正在使用MuseUI，用了BottomSheet、Picker两个组件，是按教程单独引入的， 但是在编译的时候遇到了问题：

ERROR in static/js/app.d806e474e0017b2178cb.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/muse-ui/src/internal/popup/index.j
s:37,4][static/js/app.d806e474e0017b2178cb.js:11760,16]

请帮忙看看是什么问题，谢谢！

**Comment by myronliu347** [comment]
请给出你的使用的代码，和webpack的配置

**Comment by ElderJames** [comment]
谢谢回复，我重新建了个项目并重现问题，提交到我的[仓库](https://github.com/ElderJames/Vue-ChinaAreaPicker)了

重现步骤，使用vue-cli创建，把muse-ui的BottomSheet、Picker组件放到Hello.vue里，执行npm run build,然后就报了以上错误。

**Comment by myronliu347** [comment]
这个里面我没有看到使用的代码呀？

**Comment by ElderJames** [comment]
不好意思，是在[这里使用了](https://github.com/ElderJames/Vue-ChinaAreaPicker/blob/master/src/components/Hello.vue#L4)  
[Webpack配置](https://github.com/ElderJames/Vue-ChinaAreaPicker/blob/master/build/webpack.base.conf.js#L26)

**Comment by myronliu347** [comment]
webpack里少了配置
```javascript
{
  // ...
  rules: {
    loaders: [
      // ...
      {
        test: /muse-ui.src.*?js$/,
        loader: 'babel-loader'
      }
    ]
  },
  resolve: {
    // ...
    alias: {
      'muse-components': 'muse-ui/src'
    }
  }
}
```

**Comment by ElderJames** [comment]
不好意思，但是加上后也一样有错。能编译出来，也能运行，但是压缩的插件报错了

**Comment by myronliu347** [comment]
要放在.js的前面才行

**Comment by ElderJames** [comment]
终于解决了！！十分感谢！

**Comment by profoundsoul** [comment]
@myronliu347 为什么一定要放在前面，这个解决方案很奇怪，百思不得其解
{
                test: /\.js$/,
                loader: 'babel-loader',
                include: [resolve('src'), resolve('test'),resolve('node_modules/muse-ui/src')]
},
我是这样使用的，结果是在windows打包可以，centos中导报错误
ERROR in static/js/13.e0326102d86a851cb20b.js from UglifyJs
Unexpected token: punc (() [./~/_muse-ui@2.1.0@muse-ui/src/internal/popup/index.js:30,0][static/js/13.e0326102d86a851cb20b.js:399,7]
按照你的解决方法，额外添加一一行babel-loader就可以了。请教大神
