### ISSUE TITLE
2.0.0版本使用报错

### ISSUE THREAD

**Issue by fanxl12** [museui/muse-ui#395]
[Vue warn]: Unknown custom element: <mu-paper> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
所有组件都不能用，提示没注册。
我已经使用了的
```
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'

import Loading from './components/Loading'
import './common/stylus/base.styl'

Vue.use(MuseUI)
```

**Comment by cdll** [comment]
if u do as 
````
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'

// import Loading from './components/Loading'
// import './common/stylus/base.styl'

Vue.use(MuseUI)
````
and may the warning dismiss, that means the warning is for your own codes.

**Comment by fanxl12** [comment]
没用，之前我在用2.0.0rc版本时候是正常的，今天我升级到2.0.0版本之后，就不能用了，界面元素都出不来. @cdll

**Comment by myronliu347** [comment]
请给出vue，和muse-ui的版本

**Comment by fanxl12** [comment]
vue 版本 2.2.2 muse-ui 2.0.0 @myronliu347

**Comment by fanxl12** [comment]
把项目下的node_modules删除，重新install之后正常了。 @myronliu347
