### ISSUE TITLE
在app-bar中为flat-button增加href属性后按钮会发生错位

### ISSUE THREAD

**Issue by devindwan** [museui/muse-ui#397]
对于`app-bar`中的`flat-button`按钮，在没有`href`属性时是正常的：https://jsfiddle.net/yunhao/fqm84gr9/5/
![image](https://cloud.githubusercontent.com/assets/10205466/24555310/3c99a37e-1663-11e7-9542-61584c89e4fd.png)

但是为`flat-button`添加`href`属性后会发生错位：https://jsfiddle.net/yunhao/fqm84gr9
![image](https://cloud.githubusercontent.com/assets/10205466/24555262/ffc94882-1662-11e7-8ddc-2e2023ec22bd.png)
```javascript
<div id="app">
  <mu-appbar title="Title" zDepth="3">
    <mu-flat-button href="/register" color="white" label="注册" slot="right"></mu-flat-button>
    <mu-flat-button href="/login" color="white" label="登录" slot="right"></mu-flat-button>
  </mu-appbar>
</div>
```
按钮渲染成`<a>`标签时好像样式有些问题
```javascript
"vue": "^2.1.10"
"muse-ui": "^2.0.0"
```

**Comment by myronliu347** [comment]
多谢，今天会发布新的版本修复这些bug
