### ISSUE TITLE
<mu-list-item>无法监听@contextmenu 事件

### ISSUE THREAD

**Issue by cyhhao** [museui/muse-ui#398]
其他很多组件应该也不能监听，不过<mu-list-item>没法用外层嵌套 div 来解决。
`<mu-list-item title="title" slot="nested" @contextmenu="right_click"></mu-list-item>`
是我的用法不对吗？还是组件没有传递事件？

**Comment by myronliu347** [comment]
元素本身的事件用 `.native`修饰符， `@contextmenu.native`
