### ISSUE TITLE
请问现在这个有独立运行版本么

### ISSUE THREAD

**Issue by StionZhai** [museui/muse-ui#40]
处于某些原因, vue用的独立运行的版本, script 直接引入 muse-ui 报如下错误:
```
muse-ui.js:1509 Uncaught SyntaxError: Strict mode code may not include a with statement
```

**Comment by myronliu347** [comment]
[安装说明](https://museui.github.io/#/install)

也可以直接下载github上的代码， 直接html里引入 `dist/muse-ui.js` 和 `dist/muse-ui.css`

**Comment by StionZhai** [comment]
`dist/muse-ui.js` 是 UMD 格式的么?

**Comment by myronliu347** [comment]
是umd

**Comment by StionZhai** [comment]
我那配置的事, 谢谢啦~
PS: 建议打包压缩添加版本号😉
