### ISSUE TITLE
日期控件新bug

### ISSUE THREAD

**Issue by bairdweng** [museui/muse-ui#401]
刚刚收到日期控件无法返回上个月的bug已经修复的通知，团队立马就测试了，选择2017年3月29的时候点击返回上个月这是没有问题的，这时候点击年份切换到2018，这时候不要点击确定，点击月份，这时候是2018年3月29日，点击返回上个月的时候页面卡住了，无法返回到二月份，嘻嘻，另外能不能在切换年份的时候点击确定返回到选择日期，不要直接关闭，谢谢，作者幸苦啦。

**Comment by myronliu347** [comment]
你去官网上看，我好像修复了，上次提交的时候似乎没法版

**Comment by bairdweng** [comment]
刚刚去官网看了，这个bug还未修复。点击2017年3月29。再次点击切换到2018年份，不要按确定，点击左上角的日期。返回到2017，返回上个月是卡住的。不切换年份的话没有问题。

**Comment by myronliu347** [comment]
en ，看到了，我等下改下
