### ISSUE TITLE
恢复对text field原生属性name的支持

### ISSUE THREAD

**Issue by devindwan** [museui/muse-ui#402]
有些时候项目本身可能并不是前后端分离，只是想简单使用一下输入框样式再用表单提交，顺带着跳转页面，如果特意去封装一个组件显得没有必要，没有`name`属性就很不方便。

比如Laravel框架(PHP)提供原生的vue支持，但是只是把vue当做组件化工具，还是会用到`form`表单的提交，而且事实上有时直接一个submit跳转会方便很多。

看了下，Element和Vux都保留着`input`框的`name`属性，这样对于并非完全依赖于vue的项目应该会友好一些。

可以考虑一下让`name`属性重新回归。

#339

**Comment by myronliu347** [comment]
ok,加上吧，这样的话就统一加上 `name` 属性
