### ISSUE TITLE
Chrome和Safari下显示字体粗细不一致，Safari总是细一些。

### ISSUE THREAD

**Issue by paraself** [museui/muse-ui#405]
Chrome下的文字
![chrome](https://cloud.githubusercontent.com/assets/2179686/24593066/0921083e-1852-11e7-83cc-cf288cdcf725.png)
Safari下的文字
![safari](https://cloud.githubusercontent.com/assets/2179686/24593312/bf3112b6-1854-11e7-97e5-5bee0ed4e54d.png)
用的是默认的Roboto字体，通过google 字体api在Head标签里加载的。本机也安装了Roboto字体。
搜了下stackoverflow，都说是应该设置
```css
  -webkit-font-smoothing: subpixel-antialiased;
```
但是试了下似乎没用。这个问题可能和muse ui关系不大，但是还是想问问怎么解决，谢谢啦。

**Comment by paraself** [comment]
试了下，发现
```css
-webkit-font-smoothing: antialiased;
```
可以让Chrome的字体变得和Safari一样细，但是能让Safari的变得和Chrome一样粗么TT

**Comment by paraself** [comment]
另外发现同样的主题紫色，在chrome下和safari下居然有色差TT

**Comment by myronliu347** [comment]
字体方面，我没有研究过，帮不了你了
