### ISSUE TITLE
AutoComplete对中文的支持有问题

### ISSUE THREAD

**Issue by ueqt** [museui/muse-ui#409]
例如输入m,  希望返回中文“美”，用如下的写法没有出autocomplete的框来，只有输入中文，才会弹出中文的自动完成，输入任何英文都只会出英文的自动完成，不会出中文的。。。
```javascript
    handleInput (val) {
      this.dataSource = ['美']
    }
```

**Comment by JavaCS3** [comment]
它是字符匹配啊少年！明显不支持拼音补全啊！你要自己写filter函数

**Comment by ueqt** [comment]
@JavaCS3 谢谢，加了filter果然可以了，我本来以为是绑定的datasource就是要autocomplete的内容，原来只是候选项，是我看文档不够仔细，不好意思了
