### ISSUE TITLE
muse如何引入weex

### ISSUE THREAD

**Issue by ckdlbc** [museui/muse-ui#410]
![image](https://cloud.githubusercontent.com/assets/20680413/24610063/c65a85bc-18af-11e7-9e63-71f1c13e0302.png)

![image](https://cloud.githubusercontent.com/assets/20680413/24610055/be723ad4-18af-11e7-879f-8a356f5df7ad.png)

引入weex后会报错，组件没有注册成功

**Comment by myronliu347** [comment]
没法引，这个是web项目用的
