### ISSUE TITLE
Popover width in Select Field doesn't work correct when AutoWidth is set to true

### ISSUE THREAD

**Issue by lubomir-chatoryiskyi** [museui/muse-ui#414]
Hi! 
I've noticed one issue with Select Field. I've set AutoWidth to true, FullWidth is set to true too. So, I have width of text field around 100px. Menu Items have a lot of chars, around 20-30, so their width is around 200-250px. But calculated width of the popover block is around 130px and some chars of the menu item are hidden (text-overflow: elipsis). I really have no idea why the width of popover is set to 130px, as I've understand from the source code it must be set to empty string.

**Comment by myronliu347** [comment]
https://material.io/guidelines/components/menus.html#menus-specs
Please read material  guidelines

**Comment by lubomir-chatoryiskyi** [comment]
Thanks for your answer. 
I've investigated menus specs but I haven't noticed fixed width for menus. Example form specs:
https://material.io/guidelines/components/menus.html#menus-usage 
Text in dropdowns isn't hidden.
My example with this issue:
https://www.evernote.com/shard/s389/sh/c4d7c2ba-a855-43d3-a095-ff33a5cd68ae/b04c510d6ffc1184

**Comment by myronliu347** [comment]
I know , Please wait...
