### ISSUE TITLE
2.0 muse-ui checkbox v-model doesn't work

### ISSUE THREAD

**Issue by bluemastodon66** [museui/muse-ui#416]
v-model doesn't work on 2.0.

**Comment by myronliu347** [comment]
please give online demo https://jsfiddle.net/

**Comment by bluemastodon66** [comment]
hello, I tested on jsfiddle
https://jsfiddle.net/alvinlee/roj6m8do/2/
yes, everything is working fine.
but, my case is, I use 2.0.0-rc.5 to develop my project everything is fine checkbox, v-model all good.
When I move to 2.0 then v-model on checkbox just doesn't work...
Is there different version between cdn and github ?
or maybe I just need to upgrade my vue 2.1.8 to the latest version..( I might try later.)

**Comment by myronliu347** [comment]
This demo is correct,  no bug

**Comment by myronliu347** [comment]
I don't quite understand what you mean

**Comment by bluemastodon66** [comment]
Hello, I solved it. turns out, I need to update other packages, such as vue-loader vue-templer.....etc...
After I updated it then everything worked fine..
Sorry for bothering u.
