### ISSUE TITLE
官网上 手机访问 左侧的menu自动收起这个怎么做的?

### ISSUE THREAD

**Issue by xianzhi0520** [museui/muse-ui#423]
希望能给个例子  很需要

**Comment by F-loat** [comment]
[官网源码](https://github.com/museui/muse-ui/blob/master/src-docs/App.vue)
主要就是通过窗口宽度判断和监听resize事件

**Comment by xianzhi0520** [comment]
虽然 源码 看的不是很明白  但是原理知道了
监听resize事件 同时判断窗口的宽度值 当小于某一个值 就可以定义为pad 然后再小于某个值 就定义为phone 然后设置菜单隐藏 形成一个菜单呼出按钮进行显示隐藏 对吧?

**Comment by F-loat** [comment]
对，官网的代码对desktop的新值和旧值做了比较，然后进行不同的操作，感觉这个可以直接放在watch里进行，resize时只是更新一下desktop的值就行

**Comment by caixw** [comment]
你可以 `matchMedia` 来监听屏幕事件。
