### ISSUE TITLE
在部分手机上功能的缺失

### ISSUE THREAD

**Issue by KnorienChang** [museui/muse-ui#424]
前两天采用此UI组件在部分手机上显示有问题，icon缺失，部分功能不能使用。测试官方文档的功能亦是如此。

测试环境：HUAWEI P10 PLUS  升级过Google play的webview

**Comment by xianzhi0520** [comment]
这个是字体不能正常下载的问题  你可以从官方把字体下载到本地引入

**Comment by xianzhi0520** [comment]
还有就是 有些手机的浏览器 会屏蔽广告一类的也有可能

**Comment by KnorienChang** [comment]
@xianzhi0520 经验证，关闭浏览器的广告屏蔽，将字体库下载到本地还是一样的问题

**Comment by myronliu347** [comment]
https://material.io/icons/
material的字体是有两种使用方式的，目前的使用方式在一部分安卓上是不支持的，
但是内部使用的icon都是svg，至于其他的图标库，我们也支持

**Comment by KnorienChang** [comment]
@myronliu347 所以说还是因为字体的原因吗？  我明白了      @xianzhi0520 @myronliu347 谢谢解答！！！！
