### ISSUE TITLE
自定义主题问题，不知道less文件放在哪里

### ISSUE THREAD

**Issue by youzime** [museui/muse-ui#425]
写好了这个less文件，请问这个文件是放在哪个目录下，是自己的项目，还是node_modules下面的某个？

**Comment by myronliu347** [comment]
放在自己的项目目录下，然后引入即可

**Comment by youzime** [comment]
试了几次还是没成功， 这是项目结构，
```
|- src
|   |- assets
|   |-router
|   |-components
|   |-App.vue
|   |- main.js
|   |-style.less (这就是我新建的文件)
```
然后是我先暂时修改的style.less
```
@import "../vars.less";
@primaryColor: @lightGreen500;  // 主色
@darkerPrimaryColor: @lightGreen700;
@import "../../../less/theme-vars.less";
@import "../../../less/theme.less";
```

里面的style.less就是自定义的主题，
这个文件（试过放在/node_modules/muse-ui/src/style/theme/ 下面，也试过放在/src/ 下面，然后在main.js和App.vue里面都有试过import），
我实在是没读懂到底该怎么放置这个文件以及引用方式
请麻烦再说详细一点，谢谢了

**Comment by Eric-ss** [comment]
我也遇到了，放在目录下报错 该怎么引入 @myronliu347

**Comment by myronliu347** [comment]
找正确的路径引入就可以了，如果报错肯定是import的路径有问题
