### ISSUE TITLE
mu-avatar在子组件里src获取不到图片，求优化

### ISSUE THREAD

**Issue by zhou1178539345** [museui/muse-ui#429]
````<mu-avatar` src="../../assets/logo.png" slot="leftAvatar" :size="60"/>````
这个就不能显示图片
````<img src="../../assets/logo.png">````
而下面的即可显示图片

老板，可以优化下了。

**Comment by myronliu347** [comment]
这两者是不同的，下面的在vue-template-compiler编译的时候会去加载这个图片，而avatar组件上的src属性在编译的时候是不会做处理的。

**Comment by zhou1178539345** [comment]
@myronliu347 那子组件里面使用avatar怎么办

**Comment by myronliu347** [comment]
本地图片可以现在js中import，再绑定属性
