### ISSUE TITLE
你好 我在引用你组件的时候出现如下错误

### ISSUE THREAD

**Issue by jtsky** [museui/muse-ui#43]
ERROR in ./~/.2.0.0-alpha.6@muse-ui/src/appbar/appbar.vue
Module build failed: TypeError: this._init is not a function
    at Object.Vue$2 (D:\VueProject\vue-gank\node_modules\.2.0.6@vue\dist\vue.common.js:2624:8)
 @ ./~/.2.0.0-alpha.6@muse-ui/src/appbar/index.js 7:14-33

**Comment by myronliu347** [comment]
请提供 vue的版本，和完整的出错截图

**Comment by myronliu347** [comment]
我先关掉了，仍有问题可以重开
