### ISSUE TITLE
修改菜单项的字体颜色无效果。

### ISSUE THREAD

**Issue by Mykeyb2004** [museui/muse-ui#431]
源码如下：
```
    <mu-menu desktop listClass="testmenu">
      <mu-menu-item title="Gridx" leftIcon="check" titleClass="menucolor"></mu-menu-item>
    </mu-menu>

  .testmenu, .menucolor {
    background: orange;
    color: white;
    font-size: 100px;
  }
```
我在main.js中引入过自定义主题。
```
import 'muse-ui/dist/muse-ui.css'
import 'muse-ui/dist/theme-light.min.css'
```
其它地方就再没有改动过。如果我把mu-menu放到一个div里，div的背景还是可以改的，但字体颜色还是改不了。

不论修改那个class都没有让菜单项的字体颜色发生改变。是不是我用错参数了？麻烦指点一下，谢谢！

**Comment by adrian999999** [comment]
.testmenu, .menucolor 只是帮助 Muse-UI 来渲染的一个标记 并不代表 dom 上的class。
如果你想改变颜色， 建议引入自己的.less 来 取代 Muse-UI自己的样式。
参考http://www.muse-ui.org/#/theme

**Comment by myronliu347** [comment]
你检查一下css的权值问题，应该是自定义的样式被覆盖了
