### ISSUE TITLE
input输入限制过maxlength后,输入超过就不让输入

### ISSUE THREAD

**Issue by bboywulong** [museui/muse-ui#434]
在keen UI中写过类似的功能,输入超过maxlength后则不让输入,他是设置了input的maxlength属性
```:maxlength="enforceMaxlength ? maxlength : null"```

**Comment by myronliu347** [comment]
这里我也考虑过，但是我想尽量从外部去控制，因为这个时候是要提示的，提示文字也要处理的，所以这里我们提供一个textOverflow事件，从外部控制

**Comment by bboywulong** [comment]
我的建议是提供一个开关让开发者自行选择需要使用错误提示还是,直接限定死maxlength,这个问题也是我们的用户提出来的

**Comment by myronliu347** [comment]
你可以在在你那处理啊，监听textOverflow事件，然后截取 value
