### ISSUE TITLE
muse-ui引入使用总是失败，提示module 没找到组件

### ISSUE THREAD

**Issue by luyaohua2016** [museui/muse-ui#435]
@myronliu347
![1mj 6p f3sq aglnfahx7](https://cloud.githubusercontent.com/assets/17470026/25166432/f1ae0274-250d-11e7-9c08-6d8a37d9e065.png)

**Comment by adrian999999** [comment]
把muse-ui放在 app.js 之后。
如果找不到module 很可能是在你的app.js 加载顺序不对。参考
```
import Vue from 'vue';
import MuseUI from 'muse-ui';
import 'muse-ui/dist/muse-ui.css'
import 'muse-ui/dist/theme-light.css'
Vue.use(MuseUI);


const app = new Vue({
    el: '#app',
});
```

**Comment by myronliu347** [comment]
首先检查你的muse-ui是否已经安装完毕（看下node_modules文件夹内有没有muse-ui）
然后如果是单组件使用需要安装keycode,less-loader

**Comment by nian1123** [comment]
请问解决了吗？
