### ISSUE TITLE
mu-tabs and :to router-link

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [museui/muse-ui#438]
I have a problem with mu-tabs and vue-router
this is simple tabs example:
```
<template>
<mu-tabs :value="activeTab" @change="handleTabChange">
  <mu-tab value="tab1" icon="home"/>
  <mu-tab value="tab2" icon="flight_takeoff"/>
  <mu-tab value="tab3" icon="favorite"/>
</mu-tabs>
</template>
```
```
<script>
export default {
  data () {
    return {
      activeTab: 'tab1'
    }
  },
  methods: {
    handleTabChange (val) {
      this.activeTab = val
    }
  }
}
</script>
```

if I add router link to tabs like that:
`<router-link :to="{ path: 'landing-page' }"> <mu-tab value="tab3" icon="favorite"/></router-link>
`
this is not working!!
 i expect to use tabs like this ??

`  <mu-tab value="tab3" icon="favorite" :to="{ path: 'landing-page' }" />`

can anyone help me to work with mu-tabs and vue-router and router-link ??
the href tab Props is not usefull !!

**Comment by myronliu347** [comment]
Sorry, I forgot to support tab component, please wait update

**Comment by NadhirBoukhenifra** [comment]
thank you @myronliu347  , in my project I use some tricky solution :)!

`<mu-tab value="home" icon="home" title="Home" />
`

and then in same component :
 ```
 methods: {
    handleTabChange (val) {
      this.activeTab = val
      this.$router.push('/' + val)
    }
```
and in the Router.js 
i have included the component with `home` route `name` and `path`

```
  {
    path: '/home',
    name: 'home',
    component: require('components/Home')
  }
```

and thank you for Muse-ui!
