### ISSUE TITLE
Infinite Scroll事件监听元素css高度必须设定值？

### ISSUE THREAD

**Issue by panpanhtai** [museui/muse-ui#441]
不设置值或者设100%，就不能正常工作

**Comment by myronliu347** [comment]
主要是滚动条的获取，准确的传入scroller就可以，scroller默认是window

**Comment by panpanhtai** [comment]
我弄了一下，主要是把高度处理好了，用js计算出来了，要是高度直接100%不行，我设上合适的尺寸就好了

**Comment by panpanhtai** [comment]
按照demo做的，改了一下，语句
