### ISSUE TITLE
请问你这套ui是针对 pc还是移动端？如果是移动端，我在安卓测试的时候很多组件是不能正常使用的

### ISSUE THREAD

**Issue by huangzhenxian** [museui/muse-ui#45]
rt

**Comment by myronliu347** [comment]
IE10以上， 安卓4.4.4以上， 哪些组件无法使用请提供

**Comment by huangzhenxian** [comment]
![image](https://cloud.githubusercontent.com/assets/8416974/20338724/b7cc7c66-ac13-11e6-92bf-e44f6d2a494a.png)

**Comment by huangzhenxian** [comment]
比较多的组件显示都不正常  ios就比较正常  而且我个人感觉 效果太花俏会不会导致性能体验方面降低了

**Comment by myronliu347** [comment]
这个是material design 的icon文件加载有异常，所以所有的icon都没有出来

**Comment by myronliu347** [comment]
html 中引入的这两个文件，实际的项目中可以先下载下来，就不会有icon的问题了
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
 <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

**Comment by huangzhenxian** [comment]
我目前是直接用你的api文档那个链接测试组件的  我现在直接开发看看  我现在还在等UI或选UI   再不搞定ui这块我就要狗带了

**Comment by WispYs** [comment]
@huangzhenxian `<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">`引入icon就可以了

**Comment by myronliu347** [comment]
@huangzhenxian 目前不推荐在正式项目中使用，现在还不稳定

**Comment by huangzhenxian** [comment]
ok  3q
