### ISSUE TITLE
dialog、Date Picker弹层关闭时会向左偏移

### ISSUE THREAD

**Issue by xiangle** [museui/muse-ui#452]
PC设备

**Comment by myronliu347** [comment]
请给出一个现在的demo，复现此问题

**Comment by xiangle** [comment]
就是你的http://www.muse-ui.org/#/dialog，可能是右侧滚动条切换导致的，当打开弹框时，右侧滚动条消失，关闭弹框右侧滚动条显示，屏幕缩窄，此时过渡还没有结束，产生左偏移效果

**Comment by myronliu347** [comment]
我看了下确实有这个问题，但是在手机上是不会有滚动条的，pc滚动条导致定位的时候会出现偏移，但是如果不锁定的话，弹出框之后还可以滚动这是不合理的，所以，这个问题暂时并不打算修复
