### ISSUE TITLE
Table组件不支持自定义TD的宽度

### ISSUE THREAD

**Issue by z2665** [museui/muse-ui#454]
使用Table的时候遇到一个很长的字符串就会重叠在后面的字符串上，每个TD格子的宽度都是固定的。不支持调整

**Comment by caixw** [comment]
我也碰到这个问题。只能临时用 `white-space:normal`让内容换行了。

**Comment by z2665** [comment]
@caixw 我最后也用了和你一样的办法，还加了个`word-wrap: break-word`，不过有时候看起来不太美观。希望作者能够改进一下Table组件的功能。

**Comment by myronliu347** [comment]
td上可以加上自己的样式的
