### ISSUE TITLE
全屏 Dialog，Full screen 100% 高，100% 寬

### ISSUE THREAD

**Issue by arnoldgithub** [museui/muse-ui#458]
我在開發一個 web app, 大部分用戶都是在手機上使用，我想使用全屏的 Dialog (Full screen) 的模式。
我試過調用 css 的方法，但要做很多 customization, 改很多的 css 才能用到，還覺得效果不怎麼好。

可否加一個 prop (boolean) 到 Dialog, 讓它自動 100% 全屏顯示。

**Comment by myronliu347** [comment]
requestFullScreen方法可以使元素全屏显示，这个部分功能并不打算加，更多部分更希望通过customization的方式实现
