### ISSUE TITLE
avatar 动态加载图片src

### ISSUE THREAD

**Issue by xdliuyong** [museui/muse-ui#46]
https://museui.github.io/#/avatar 动态加载图片src； 用v-for渲染list， 然后每个avatar的图片地址，是根据v-for的元素字段更改的；我使用相对路径貌似不行；请作者是怎么处理的呢？

**Comment by xdliuyong** [comment]
`<mu-avatar :src="'static/assets/'+ host.type + '.jpg'"`用这种方式勉强实现了，但是感觉不够优雅，本意是想用directive实现。

**Comment by myronliu347** [comment]
可以写一个方法，或者filter
```html
<mu-avatar :src="'fullPath(host.type)"/>
```
```javascript
export default {
   methods: {
       fillPath (val) {
         return 'static/assets/'+ val + '.jpg'
       }
   }
}
```
