### ISSUE TITLE
table组件被选中的行被删除时，残留在selectedRowsIndex中

### ISSUE THREAD

**Issue by moondropx** [museui/muse-ui#463]
*table组件允许allRowsSelected，multiSelectable，showCheckbox。*
将某row**选中之后**将其移除，再通过选中其他行触发rowSelection事件，发现接收到的selectedRowsIndex数组中残留有一个index为-1的元素。

**Comment by adrian999999** [comment]
你是如何把选中行删除的

**Comment by myronliu347** [comment]
请给出了一个在线的demo，模拟出错情况 
https://jsfiddle.net/

**Comment by moondropx** [comment]
抱歉没有描述清楚……
https://jsfiddle.net/kdz9Lt0s/
重现步骤：
- 选中第一行
- 点击删除
- 选择第二行
- 可以发现`selectedRowsIndex`为`[-1, 0]`

**Comment by myronliu347** [comment]
我这里显示是正常的诶，你看下你的浏览器版本

**Comment by moondropx** [comment]
这边是`chrome 58.0.3029.96 (64-bit)`，不过我用safari和firefox都试了一下应该不是浏览器的问题。
<img width="550" alt="2017-05-08 6 11 56" src="https://cloud.githubusercontent.com/assets/8750386/25797958/561dc2c4-341a-11e7-9d48-5145f9f14563.png">
