### ISSUE TITLE
按需引入组件在编译的时候报错，说是es6的语法let识别不了

### ISSUE THREAD

**Issue by raintao** [museui/muse-ui#467]
ERROR in static/js/vendor.ec7cd7c57296e90266ef.js from UglifyJs
Unexpected token: name (width) [./~/.2.0.2@muse-ui/src/utils/index.js:33,0][static/js/vendor.ec7cd7c57296e90266ef.js:10468,6]      
这个在index.js的33行是ES6申明的变量 let width=……   webpack用的是vue-cli  这个是可以编译ES6的，为啥在muse按需引入时报错？？？ 全部引入没有问题

**Comment by adrian999999** [comment]
应该是和babel-plugin-transform-object-rest-spread babel-preset-es2015 .babelrc 文件配置关系

**Comment by myronliu347** [comment]
局部组件引入需要加上webpack配置 
http://www.muse-ui.org/#/usage

**Comment by gavinliu6** [comment]
遇到了同样的问题，同样也是按照官方文档配置过了，请问如何解决？ @raintao @myronliu347
