### ISSUE TITLE
Tooltip 在手機上沒有顯示

### ISSUE THREAD

**Issue by arnoldgithub** [museui/muse-ui#468]
在普通電腦上完全沒問題，但我在iPhone 上試過，按下去沒有反應。
我試過Safari 跟 Google Chrome 都有同樣情況。

只需用手機上 http://www.muse-ui.org/#/tooltip ，就可以看到問題。

**Comment by adrian999999** [comment]
Tooltip是鼠标放在图标上才会显示 ， 手机上没有图标所以没办法显示

**Comment by arnoldgithub** [comment]
Tooltip 不一定要用滑鼠才能激活，在智能手機上應該可以透過touch 來激活 hover 的事件。

例如，你可以試下用手機上vuematerial 的 tooltip，手機上是可以做到：

https://vuematerial.github.io/#/components/tooltip

**Comment by myronliu347** [comment]
tooltip组件设计是在pc端使用，手指上touch是出现tooltip会被遮挡
