### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [museui/muse-ui#469]
hi, you you have any plan to support rtl version ??

**Comment by adrian999999** [comment]
Yeah,

I would like to support but my self still learning frontend Vue.

I am kind of full stack develop doing 80% php larval and Vue components for frontend.

**Comment by MahdiMajidzadeh** [comment]
I can help , if it's possible

**Comment by myronliu347** [comment]
Sorry, I don't know what is the RTL

**Comment by MahdiMajidzadeh** [comment]
RTL refer to [Right-to-Left](https://en.wikipedia.org/wiki/Right-to-left) which layout start from right to left

for example: 

![untitled-1](https://cloud.githubusercontent.com/assets/6115476/25609694/7fe01b28-2f35-11e7-8edf-387002037e53.jpg)

**Comment by NadhirBoukhenifra** [comment]
I can help you to RTL the project,
I can RTL directly the file:

`https://github.com/museui/muse-ui/blob/master/dist/muse-ui.css`

to be 

`/dist/muse-ui-rtl.css`

but it's not a solution for Vue users, can you make Muse-ui read this property  first then load the RTL code:

`<html dir="rtl">`

or since you are using LESS:

```
<style lang="less">
@import "../styles/import.less";
.mu-appbar {
  display: flex;
  align-self: flex-start;
  **& when (@rtl) {
    align-self: flex-end;
  }**
}
```
like this i  found it (https://github.com/less/less-plugin-rtl)
so u can use it with` & when ()` or with [dir=rtl]:

```
<style lang="less">
@import "../styles/import.less";
.mu-appbar {
  display: flex;
  align-self: flex-start;
}
[dir=rtl].mu-appbar {
  align-self: flex-end;
}
```

**Comment by MahdiMajidzadeh** [comment]
I was in rush so I made it:

https://mahdimajidzadeh.github.io/muse-ui-rtl/#/install

It's works fine and just have some bugs that I fix asap I can

**Comment by myronliu347** [comment]
```html
<template>
<div>
  <mu-raised-button label="toggle drawer" @click="toggle()"/>
  <mu-drawer right :open="open" @close="toggle()">
    <mu-appbar title="Muse UI"/>
    <mu-list>
      <mu-list-item title="Menu Item 1"/>
      <mu-list-item title="Menu Item 2"/>
      <mu-list-item title="Menu Item 3"/>
      <mu-list-item @click.native="open = false" title="Close"/>
    </mu-list>
  </mu-drawer>
</div>
</template>

<script>
export default {
  data () {
    return {
      open: false
    }
  },
  methods: {
    toggle () {
      this.open = !this.open
    }
  }
}
</script>
```
Drawer support right
