### ISSUE TITLE
求助，table组件的Event事件怎么触发啊

### ISSUE THREAD

**Issue by WispYs** [museui/muse-ui#47]
@myronliu347 类似于这个组件的rowSelection，rowClick事件都怎么触发，直接写入好像不可以

**Comment by myronliu347** [comment]
```html
<mu-table @rowClick="handleClick"></mu-table>
```

vue 2.0 事件系统做过改动，监听组件内部元素的事件需要 `@click.native`

**Comment by WispYs** [comment]
谢谢，建议rowSelection像rowClick一样能输出下标参数，这样更好判断是哪个被选中了，id的话还要做处理

**Comment by myronliu347** [comment]
好的，我会改进api
