### ISSUE TITLE
InfiniteScroll下拉刷新多次加载

### ISSUE THREAD

**Issue by panpanhtai** [museui/muse-ui#473]
开始的时候  this.loading = true,
结束的时候 this.loading = false
可是还是要加载多次，请问是那里处理的不对吗？

**Comment by myronliu347** [comment]
就是这么处理的，不会多次加载,
请给出你使用部分的代码

**Comment by huanshili** [comment]
InfiniteScroll 和官网一摸一样的代码 为什么没有效果

**Comment by myronliu347** [comment]
请给出在线demo，模拟出错情况
或者给出你的使用代码
