### ISSUE TITLE
help customizing theme

### ISSUE THREAD

**Issue by shayneo** [museui/muse-ui#475]
Hey! I'd like to customize the theme, but I'm not sure how, even after reading the documentation [here](http://www.muse-ui.org/#/theme) and trying a few things.

Would you be kind enough to provide some more detailed instructions? I'd be happy to add to the docs once I understand how do it. 😄

**Comment by adrian999999** [comment]
@shayneo What kind of customizations you like to make?

**Comment by shayneo** [comment]
@adrian999999 just want to swap add my own color scheme, similar to what's shown in the docs

**Comment by adrian999999** [comment]
You can simply write your own less to overwrite the theme and import it after the default CSS style.
But make sure that you use the variables that provider in the less and material design doc. 
```
import Vue from 'vue';
import MuseUI from 'muse-ui';
import 'muse-ui/dist/muse-ui.css';
import '../less/theme-custom.less';
Vue.use(MuseUI);
```

**Comment by shayneo** [comment]
thanks @adrian999999 I think I have things configured properly now!!

I've never used less though, and am getting this error:
```
ERROR  Failed to compile with 1 errors                                                                                      10:30:59 AM

 error  in ./less/vinli.less

Module build failed:

// load the styles
var content = require("!!../node_modules/css-loader/index.js??ref--7-1!../node_modules/less-loader/dist/index.js??ref--7-2!./vinli.less"
);
          ^
Unrecognised input
      in /Users/shayneosullivan/projects/vinli/dealer-demo-app/less/vinli.less (line 4, column 12)

 @ ./src/main.js 10:0-28
 @ multi ./build/dev-client ./src/main.js
```

my less file (just using the example from the docs to get things going):
```less
@import "muse-ui/less/vars.less"; // default basic variable

// change defalut basic variable

@primaryColor: @lightBlue700;
@darkerPrimaryColor: @lightBlue700;
@lighterPrimaryColor: @grey600;
@accentColor: @pinkA200;
@darkerAccentColor: @pinkA400;
@lighterAccentColor: @pinkA100;

@textColor: @fullWhite;
@secondaryTextColor: fade(@fullWhite, 70%);
@alternateTextColor: #303030;
@borderColor: fade(@fullWhite, 30%);
@disabledColor: fade(@fullWhite, 30%);

// background
@backgroundColor: #303030;
@statusBarBackgroundColor: @fullBlack;
@appbarBackgroundColor: @grey900;
@dialogBackgroundColor: #424242; // dialogs or cards

// icon
@activeIconColor: fade(@fullWhite, 100%);
@inActiveIconColor: fade(@fullWhite, 50%);

@import "muse-ui/less/theme-vars.less";  // default component variable

// change the component variable
@avatarBackgroundColor: lighten(@alternateTextColor, 26%);
@datePickerHeaderColor: fade(@fullWhite, 12%);
@timePickerHeaderColor: fade(@fullWhite, 12%);
@timePickerClockCircleColor: fade(@fullWhite, 12%);
@avatarBackgroundColor: lighten(@alternateTextColor, 26%);
@chipColor: lighten(@alternateTextColor, 12%);
@floatButtonDisabledColor: lighten(@alternateTextColor, 12%);

@tableRowHoverBackgroundColor: fade(@textColor, 10%);
@tableRowSelectedBackgroundColor: fade(@textColor, 5%);

@import "muse-ui/less/theme.less"; // style related to theme

```

I'm guessing there is something wrong with my less file

**Comment by shayneo** [comment]
I just tried using a custom css theme and it seems to be working. Here's what I did
```
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
import '../css/custome-theme.css'

Vue.use(MuseUI)
```
I'm using the theme files from the main project as templates: https://github.com/museui/muse-ui/tree/master/dist

Still would love to get it working "the right way"

**Comment by adrian999999** [comment]
I guess you need to get more understanding of how does .less and .sass work. I personally use sass, but it is the same idea. Here is the link on how to install and use less. http://lesscss.org/#using-less

You can install pulgin to config webpack to recognize .less file and compile to the directory you want in a css format and import .css as you were showing in the second example. https://github.com/webpack-contrib/less-loader
In the .less file you created, the code will be look like your first example.

The .css file in your example 2 was generated using .less file located here. https://github.com/museui/muse-ui/tree/master/less

I strongly recommand you take a look this 
https://laracasts.com/series/webpack-for-everyone
this is basicly about how frontend should work,
and episodes 4  is much related to your current situation.

**Comment by zd1010150** [comment]
I encounter the same problem.I fix this problem by this,I add less-loader to compile the less,the theme is customized the theme *components/ui/muse-ui/theme-dark.less*.
changeTheme.js
`
import dark from '!!raw-loader!less-loader!components/ui/muse-ui/theme-dark.less'
import light from '!!raw-loader!less-loader!components/ui/muse-ui/theme-light.less'


let themes = {
    light, dark
  },

  getThemeStyle = () => {
    const themeId = 'muse-theme'
    let styleEl = document.getElementById(themeId)
    if (styleEl) return styleEl
    styleEl = document.createElement('style')
    styleEl.id = themeId
    document.body.appendChild(styleEl)
    return styleEl
  };
console.log("themes",JSON.stringify(themes.light),JSON.stringify(themes.dark));
export default (theme) => {
  let $html = document.querySelector("html");
  $html.classList.toggle("dark",theme == "dark");
  $html.classList.toggle( "sidebar-light",theme != "dark");
  const styleEl = getThemeStyle()
  styleEl.innerHTML = themes[theme] || ''
}`

theme-dark.less

`/*dark主题*/

@import "~lesshat/lesshat.less";
@import "~assets/less/variable.less";
@import "~muse-ui/less/vars.less"; // 默认基础的变量


// 修改基础变量

@primaryColor: @lightBlue700;
@darkerPrimaryColor: @lightBlue700;
@lighterPrimaryColor: @grey600;
@accentColor: @blue-color;
@darkerAccentColor: @pinkA400;
@lighterAccentColor: @pinkA100;

@textColor: @dark-font-color;
@secondaryTextColor: fade(@fullWhite, 70%);
@alternateTextColor: #303030;
@borderColor: fade(@fullBlack, 30%);
@disabledColor: fade(@fullWhite, 30%);

// background
@backgroundColor: @dark-bg-color;
@statusBarBackgroundColor: @fullBlack;
@appbarBackgroundColor: @grey900;
@dialogBackgroundColor: #424242; // dialogs or cards

// icon
@activeIconColor: fade(@fullWhite, 100%);
@inActiveIconColor: fade(@fullWhite, 50%);
@iconSize: 18px;


@import "~muse-ui/less/theme-vars.less";  // 默认组件变量

// 修改组件变量
@avatarBackgroundColor: lighten(@alternateTextColor, 26%);
@datePickerHeaderColor: fade(@fullWhite, 12%);
@timePickerHeaderColor: fade(@fullWhite, 12%);
@timePickerClockCircleColor: fade(@fullWhite, 12%);
@avatarBackgroundColor: lighten(@alternateTextColor, 26%);
@chipColor: lighten(@alternateTextColor, 12%);
@floatButtonDisabledColor: lighten(@alternateTextColor, 12%);

@tableRowHoverBackgroundColor: fade(@textColor, 10%);
@tableRowSelectedBackgroundColor: fade(@textColor, 5%);

@import "~muse-ui/less/theme.less"; // 主题相关的样式


@import "component-index.less";

`

**Comment by 531431988** [comment]
@zd1010150 good! 
I wrote it  import green from '!raw-loader!../../theme/theme-green.less'   So make a mistake
baidu fanyi
