### ISSUE TITLE
About Issue submit format

### ISSUE THREAD

**Issue by adrian999999** [museui/muse-ui#476]
I suggest maybe we should format the issue a bit more clear in the following format
@myronliu347  https://help.github.com/articles/creating-an-issue-template-for-your-repository/

- Vue Version: 
- Muse-UI Version:
- Package Tools:

### Description:
- componments ?
- error ?

**Comment by linxiaowu66** [comment]
good idea

**Comment by myronliu347** [comment]
Good idea, Thanks!
