### ISSUE TITLE
能不能做一个billboard形式的展示板

### ISSUE THREAD

**Issue by yutiansut** [museui/muse-ui#477]
![](http://i4.buimg.com/567571/898c2b8db6c75ab1.png)

如图,目前我只能用两个表格去展示,有没有其他合适的控件呢

**Comment by adrian999999** [comment]
可不可以用flexbox 或者Grid 来展示
CSS需要自己写啊

**Comment by yutiansut** [comment]
grid list感觉可以,但是得改很多东西

**Comment by adrian999999** [comment]
你可以用grid list写一个自定义 的 component 用来试用你的billboard情况

**Comment by yutiansut** [comment]
恩恩

**Comment by myronliu347** [comment]
为了满足更多的业务情况，肯定是需要自定制的，毕竟不可能吧所有组件都做全，精力有限。。
