### ISSUE TITLE
icon 在微信android版 浏览器里 显示不出来

### ISSUE THREAD

**Issue by reyboo** [museui/muse-ui#478]
android手机 小米5 
在系统自带的浏览器里可以显示
但是在微信浏览器里显示不出来
如图：
![_20170504091910](https://cloud.githubusercontent.com/assets/20931606/25687722/60fc531c-30ab-11e7-8414-0987e6de9ab5.jpg)
![_20170504091924](https://cloud.githubusercontent.com/assets/20931606/25687725/6947ac92-30ab-11e7-88dd-8ed429a587c0.jpg)

这个问题该怎么解决啊？

**Comment by myronliu347** [comment]
https://material.io/icons/

icon的两种使用方式在这 #123 #244

**Comment by reyboo** [comment]
我html里引入了 
vue里用的自带的icon组件
测了几种浏览器 目前就是安卓版的微信浏览器里 显示不出来

**Comment by myronliu347** [comment]
icon的使用方式有两种的

https://material.io/icons/
