### ISSUE TITLE
关于select-field的一些问题，附代码

### ISSUE THREAD

**Issue by efanng** [museui/muse-ui#479]
[https://jsfiddle.net/fanng/ejLyzkg5/2/](url)
![qq20170504-162644](https://cloud.githubusercontent.com/assets/1562932/25695691/b1e9d642-30e6-11e7-8386-9979e5816c73.png)

直接看代码吧，在做联动的时候，比如显示一个表单时，先有该select的value，然后后台再加载该select的列表。此时该select的item中已经显示选中，但是label却为空。

**Comment by myronliu347** [comment]
vue 在slot内容改变时无法触发更新，所以这时需要强制更新
this.$forceUpdate();

**Comment by Kanchil** [comment]
同样的问题，没办法做数据的回显了
