### ISSUE TITLE
不知道如何入门

### ISSUE THREAD

**Issue by nbslr** [museui/muse-ui#48]
东西很好，能否给个示例，谢谢，我的qq是6778770 能有朋友帮我一下吗

**Comment by xiaoluoboding** [comment]
muse-ui的[快速入门](https://museui.github.io/#/install)从这里开始，例子都有的。如果你对`vue`不熟悉的话，可以去看看如何使用vue构建spa，另外vue官网提供了`vue-cli`命令行工具。可以帮助你快速构建应用。

**Comment by nbslr** [comment]
谢谢，能否加个qq带带我

**Comment by myronliu347** [comment]
使用上有问题可以直接来  [gitter](https://gitter.im/muse-ui/muse-ui) 里提，或者开 issue 哦

**Comment by bossware** [comment]
现在的示例都是 es6 的写法，我贴个传统的写法：
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" href="muse-ui/dist/muse-ui.css">
    <script src="js/vue.min.js"></script>
    <script src="muse-ui/dist/muse-ui.js"></script>
</head>
<body>
<div id="app">
    <template>
        <mu-appbar title="Title">
            <mu-icon-button icon='menu' slot="left" @click="toggle()"/>
            <mu-icon-button icon='expand_more' slot="right"/>
        </mu-appbar>
    </template>
    <template>
            <mu-drawer :open="open" :docked="docked" @close="toggle()">
                <p>first</p>
                <p>second</p>
            </mu-drawer>
    </template>
</div>
<script>
    Vue.use(MuseUI);
    var vm = new Vue({
        el:"#app",
        data:{
            open:false,
            docked:false
        },
        methods:{
            toggle:function () {
                this.open = !this.open
            }
        },
        mounted:function(){
        }
    });
</script>
</body>
</html>
`

修改引用的js和css文件路径后可以直接看到效果
