### ISSUE TITLE
动态的切换主题 没有生效

### ISSUE THREAD

**Issue by hyphantom** [museui/muse-ui#487]
https://github.com/hyphantom/myweb-test
动态的切换主题 没有生效
我在https://github.com/hyphantom/myweb-test/blob/master/src/app.vue
做了修改
在没有加 methods: { 时 直接不能找到 changeTheme函数
现在虽然点击有效果了 但是主题并没有切换

**Comment by adrian999999** [comment]
```import light from '!raw-loader!muse-ui/dist/theme-default.css';
import dark from '!raw-loader!muse-ui/dist/theme-dark.css';
import carbon from '!raw-loader!muse-ui/dist/theme-carbon.css';
import teal from '!raw-loader!muse-ui/dist/theme-teal.css';

**Comment by hyphantom** [comment]
3Q！ adrian999999

**Comment by hyphantom** [comment]
### 继续提出问题：
[app.vue](https://github.com/hyphantom/myweb-test/blob/master/src/app.vue) 中，我使用的是官方文档中的写法。如果确实要在函数前加上` methods: `，那么是不是应该修改一下官方文档呢？ 毕竟，我用muse-ui，就是应为自己小白，加上有中文方便，大家都很积极。放弃material-ui的

**Comment by adrian999999** [comment]
应该需要加`methods:` @myronliu347

**Comment by myronliu347** [comment]
确实需要加上，多谢提醒

**Comment by hyphantom** [comment]
!raw! 和 methods: 都加一下把 @myronliu347  亲爱的作者大人
