### ISSUE TITLE
请问和material-ui（http://www.material-ui.com/）是什么关系

### ISSUE THREAD

**Issue by hellereye** [museui/muse-ui#49]
请问和material-ui是什么关系
http://www.material-ui.com/

**Comment by SoyMeng** [comment]
material是一个设计标准

**Comment by myronliu347** [comment]
都是material design 的设计规范来的，里面很多样式 API，我都有参考和借鉴 `material-ui` ,一直都觉得 `material-ui` 是目前最好的实现

**Comment by hellereye** [comment]
感谢作者辛苦努力
