### ISSUE TITLE
mu-infinite-scroll 调用无效

### ISSUE THREAD

**Issue by Edwardelric** [museui/muse-ui#492]
`<mu-refresh-control :refreshing="loading" :trigger="trigger" @refresh="refresh"/>
    <mu-list>
      <ul>
      <template v-for="(item, index) in list">
        <li class="flex topic-list">
        <router-link :to="'/topics/topiclist/topicdetail/' + item.id" class="link">
          <img :src="item.img"/>
          <dl>
            <dt>{{item.title}}</dt>
            <dd>{{item.summary}}</dd>
          </dl>
        </router-link>
        </li>
      </template>
      </ul>
    </mu-list>
    <mu-infinite-scroll :scroller="scroller" :loading="loading" @load="loadMore"/>`
 

data() {
      return {
        trigger: null,
        scroller: null
      };
    },

methods： {
   refresh() {
        if (!this.hasMore() || this.loading) {
          return;
        } else {
          this.loadData(0);
        }
    },
    loadMore() {
        if (!this.hasMore() || this.loading) {
          return;
        } else {
          this.loadData();
        }
    }
}
mounted() {
     this.trigger = this.$el;
     this.scroller = this.$el
     this.loadData();
}

loadData 是 数据请求方法，触发这个方法前需要判断 hasMore 或 loading  ,分别由 fresh 和 loadMore 调用。。但是就是mu-infinite-scroll 这个组件始终display:none

**Comment by ws511341206** [comment]
你好，怎么解决的，遇到了同样的问题？
