### ISSUE TITLE
怎么统一修改主题的颜色，我在styles>themes>dark.less修改主题颜色不生效。

### ISSUE THREAD

**Issue by bwqgithub** [museui/muse-ui#494]
用什么方法统一修改主题颜色。

**Comment by myronliu347** [comment]
http://192.168.31.152:8080/#/theme
参考，自定义主题，其实就是样式覆盖

**Comment by bwqgithub** [comment]
@myronliu347  不好意思再打扰一下，我这样使用less还是无法覆盖样式，可是使用css可以，怎么使用less统一把主题样式更改掉呢。
![qq 20170515211354](https://cloud.githubusercontent.com/assets/11193687/26059202/76c3ae6e-39b3-11e7-8f15-74de76b6e79d.png)

**Comment by adrian999999** [comment]
https://github.com/hyphantom/myweb-test 你可以看一下这个

**Comment by bwqgithub** [comment]
@myronliu347 这里面并不是按照模块引入的而是全部加在啊。

**Comment by lizhenggan** [comment]
@bwqgithub 解决了吗？能否告知一下解决办法

**Comment by myronliu347** [comment]
变量是不可以覆盖的，你可以尝试自定义主题的方式，生成一份自己的css文件
