### ISSUE TITLE
mu-list-item里面的mu-icon-menu的tooltip产生了滑动栏

### ISSUE THREAD

**Issue by shijiansu** [museui/muse-ui#499]
Muse UI版本：^2.0.0-rc.5

在mu-list-item里面使用
`<mu-icon-menu slot="right" icon="more_vert" tooltip="More Actions">`
如果mu-list-item只有两行内容，当鼠标移动到mu-icon-menu上面显示tooltip时候，右侧会产生滑动栏。

原来：
![image](https://cloud.githubusercontent.com/assets/21063434/26093342/1d591aa4-3a48-11e7-983b-457ed9a2d024.png)

当鼠标停留在mu-icon-menu并显示tooltip内容时：
![image](https://cloud.githubusercontent.com/assets/21063434/26093324/0000b39a-3a48-11e7-9c0d-443b12d014e5.png)

谢谢！

**Comment by myronliu347** [comment]
你更下版本再试试看，这个问题之前似乎修复过
