### ISSUE TITLE
在Android上运行效率好像不高，有没有优化的办法呢

### ISSUE THREAD

**Issue by zhengyuxi1991** [museui/muse-ui#50]
在Android上运行效率好像不高，有没有优化的办法呢

**Comment by myronliu347** [comment]
是动画卡顿么

**Comment by myronliu347** [comment]
最好能给出你的安卓的版本，我找个机器测试下，然后根据实际情况做调整

**Comment by huangzhenxian** [comment]
@myronliu347 我用 安卓5.0 小米2s   体验不怎么流畅

**Comment by bossware** [comment]
@myronliu347 两部手机 
android 6.0 小米note 效果不佳；
iphone 6s上表现良好；
整体确实需要进一步优化

**Comment by huangzhenxian** [comment]
@myronliu347  苹果6  ios10 的体验也是偏低  我个人感觉  流畅程度比效果更重要  我宁愿不要动画效果 只要配色和谐  可惜我不能为你献一份力量   我前端很烂 只能按我个人感觉提点意见

**Comment by myronliu347** [comment]
嗯，好的，我会在近期做一下优化

**Comment by ghprod** [comment]
Hi, 

Do you all feel that muse ui seems laggy when open in mobile browser?

**Comment by myronliu347** [comment]
目前卡顿的原因，每次切换页面都要进行大量 markdown文档解析和代码高亮渲染，所以在页面切换的时候会有明显的卡顿，ios 上js的运行速度比android上要快很多，所以还好。
然后文档内的dom数量过多也是导致卡顿的原因

**Comment by myronliu347** [comment]
周末优化了一些组件的动画，每个组件的动画效果还算比较流畅，

**Comment by ghprod** [comment]
> Weekend optimize some animation components, each component of the animation is still relatively smooth,

:+1:

**Comment by myronliu347** [comment]
现在所有的弹出框组件 drawer, popup, bottomSheet,popover, dialog 都增加了 `show` (打开动画结束后), `hide` (关闭动画结束后) 事件,  向侧栏导航这种点击之后需要切换视图的可以监听hide事件再切换，以保证动画的流畅

**Comment by lqixv** [comment]
我用 android 手机自带浏览器看了下museui官网，感觉还是不怎么流畅，主要体现是：
1、首次加载有点慢
2、点击左侧菜单后，新组件内容加载时间有点长（好像都是动画执行完后才进行加载）
能不能增加一个全局的选项，以决定是否加载动画呢？然后，每个组件也有动画效果选择，组件动画效果的选择优先于全局选择。类似 css 的加载。然后，如果不设定全局选项的话，默认手机是关闭动画，而桌面默认是打开的。我想这样感觉会体验更好些。

**Comment by myronliu347** [comment]
@lqixv 那个markdown 解析有点慢

**Comment by myronliu347** [comment]
@lqixv  首页加载慢是因为这个项目依赖的js过多，资源太大下载慢，另外每个页面打开时都会经过markdown的解析，我为了保证drawer动画的流畅所以让切换页面在动画完成之后再执行。

另外实际的项目的优化还需要根据实际情况处理,以后我会写些demo项目，分享一些优化方案.
