### ISSUE TITLE
menu出现滚动条时,点击其中任意一条,都会滚到底部

### ISSUE THREAD

**Issue by huyiwei93** [museui/muse-ui#501]
我menu的menu-item是动态加载出来的
这样的代码
` <mu-paper class="mu-paper">
          <mu-menu v-for="item in area" :key="item.id" v-model="selectId">
            <mu-menu-item :value="item.id" :title="item.area_name" leftIcon=" " leftIconClass="area-icon"
                          @click="getArea(item.id)">
            </mu-menu-item>
          </mu-menu>
        </mu-paper>`
不知道大家有没有遇到过这样的问题

**Comment by myronliu347** [comment]
请给出一个在线的demo，模拟出错情况https://jsfiddle.net/
