### ISSUE TITLE
移动端 body 穿透滚动

### ISSUE THREAD

**Issue by lany44** [museui/muse-ui#505]
@myronliu347 
我今天在 2.0.2 上使用还是遇到页面 body 穿透移动的问题。

官网的 pop-up 组件，底部弹出时可以重现。

自己在业务中 hack 了，这算是一个 bug 吗

**Comment by lany44** [comment]
iphone 6 下 新版 wx webview

**Comment by myronliu347** [comment]
ios下就会滚动穿透，实际代码中已经把滚动条屏蔽了
