### ISSUE TITLE
为什么单独引入组件的时候其他组件可以正常引入，但是引入tabs的时候会报错。

### ISSUE THREAD

**Issue by bwqgithub** [museui/muse-ui#506]
![20170518184726](https://cloud.githubusercontent.com/assets/11193687/26198953/cc75e572-3bfa-11e7-82cd-43589dc58517.png)
![4702](https://cloud.githubusercontent.com/assets/11193687/26198954/cca56fd6-3bfa-11e7-9c72-751bf6368f18.png)

**Comment by adrian999999** [comment]
tabs.name
毕文强 <notifications@github.com>于2017年5月18日 周四下午8:50写道：

**Comment by bwqgithub** [comment]
@adrian999999   我看源码中tabs用了as 是因为这个的原因所有我们引入组建的时候要特殊处理吗？
![qq 20170518190823](https://cloud.githubusercontent.com/assets/11193687/26199767/d8f42a7c-3bfd-11e7-9db8-b2349cd93888.png)
![qq 20170518190852](https://cloud.githubusercontent.com/assets/11193687/26199768/d93edc16-3bfd-11e7-9721-12082e92969d.png)

**Comment by adrian999999** [comment]
tabs 不是一个单一组件里面包含tab 组件
正常来说设计里tabs 应该自动加载tab 组件 但是源代码里好像并没有 你试试把tab 也加再进去
毕文强 <notifications@github.com>于2017年5月18日 周四下午9:12写道：

**Comment by bwqgithub** [comment]
不行的 @adrian999999   你们是不是单独引入 tabs存在bug？

**Comment by bwqgithub** [comment]
@myronliu347 这是bug吗还是引入方式不对吗 。

**Comment by myronliu347** [comment]
有些组件是两个配合的，例如 tabs , menu, list 导出时候不是default

```javascript
import {tabs, tab} from ''
import {menu, menuItem} from ''
import {list, listItem} from ''
```
