### ISSUE TITLE
建议取消无效a-href

### ISSUE THREAD

**Issue by fuchao2012** [museui/muse-ui#507]
muse 做的很棒，准备投入生产。

其中有个小建议，希望在demo中取消 a 链接的无效指向。

比如： [APP bar](http://www.muse-ui.org/#/appbar) 中 expand more 的 href=333 

抱歉没有具体的去列出对应的清单。

如果需要，我可以pr

**Comment by myronliu347** [comment]
ok,多谢，之前调试遗留下来的
