### ISSUE TITLE
flexbox import error

### ISSUE THREAD

**Issue by SoyMeng** [museui/muse-ui#51]
版本：
2.0.0-alpha.6
现象：
![image](https://cloud.githubusercontent.com/assets/6083582/20378548/bb560898-acd1-11e6-823b-bd860f3d352f.png)
说明：

```
import Flexbox from 'muse-ui/flexbox';
Vue.component(Flexbox.name, Flexbox);
```
webpack中alias设为muse-ui,其他组件已经引入成功,flexbox缺失败了

**Comment by myronliu347** [comment]
flexbox这里有两个组件

```javascript
import {flexbox, flexboxItem} from 'muse-ui/flexbox';
Vue.component(flexbox.name, flexbox);
Vue.component(flexboxItem.name, flexboxItem);
```

**Comment by huangzhenxian** [comment]
单个组件引入都要用  improt {} from 'muse-ui/***' 吧  要  {}

**Comment by huangzhenxian** [comment]
我引入 单个   flexbox也不至于报错  只是   flexboxItem 标签无法使用而已 flexbox标签是正常使用的

**Comment by SoyMeng** [comment]
希望能像mint-ui那样,从一个ui组件中import
