### ISSUE TITLE
[Feature Request] Importing single components with a specific theme

### ISSUE THREAD

**Issue by n1ru4l** [museui/muse-ui#516]
It should be possible to specify a theme for the imported components. At the moment it is only possible to additionally import the `.css` theme file which includes many unused styles.

From my research the best way to implement this would be http://lesscss.org/features/#variables-feature-import-statements

With a folder structure like this:
```
styles
  themes
    variables.default.less
    variables.dark.less
    variables.light.less
    variables.teal.less
```

The `styles/import.less` file would then be changed to:
```less
@import "./variables.@{theme}.less";
@import "./mixins.less";
```

The variable `theme` would be injected as a global variable like this:
```javascript
{
  loader: 'less-loader',
  options: {
  globalVars: {
    theme: 'default'
    }
  }
}
```

People that load single components also need to add the globalVars option to their vue-loader configuration.

```javascript
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      less:  [
        'vue-style-loader',
        'css-loader',
        {
           loader: 'vue-loader',
           options: {
             globalVars: {
               theme: 'dark'
             }
        }
      ],
    }
  }
}
```

I will try if this methods works out and create a PR @myronliu347

**Comment by myronliu347** [comment]
Thanks, this is good idea
