### ISSUE TITLE
required attribute on mu-text-field

### ISSUE THREAD

**Issue by sombriks** [museui/muse-ui#517]
Hello, 
if i use something like this inside a form:

`<mu-text-field type="email" label="Email" labelFloat v-model="usuario.email" required/>`

i expected the browser do some validation, however it does not happen.

how can i make a text field to be a required form field?

**Comment by n1ru4l** [comment]
There is no implementation for this at the moment (https://github.com/museui/muse-ui/blob/master/src/textField/textField.vue). In order to make it required a required property must be implemented. You could do a PR for this - and if you don't want I can do it for you :)

**Comment by sombriks** [comment]
Hi @n1ru4l ,

feel free to PR for this, it's a nice feature and the community would be glad :-)

**Comment by n1ru4l** [comment]
Hm I think then we should implement all validation attributes

**Comment by kgrosvenor** [comment]
I use VeeValidate it works perfectly with this :) I wouldn't say its required or the project

**Comment by n1ru4l** [comment]
@kgrosvenor I think it should be possible to use the basic html5 attributes for forms in order to benefit from browser validation instead of being forced to use an other library for handling form validation.

**Comment by myronliu347** [comment]
fixed
