### ISSUE TITLE
root font-size (rem) 62.5% !== 10px in Chinese environment

### ISSUE THREAD

**Issue by yuqianma** [museui/muse-ui#518]
Using rem in my project.
I found muse-ui set <html> font-size to 62.5%.
[here](https://github.com/museui/muse-ui/blob/bcee45c544372c3f8d6d49fbb785c3444b0ceced/src/styles/base.less#L9)
Maybe it's widely used in English world to get rem = 10px. But unfortunately it's wrong in Chinese environment.
Chrome in Chinese's minimal font-size is 12px. Any size smaller than 12px will be set to 12px at last.
You can check by:
``` javascript
getComputedStyle($('html')).fontSize
```

中文Chrome的最小字体是12px，这样导致62.5% * 16 = 10, 10 < 12变成了12px。
真希望那群看上去很较真的老外们能知道这回事→_→

**Comment by myronliu347** [comment]
嗯，我这里并没有用到rem，后面我会吧这个部分的css去掉
