### ISSUE TITLE
关于checkbox的问题

### ISSUE THREAD

**Issue by kunnisser** [museui/muse-ui#519]
checkbox的v-model绑定在项目使用众貌似不起作用，有其他人遇到这样的情况么？官网的示例是可以正常执行的。但是把示例代码直接复制到本地项目里v-model貌似有问题

**Comment by myronliu347** [comment]
请给出在线的demo，模拟出错情况
https://jsfiddle.net

**Comment by xianzhi0520** [comment]
我的也是  我最后都是用watch监视click实现的
