### ISSUE TITLE
Auto complete component doesn't work

### ISSUE THREAD

**Issue by dusterio** [museui/muse-ui#523]
Hey guys, is anybody else using auto complete component?

It renders just as plain text input field for me. I tried different components from Muse-UI - everything else worked fine.

Tried different versions of Muse-UI and Vue - all the same. No warnings or errors given.

It just works as normal text field, no hints (datasource), all props make no effect

**Comment by n1ru4l** [comment]
For me it is working. Does the demo on http://www.muse-ui.org/#/autoComplete work for you?
