### ISSUE TITLE
在Webkit 534.30内核浏览器下页面渲染问题

### ISSUE THREAD

**Issue by hearain** [museui/muse-ui#525]
在Webkit 534.30内核浏览器下，muse-ui 部分控件不能正确显示和运行
日历出现错位，icon无法显示或者显示的为英文没有正确的被渲染

![image](https://cloud.githubusercontent.com/assets/9176349/26439381/76919506-415a-11e7-9e60-70b1ef89e1f4.png)

![image](https://cloud.githubusercontent.com/assets/9176349/26439393/819be078-415a-11e7-8840-b590959cd5be.png)

![image](https://cloud.githubusercontent.com/assets/9176349/26439402/8e0e79a6-415a-11e7-8b2b-c7ba909103c2.png)

**Comment by jeffwcx** [comment]
界面在uc上完全崩了，感觉flex布局兼容有些问题

**Comment by fancymo** [comment]
项目是使用 react 吗？
