### ISSUE TITLE
dialog

### ISSUE THREAD

**Issue by NoBey** [museui/muse-ui#529]
## mu-dialog  lack of css ` overflow-y:auto`

<img width="1041" alt="dialog" src="https://cloud.githubusercontent.com/assets/10740524/26519303/8da2b8d6-42f1-11e7-917f-f2241b6dcc99.png">

**Comment by n1ru4l** [comment]
I think this is related to https://github.com/museui/muse-ui/pull/515.
Looks like the documentation was not updated.

**Comment by NoBey** [comment]
@n1ru4l 
The latest version 2.0.3 still has the problem
I think that can be solved
https://github.com/museui/muse-ui/pull/530

**Comment by n1ru4l** [comment]
@NoBey The master branch is ahead version 2.0.3

<img width="1280" alt="bildschirmfoto 2017-05-27 um 12 48 26" src="https://cloud.githubusercontent.com/assets/14338007/26520844/dcd9c69a-42da-11e7-8caf-470cf6267c3f.png">

**Comment by myronliu347** [comment]
fixed
