### ISSUE TITLE
升级到alpha.7后全局加载组件不能使用

### ISSUE THREAD

**Issue by mokaikai** [museui/muse-ui#53]
![screen shot 2016-11-18 at 11 11 39](https://cloud.githubusercontent.com/assets/11897616/20417420/029c256c-ad80-11e6-9df8-10bcff07f5b2.png)

**Comment by myronliu347** [comment]
使用 [jsfiddle](https://jsfiddle.net/), 然后重开
我刚在自己的里升级了下，没有问题啊，

**Comment by mokaikai** [comment]
我把node_modules目录删了，重新install一遍就没问题了。
