### ISSUE TITLE
<mu-flexbox>gutter赋值出现错误提示

### ISSUE THREAD

**Issue by 529457764** [museui/muse-ui#533]
gutter=“0”，gutter=0，我这样传值，都会有错误提示：
vue.esm.js?65d7:434 [Vue warn]: Invalid prop: type check failed for prop "gutter". Expected Number, got String

**Comment by 529457764** [comment]
改成 :gutter=“0”就没有报错了，求解答

**Comment by hjlld** [comment]
不用v-bind，直接双引号传值，传过去的是字符串

**Comment by myronliu347** [comment]
就是楼上的道理，这个 gutter是number类型
