### ISSUE TITLE
建议 InfiniteScroll 扩大应用场景

### ISSUE THREAD

**Issue by hjlld** [museui/muse-ui#534]
目前 InfiniteScroll 只能用在 overflow: scroll; 的元素上，应用场景太小。

而当元素底部接触视口底部触发 load 事件才是通常大部分人认为的 InfiniteScroll 吧？这种情况也是更多会遇到的情况。例如 eleme 的 infinite scroll 就是这么做的。

建议提供这种情况下的支持。

**Comment by F-loat** [comment]
不使用100%高度的方式布局的话，直接把scroller设为window也可以

**Comment by myronliu347** [comment]
scroller不设置默认就是window
