### ISSUE TITLE
Bottom Sheet使用问题

### ISSUE THREAD

**Issue by Mexcellent** [museui/muse-ui#538]
![image](https://cloud.githubusercontent.com/assets/14340202/26765712/63051866-49b4-11e7-88ba-0c0b125a25b9.png)
请问为何会报这个错误，提示信息太少，根本找不到，我是放这个组件放在子页面，然后从子页面跳转回主页就报这个错误，请问谁能帮忙解答下嘛，实在找不到，多谢。

**Comment by lry210** [comment]
1
