### ISSUE TITLE
textFieldHint文本溢出和换行问题

### ISSUE THREAD

**Issue by ShanaMaid** [museui/muse-ui#542]
the text overflow 
![](http://wx2.sinaimg.cn/mw690/dc58f491ly1fg62nyhkvqj20dh08wdfx.jpg)
![](http://wx4.sinaimg.cn/mw690/dc58f491ly1fg62nzgtp8j20dt07qjrf.jpg)

fixed
![](http://wx4.sinaimg.cn/mw690/dc58f491ly1fg62nxz3azj20ct08mgln.jpg)

已提pr

**Comment by myronliu347** [comment]
ok，已合并pr, 多谢
