### ISSUE TITLE
自定义主题动态切换问题？

### ISSUE THREAD

**Issue by bwqgithub** [museui/muse-ui#545]
你好我看到muse动态切换主题是通过动态引入不同的theme css完成的。
现在我的项目中是用的scss，我利用相同的方法动态的引入不同的scss（color.scss）并不会生效，引入不同的css却可以。
那么我需要把scss编译成多个theme的css吗，还是说有别的解决方案。

**Comment by myronliu347** [comment]
动态主题方案，目前只支持less，因为内部使用less，如果要支持scss需要把全部样式文件转一份scss版本，工作量太大
