### ISSUE TITLE
全局tooltip及改变appBar的大小问题

### ISSUE THREAD

**Issue by easyfrog** [museui/muse-ui#550]
刚接触 Muse-ui 现在遇到这两个问题
1. appBar的大小感觉有些太大了. 是否有 small 属性?
2. toolTip的使用. 我看了官网上的例子
> <div class="demo-icon-tip" ref="demo" @mouseenter="handleHover" @mouseleave="handleHoverExit">
    <mu-icon value="print"/>
    <mu-tooltip label="打印" :show="show" :trigger="trigger" :touch="touch" :verticalPosition="verticalPosition" :horizontalPosition="horizontalPosition"/>
  </div>
好像必须在这两句外面套上一个div.  还要自己处理 mouseenter mouseleave 事件.
可不可以 做成一个全局的 tooltip, 就是在 标签里添加一个 tooltip 属性. 就会在mouseenter的时候. 自动出现呢?  现在的使用方式是要在每个需要tooltip的标签都需要一个mu-tooltip 标签. 使用起来有些不方便呀.

**Comment by myronliu347** [comment]
appBar的大小是根据设计规范确定的，
tooltip现在确实需要在调用方式做下改变，不过现在内部需要tooltip的组件 icon-button 这类，都已经内置了tooltip
