### ISSUE TITLE
Themeing documentation and colors

### ISSUE THREAD

**Issue by lgullestrup** [museui/muse-ui#555]
It would be great if there was better documentation on themeing.

I am finding myself running a lot of trial and error to determine which variable affects which part of the component at each state.
Eg.
textFieldTextColor vs textFieldInputColor vs textFieldFocusTextColor ect....

having to go through each one and set a color and recompile to see what changes is very time consuming. 

Other than that, it would be great if there was greater control over the the colors used on the fly, and not having to rely souly on themes. eg.. appBar would only be used once, but you have to define its color in a theme.

Being able to override the themes colors for special occasions would be nice.

**Comment by myronliu347** [comment]
We recommend using a `theme.less` to change components style, `textFieldFocusTextColor ` only used for fine adjustment style
http://www.muse-ui.org/?lang=en#/theme
