### ISSUE TITLE
关于mu-appbar的title和zDepth

### ISSUE THREAD

**Issue by hezhongfeng** [museui/muse-ui#556]
1. `title`的居中不是基于`mu-appbar`而是基于图标剩余的部分,也就是`mu-appbar-title`
2. `zDepth`的值无效，通过vue tool查看确实设置了，但是没作用
版本2.0.3 通过npm安装

**Comment by myronliu347** [comment]
1. title并不是居中显示的
2. zDepth使用是改变阴影层级，本地测试没有问题，如果出错，请给出在线的demo

**Comment by hezhongfeng** [comment]
是我的问题，在别的地方设置了`text-align`
当时看的中文教程，其中的`appBar`写了
>  标题, 显示在中间
然后就先入为主以为居中有问题

**Comment by myronliu347** [comment]
https://jsfiddle.net/0zmhua70/11/
html中使用和`.vue`中使用上略有不同
