### ISSUE TITLE
mu-text-field 不响应 keydow 事件？

### ISSUE THREAD

**Issue by jimmydong** [museui/muse-ui#561]
没有反应。

`
<mu-text-field v-model="keyword" @keydown.enter="search()" icon="search" class="appbar-search-field" slot="right" hintText="请输入搜索内容"/>
<input type=text @keydown.enter="search()"/> 
`

用INPUT可以正常工作。

**Comment by myronliu347** [comment]
#329 
组件内没有冒泡出keydown事件

**Comment by Genuifx** [comment]
@myronliu347 组件求冒泡键盘时间，想监听回车事件！
