### ISSUE TITLE
Picker组件在安卓机上滑动卡顿，最开始没有数据的情况下，上面或下面的空白处不能滑动

### ISSUE THREAD

**Issue by fengxinming** [museui/muse-ui#569]
我对比了其他的开源项目mint-ui也是在安卓机上划不动，上面或者下面的空白处不能滑动；但是vux下滑动很流畅，建议可以参考一下。

**Comment by myronliu347** [comment]
不太懂你描述的情况，没有数据的情况为什么要滑动呢？

**Comment by fengxinming** [comment]
@myronliu347 比如：我们要做一个选择城市的picker，初始化默认选中北京市，北京市上面不是有块空白处，我是意思是触摸上面的区域滚轮不能往上滚动，应该懂了吧，我是参考了 https://vux.li/demos/v2/?x-page=v2-doc-home#/component/picker
