### ISSUE TITLE
关于muse-ui的FAQ聚合展示问题

### ISSUE THREAD

**Issue by ShanaMaid** [museui/muse-ui#570]
muse-ui使用时的一些FAQ可以在muse官网上开一个模块进行列举，部分人使用的时候不会看issues，而且issues的FAQ存在比较分散的问题。

可以在muse-ui文档的快速开始下增添一个FAQ，进行聚合展示。

没问题的话我可以发一个pr添加这个模块。

**Comment by myronliu347** [comment]
你可以pr，之前我有在issue里写的一些都可以转过去
