### ISSUE TITLE
Autocomplete 组件ios10.3.2safari bug

### ISSUE THREAD

**Issue by soapper** [museui/muse-ui#571]
![](http://i.imgur.com/AmodIPT.jpg)

**Comment by soapper** [comment]
光标也会透到下拉选择里面

**Comment by soapper** [comment]
测试了angular的mertirial ui也是这种情况，感觉是ios 输入法弹出后视窗变小，正在尝试用google 的搜索框的解决方案。

**Comment by myronliu347** [comment]
目前没有控制光标的解决方案，但是如果你用使用window下的滚动条是不会出现，在样式中使用overflow:auto，就会有这种情况

**Comment by soapper** [comment]
ok 我测试下Thx
