### ISSUE TITLE
表格宽度过小时表格内容会重叠

### ISSUE THREAD

**Issue by lzp4ever** [museui/muse-ui#574]
@如果表格内容过长，表格宽度过小时表格内容会重叠，即使在官方实例中也如此，能否设定每列的最小宽度？ [http://www.muse-ui.org/#/table](http://www.muse-ui.org/#/table)

**Comment by ShanaMaid** [comment]
#568 已经解决这个问题，请等待下个版本进行更新

**Comment by myronliu347** [comment]
这并不是最佳的解决方案，实际表格使用在窗口变小，应该尝试隐藏部分列，比较屏幕小也显示不了那么多东西，落地在项目中需要添加一些css去控制这种情况。

**Comment by lzp4ever** [comment]
目前表格宽度过小的时候会出现横向滚动条，但是横向滚动条出现时表格内容已经处于重叠状态了
