### ISSUE TITLE
Pagination在页数超过六页时，在手机尺寸上下一页按钮会超出边界

### ISSUE THREAD

**Issue by lzp4ever** [museui/muse-ui#576]
如页数为7页时，选择3，4，5页，下一页按钮会超出边界

**Comment by myronliu347** [comment]
请给出在线demo，处理出错情况，并附上出错的截图

**Comment by lzp4ever** [comment]
demo可以直接参考官方实例 [http://www.muse-ui.org/#/pagination](http://www.muse-ui.org/#/pagination)
可以看到更多分页下长度已经大幅超出了边界
![](https://ooo.0o0.ooo/2017/06/20/59489452cf204.png)
![](https://ooo.0o0.ooo/2017/06/20/594894d3e8092.png)

**Comment by myronliu347** [comment]
那是显示页数设置过多了呀，分页组件基本就是在pc端上使用的，手机上都是infitescroll,
