### ISSUE TITLE
infinite-scroll 下拉后无限循环调用loadMore方法

### ISSUE THREAD

**Issue by jjjachyty** [museui/muse-ui#577]
更新2.0.3后 下拉一次 死循环调用loadMore方法

**Comment by linxiaowu66** [comment]
请给出在线demo, 你有检查过你的代码 有没有死循环调用了？

**Comment by jjjachyty** [comment]
检查了 之前一直用2.0.0-rc.5 今天突然想升级 然后发现下拉进入无限死循环 已退回到2.0.0-rc.5 demo 用你们提供的demo 改了下 去掉for循环就死循环了

<template>
<div class="demo-infinite-container">
  <mu-list>
    <template v-for="item in list">
      <mu-list-item :title="item"/>
      <mu-divider/>
    </template>
  </mu-list>
  <mu-infinite-scroll :scroller="scroller" :loading="loading" @load="loadMore"/>
</div>
</template>

<script>
export default {
  data () {
    const list = []
    for (let i = 0; i < 10; i++) {
      list.push('item' + (i + 1))
    }
    return {
      list,
      num: 10,
      loading: false,
      scroller: null
    }
  },
  mounted () {
    this.scroller = this.$el
  },
  methods: {
    loadMore () {
        console.log("this.scroller",this.scroller)
      this.loading = true
      setTimeout(() => {
        // for (let i = this.num; i < this.num + 10; i++) {
        //   this.list.push('item' + (i + 1))
        // }
        console.log("this.scroller",this.scroller)
        this.num += 10
        this.loading = false
      }, 200)
    }
  }
}
</script>

<style lang="css">
.demo-infinite-container{
  height: calc(100vh - 160px);     
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  border: 1px solid #d9d9d9;
}
</style>

**Comment by myronliu347** [comment]
增加了一个isLoaded属性，用于判断数据是否全部加载了
```html
<template>
<div class="demo-infinite-container">
  <mu-list>
    <template v-for="item in list">
      <mu-list-item :title="item"/>
      <mu-divider/>
    </template>
  </mu-list>
  <mu-infinite-scroll :scroller="scroller" :loading="loading" :isLoaded="isLoaded" @load="loadMore"/>
</div>
</template>

<script>
export default {
  data () {
    const list = []
    for (let i = 0; i < 10; i++) {
      list.push('item' + (i + 1))
    }
    return {
      list,
      num: 10,
      loading: false,
      isLoaded: false,
      scroller: null
    }
  },
  mounted () {
    this.scroller = this.$el
  },
  methods: {
    loadMore () {
        console.log("this.scroller",this.scroller)
      this.loading = true
      setTimeout(() => {
        // for (let i = this.num; i < this.num + 10; i++) {
        //   this.list.push('item' + (i + 1))
        // }
        console.log("this.scroller",this.scroller)
        this.num += 10
        this.loading = false
        this.isLoaded = true
      }, 200)
    }
  }
}
</script>

<style lang="css">
.demo-infinite-container{
  height: calc(100vh - 160px);     
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  border: 1px solid #d9d9d9;
}
</style>
```
