### ISSUE TITLE
pagination 页面选择标签显示不正确

### ISSUE THREAD

**Issue by magicxin** [museui/muse-ui#578]
![qq 20170620173227](https://user-images.githubusercontent.com/17487870/27326620-848280ba-55de-11e7-835c-8ee5d9c2f734.png)

能指点下是大概什么方向的错误码？

**Comment by ShanaMaid** [comment]
请提供在线demo

**Comment by linxiaowu66** [comment]
@magicxin 请问你是怎么配置这个组件的？

能给个demo代码吗？
