### ISSUE TITLE
 在父组件中修改mu组件的样式，一旦父组件scoped，修改就失效

### ISSUE THREAD

**Issue by pyuyu** [museui/muse-ui#581]

**Comment by ShanaMaid** [comment]
这是vue本身的机制
[scoped说明](http://cn.vuejs.org/v2/guide/comparison.html#CSS-的组件作用域)

**Comment by pyuyu** [comment]
那想修改子组件的样式 有什么比较好的解决方案吗

**Comment by myronliu347** [comment]
主要css的权值为题，家欢神那个scoped之后样式会加上属性，然后就没法覆盖之前组件样式。目前不推荐使用scoped的方式，因为真的没有特别好的方案。
