### ISSUE TITLE
Scroller Dialog

### ISSUE THREAD

**Issue by lgullestrup** [museui/muse-ui#584]
Iv been wanting to use the scroller dialog, but i seem to be stuck with v2.0.3.

is there a way to get a hold of the fix? or do i have to wait for next release?

**Comment by ShanaMaid** [comment]
Yes,  please wait for next release!

**Comment by lgullestrup** [comment]
ok no problem.

I have found muse to be rather amazing to work with. (although in some areas a little constricting) but amazing none the less.

keep up the great work!

**Comment by ShanaMaid** [comment]
Thanks for your blessing, we will do better!
