### ISSUE TITLE
Autocomplete nice to have - Templates

### ISSUE THREAD

**Issue by lgullestrup** [museui/muse-ui#587]
I'm not sure how you would achieve this, but it would be nice to be able to define your own template for the items displayed in the auto-complete.

not everything can be displayed on a single line, so being able to make a template to customize the output of the drop down would be usefull. 

i will work around this for now how ever.

edit: after a bit of research, i found this could be achieved using 'scoped slots' which was released in Vue2.1

just some food for thought.

**Comment by myronliu347** [comment]
Yes, I think this is a good idea, But now is hard to change `AutoComplete`， You can use `TextField` and `Popover`
