### ISSUE TITLE
方便写一个基础的页面结构吗

### ISSUE THREAD

**Issue by wh469012917** [museui/muse-ui#59]
如题目，就类似文档页那样的，左边是菜单右边内容，而且移动的体验也很好，这样别人用来写项目文档或者做后台都可以很方便

**Comment by huangang** [comment]
+1

**Comment by sjcarr** [comment]
+1

**Comment by xuexb** [comment]
建议在`/museui`分组下开设几个`demo`项目, 也让我们学习下~  @myronliu347 
最后感谢muse-ui~

**Comment by myronliu347** [comment]
[museui-demo](https://github.com/museui/museui-demo)
这是团队内的人的一个demo项目，以后我也会写两个实际的项目放上去
