### ISSUE TITLE
tab在手机上卡

### ISSUE THREAD

**Issue by huziyang410** [museui/muse-ui#592]
tab切换的时候卡

**Comment by DearAKuan** [comment]
你也不贴个代码就说卡,这个muse UI无关吧, 是你自己哪里代码没写好吧 调了大量的循环之类的..

**Comment by huziyang410** [comment]
在手机浏览器上的时候，那个过渡动画会卡。

**Comment by DearAKuan** [comment]
你把你的业务逻辑都移除了,单独切换看卡不卡,肯定不卡吧,切换的时候肯定执行其他事件了吧,自己用性能检测工具看一下你的js代码,看是哪一步耗时耗cpu了
