### ISSUE TITLE
pagination 组件的 actualPageSize 设置有误

### ISSUE THREAD

**Issue by SamChan1204** [museui/muse-ui#598]
传入参数如下：
```
const pagination = {
  defaultPageSize: 10,
  showSizeChanger: true,
  pageSizeOption: [5, 10, 15]
}
```

现象：
`defaultPageSize` 不生效，且组件初始化之后，马上触发了 `pageSizeChange` 事件。

原因：
查看源码，发现是因为如下代码：
```
data () {
  return {
    // ...
    actualPageSize: this.defaultPageSize,
    // ...
  }
},
mounted () {
  // ...
  if (this.showSizeChanger) {
    this.actualPageSize = this.pageSizeOption[0]
  } else if (this.pageSize) {
    this.actualPageSize = this.pageSize
  }
  // ...
},
```
`mounted` 方法中，忽略了 `defaultPageSize`，始终将 `actualPageSize` 设置为 `pageSizeOption[0]`，并不是客户代码想要的。而且导致前后设置的 `actualPageSize` 不一致，触发了 `watch` 里面的回调。

**Comment by linxiaowu66** [comment]
@SamChan1204 
    你好！非常感谢使用这个组件。也很高兴你能够进入到源码去定位错误。

但是如果你有看源码的话，相信你肯定有看到这个注释：

```
mounted () {
    this.iconIsDisabled(this.actualCurrent)

    // 优先使用pageSizeOption,如果props配置了默认值，那么该props无论在父组件
    // 中是否配置该值都不会为undefined,所以需要使用showSizeChanger来做这个判断
    // 才对
    if (this.showSizeChanger) {
      this.actualPageSize = this.pageSizeOption[0]
    } else if (this.pageSize) {
      this.actualPageSize = this.pageSize
    }

    this.totalPageCount = Math.ceil(this.total / this.actualPageSize)
    this.pageList = this.calcPageList(this.actualCurrent)
  },
```

也就是说在设计之初就是考虑到你既配置了默认条数以及可选页条数，如果二者都配置的话，代码中优先使用pageOption，至于你说的watch回调是因为，我一开始就默认这样的：

```
data () {
    return {
      leftDisabled: false,
      rightDisabled: false,
      actualCurrent: this.current,
      actualPageSize: this.defaultPageSize,
      totalPageCount: 0,
      pageList: [],
      quickJumpPage: ''
    }
  },
```
你可以看到一开始actualPageSize默认就等于defaultPageSize的。所以你说的这些问题应该是正常的。

如果有什么不好的话应该是我的文档没有注明这些信息，导致你误用。

**Comment by SamChan1204** [comment]
@linxiaowu66 你好！
上面的注释，我之前是有看到的，也理解设计的初衷。
可能我没有描述清楚，我的意思是，直接把 `actualPageSize` 设置为 `pageSizeOption[0]` 是不太妥当的。因为有时候用户配置了 `pageSizeOption`，但是不一定想要设置第一个值为默认页条数。
比如上面我的使用例子中，我设置了 `pageSizeOption` 为 `[5, 10, 15]`，但是我想要第二个值，也就是 `10` 为默认值，这个时候就没法实现我的需求了。
我建议在设置 `actualPageSize` 的时候可以做一次判断，比如：
```
if (this.showSizeChanger) {
  this.actualPageSize = (this.defaultPageSize && this.pageSizeOption.indexOf(this.defaultPageSize) >= 0) ? this.defaultPageSize : this.pageSizeOption[0]
}
```
当然可能这种场景比较少见，所以只是提出一个建议 :)

**Comment by linxiaowu66** [comment]
@SamChan1204 
 很感谢你的建议，按照你的场景，你可以这样传参的：
`pageSizeOption 为 [10, 5, 15]`

不过这有点违反逻辑，所以只能由开发者自己去取舍这个了

**Comment by SamChan1204** [comment]
@linxiaowu66 嗯嗯，我想了一下，一般都是默认最小页条数的，我这个有点伪需求了，所以就不纠结了
