### ISSUE TITLE
textField 提示错误

### ISSUE THREAD

**Issue by peirancao** [museui/muse-ui#6]
template syntax error `<input :type="type" v-model="inputValue">`:
v-model does not support dynamic input types. Use v-if branches instead.

**Comment by myronliu347** [comment]
你的 vue2 的版本是多少

**Comment by peirancao** [comment]
2.0.3

**Comment by myronliu347** [comment]
能不能给出具体的使用代码呢？

**Comment by myronliu347** [comment]
textField，我也测试过，没有这种问题，

**Comment by peirancao** [comment]
我使用的 vue-cli创建的项目 然后再项目中 Vue.use(MuseUI)  npm run dev  控制台直接抛出错误 把 textfiled selectfied 在 muse-ui 中的 index.js 注释掉就没问题了 

ERROR in ./~/.9.7.0@vue-loader/lib/template-compiler.js?id=data-v-97111a4c!./~/.9.7.0@vue-loader/lib/selector.js?type=template&index=0!./src/muse-ui/textField/textField.vue     
template syntax error <input :type="type" v-model="inputValue">:                                                                                                                 
v-model does not support dynamic input types. Use v-if branches instead.

是不是我的vue-loader 也需要升级啊 我试试

**Comment by myronliu347** [comment]
我升级 vue 之后也发现了，等下我改好提交

**Comment by peirancao** [comment]
好的

**Comment by myronliu347** [comment]
升级之后v-model不支持动态 type的input元素， 已经解决了
