### ISSUE TITLE
时间选择插件DatePicker,当选择日期为31时, 点击下月如果下月没有31号就会跳到有31号的月份

### ISSUE THREAD

**Issue by Mmpc1994** [museui/muse-ui#600]
比如选择日期为8月31日, 点击右箭头下一个月, 会跳到10月而不是9月, 看了下源码, 应该是setMonth()方法那边出错了, 因为9月没有31 会设置成10月1日

**Comment by ShanaMaid** [comment]
用官网的例子测试了一下并没能够进行复现

**Comment by Mmpc1994** [comment]
@ShanaMaid  因为官网的例子理没有 v-model

**Comment by ShanaMaid** [comment]
请提供在线demo

**Comment by myronliu347** [comment]
之前的版本是有这个问题，我在上个版本修复过，请检查你的muse-ui版本
