### ISSUE TITLE
2.0.3 ssr 使用appbar 浏览器出现异常提示

### ISSUE THREAD

**Issue by dddrecall** [museui/muse-ui#601]
使用muse2.0.3 组件:appbar, 浏览器出现出现异常提示：
`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`
调用appbar组件的代码为:
`<mu-appbar ></mu-appbar>`

**Comment by jaweii** [comment]
我的也是，用的Nuxt.js

话说现在muse-ui支持nuxt吗

**Comment by dddrecall** [comment]
@jaweii 不支持吧....

**Comment by myronliu347** [comment]
这个是生成dom树不匹配诶，你可以检查你的html模板是不是有标签没有闭合的

**Comment by dddrecall** [comment]
@myronliu347 好的，可能我使用ssr的方式不太对导致的
