### ISSUE TITLE
含有 mu-bottom-sheet 组件的页面跳转其他页面时报错

### ISSUE THREAD

**Issue by jerryHu570** [museui/muse-ui#602]
> 当页面有 mu-bottom-sheet 组件的时候，单页应用时，进入这个页面不点击bottom-sheet立即退出报错：Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by lry210** [comment]
[https://github.com/museui/muse-ui/issues/538](url)
16天之前就有了，这是月更么

**Comment by ShanaMaid** [comment]
@lry210 
最近@myronliu347 的公司的事情似乎比较多，可能要等他忙完这段时间了吧
