### ISSUE TITLE
dialog 内容超出弹出框范围

### ISSUE THREAD

**Issue by dddrecall** [museui/muse-ui#606]
muse-ui v 2.03 
手机端
在使用的过程中发现
如果弹出框内容过多
会导致内容直接超出了弹出框范围
经过代码查看
发现是有地方会限制长度
猜测是如下代码:
/src/dialog/dialog.vue

![dialog](https://user-images.githubusercontent.com/8815759/27775340-aa974aa2-5fd3-11e7-8dfe-c893ba4a806a.png)

这里面有一个简单的判断算法，给他一个固定的最大高度
目前我不清楚这个地方是否是算一个BUG
但是使用过程中，手机端，如果dialog内容过长，确实会出现内容超出范围

**Comment by ShanaMaid** [comment]
BUG已经修复，下个版本发布就正常了。
