### ISSUE TITLE
问题：mu-dropDown-menu组件无法通过v-for循环创建item

### ISSUE THREAD

**Issue by Sandune** [museui/muse-ui#613]
没报错，无效果
![image](https://user-images.githubusercontent.com/16025813/27820490-65b21012-60d1-11e7-9162-9153e67de36b.png)

**Comment by stevefermi** [comment]
可以分享一下如何解决这个问题的吗？

**Comment by Sandune** [comment]
用了个蠢办法
`mu-menu-item(value="001",title="选择类型")`
写一个固定的在v-for前面
