### ISSUE TITLE
请问有轻量手机版的吗

### ISSUE THREAD

**Issue by fengqiaoguke** [museui/muse-ui#616]
muse-ui是非常棒的一个作品!
现在移动端比pc端火很多,基本上都是优先考虑移动端了.虽然muse-ui可以开发移动端webapp,但总是感觉太臃肿了,有精简版适合移动端而且还在维护的吗?
我在开发webapp,在ios性能不是问题,但国产安卓的webview千奇百怪,只是希望可以让更多的用户有更好的体验.所以问问有没有专门针对移动端的优化版.
muse-ui好像没有专门针对移动端的list view,但我在vuecarbon 看到有了,但vuecarbon是9个月前最后一次更新,请问vuecarbon是放弃了,全面转muse-ui了吗?

**Comment by myronliu347** [comment]
谢谢支持，vue-carbon是基于vue1.0开发的，目前基本都升到vue2.0了所以这个项目不打算继续维护，muse-ui很多组件都可以在移动端使用，完全遵循的material design规范。vue -carbon 中的listView组件可以对应成muse-ui的list组件 通过list 和 listItem 也可以达到这个效果

**Comment by fengqiaoguke** [comment]
好的,谢谢
