### ISSUE TITLE
下拉刷新组件调整建议

### ISSUE THREAD

**Issue by zengzuozuo** [museui/muse-ui#619]
在下拉刷新组件中可否将下拉刷新触发距离加大，目前只要下拉一点点松开就触发刷新操作，体验不是很好，其他的用着都很好。 或者是将触发距离通过状态暴露出来 开发者可以自定义更好

**Comment by ShanaMaid** [comment]
@myronliu347 我觉得可以添加一个api暴露触发距离

**Comment by blessbygod** [comment]
为什么 619和644都关掉了，muse-ui并没有解决该问题啊

**Comment by blessbygod** [comment]
@ShanaMaid  这个问题你们有解决方案了吗？我看muse-ui并没有处理该问题
