### ISSUE TITLE
<mu-menu-item href> hover背景色

### ISSUE THREAD

**Issue by xuexb** [museui/muse-ui#62]
发现当`<mu-menu-item href="https://baidu.com">`之后(有`href`属性), 鼠标滑过该元素时没有背景色, 并且点击也没有背景色.

看样式应该是`.mu-menu-item-wrapper`为`A`标签时不是块级元素, 添加了`display:block`解决问题~

谢谢~

**Comment by myronliu347** [comment]
多谢，可以提交一个pr 哦
