### ISSUE TITLE
Bottom Sheet 不激活 切换视图 控制台出现错误

### ISSUE THREAD

**Issue by dddrecall** [museui/muse-ui#621]
在官方文档网站的那个例子就有这个情况
打开Bottom Sheet 这个例子后
切换其他例子
控制台就能看到这样错误:
![bug](https://user-images.githubusercontent.com/8815759/27868216-aa907680-61ce-11e7-9187-5e75b019535d.png)
触发Bottom Sheet后，就不会报错误了

**Comment by myronliu347** [comment]
#538
