### ISSUE TITLE
@museUITheme is undefined? Whats going on here? I've reverted back to previous version.

### ISSUE THREAD

**Issue by kgrosvenor** [museui/muse-ui#624]
The latest update has caused breaking changes, i tried the new **webpack.base.conf** but that causes all kinds of reference and module errors, can you not keep this the same or please revert it the config to the same way it was as it's seriously not working... and it was much simpler before....

**Comment by dxcqcv** [comment]
最后怎么解决的？回滚？

**Comment by CHENXCHEN** [comment]
i met this problem too, reinstall to 2.0.3 can solve this problem.

**Comment by kgrosvenor** [comment]
i want to upgrade though how do i do this?
