### ISSUE TITLE
GridList中的属性cols和padding的类型报错

### ISSUE THREAD

**Issue by keysple** [museui/muse-ui#625]
GridListAPI中的属性cols和padding设置时，无论是string还是Number类型，都会报错。
这是报错信息：`[Vue warn]: Invalid prop: type check failed for prop "cols". Expected Number, got String.`
`[Vue warn]: Invalid prop: type check failed for prop "padding". Expected Number, got String.
`
code：`<mu-grid-list class="gridlist-demo" cols="3" padding=40>
      <mu-sub-header>XXXX</mu-sub-header>
      <mu-grid-tile v-for="tile, index in BookList" :key="index" titlePosition="bottom">
        <img :src="tile.image"/>
        <span slot="title">{{tile.title}}</span>
        <mu-icon-button slot="action"  />
      </mu-grid-tile>
    </mu-grid-list>`

**Comment by myronliu347** [comment]
不会的，类型就是 Number 绑定String检查就会出错

**Comment by bobliaos** [comment]
在padding前面加上"v-bind:"或者“:”就不会报错了
<mu-grid-list class="gridlist-demo" cols="3" :padding=40>
