### ISSUE TITLE
Date Picker 中的取消按钮是否可以自己增加取消的自定义方法  

### ISSUE THREAD

**Issue by youngchen1987** [museui/muse-ui#626]
Date Picker 中的取消按钮是否可以自己增加取消的自定义方法  ？
我现在的需求是  默认是没有选择任何时间   点击Date Picker可以选择时间   但是我想利用cancel button设置为clear  当点击的时候 我可以清空选中的时间  是否可以？

**Comment by myronliu347** [comment]
目前不提供这种实现，后续可能会增强datePicker 的功能，使之可以自定义一些快捷的方法
