### ISSUE TITLE
主页和文档页面报“不安全的连接”错误，改成HTTP的就没事了。

### ISSUE THREAD

**Issue by hibobby** [museui/muse-ui#627]
是不是证书不对？

**Comment by myronliu347** [comment]
我没有https的域名，等下我去改回来

**Comment by ShanaMaid** [comment]
@myronliu347 可以用国外免费的cloudflare代理一下
我写了个博客，[配置https](https://blog.shanamaid.top/2017/05/02/%E5%8D%9A%E5%AE%A2%E5%B0%8F%E7%BB%BF%E9%94%81%E6%B7%BB%E5%8A%A0%E6%97%A5%E8%AE%B0%E4%B8%8Enginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86/)
但是如果用了cf的话网页加载速度是个问题，这点需要权衡一下

**Comment by myronliu347** [comment]
我这个就是域名映射，没有服务器的，我已经改回来了

**Comment by ShanaMaid** [comment]
@myronliu347 把域名的dns改成自定义解析，把cf分配的2个dns填进去，再把在cf上面添加CNAME就可以。我的博客也是搭在github上的静态页面

**Comment by myronliu347** [comment]
我去试试看
