### ISSUE TITLE
Value in the text-field 

### ISSUE THREAD

**Issue by creepteed** [museui/muse-ui#628]
For some reason I can't bind value to text-field. Any suggestions why ? 

`<mu-text-field fullWidth multiLine :rows="3" :rowsMax="6" :maxLength="100" :value="project.description" v-model="newProject.description" v-else/>`
It defines like that  ` value: ' ' `

Even if I won't bind but just put some string in it , this prop stays like ` value: ' ' `
` <mu-text-field fullWidth multiLine :rows="3" :rowsMax="6" :maxLength="100" value="something here" v-model="newProject.description" v-else/>`

Any help would be appreciated and huge thanks for a good job done in the template guys !

**Comment by myronliu347** [comment]
`value` and `v-model` cannot be used at the same time
