### ISSUE TITLE
Variable @museUiTheme is undefined

### ISSUE THREAD

**Issue by Topthinking** [museui/muse-ui#629]
error  in ./~/_muse-ui@2.1.0@muse-ui/src/textField/textFieldLabel.vue

Module build failed:

@import "@{museUiTheme}";
      ^
Variable @museUiTheme is undefined

**Comment by Topthinking** [comment]
这个怎么回事，怎么解决

**Comment by Topthinking** [comment]
https://github.com/museui/muse-ui/blob/6bdbae5b7bd0947b167076f2bde6f494c648dbe1/src-docs/views/get-stared/usage.md
查看这个已解决
但是还有个问题
我之前在公司电脑上没有配置
{
                loader: 'less-loader',
                options: {
                  globalVars: {
                    museUiTheme: `'${museUiThemePath}'`,
                  }
                }
              }
这个，可以跑的通，在家里就不能跑了？？望解答

**Comment by luozhihua** [comment]
遇到同样的问题

**Comment by luozhihua** [comment]
会不会是 vue-loader 的问题

**Comment by lqzhgood** [comment]
#624
降级到  2.0.3 可用~

<hr/>

**我做了如下尝试**  

用全新的  vue init webpack


按照  [这里的说明](https://github.com/museui/muse-ui/blob/6bdbae5b7bd0947b167076f2bde6f494c648dbe1/src-docs/views/get-stared/usage.md)  进行配置webpack2 。
webpack2 配置说明那里缺了以下代码
```
const path = require('path')
const museUiThemePath = path.join(
  __dirname,
  'node_modules',
  'muse-ui',
  'src/styles/themes/variables/default.less'
)
```
然后在 ./build/vue-loader.conf.js 里面添加 loader
```
var utils = require('./utils')
var config = require('../config')
var isProduction = process.env.NODE_ENV === 'production'

const path = require('path')
const museUiThemePath = path.join(
	__dirname,
	'node_modules',
	'muse-ui',
	'src/styles/themes/variables/default.less'
)
var a = utils.cssLoaders({
	sourceMap: isProduction ?
		config.build.productionSourceMap : config.dev.cssSourceMap,
	extract: isProduction
})
a.less = [
	'vue-style-loader',
	'css-loader',
	{
		loader: 'less-loader',
		options: {
			globalVars: {
				museUiTheme: `'${museUiThemePath}'`,
			}
		}
	}
]

module.exports = {
	loaders: a
}
```

依然无法成功。 降级到 2.0.3 可以通过没有问题~ 求解

**Comment by willnewii** [comment]
试了一下是可以用的.    你们可以打印一下  museUiThemePath  ,看看路径是否正确.   可能需要根据自己的实际目录稍微调整一下.

**Comment by windwander** [comment]
遇到同样问题，打印 museUiThemePath 查看发现确实是路径问题，`__dirname` 进入了build目录，修改下就可以了。
```javascript
const museUiThemePath = path.join(
        __dirname,
        '../node_modules',  // <---- 修改这里，从build目录回到上一级目录
        'muse-ui',
        'src/styles/themes/variables/default.less'
)
```

**Comment by willnewii** [comment]
@dxcqcv 看 你楼上...  或者看你楼上的楼上.  根据你项目的具体情况,修改一下主题指向的路径就行了.   museui是正常的.

**Comment by mcwanderer** [comment]
终于，降级到2.0.3版本不再有这个错误。
npm install --save muse-ui@2.0.3

2.1.0 折腾了一天不行。盼修复~

**Comment by liuwm91** [comment]
降级到2.0.3解决问题了

**Comment by Aliceco** [comment]
解决了，我刚刚写的博客，需要可以帮助到你  http://blog.csdn.net/echo_ae/article/details/77913877
