### ISSUE TITLE
文档写的太简单了，调用的组件名称都没有，小白看着很累…………

### ISSUE THREAD

**Issue by sjcarr** [museui/muse-ui#63]

**Comment by myronliu347** [comment]
每个demo都有可以看源码的

**Comment by hefengxian** [comment]
右上角有个<>这样的符号，点一下源码就出来了！

**Comment by sjcarr** [comment]
可能我太笨了，mintUI比较轻松店

**Comment by myronliu347** [comment]
@sjcarr demo项目正在整理， 使用上有问题可以来[gitter](https://gitter.im/muse-ui/muse-ui) ，我目前大部分时间都在线
