### ISSUE TITLE
安卓端（如微信，或某些安卓机型自带浏览器，安卓版本都在4.4.0以上了）无法显示图标

### ISSUE THREAD

**Issue by HomeEmail** [museui/muse-ui#638]
安卓端（如微信，或某些安卓机型自带浏览器，安卓版本都在4.4.0以上了）无法显示图标

看了生成后的html，图标是使用symbol 表示的，，自己自定义的图标使用fontclass  或 unicode 表示在同样机型同样浏览器上是可以显示图标，，想问下muse ui怎么修复这bug，或者有方法切换图标显示模式吗

**Comment by myronliu347** [comment]
https://material.io/icons/， icon相关的问题可以查看官网解决，使用方式是有两种的
