### ISSUE TITLE
似乎不支持非material的图标

### ISSUE THREAD

**Issue by s51983** [museui/muse-ui#64]
试着用了下Bottom Navigation，发现iconfont的图标不能正常使用。看了下生成的html似乎绑定了material的图标。

**Comment by xiaoluoboding** [comment]
需要在html里引入资源文件的
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
个人建议`npm`安装`material-design-icons`作为本地图标使用。

例如：

```css
@import '~material-design-icons/iconfont/material-icons.css';
```

**Comment by s51983** [comment]
不考虑支持iconfont这种图标库么，毕竟material-design-icons再好也有一堆用不着的，还是iconfont类的自定义图标库更符合实际需求吧。

**Comment by myronliu347** [comment]
后续会考虑吧内部使用的图标改成svg图标，这样就不用强制依赖 material-design-icons，不过目前的版本还是需要

**Comment by myronliu347** [comment]
@s51983 我打算外部图标的都要加个前缀，目前是 `:` 像这样
```html
<icon value=":fa-info"/>
```

你看这样有没有问题

**Comment by s51983** [comment]
@myronliu347 
国外的话 Font Awesome 是这样的 <i class="fa fa-address-book" aria-hidden="true"></i>
国内的话iconfont 是这样的 <i class="iconfont icon-address-book"></i>
其它的用的少不太清楚，muse-ui当前貌似是识别一个不含空格的字符串。如果取巧的话识别下有没有空格，没有的话就用material icons的方法，有的话就设定按只保留value的值。

**Comment by myronliu347** [comment]
加前缀是最保险方式，iconmoon里面的icon都是没有空格的

**Comment by s51983** [comment]
那就OK。

**Comment by myronliu347** [comment]
刚更新版本，在线外部图标加 `:`

**Comment by jaweii** [comment]
不会用iconfont图标

文档里没有补充上啊？

**Comment by myronliu347** [comment]
推荐使用material design icon 所以没加在文档上,非material的图片使用是前面加:

```
<mu-icon value=":fa fa-info"/>
```

**Comment by 1008611** [comment]
@myronliu347   我使用了 font-awesome，就像你上面的写法（<mu-icon value=":fa fa-info"/>），在浏览器里面显示都没问题，但是打包成apk，放手机上就显示不出来了，只显示个☒

**Comment by myronliu347** [comment]
没有将字体文件引入吧,具体在apk中的使用我没有测试过，麻烦提供些详细的信息,或生成的apk的包

**Comment by lgs442874490** [comment]
:action-icon 好像不支持外部引用的icon是吗？<mu-icon value=":iconfont icon-home"/> 只有这种方式支持
