### ISSUE TITLE
文档中Pagination组件的total属性默认值有误

### ISSUE THREAD

**Issue by bigsupersniper** [museui/muse-ui#647]
Pagination组件total的默认值在代码中为：1。但在文档说明时候默认值却为0。这会导致当total初始值为0时首页页码无法选中问题。

**Comment by linxiaowu66** [comment]
@bigsupersniper Hi,
  你的意思是你配置了total的值为0还是说什么都不配置？
  如果是因为文档的误导的话我稍后改一下

**Comment by bigsupersniper** [comment]
我是设置total的初始值为0
然后在页面加载后异步获取列表数据成功后发现首页无法选中。
若将初始值设置为大于0的值，则会正常选中首页页码

**Comment by linxiaowu66** [comment]
@bigsupersniper  这样的话我把文档修改一下，然后再判断传值。多谢了

**Comment by linxiaowu66** [comment]
@myronliu347 可以关闭这个issue了。
