### ISSUE TITLE
slider最小值显示问题

### ISSUE THREAD

**Issue by mokaikai** [museui/muse-ui#65]
当min值大于0时，无法显示在最小值的位置。
```
applyAmount: 0.1
...
<p>申请金额{{applyAmount}}元</p>
<mu-slider v-model="applyAmount" :min="0.1" :max="3"/>
```
<img width="395" alt="screen shot 2016-11-19 at 16 03 30" src="https://cloud.githubusercontent.com/assets/11897616/20454147/4b7e51a4-ae72-11e6-8d9d-97f6b9aa5b60.png">

想用jsfiddle的，找不到cdn

**Comment by myronliu347** [comment]
你可以用

https://unpkg.com/muse-ui@2.0.0-alpha.7/dist/muse-ui.js
https://unpkg.com/muse-ui@2.0.0-alpha.7/dist/muse-ui.css

**Comment by mokaikai** [comment]
@myronliu347 
https://jsfiddle.net/cxmokai/Ls42v2se/

**Comment by myronliu347** [comment]
嗯，多谢，我已经修复，会在这两天发下一个版本

**Comment by myronliu347** [comment]
在 2.0.0.alpha.8 版本修复，请更新
