### ISSUE TITLE
datePicker和timePicker的inline模式问题

### ISSUE THREAD

**Issue by chenqf6** [museui/muse-ui#652]
picker在container=inline模式下，通过点击textField 打开popover再点击textField关闭后，会出现再次点击无相应的情况。

查看审查元素窗口后发现，popover已经存在了但大小为0

![screenshot from 2017-07-20 12 15 52](https://user-images.githubusercontent.com/11461777/28400369-391c777e-6d45-11e7-8ccc-679e95b751c2.png)

查看代码后发现，每次点击textField他都执行一次openDialog导致重复创建Calendar

至于是怎么导致不可再次点击，暂时没查出来

但按照代码逻辑，无论是inline模式还是dialog模式都会出现这样的问题，只是dialog模式在界面上没办法再次点击textField所以没有出现这样的问题。

**Comment by Hanruis** [comment]
遇到了同样的问题。

**Comment by chenqf6** [comment]
2个月了大神，修复一下拉(ง •̀_•́)ง

**Comment by Hanruis** [comment]
@chenqf6  尝试提个 pr 给作者吧。
