### ISSUE TITLE
图标在线地址不稳定，有没有国内的资源？

### ISSUE THREAD

**Issue by gyzwang** [museui/muse-ui#655]
fonts.gstatic.com/s/materialicons/v22/2fcrYFNaTjcS6g4U3t-Y5RV6cRhDpPC5P4GCEJpqGoc.woff:1 GET https://fonts.gstatic.com/s/materialicons/v22/2fcrYFNaTjcS6g4U3t-Y5RV6cRhDpPC5P4GCEJpqGoc.woff net::ERR_QUIC_PROTOCOL_ERROR

**Comment by ShanaMaid** [comment]
可以下载到本地
