### ISSUE TITLE
老哥，你这个UI框架真的太多BUG了。无力吐槽。。。

### ISSUE THREAD

**Issue by 5SSS** [museui/muse-ui#674]
dom嵌套能不能在深一点。
table表格用起来很麻烦。
用了你在框架，简直就神坑。。。
我已经没有退路了。
只能重构。。

**Comment by lupuxyz** [comment]
反对+没有帮助系列   🌸🐔

**Comment by ShanaMaid** [comment]
UI框架如果有BUG欢迎提issue或者pr进行完善，一味地吐槽没有任何意义。
如果对你的工作带来了不便，对此表示抱歉。
