### ISSUE TITLE
radio 和switch的v-model 类型通常为整型,但museui中必须强制传入string和boolean,希望能够做点修改

### ISSUE THREAD

**Issue by ukton11123** [museui/muse-ui#677]
radio 和switch的v-model 类型经常传入0,1这样的整型数值,但museui中必须强制传入string和boolean,
但v-model中又无法写成.toString() 希望兼容number类型

**Comment by myronliu347** [comment]
获取的时候转换一下就好了 `Number(true)`

**Comment by fy0** [comment]
@myronliu347  同样问题 附议
