### ISSUE TITLE
Autocomplete on iOS

### ISSUE THREAD

**Issue by chrisfromneptune** [museui/muse-ui#678]
The dropdown with Autocomplete on iOS 10.3.3 iPhone 6+ often isn't aligned vertically correctly - using the docs example - it is often off vertically.
On iOS 9.3.5 it is worse - often off screen 

Any ideas on how to fix?

**Comment by myronliu347** [comment]
Please write online demo https://jsfiddle.net/

**Comment by chrisfromneptune** [comment]
The documentation site reproduces it:
 1) load docs and see it is not aligned correctly on mentioned device
