### ISSUE TITLE
当前存在的一些问题和建议

### ISSUE THREAD

**Issue by zhangzicao** [museui/muse-ui#679]
先说说问题
1、手机端滚动时的触摸会触发波纹效果，特别是list.item的，手机端可能照成滚动的卡顿
2、Infinite Scroll组件当第一次加载时，若长度不够没有生成滚动条（ipad里有可能），继续下拉并不会触发下拉加载更多。目前只能通过添加个加载更多的按钮避免这种情况，无奈
2、Infinite Scroll组件当第一次加载时，若长度不够没有生成滚动条（ipad里有可能），继续下拉并不会触发下拉加载更多。目前只能通过添加个加载更多的按钮避免这种情况，无奈

组件建议：
1、datepicker的日历插件可以提取出来，加些新属性和事件。最近做了个日历事件，还是自己提取出来做了修改的。。另外提取出来后，可以和input框间解耦，像要做点击列表项弹窗选择日期的功能就方便多了，不用写个隐藏的datepicker加个label强行触发隐藏的input了
2、card布局太少了，可用性太低，推荐新增slot和props，样式可以参考Vue Material的card组件

**Comment by Sulsummer** [comment]
Hi,
问题第一条我想做个补充。
手机浏览器里面，如果一个页面连续的input很多，在滑动页面的时候会感觉到卡。手指在input的区域内（还没有focus）试图滑动页面，就会出现这个情况。是否可以优化？

**Comment by eric0115** [comment]
First, I am really happy to have this choice when deciding to choose a third ui-framework. When experienced a few days in my project , I made a decision to code all the components rather than use muse-ui. In a word, it is so hard to use. I am so sorry for muse-ui team.
