### ISSUE TITLE
按需加载的时候总是报错说找不到,全局加载又没问题

### ISSUE THREAD

**Issue by TOBOM** [museui/muse-ui#681]
These dependencies were not found:

* muse-ui/src/appBar in ./src/views/photo/index/index.js
* muse-ui/src/avatar in ./src/views/photo/index/index.js
* muse-ui/src/styles/base.less in ./src/views/photo/index/index.js

To install them, you can run: npm install --save muse-ui/src/appBar muse-ui/src/
avatar muse-ui/src/styles/base.less

**Comment by DearAKuan** [comment]
我和你也是一样的问题 老哥你解决了吗 q  844_591_ 473

**Comment by TOBOM** [comment]
@DearAKuan 没有....看之前关闭的提问里有回答,但是不知道那位老哥怎么解决的

**Comment by DearAKuan** [comment]
@TOBOM 好吧。。实在不想全局加载  打包文件太大了。。

**Comment by returnjinx** [comment]
老铁 解决了没

**Comment by pasturn** [comment]
#412 
```
npm install  less less-loader --save-dev
```
