### ISSUE TITLE
Text Field作搜索框时，我无法在输入框内部右边定制个用来清空内容的小叉叉

### ISSUE THREAD

**Issue by huziyang410** [museui/muse-ui#685]
用自带的api没有点击事件接口，自己往里面塞一个，又输入无效。建议开个api接口，可以弄个清空内容的小叉叉。

**Comment by huziyang410** [comment]
![image](https://user-images.githubusercontent.com/8708824/29350474-531adc68-8291-11e7-8881-e311f06a5a70.png)
此时我不能输入

**Comment by huziyang410** [comment]
建议加个自动聚焦

**Comment by myronliu347** [comment]
可以通过自定义样式，作出这种样子的，聚焦目前只能通过手动操作dom聚焦
