### ISSUE TITLE
muse-ui.js这个文件有未压缩的版本嘛

### ISSUE THREAD

**Issue by DearAKuan** [museui/muse-ui#688]
因为下拉框组件屏幕高度不够的时候，下拉框会自动跑到屏幕上面去，产品部的必须要要求改到下面去，现在muse-ui.js这个文件是压缩的 我这不好改呀

**Comment by myronliu347** [comment]
没有未压缩的版本，源码都在src中，你可以选择fork，最近都没上github了，回复有点晚，不好意思
