### ISSUE TITLE
mu-tabs的z-index层级有点低

### ISSUE THREAD

**Issue by s51983** [museui/muse-ui#69]
mu-tabs使用fixed悬浮在页面顶端时由于z-index较低导致其它控件在滑动后会覆盖在mu-tabs上面。

**Comment by myronliu347** [comment]
会在这两天修复并发布新版本，现在请使用

```html
<mu-tabs style="z-index: 100;" >
</mu-tabs>
```

**Comment by myronliu347** [comment]
已在 [2.0.0-alpha.9](https://museui.github.io/#/changeLog) 中修复，请更新

**Comment by i2Echo** [comment]
@myronliu347 在项目文档中这个bug还未修复，https://www.muse-ui.org/#/tabs依然还出现了覆盖

**Comment by myronliu347** [comment]
现在的默认层级是100，后续如果会有覆盖问题，可以自行设置zIndex
