### ISSUE TITLE
Discrete Sliders

### ISSUE THREAD

**Issue by delaneyj** [museui/muse-ui#693]
[The Material Design guideline has a section of discrete sliders. ](https://material.io/guidelines/components/sliders.html#sliders-discrete-slider) Is there a way to combine badge and slider to generate a discrete slider?

![image](https://user-images.githubusercontent.com/438252/29622977-b8f46124-87d9-11e7-86d3-11279432141d.png)

**Comment by myronliu347** [comment]
Yes, we will update slider.

**Comment by delaneyj** [comment]
Great news, thanks! 👍 👍

**Comment by myronliu347** [comment]
https://www.muse-ui.org/#/zh-CN/slider
