### ISSUE TITLE
怎么使用less变量啊

### ISSUE THREAD

**Issue by yb3616** [museui/muse-ui#697]
不是配置全局的主题，就是单纯地想用你的less变量来高亮一些自己写的组件，不想用#FFF这样直接写死。看了看没找到此类说明。

已安装less less-loader
npm install --save-dev less less-loader

组件中已做如下修改：
<style lang="less">

然后我应该怎么做?

**Comment by myronliu347** [comment]
正常引入变量文件 src/styles/import.less
