### ISSUE TITLE
mu-icon-button click not firing 

### ISSUE THREAD

**Issue by yangwenhaowenhe** [museui/muse-ui#703]
`<div v-show="showStatus == 'mini'" class="bottomPlayer" @click.self="switchPlayerStatus">
                <div class="imgContainer">
                    <img :src="playingMusic.picUrl" />
                </div>
                <mu-icon-button @click.self="handlePlay" color="teal">
                    <i :class="playing ? 'iconfont icon-pause': 'iconfont icon-play'"></i>
                </mu-icon-button>
 </div>`

`handlePlay(e) {
            console.log('handlePlay called: ', audio.paused)
            ...
  }`

handlePlay not being called when i click button ,what's wrong ?

**Comment by myronliu347** [comment]
Please provide online example, https://jsfiddle.net/
