### ISSUE TITLE
下拉时无法使用嵌套菜单

### ISSUE THREAD

**Issue by wangzaiyi** [museui/muse-ui#709]
在menu组件里使用多级的嵌套菜单没问题，但是菜单改为下拉后，嵌套的菜单就就没法点击弹出二级菜单，变成普通的菜单项了，点击直接缩回去了。。。

**Comment by wangzaiyi** [comment]
自己用menu和点击事件写了一个，希望官方能补全这个功能啊，对于内容很多的下拉框，有个多级菜单做分类是非常必要的

**Comment by myronliu347** [comment]
请提供在线示例，模拟出错情况
https://jsfiddle.net/
