### ISSUE TITLE
select中当一个item文本太长的时候，显示重叠

### ISSUE THREAD

**Issue by mokaikai** [museui/muse-ui#72]
```
<mu-select-field v-model="" >
  <mu-menu-item value="0" title="已婚已婚已婚已婚已婚已婚已婚已婚"/>
  <mu-menu-item value="1" title="未婚"/>
  <mu-menu-item value="2" title="离异"/>
</mu-select-field>
```
![screen shot 2016-11-21 at 19 30 47](https://cloud.githubusercontent.com/assets/11897616/20481291/592f540a-b021-11e6-9d00-8947f9fbfb44.png)

**Comment by myronliu347** [comment]
已在 [2.0.0-alpha.9](https://museui.github.io/) 中修复，请更新
