### ISSUE TITLE
TypeError: Cannot read property 'scrollTop' of undefined

### ISSUE THREAD

**Issue by alexey-baranov** [museui/muse-ui#721]
hello!

I just update muse-ui in my project and get this error right after any scroll action. There is very short stacktrace and no option to debug it.

> muse-ui.js:9 Uncaught TypeError: Cannot read property 'scrollTop' of undefined
>     at VueComponent.onScroll (muse-ui.js:9)
>     at VueComponent.boundFn [as onScroll] (vue.common.js:185)
>     at _handleScroll (muse-ui.js:9)

**Comment by alexey-baranov** [comment]
After short research i found this is `mu-infinite-scroll` bug

Error does not appeared after commenting this line 
'''html
<mu-infinite-scroll :loading="areKopiLoaded" loadingText="Подождите..." @load="scroll_load"/>
```

**Comment by huziyang410** [comment]
the same error

**Comment by sombriks** [comment]
hi, 

i can confirm the very same bug, even if i define scroller to a valid html element.

```html
<mu-infinite-scroll :scroller="scroller" :loading="loading" loadingText="carregando" @load="paginacao(1)"/>
```

```javascript
// ...
  created() {
    this.paginacao()
    this.lastup = new Date().getTime() + 6000
  },
  mountde() {
    this.scroller = document.body
  },
  methods: {
    paginacao(p) {
// ...
```

**Comment by myronliu347** [comment]
fixed
