### ISSUE TITLE
pagination:  Current  出现bug了

### ISSUE THREAD

**Issue by HZZformGD** [museui/muse-ui#726]
![image](https://user-images.githubusercontent.com/26340739/30312001-4ddf2134-97ca-11e7-9ce9-a2edbe2b9bdf.png)

![image](https://user-images.githubusercontent.com/26340739/30311943-139a59d0-97ca-11e7-8f66-0ffe58be91ac.png)
![image](https://user-images.githubusercontent.com/26340739/30311970-2c95c140-97ca-11e7-9052-54e6540eb118.png)

在vue-developer tools 看到的 data 和props 如图1  current 接收到了 1   我看了下pagination源码 然后后加了一个 || 1   依旧是没效果的   图三是我  在vue使用pagination的详细代码

```
<template lang="html">
  <mu-pagination :total="total" :current="current" :defaultPageSize="limit"   @pageChange="changePage">
  </mu-pagination>
</template>

<script>
export default {
  props: ['limit','total'],
  data () {
    return {
      current: 1
    }
  },
```

**Comment by HZZformGD** [comment]
@myronliu347 @linxiaowu66

**Comment by linxiaowu66** [comment]
Hi @HZZformGD 
 能否贴个demo吗？

**Comment by HZZformGD** [comment]
@linxiaowu66   这几天 都在忙搬家 没时间回复你 抱歉哈   我现在来贴一下代码
父组件 引用
```
      <div class="page">
        <Pager @getArt="getArticle" current=1 :limit="limit" :total="total"></Pager>
      </div>
```
子组件也就是pagination 

```
<template lang="html">
  <mu-pagination :total="total" :current="current" :defaultPageSize="limit"   @pageChange="changePage">
  </mu-pagination>
</template>

<script>
export default {
  props: ['limit', 'total'],
  data () {
    return {
      current: 1
    }
  },
  computed: {
  },
  created () {
    console.log(this)
  },
  methods: {
    changePage (page) {
      this.$emit('getArt', page)
    }
  }
}
</script>
```

**Comment by linxiaowu66** [comment]
@HZZformGD 
那最后你想说的问题是currentPage不对？等于0？

**Comment by HZZformGD** [comment]
@linxiaowu66  就是默认情况下     第一页不是active 状态    都是灰色的 而不是主题的颜色

**Comment by linxiaowu66** [comment]
@HZZformGD 
  我的代码如下：
```
<template>
  <mu-pagination :total="total" :current="current" @pageChange="handleClick" :defaultPageSize="3">
  </mu-pagination>
</template>

<script>
export default{
  data () {
    return {
      total: 4,
      current: 1
    }
  },
  methods: {
    handleClick (newIndex) {
    }
  }
}
</script>

```

Vue devtool：

![selection_004](https://user-images.githubusercontent.com/13563876/30791560-dd808d76-a1e5-11e7-8f3c-0e274c349632.jpg)

但是没发现你的那个问题诶，应该是有某个我没注意到的因素，你再检查一下，然后告知一下 多谢哈
