### ISSUE TITLE
how to focus <mu-text-field>?

### ISSUE THREAD

**Issue by alexey2baranov** [museui/muse-ui#728]
Hello! How we can focus `<mu-text-field>` programmatically?

**Comment by HumiH** [comment]
html:
``` html
<mu-text-field ref="textField" v-model="input"/>
```
js:
``` javascript
this.$refs.textField.focus()
```

**Comment by ChadSmith2020** [comment]
I had to drill down to put focus to the input element:
        this.$refs.textField.$el.firstChild.firstChild.focus();
