### ISSUE TITLE
museUI 在vue中怎么使用cdn？

### ISSUE THREAD

**Issue by zhuqitao** [museui/muse-ui#735]
你好，我现在是因为vue打包的时候vendor文件太大，所以不想把muse也打包进去。

我是在vue的index.html文件引入
<link href="https://unpkg.com/muse-ui@2.1.0/dist/muse-ui.css" />
<script src="https://unpkg.com/muse-ui@2.1.0/dist/muse-ui.js" />
然后在webpack设置
 externals: {
    'MuseUI': 'MuseUI'
  },
那么我怎样全局引用museUI呢？要在每个.vue组件中都加上import MuseUI from 'MuseUI' 吗？

**Comment by linxiaowu66** [comment]
你的webpack的entry文件中import就行了

**Comment by zhuqitao** [comment]
具体怎么引用可以给个代码示例吗？

**Comment by linxiaowu66** [comment]
```
// global register
Vue.use(MuseUI);
```

**Comment by myronliu347** [comment]
#736
