### ISSUE TITLE
异步加载组件后，主题被覆盖

### ISSUE THREAD

**Issue by wangzaiyi** [museui/muse-ui#737]
组件加载完成后加载主题CSS可以正常显示主题的颜色。
但是主题CSS加载完成后，异步加载其他组件（webpack），会导致主题被覆盖，显示默认的紫色。

**Comment by wangzaiyi** [comment]
看了一下，应该是没有专门针对主题设计CSS的权重，异步加载的组件CSS（使用默认颜色，CSS的顺序在后）覆盖了前面已经加载好的CSS（使用主题颜色，CSS的顺序在前）

只好暂时先修改了默认的主题颜色解决了。。

**Comment by pyyzcwg2833** [comment]
@wangzaiyi 请问你是如何异步加载组件的呢，能看一些代码么

**Comment by myronliu347** [comment]
嗯嗯是的，所以 muse-ui的组件最好再全局引入使用

**Comment by myronliu347** [comment]
目前的方法只能是想办法，提升主题的权值
