### ISSUE TITLE
backTop 没有效果

### ISSUE THREAD

**Issue by TiggerYuan** [museui/muse-ui#739]
连官网的演示也没有

**Comment by ShanaMaid** [comment]
@TiggerYuan 应该是你浏览器视窗太大了，无法触发backtop的出现条件，你把浏览器的高度拉小点，知道视窗Y轴出现滚动条，滚动一下应该就能触发了。

**Comment by TiggerYuan** [comment]
这个一开始就试过了，也是没有的

**Comment by szj1006** [comment]
+1，backTop 没有效果，官网的演示也没有，添加后只出现`<!---->`

**Comment by J3DFox** [comment]
在低版本的CHROME或者IE可能触发backtop 
最近升级到chrome 62.0.3202.75 以后 backtop无法触发

**Comment by myronliu347** [comment]
https://github.com/museui/muse-ui/blob/master/docs/src/components/back-top.js
