### ISSUE TITLE
Text Field multiLine设置rowsMax的问题

### ISSUE THREAD

**Issue by ccchangkong** [museui/muse-ui#74]
rows属性应该是类似或`height`，那rowsMax应该是类似`max-height`的效果吧？
![image](https://cloud.githubusercontent.com/assets/13186101/20482398/74b79ca4-b027-11e6-87af-73d2722e1e3e.png)
官网的例子，设置了rowsMax但textarea依旧能拉的很长，问题就是没体现出`max-height`的效果。
另外，方便实现一个设置显示行数随输入增加的属性么（比如设置了:rows="3" :rowsMax="6"后能实现输入行数超过3行后增加显示行数至6行，相当于rows决定`min-height`）
麻烦了！

**Comment by myronliu347** [comment]
rowsMax不设置默认就是高度随输入的内容而增加，
不过window上rowsMax属性似乎有问题，我会尽快修复

**Comment by myronliu347** [comment]
刚看了下确实有问题，会在这两天修复，请稍等

**Comment by ccchangkong** [comment]
@myronliu347 多谢啦

**Comment by myronliu347** [comment]
已在 [2.0.0-alpha.9](https://museui.github.io/#/textField) 中修复，请更新
