### ISSUE TITLE
Pagination 组件问题，刷新页面会触发pageChange事件，并且返回的默认值1，刷新页面设置设置current值无效

### ISSUE THREAD

**Issue by kang558** [museui/muse-ui#742]
Pagination 组件问题，刷新页面会触发pageChange，并且返回的默认值1，刷新页面设置设置current值无效。我是想通过地址栏的参数来设置当前页面的值的，也就是说用户刷新浏览器的时候还可以保留当前的页面的页码。但是我发现刷新浏览器时会触发pageChange，返回了默认页面1；因为我在pageChange事件中也设置了路由跳转【页面跳转】，导致了刷新浏览器路由就会跳转到第一页

**Comment by linxiaowu66** [comment]
你不能通过设置current这个属性为你指定的页面吗？  如果你设置current=5的时候刷新浏览器会停留在第5页上面的。

**Comment by kang558** [comment]
@linxiaowu66 设置了也不行啊，刷新浏览器又回到默认的第1页了，因为触发了pageChange事件

**Comment by linxiaowu66** [comment]
能给个demo吗？

**Comment by kang558** [comment]
@linxiaowu66  [demo在GitHub上，点击这里查看，我重现了这个情况](https://github.com/kang558/vue-test)

问题我几经解决了，就是设置默认的初始total值不能小于后端API返回的真实total值。。。不然会出现上述情况。
