### ISSUE TITLE
lang="less"时，设置Popup的样式无效

### ISSUE THREAD

**Issue by Kinghts** [museui/muse-ui#743]
````
<mu-popup position="bottom"  popupClass="popup-reply">
</mu-popup>

<style lang="less" scoped>
   .popup-reply { 
      width: 100%; 
      min-width: 400px; 
  } 
</style> 
````

在浏览器中查看，发现popup-reply已经在class里了，但是设置的样式没有

**Comment by Kinghts** [comment]
去掉scoped就生效了，不知道有没有其他的办法

**Comment by zhongyi12** [comment]
我最近也在纳闷这个问题，组件里写了scoped定义了局部样式，Muse-UI的某些样式就修改不了

**Comment by Kinghts** [comment]
@zhongyi12 只好自己写了个popup和overlay组件

**Comment by ShareQiu1994** [comment]
scoped 是当前组件内的样式生效  mu-popup是museui定义好的其他组件   一般情况不能用你当前的vue组件文件写其他组件的样式  建议你在APP.vue文件 写全局less
