### ISSUE TITLE
动态主题文档写错了，

### ISSUE THREAD

**Issue by kang558** [museui/muse-ui#746]
[官网的文档这样写会报错。](http://www.muse-ui.org/#/theme)  ![image](https://user-images.githubusercontent.com/22288837/30847161-12f7e7c8-a2cd-11e7-8319-0ee3f18d6212.png)
实际写法这样才对
![image](https://user-images.githubusercontent.com/22288837/30847233-59f5c244-a2cd-11e7-8817-07fc827f5af9.png)
前几天排查好久才知道这个引入是这样写的，对于新手来说真不容易啊！这个库很好用。

**Comment by weituotian** [comment]
@kang558 我引入了这个carbon主题
```
import Vue from 'vue'
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
import 'muse-ui/dist/theme-carbon.css' // 使用 carbon 主题
Vue.use(MuseUI)
```

怎么在carbon的基础上修改appbar的color
不是在default的主题上，我只改appbar的color这一个，不想重写carbon的所有变量，
carbon的主题变量也找不到在哪个文件了
