### ISSUE TITLE
dialog中添加组件 为什么会闪一下才渲染 ？

### ISSUE THREAD

**Issue by ShareQiu1994** [museui/muse-ui#747]
<mu-dialog :open="searchDialog"  @close="searchClose" bodyClass='searchDialog' > 
         <mu-text-field  hintText="请输入地名或经纬度查询" fullWidth icon="search" v-model="srarchText" @keyup.native.enter="searchText"/><br/>
         <mu-raised-button  slot="actions" @click="searchText" class="demo-raised-button" label="搜索" icon="touch_app" primary/>
    </mu-dialog>

如题 按钮会从有渲染一闪的过程  是否是因为远程icon的原因？？

**Comment by ShareQiu1994** [comment]
![image](https://user-images.githubusercontent.com/19948086/30852405-40a0a474-a2de-11e7-93e3-2809f3cc0767.png)

**Comment by myronliu347** [comment]
目前本体调试中并未发现一闪的过程，请给出在线demo，方便我调试查找问题
