### ISSUE TITLE
picker默认选中bug

### ISSUE THREAD

**Issue by RunningV** [museui/muse-ui#749]
1.问题描述：
 当循环出的`values`是一个数组对象时每个`item`必须包含item.text的值才能显示（不知道这样的设计是否合理？），但是这样无法自定义选中项
看了下picker的源码有一段如下：
```
<div v-if="!divider" class="mu-picker-slot-wrapper" :class="{'animate': animate}" :style="{'height': contentHeight + 'px'}" ref="wrapper">
      <div class="mu-picker-item" :style="{'text-align': textAlign}" :class="{'selected': item === value}"
      v-for="item, index in values" :key="index">{{item.text || item}}</div>
    </div>
```

2. 那么` :class="{'selected': item === value}"`是否应该写成` :class="{'selected': item === value || item.text === value}"` 不然默认选中失效，希望修复下，或者考虑下当循环的是数组对象时的更好实现方式。

**Comment by J3DFox** [comment]
我也遇到这个问题了,当循环一个数组对象的时候 默认选择 不会显示出来
