### ISSUE TITLE
Feature Request: Fill timeline icon completely with given background color

### ISSUE THREAD

**Issue by kgrosvenor** [museui/muse-ui#752]
i would like to see something where i can completely fill the background of the icon circle, i can do with css but it would make a good feature.

Spoken api could be like so: 

```
 <mu-timeline-item iconColor="red" backgroundColor="red" iconType="solid">
     <span>Time line item</span>
 </mu-timeline-item>
```

**Comment by myronliu347** [comment]
You can resetset css to change style
