### ISSUE TITLE
Add mu-icon to mu-toast/mu-snackbar

### ISSUE THREAD

**Issue by fergardi** [museui/muse-ui#754]
I know is not part of the Material Design spec, but a simple icon addition will bring much more information to the user. It won't be hard to develop, just in case someone needs it.

`mu-toast(:icon="done", message="Success!")`
`mu-snackbar(:icon="done", message="Success!")`

![image](https://user-images.githubusercontent.com/3602272/31162500-24eda230-a8de-11e7-8759-59d3d7b5e287.png)

**Comment by myronliu347** [comment]
Thanks, I will improve

**Comment by myronliu347** [comment]
https://www.muse-ui.org/#/zh-CN/snackbar
