### ISSUE TITLE
最新本Vue-cli使用单组件加载问题？

### ISSUE THREAD

**Issue by ShareQiu1994** [museui/muse-ui#755]
main.js文件：

import Vue from 'vue'
import App from './App'
import router from './router'

import 'muse-components/styles/base.less' // 加载基础的样式
import appBar from 'muse-components/appBar'
Vue.component(avatar.name, avatar)

Vue.config.productionTip = false
/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})

webpack.base.conf.js 文件：

'use strict'
const path = require('path')
const utils = require('./utils')
const config = require('../config')
const vueLoaderConfig = require('./vue-loader.conf')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
       'muse-components': 'muse-ui/src'
    }
  },
  module: {
    rules: [
      {
        test: /muse-ui.src.*?js$/,
        loader: 'babel-loader'
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}

出错问题：
@import "@{museUiTheme}";
      ^
Variable @museUiTheme is undefined
      in F:\museUi\node_modules\_muse-ui@2.1.0@muse-ui\src\styles\import.less (line 1, column 8)

 @ ./node_modules/_vue-style-loader@3.0.3@vue-style-loader!./node_modules/_css-loader@0.28.7@css-loader?{"minimize":false,"sourceMap":false}!./node_modules/_vue-loader@13.0.5@vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2a938066","scoped":false,"hasInlineConfig":false}!./node_modules/node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":false}!./node_modules/_vue-loader@13.0.5@vue-loader/lib/selector.js?type=styles&index=0!./node_modules/_muse-ui@2.1.0@muse-ui/src/appBar/appBar.vue 4:14-442 13:3-17:5 14:22-450
 @ ./node_modules/_muse-ui@2.1.0@muse-ui/src/appBar/appBar.vue
 @ ./node_modules/_muse-ui@2.1.0@muse-ui/src/appBar/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

这个是什么原因？

**Comment by gitzhang** [comment]
我也出现了同样的问题，不知道你解决了吗？

**Comment by myronliu347** [comment]
less-loader需要增加全部变量 
{
                loader: 'less-loader',
                options: {
                  globalVars: {
                    museUiTheme: `'${museUiThemePath}'`,
                  }
                }
              }
