### ISSUE TITLE
icon在安卓的微信、QQ内置浏览器中不显示

### ISSUE THREAD

**Issue by aaron0713** [museui/muse-ui#757]
mu-icon-button
按钮图标不显示

pc显示正常，模拟移动端也正常

苹果 微信、QQ、原生浏览器显示正常
安卓 原生浏览器显示正常。
只有【安卓 微信、QQ】上不显示。
求解决方案。

**Comment by XShire** [comment]
@aaron0713 我的也是，你现在解决了吗？

**Comment by aaron0713** [comment]
@XShire 没有啊

**Comment by XShire** [comment]
@aaron0713 使用本地图标就好了，不知道为什么在其他端都可以用，安卓上就不可以

**Comment by aaron0713** [comment]
@XShire 
加两个CSS属性解决了
.material-icons{
        text-rendering: optimizeLegibility;
        font-feature-settings: 'liga' 1;
    }
