### ISSUE TITLE
[Violation] Non passive event listener

### ISSUE THREAD

**Issue by fergardi** [museui/muse-ui#761]
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

![image](https://user-images.githubusercontent.com/3602272/31576365-d1b57b32-b0f9-11e7-8f1b-8d106e103f4c.png)

How to solve?

**Comment by fergardi** [comment]
> Passive event listeners are an emerging web standard, new feature shipped in Chrome 51 that provide a major potential boost to scroll performance. Chrome Release Notes.
> It enable developers to opt-in to better scroll performance by eliminating the need for scrolling to block on touch and wheel event listeners.

> Problem: All modern browsers have a threaded scrolling feature to permit scrolling to run smoothly even when expensive JavaScript is running, but this optimization is partially defeated by the need to wait for the results of any touchstart and touchmove handlers, which may prevent the scroll entirely by calling preventDefault() on the event.

> Solution:- {passive: true}

> By marking a touch or wheel listener as passive, the developer is promising the handler won't call preventDefault to disable scrolling. This frees the browser up to respond to scrolling immediately without waiting for JavaScript, thus ensuring a reliably smooth scrolling experience for the user.

> ```
> addEventListener(document, "touchstart", function(e) {
>     console.log(e.defaultPrevented);  // will be false
>     e.preventDefault();   // does nothing since the listener is passive
>     console.log(e.defaultPrevented);  // still false
>   }, Modernizr.passiveeventlisteners ? {passive: true} : false);
> ```

Source: https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners

**Comment by fergardi** [comment]
It can be solved using https://github.com/zzarcon/default-passive-events

See https://github.com/zzarcon/default-passive-events/issues/7

**Comment by myronliu347** [comment]
Thanks! I'll think about it
