### ISSUE TITLE
TextField : how to use  floatlabel only?

### ISSUE THREAD

**Issue by donaldlulu** [museui/muse-ui#769]
I want there is label at start, and it disappears when focused.  HintText is different to this, it displays when focused. How to remove the label when focused ?

**Comment by donaldlulu** [comment]
Setting labelFocusClass to "dsiplay: none"  won't work, since  when there is some words input to the field, and then loss focus, the label will appear again.

**Comment by myronliu347** [comment]
Please give me some demo code...
