### ISSUE TITLE
修改了源码组件内部的prop参数类型不生效？

### ISSUE THREAD

**Issue by ShareQiu1994** [museui/muse-ui#770]
![image](https://user-images.githubusercontent.com/19948086/31850095-8bb6f486-b67f-11e7-99c4-81144f3ccb77.png)
![image](https://user-images.githubusercontent.com/19948086/31850105-a45fe344-b67f-11e7-879c-bbd4b243ac92.png)
这个是 怎么回事呢 网上说必须编译下 请问下如何重新编译muse-ui？

**Comment by myronliu347** [comment]
如果是单组件引入是不需要,但是不建议直接修改，这样当重装时又会被覆盖
