### ISSUE TITLE
Ripple not working with the electron-vue template

### ISSUE THREAD

**Issue by SylvainMarty** [museui/muse-ui#772]
Hi everyone,

I'm facing an issue with the ripple animation in a project started with the [electron-vue](https://github.com/SimulatedGREG/electron-vue) boilerplate.

The ripple doesn't show on any component (list items, buttons, etc.).

Here is the setup of the Vue app (the `main.js` file) : 
```js
import Vue from 'vue'
import MuseUI from 'muse-ui'
import 'muse-ui/dist/muse-ui.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import 'roboto-fontface/css/roboto/roboto-fontface.css'
import App from './App'
import router from './router'
import store from './store'

if (!process.env.IS_WEB) Vue.use(require('vue-electron'))
Vue.config.productionTip = false

Vue.use(MuseUI)

/* eslint-disable no-new */
new Vue({
  components: { App },
  router,
  store,
  template: '<App/>'
}).$mount('#app')
```

As you can see, I use two more plugins : **vue-router** and **Vuex**.
The app need to be used without internet so I didn't use Google's CDN to load Roboto fonts and Material Design Icons. However, I tried without them but it didn't fix anything...

For the layout, I tried to copy/paste the exact snippet of the layout called [`Sider Layout`](http://www.muse-ui.org/#/layout) in the doc but the ripple effect still didn't show up.

Did someone know what I am doing wrong ?

PS : English is not my native language so sorry for the spelling...

**Comment by myronliu347** [comment]
Please give you use components code
