### ISSUE TITLE
Mu-back-top not working

### ISSUE THREAD

**Issue by fergardi** [museui/muse-ui#776]
I cannot get it to work. I don't even see it working in the [example page](http://www.muse-ui.org/#/backTop).

**Comment by J3DFox** [comment]
same to me!
it doesn't work on chrome 62.0.3202.75
but worked on others, IE, edge , chrome 49

**Comment by myronliu347** [comment]
https://github.com/museui/muse-ui/blob/master/docs/src/components/back-top.js
