### ISSUE TITLE
BottomNavigation图标不可用自定义嘛,只能用谷歌字体图嘛?

### ISSUE THREAD

**Issue by lhalcyon** [museui/muse-ui#779]
如题

**Comment by hjdtl** [comment]
@lhalcyon 
以下代码可以显示第三方icon，我使用的是阿里巴巴的icon。要点就是[ iconClass="iconfont icon-rfqquantity" icon=" "]，1. iconClass里面添加阿里巴巴的icon class名，2. icon属性为" "。
`<mu-paper class="bottom">
      <mu-bottom-nav :value="bottomNav" @change="bottomHandleChange ">
        <mu-bottom-nav-item value="recents" title="Recents" iconClass="iconfont icon-rfqquantity" icon=" "/>
        <mu-bottom-nav-item value="favorites" title="Favorites" iconClass="iconfont icon-clock" icon=" "/>
        <mu-bottom-nav-item value="nearby" title="Nearby" iconClass="iconfont icon-account" icon=" "/>
        <mu-bottom-nav-item value="info" title="info" iconClass="iconfont icon-all" icon=" "/>
      </mu-bottom-nav>
    </mu-paper>`
