### ISSUE TITLE
关于date-picker遮盖层的问题

### ISSUE THREAD

**Issue by ccchangkong** [museui/muse-ui#78]
![image](https://cloud.githubusercontent.com/assets/13186101/20516904/bd6779ea-b0d3-11e6-9c4c-44d34ff84c23.png)
像图上这样，已经有一个带遮盖层的弹窗出现，弹窗里再打开非内联的日期选择器，变成了原页面->遮蔽层->弹窗->日期选择器，在这种情形下是可以直接按到弹窗的关闭按钮的，然后弹窗和日期选择器关闭，但还留着个遮盖层，粗粗试了下弹窗套弹窗虽然也可以按到下层弹窗的按钮，但遮盖层是正常的。
另外，将date-picker改成内联的话，在有弹窗的情况下定位好像有问题，还有个小细节就是开关遮盖层时候隐藏滚动条导致的[抖动问题](http://www.zhangxinxu.com/wordpress/2015/01/css-page-scrollbar-toggle-center-no-jumping/)，不知该不该写在框架里
![image](https://cloud.githubusercontent.com/assets/13186101/20517490/39117134-b0d6-11e6-90e9-90b97941667d.png)
![pb2o z9 ngza4 hzes88](https://cloud.githubusercontent.com/assets/13186101/20517637/f47ca344-b0d6-11e6-9773-3390694b89ec.png)

**Comment by myronliu347** [comment]
请问是哪个滚动条抖动？？

**Comment by ccchangkong** [comment]
@myronliu347 body的

**Comment by myronliu347** [comment]
确实是个bug，我会尽快修改

**Comment by myronliu347** [comment]
在 2.0.0-alpha.9 版本中修复, dialog， popup,popover, bottomSheet 这四个组件不可以使用 `v-if` 控制了 需要改成 `open` 属性控制

```html
<mu-dialog :open="dialog" title="Dialog" @close="close">
    这是一个简单的弹出框
    <mu-flat-button slot="actions" @click="close" primary label="取消"/>
    <mu-flat-button slot="actions" primary @click="close" label="确定"/>
  </mu-dialog>
```

更多更新内容请看： [更新日志](https://museui.github.io/#/changeLog)
