### ISSUE TITLE
感觉很久都没更新了啊，相比Vuetify和Vue-material落后了好多了！

### ISSUE THREAD

**Issue by paraself** [museui/muse-ui#781]
RT

**Comment by hrbzcj** [comment]
被你带到沟里去了😭，虽然Vuetify好用一点，但是在ie浏览器里样式有点问题。又用回这个了。

**Comment by paraself** [comment]
@hrbzcj Vuetify说了仅支持IE11以上
![screen shot 2017-12-02 at 5 57 36 pm](https://user-images.githubusercontent.com/2179686/33514190-7bc97d7e-d78a-11e7-9c21-8e303a8d9a7e.png)

**Comment by myronliu347** [comment]
唉唉，放了个长假落后太多，后续会慢慢恢复的。。。
