### ISSUE TITLE
使用auto complete时设置在inputClass所在样式设置width无效

### ISSUE THREAD

**Issue by lipengfei217** [museui/muse-ui#782]
使用auto complete时设置在inputClass所在样式设置width无效，什么方法都试过了。始终只有256px，使用fullwidth="true是可以的，但是尺寸不适合。 是不是不能直接设置width，需要我用div包裹？"

**Comment by myronliu347** [comment]
有可能是css的权值不够，后续会把xxxClass这类参数删除，因为这样的方式修改样式会有很多权值不够的问题， 建议使用css样式覆盖的方式
