### ISSUE TITLE
DatePicker 日期选择组件希望有一个月份选择视图，否则像生日选择这类场景用户操作起来太麻烦了。

### ISSUE THREAD

**Issue by charleslo1** [museui/muse-ui#783]
DatePicker 日期选择组件希望有一个月份选择视图，否则像生日选择这类场景用户操作起来太麻烦了。个人觉得在选择年份列表后面加一个月份选择列表是一个比较简单快捷的方案。
现在移动端的新项目都在用 muse-ui 开发，整体感觉都蛮不错，开发效率和质量上有了很大提升，希望 muse-ui 越来越好。

**Comment by walure** [comment]
目前也正在使用这个 刚好也有这个需求

**Comment by myronliu347** [comment]
fixed https://www.muse-ui.org/#/zh-CN/date-picker
