### ISSUE TITLE
mu-text-field 不能限制input长度

### ISSUE THREAD

**Issue by waynewgl** [museui/muse-ui#789]
mu-text-field 不能限制input长度，非常不方便，原来input的maxlength也不能直接用， 麻烦作者能够优化一下

**Comment by yanjingenious** [comment]
貌似作者没管了

**Comment by myronliu347** [comment]
目前没有强制限制输入长度，但当输入超长时会触发 text-overflow事件,自行处理，后续会加上长度的限制
