### ISSUE TITLE
自定义主题样式优先级问题

### ISSUE THREAD

**Issue by peirancao** [museui/muse-ui#79]
https://github.com/museui/muse-ui/blob/master/less/theme-vars.less#L23
问题：我自定义的主题样式优先级低于默认主题样式

**Comment by peirancao** [comment]
另外能不能让自定义组件使用 ripple 效果

**Comment by myronliu347** [comment]
注意一下加载顺序， 只需要在后theme样式后面加载就行，

**Comment by myronliu347** [comment]
ripple 效果需要自定义哪些内容呢，除了颜色 ？

**Comment by peirancao** [comment]
`import 'muse-ui/dist/muse-ui.css'
import './theme/default.less'`
这样加载的顺序不对吗

**Comment by peirancao** [comment]
之前下载源码到本地可以使用touchRipple现在没法引用了

**Comment by peirancao** [comment]
https://github.com/museui/muse-ui/blob/c4c27abd2bc2de2a6ed072525fea80c071060e62/src/bottomNav/bottomNavItem.vue#L103
我把这里的样式覆盖了没问题
