### ISSUE TITLE
怎么固定appbar

### ISSUE THREAD

**Issue by weituotian** [museui/muse-ui#792]
文档没有说，也不知道怎么做

泪奔%

**Comment by 1008611** [comment]
position: fixed;....

**Comment by weituotian** [comment]
感觉官方应该提供属性或者方法

不然appbar下面的元素都要加个padding-top: 56px

要是appbar的高度改了呢？

不累死？

**Comment by myronliu347** [comment]
的确是需要手动去position:fixed , appBar不一定会在顶部使用，所以没有提供固定的函数

**Comment by weituotian** [comment]
@myronliu347 不能提供个参数去设置么？这么早关我issue！这是requset feature

**Comment by myronliu347** [comment]
唉，这个组件是不提供fixed这类的方法的，就算我加上position:fixed， 后面还是需要padding-top: 56px

**Comment by myronliu347** [comment]
今天，要处理的太多，所以有些地方就没说的这么清楚了，不好意思哦

**Comment by passioncsu** [comment]
既然官方都让fixed 那我就不折腾了

**Comment by wangxm345566462** [comment]
好奇怪的操作，这个固定不是常规设置么？为什么没有加？手动设置了position:fixed ，感觉回归原始社会了
