### ISSUE TITLE
timeline和card组件组合在一起的时候就悲剧了

### ISSUE THREAD

**Issue by weituotian** [museui/muse-ui#793]
![image](https://user-images.githubusercontent.com/7270968/32821351-c92d8964-ca0d-11e7-9723-b73103e39ffd.png)

右边显示不全，30px都被埋没了

**Comment by myronliu347** [comment]
组合使用的样式问题吧，你可以更改下样式，或者在http://jsfiddle.net/ 上重现，我可以看下是哪个部分的问题
