### ISSUE TITLE
mu-select-field当选中列表项的时候，在输入框的文字大小没办法改变

### ISSUE THREAD

**Issue by leichao998877** [museui/muse-ui#796]
@pborreli @idealley @fourcels @shayneo @

**Comment by leichao998877** [comment]
因为在mu-select-field没有给mu-dropDown-menu组件提供labelClass属性

**Comment by myronliu347** [comment]
可以覆盖样式的方式修改吧，后续会把 XXXClass的参数取消掉，这种方式确实不太好
