### ISSUE TITLE
how to use touchRipple?

### ISSUE THREAD

**Issue by weituotian** [museui/muse-ui#798]
`    import touchRipple from 'muse-ui/src/internal/touchRipple.vue';
`

```
            <li>
                <touchRipple></touchRipple>
                <mu-icon value="alarm" :size="48" color="green"/>
                <div>提醒列表</div>
            </li>
```

is not work for me, how to configure it?

**Comment by myronliu347** [comment]
https://github.com/museui/muse-ui/blob/master/src/internal/abstractButton.js
这个组件中使用了，可以看看
