### ISSUE TITLE
solve backTop not working

### ISSUE THREAD

**Issue by Gus-Wang** [museui/muse-ui#803]
Modify the **node_modules\muse-ui\src\backTop\backTop.vue** source
 mounted () {
    window.addEventListener('scroll', this.scrollListener, false)
    window.addEventListener('resize', this.scrollListener, false)
  }
to
 mounted () {
    window.addEventListener('scroll', this.scrollListener, **true**)
    window.addEventListener('resize', this.scrollListener, **true**)
  }

**Comment by myronliu347** [comment]
#786
