### ISSUE TITLE
不好，listitem的内边距不能设置

### ISSUE THREAD

**Issue by weituotian** [museui/muse-ui#806]
![image](https://user-images.githubusercontent.com/7270968/33227607-4887b29a-d1e1-11e7-980a-fb8da27fe9fc.png)

这么大一块

**Comment by myronliu347** [comment]
这个间隔是根据设计规范来的，目前不可以通过设置更改，不过你可以同覆盖样式的方式修改间隔

**Comment by weituotian** [comment]
@myronliu347 怎么覆盖样式？

文档并没有说！！！

**Comment by myronliu347** [comment]
就正常的样式覆盖就好了，文档大部分是我写的，可能有很多不完善的地方
```html
<template>
<mu-list-item class="customer-item"/>
</template>
<style>
.customer-item.mu-item.show-left {
    padding-left: 48px;
}
</style>
```
