### ISSUE TITLE
关于check事件多次触发的问题

### ISSUE THREAD

**Issue by wh469012917** [museui/muse-ui#81]
直接上代码：

```javascript
<mu-checkbox v-on:change="setStatus" name="group" nativeValue="check1" v-model="list" label="checkbox1" class="demo-checkbox"/> 
<mu-checkbox v-on:change="setStatus" name="group" nativeValue="check2" v-model="list" label="checkbox2" class="demo-checkbox"/> 
<mu-checkbox v-on:change="setStatus" name="group" nativeValue="check2" v-model="list" label="checkbox2" class="demo-checkbox"/> 
```

根据文档，给每个check设置了相应的改变事件，这时假如有一个checkbox的状态改变了，都会触发三次事件，而且这个触发的事件次数是和checkbox的数量一致的，有三个checkbox绑定了事件就触发三次，N个就触发N次，不知是有意而为之还是？

**Comment by myronliu347** [comment]
v-model值改变了就会触发change事件，这里有三个checkbox所以就触发了三次

**Comment by wh469012917** [comment]
在checkbox数量多的时候，动画会有明显的卡顿，我一个项目中，checkbox差不多有240多个，每一个打钩取消钩的时候，动画都有很明显的卡顿，希望可以在下一版本优化。
设备：MacBook Pro (Retina, 13-inch, Early 2015)
浏览器：chrome54.0.2840.98
