### ISSUE TITLE
请问如何实现的一次打包出多个css主题。

### ISSUE THREAD

**Issue by bwqgithub** [museui/muse-ui#812]
我项目中使用的sass定义了多个主题色文件，打包时候提取出所有的css。但是现在是每次只能打包一个主题然后修改路径再打包一次，请问你们是如何实现的多个less主题文件一次打包出多个css主题，谢谢。

**Comment by myronliu347** [comment]
使用gulp把每个主题文件，单独的合并编译 [gulpfile.js](https://github.com/museui/muse-ui/blob/master/gulpfile.js)
