### ISSUE TITLE
请问这个项目还有木有维护？

### ISSUE THREAD

**Issue by highmore** [museui/muse-ui#813]

**Comment by guog** [comment]
没有继续维护的话就太可惜了

**Comment by paraself** [comment]
作者今天回复我说最近会有大动作，期待！

**Comment by ShanaMaid** [comment]
根据myron说的近期应该会有动作，各位拭目以待吧！

**Comment by highmore** [comment]
期待中...

发自我的 iPhone

**Comment by yanjingenious** [comment]
只能等了，不知道会不会更新，文档中控件的属性要是有相应的实例就好了，有时候真看不懂，萌新啊

**Comment by myronliu347** [comment]
后面会维护的，之前由于一些琐碎的事情和工作太忙的原因，给自己放了个长长的假，下一步为，对这个项目进行迭代和重构（这个是大动作哦）,以及后续的推广的社区，和后台的admin模板等等...... 谢谢大家在这段时间内，仍然关注着muse-ui,不胜感激
