### ISSUE TITLE
DatePicker minDate和maxDate第一次不能选择

### ISSUE THREAD

**Issue by zc58778560** [museui/muse-ui#814]
[组件-DatePicker](http://www.muse-ui.org/#/datePicker)
`选择控制`小节的例子：选择 2016-09-01 到 2016-12-20
第一次打开是这样的：
![d1](https://user-images.githubusercontent.com/10148442/33812121-7dfe2294-de55-11e7-9fc7-ad6d3a30ddf8.PNG)
很明显，数字都是灰色的，但是`确定`按钮可以点击。点击后，选择的日期是`2016-12-20`。这时候，再次选择日期，就恢复正常了

**Comment by myronliu347** [comment]
这里是默认开打会选择今天，定义了不可选择的日期，而时间推移，今天不可被选择出的问题，所以选择的为可以选择的最后一天，实际使用中不会出现该问题
