### ISSUE TITLE
如何引用MUSE-UI

### ISSUE THREAD

**Issue by Hardlygo** [museui/muse-ui#816]
在main.js中引入如下：
![image](https://user-images.githubusercontent.com/33127984/34031666-5e9c1a9a-e1ad-11e7-8f77-9d21262088d5.png)
但是效果没出来

![image](https://user-images.githubusercontent.com/33127984/34031692-809d4808-e1ad-11e7-8324-8a4ab1caebe1.png)
何解？（新手抱头-.-）

**Comment by superlovers** [comment]
这个应该是需要设置编辑器js版本为ES6

**Comment by myronliu347** [comment]
这种方式引用需要使用webpack 打包时使用，如果萌新直接在html中引入
```html
<link href="https://unpkg.com/muse-ui@2.1.0/dist/muse-ui.css" rel="stylesheet" >
<script src="https://unpkg.com/muse-ui@2.1.0/dist/muse-ui.js"></script>
```
