### ISSUE TITLE
 Text Field multiLine，如果带浮动标签，则容器高度不对

### ISSUE THREAD

**Issue by ccchangkong** [museui/muse-ui#82]
描述如题~
![h70i 3 jpnt _zgq 2 ui](https://cloud.githubusercontent.com/assets/13186101/20586846/2a557546-b243-11e6-94fe-da5b63efe1e3.png)

**Comment by myronliu347** [comment]
刚发了新版本 alpha.10， 更新后就可以了，万分感谢！！
