### ISSUE TITLE
Drawer的遮罩在iOS上有问题

### ISSUE THREAD

**Issue by GEOHOTIOS** [museui/muse-ui#820]
遮罩覆盖到了抽屉菜单的上面

**Comment by myronliu347** [comment]
请给出出错截图

**Comment by y13818463245** [comment]
看父级元素，是不是父级z-index低于 遮罩的z-index

**Comment by GEOHOTIOS** [comment]
谢谢。这个组件我自己重写了下




------------------ 原始邮件 ------------------
发件人: "y13818463245"<notifications@github.com>; 
发送时间: 2019年6月6日(星期四) 下午5:26
收件人: "museui/muse-ui"<muse-ui@noreply.github.com>; 
抄送: "小豆总"<1251439875@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [museui/muse-ui] Drawer的遮罩在iOS上有问题 (#820)




看父级元素，是不是父级z-index低于 遮罩的z-index
