### ISSUE TITLE
AppBar 在小屏幕上Title显示不全

### ISSUE THREAD

**Issue by huanglintian** [museui/muse-ui#826]
![image](https://user-images.githubusercontent.com/11827846/34769000-71ba8578-f637-11e7-8fc0-5590f6986b7c.png)

在AppBar里面加入搜索和按钮后，在宽度较小的手机屏幕上搜索会覆盖掉Title

**Comment by myronliu347** [comment]
这个本身不是组件的问题， text-field 是有默认有设置宽度的，你可以调整的textField的宽度，让它不会挤着title
