### ISSUE TITLE
单个组件加载

### ISSUE THREAD

**Issue by anghuang** [museui/muse-ui#827]
请问下按需加载移动端的国内uc浏览器和别的浏览器都正常，但是国外uc浏览器打不开是为什么？配置是和官网上写的一样，

**Comment by myronliu347** [comment]
没有使用过国外UC浏览器，可以看下是否有js不兼容之类的额报错，提供全一点的错误信息

**Comment by anghuang** [comment]
没事了，自己少配置了一项，但是少配置竟然在国内的还能运行，不好意思哈
