### ISSUE TITLE
List 的 left icon 不会跟随主题颜色

### ISSUE THREAD

**Issue by lsqi** [museui/muse-ui#834]
如图：
![1](https://user-images.githubusercontent.com/11209211/35140549-a71e79e8-fd32-11e7-91e6-f76ef6ba3c54.PNG)

**Comment by myronliu347** [comment]
left icon 使用 `slot` 方式去定制的，不会跟随主题颜色的

**Comment by Lanfei** [comment]
@myronliu347 请问具体如何定制选中项的 icon 颜色？

**Comment by myronliu347** [comment]
<mu-icon value="send" color="primary"/>

**Comment by Lanfei** [comment]
@myronliu347 请问是忘记填写正文了吗？

> No description provided.
