### ISSUE TITLE
icon-button tooltip causing infinite loop on router transition

### ISSUE THREAD

**Issue by DreaMinder** [museui/muse-ui#840]
If route contains mu-icon-buttons with tooltips, it sometimes hangs on transition to another route.  CPU 100%, can't even run profiler.
I have been searching cause of the issue for 4 month. And I still can't  believe that after I replaced all 
`:tooltip="`
to
`:tooltip_=`
in my code, it's gone.
Sorry, no reproduction. Even in my project it happened not every time and for no reason. Maybe something with race conditions.
I figured it out using source tab in DevTools. Sometimes if I stop execution, it shows vue reactive functions and "mu-tooltip" values in it's variables.
Maybe this issue somehow related only with my project. But still, I think I should warn you.

Version 2.1.0

**Comment by myronliu347** [comment]
https://www.muse-ui.org/#/zh-CN/tooltip
