### ISSUE TITLE
怎样获取mu-table选中的值

### ISSUE THREAD

**Issue by zhanghjgnu** [museui/muse-ui#844]
table控件单选，选中后如何获取值？

**Comment by zhanghjgnu** [comment]
搞定了，有需要的可以看一下
<template>
<div>
  <mu-table selectable @rowSelection="handleSelect">
    <mu-thead slot="header">
      <mu-tr>
        <mu-th tooltip="ID">ID</mu-th>
        <mu-th tooltip="名称">Name</mu-th>
        <mu-th tooltip="状态">Status</mu-th>
      </mu-tr>
    </mu-thead>
    <mu-tbody>
      <mu-tr v-for="(item,index) in tableData" :selected="item.selected" :key="item.name">
        <mu-td>{{index + 1}}</mu-td>
        <mu-td>{{item.name}}</mu-td>
        <mu-td>{{item.status}}</mu-td>
      </mu-tr>
    </mu-tbody>

  </mu-table>
  <div>
    <mu-float-button icon="确认" Primary @click="clickevent"/>
  </div>
</div>
</template>

<script>
export default {
  data () {
    return {
      tableData: [
        {
          name: 'John Smith',
          status: 'Employed',
          selected: true
        },
        {
          name: 'Randal White',
          status: 'Unemployed'
        },
        {
          name: 'Stephanie Sanders',
          status: 'Employed'
        },
        {
          name: 'Steve Brown',
          status: 'Employed'
        },
        {
          name: 'Joyce Whitten',
          status: 'Employed'
        },
        {
          name: 'Samuel Roberts',
          status: 'Employed'
        },
        {
          name: 'Adam Moore',
          status: 'Employed'
        }
      ],
      selectData: {}
    }
  },
  methods: {
    handleSelect (rowIndexs) {
      console.log('rowIndexs=' + rowIndexs)
      console.log(JSON.stringify(this.tableData[rowIndexs]))
      this.selectData = this.tableData[rowIndexs]
    },
    clickevent () {
      window.alert('选中的记录' + JSON.stringify(this.selectData))
    }
  }
}
</script>

**Comment by Lanfei** [comment]
可以用 ` ``` ` 把代码括起来，就不会有显示问题了：

> \```
> // 代码
> \```

**Comment by myronliu347** [comment]
https://www.muse-ui.org/#/zh-CN/data-table 请用 `mu-data-table` 替换 `mu-table`
