### ISSUE TITLE
mu-raised-button 设置icon不管用

### ISSUE THREAD

**Issue by wave2588** [museui/muse-ui#845]
`        <mu-raised-button class="sync_slce" :icon="sync_slice_icon_path" :label="sync_slice_title" primary/>
`

![image](https://user-images.githubusercontent.com/13011595/35714307-db4222d6-0806-11e8-9927-149a2e32a704.png)

这个图片路径确定是有效的,但是设置不上去icon..

**Comment by wave2588** [comment]
![image](https://user-images.githubusercontent.com/13011595/35714337-04d31d1c-0807-11e8-8540-f4f813488bb9.png)

结果出来的样子把路径当成字符串展示了.
坐等解答~~~☺☺☺

**Comment by zhanghjgnu** [comment]
加上这句
 <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>

**Comment by wave2588** [comment]
hi 在文件中加上这句？？？ 
请原谅我没太明白....

**Comment by zhanghjgnu** [comment]
我加在webpack的工程的根目录 index.html，因为后面大部分页面都用到muse-ui的图标

**Comment by wave2588** [comment]
好的 我已经搞定了 感谢你的回答~~
