### ISSUE TITLE
分页bug

### ISSUE THREAD

**Issue by lqixv** [museui/muse-ui#85]
如图，当改变每页显示数量时，分页每页跟着改变
![p](https://cloud.githubusercontent.com/assets/2187137/20594796/7c7da666-b272-11e6-88ae-588b7c9da7ff.gif)

**Comment by linxiaowu66** [comment]
@lqixv 
多谢帮我找到一个bug， 我马上修复

**Comment by linxiaowu66** [comment]
@Iqixv
这个bug已经修复 详见刚提交的[PR 86](https://github.com/museui/muse-ui/pull/86)
