### ISSUE TITLE
Text Field的一些bug

### ISSUE THREAD

**Issue by dawufenfen** [museui/muse-ui#854]
required不起效，使用后在页面中输入框为空时，不能触发报错样式。
绑定了model为name(任意名称均可)之后，在输入的时候js无法控制绑定的值，比如js实现这个输入框最长为3位，在监听input的时候判断超出时将name进行处理，如输入了1234，js将name改为123，可是改变无法反映到输入框中，输入框还是1234，这时候再输入5，输入框变成了12345，name也变成了12345。

**Comment by myronliu347** [comment]
fixed
