### ISSUE TITLE
一个refresh-contrl的问题

### ISSUE THREAD

**Issue by Hardlygo** [museui/muse-ui#857]
今天试了一下refresh-contrl组件，这里是在appbar组件下再加了一个tabs组件
出现refresh-contrl组件遮盖住了appbar请问这个问题能解决吗
![tim 20180301173122](https://user-images.githubusercontent.com/33127984/36837389-3e386b04-1d77-11e8-9c94-05c90dbac5ad.png)

**Comment by myronliu347** [comment]
提高上述组件的z-index
