### ISSUE TITLE
自定义的样式类的优先级比muse-ui自带的类的优先级低，何解？

### ISSUE THREAD

**Issue by Hardlygo** [museui/muse-ui#861]
新手在做项目时为了覆盖muse-ui自带的一些样式效果打算自定义一些样式，问题：自定义样式在开发阶段能成功覆盖muse-ui原来的默认的样式，但是在npm run build 后运行时自定义样式类优先级覆盖不了原来的样式类。
自定义样式：
`.toast{
  height: 68px;
    line-height: 68px;
    padding: 0 24px;
    background-color: rgba(71, 67, 67, 0.87);
    color: #fff;
    border-top-left-radius: 0px;
    border-top-right-radius: 0px;
    border-bottom-right-radius: 0px;
    border-bottom-left-radius: 0px;
    white-space: nowrap;
    -o-text-overflow: ellipsis;
    text-overflow: ellipsis;
    overflow: hidden;
    word-wrap: break-word;
    max-width: 300px;
    width: 100%;
    position: absolute;
    left: 12%;
    bottom: 45%;
}`

**Comment by langki** [comment]
I have the same problem.

**Comment by Hardlygo** [comment]
try this!!!!!!!!
`
import 'muse-ui/dist/muse-ui.css'
import Vue from 'vue'
import MuseUI from 'muse-ui'
import App from './App.vue'

import './pathtoyourcss/main.css'
import './pathtoyourtheme/theme-custom.less'
`
