### ISSUE TITLE
icon menu增加新的prop可以在最外层.mu-menu层上增加class

### ISSUE THREAD

**Issue by prototype0605** [museui/muse-ui#872]
现在icon menu组件支持的三种添加class的prop：iconClass  menuClass  menuListClass都无法在浮框最外层.mu-menu层上增加class
项目有个需求就是浮框不要遮住icon，这样就需要改变这个浮框的margin，可是最外层.mu-menu上不能自定义添加class是不能实现这个需求的。
希望作者能开放出一个新的prop，在最外层上添加自定义的class

**Comment by prototype0605** [comment]
up

**Comment by myronliu347** [comment]
fixed https://www.muse-ui.org/#/zh-CN/menu
