### ISSUE TITLE
输入框焦点问题

### ISSUE THREAD

**Issue by yoke233** [museui/muse-ui#88]
mu-text-field 的焦点有时候会失效 无法双击全选 拖拽选择

**Comment by myronliu347** [comment]
双击全选是可以的，选择文本都是可以的，这个拖拽选择是啥 ？

**Comment by myronliu347** [comment]
方面写个 jsfiddle 么？

资源可以用
https://unpkg.com/muse-ui@2.0.0-alpha.10/dist/muse-ui.js
https://unpkg.com/muse-ui@2.0.0-alpha.10/dist/muse-ui.css

写好再重开吧
