### ISSUE TITLE
date picker无法显示日历

### ISSUE THREAD

**Issue by chenchengfa93** [museui/muse-ui#885]
设置 container=inline时，
1、点击输入区域，跳出日历；
2、再次点击该输入区域，日历隐藏；
3、再一次点击该输入区域，日历不显示

步骤2点击完成后，DatePicekrDialog组件的showCalendar变为false，但是open仍然为true，导致再次点击输入区域时，showCalendar由于没能触发open的watch事件，无法变为true

**Comment by myronliu347** [comment]
fixed
