### ISSUE TITLE
Autocomplete can not set value and show at initial loading

### ISSUE THREAD

**Issue by ghprod** [museui/muse-ui#89]
Hi,

How to set initial value for autocomplete? i'm using version 2 alpha 10

I've try using `v-model`, `:value` but still no luck, and there's no error in my console log

![image](https://cloud.githubusercontent.com/assets/1922652/20613965/a9a75ebe-b2fb-11e6-9f94-98fa11206886.png)

```html
<mu-auto-complete 
  filter="caseInsensitiveFilter" 
  label="Kabupaten" 
  :dataSource="regencies" 
  :dataSourceConfig="dataSourceConfig"
  openOnFocus
  @select="regencyOnSelect"
  v-model="regency"
/>
```

```js
  data () {
    return {
      regency: '1101', // its value not text
      dataSourceConfig: {
          text: 'name',
          value: 'id'
        }
    }
  },
  methods: {
    getRegencies () {
      this.axios.get('regencies/all')
        .then(response => {
          this.regencies = response.data.data
        })
    }
}
```

Thanks

**Comment by ac51300696** [comment]
v-model need input function ，you can add your templatecode

**Comment by ghprod** [comment]
@ac51300696 Hi, can you give some example? Thanks :+1:

**Comment by ac51300696** [comment]
hintText="regency" instand of v-model="regency"

**Comment by ac51300696** [comment]
```
<mu-auto-complete hintText="regency"  />

data: function () {
    return {
      regency: '1101'
    }
  },
```

**Comment by ghprod** [comment]
@ac51300696 

Hi, seems like `hintText` for right now is our best option, but i'm still wondering why we cant set value directly ..

![image](https://cloud.githubusercontent.com/assets/1922652/20616737/e5852a40-b316-11e6-907a-9fdf68f0babe.png)

Thanks

**Comment by ac51300696** [comment]
first in design ,it is not a value ,its prompt text, so in code ,itis a <div> ,not is input value

**Comment by ghprod** [comment]
Yes, its kinda a placeholder, at least right i can show to user the saved value :+1: 

Thanks

Should i close right now?

**Comment by ac51300696** [comment]
ok

**Comment by jaweii** [comment]
@ac51300696 hi

…………

我也遇到了这个问题，并且不想用hintText 代替value

主要用于保存用户的输入和方便用户的修改，但是试了很久，发现value或者v-model都不工作，但是文档中又提供了这个参数

请问怎么绑定和设置autoComplate中input的value的值？

**Comment by myronliu347** [comment]
@jaweii 可以写个 [jsfiddle](https://jsfiddle.net) 么, 也许我可以给你些建议

资源可用

https://unpkg.com/muse-ui/dist/muse-ui.js
https://unpkg.com/muse-ui/dist/muse-ui.css

**Comment by jaweii** [comment]
@ghprod 
https://jsfiddle.net/4vtv0ocx/

**Comment by myronliu347** [comment]
这确实是个bug,我会尽快修复

**Comment by myronliu347** [comment]
I fixed, please updated
