### ISSUE TITLE
date-picker 组件可以对外提供api 唤起date-picker-dialog 组件吗

### ISSUE THREAD

**Issue by yanzi475** [museui/muse-ui#891]
我现在的页面上有一个 按钮，需要调起日历框来选择。。。现在两个组件放在一起，可以单独在date-picker 提供一个事件，显示日历框 ，可以进行选择控制吗？或者也可以在icon 上添加事件，看了源码，icon只能控制样式
 :icon="icon" :iconClass="iconClass"

**Comment by myronliu347** [comment]
https://www.muse-ui.org/#/zh-CN/date-picker
现在date-picker 和data-input 已重构
