### ISSUE TITLE
单组件加载失败，能否提供个demo

### ISSUE THREAD

**Issue by xufangda** [museui/muse-ui#892]
已解决
教程使用章节 webpack配置有问题

node_modules前边要加两个点，回上级目录就好使了。

const museUiThemePath = path.join(
  __dirname,
  '../node_modules',
  'muse-ui',
  'src/styles/themes/variables/default.less'
)

**Comment by myronliu347** [comment]
单组件加载方式以及更改了哦
https://www.muse-ui.org/#/zh-CN/usage

**Comment by xufangda** [comment]
SSL证书过期了
