### ISSUE TITLE
mu-popup与mu-dialog在同一个页面内使用的时候,遮罩层出现bug

### ISSUE THREAD

**Issue by qwe4251782** [museui/muse-ui#893]
`<mu-popup position="top" :overlay="false" popupClass="top-popup-tips" :open="true">
    </mu-popup>
    <mu-dialog :open="showHelpDialog" :title="helpDialogTitle" @close="closeHelpDialog">
      {{helpDialogContent}}
      <mu-flat-button slot="actions" class="color-green" @click="closeHelpDialog" label="确定"/>
    </mu-dialog>
`
这种情况下,打开了dialog,再关闭,遮罩层依然存在

**Comment by myronliu347** [comment]
fixed
