### ISSUE TITLE
mu-text-field行内文字颜色修改不生效的问题

### ISSUE THREAD

**Issue by zwdgit** [museui/muse-ui#899]
在<style lang="less">下面可以修改，但并不是自己想要的，因为这样会全局修改文字颜色，而我只想修改当前页面下的mu-text-field；
在<style scoped lang="less">下面修改mu-text-field行内文字颜色不生效；
或者是我的方法不对吗？有没有人可以帮助我一下

**Comment by myronliu347** [comment]
scoped会对于组件会生效，
