### ISSUE TITLE
list组件动画问题

### ISSUE THREAD

**Issue by chutzstudio** [museui/muse-ui#904]
使用list组件显示双层列表，一级菜单设置toggleNested开合，控制二级菜单显示。

使一级菜单打开，再关闭。在关闭的瞬间（在关闭动画还在进行时），点击该一级菜单下属的二级菜单，会导致出现错误，如下图所示：
![default](https://user-images.githubusercontent.com/14048174/39976153-b8aff89e-5764-11e8-8aec-40c76a5e8a36.png)

**Comment by myronliu347** [comment]
fixed
