### ISSUE TITLE
建议把AppNavDrawer也组建化&&感谢提供@import "~muse-ui/less/*"的调用方式

### ISSUE THREAD

**Issue by hyphantom** [museui/muse-ui#905]
感谢作者 提供src-docs 让我能够参考实现自己的页面
AppNavDrawer也很不错 希望能组件化 

现在我是在
<style lang="less">
@import "~muse-ui/less/vars.less";
@import "~muse-ui/less/mixins.less";
实现的 避免了utils.js去修改less-loader 点赞

**Comment by myronliu347** [comment]
切换主题方式有了变动，现在定义主题极为优雅
https://www.muse-ui.org/#/zh-CN/usage
