### ISSUE TITLE
有没有单组件加载的配置demo

### ISSUE THREAD

**Issue by xingguangsixian** [museui/muse-ui#909]
参考这个单组件加载配置，出现各种问题
完全参考这个配置，目前问题如下
![image](https://user-images.githubusercontent.com/6493023/40226052-4c7399a4-5abd-11e8-99c3-ce13523db997.png)

环境：
Vue 2.5.3
![image](https://user-images.githubusercontent.com/6493023/40226131-7b271a78-5abd-11e8-8253-9b0ebdc267c5.png)

**Comment by myronliu347** [comment]
docs in https://www.muse-ui.org/#/zh-CN/usage
