### ISSUE TITLE
AutoComplete: dropdown moved when scrolled

### ISSUE THREAD

**Issue by ghprod** [museui/muse-ui#91]
Before page scroll

![image](https://cloud.githubusercontent.com/assets/1922652/20615812/c08b57fc-b30f-11e6-9b58-fe397e834a03.png)

After page scrolled

![image](https://cloud.githubusercontent.com/assets/1922652/20615799/b132369a-b30f-11e6-8714-e165cf8ce1ad.png)

Dropdown container moved to bottom, seems like the position is `fixed` to screen, not the component it self.

Thanks

**Comment by ac51300696** [comment]
well ,can you show your package.json code

**Comment by ghprod** [comment]
This is my `dependecies`

```json
  "dependencies": {
    "axios": "^0.15.2",
    "fastclick": "^1.0.6",
    "lodash": "^4.17.2",
    "moment": "^2.17.0",
    "muse-ui": "file:/home/ferri/Downloads/muse-ui-2.0.0-alpha.10/",
    "vue": "^2.0.1",
    "vue-axios": "^1.2.2",
    "vue-events": "vue-2.x",
    "vue-google-maps": "https://github.com/Kofre/vue-google-maps.git",
    "vue-router": "^2.0.3",
    "vuex": "^2.0.0",
    "vuex-router-sync": "next"
  },
```

Please note i use latest alpha 10 but still not resolved via yarn or npm so i need to pointing from my local folder

Thanks

**Comment by ac51300696** [comment]
thanks ，we need some times for it 。
Please wait patiently

**Comment by ghprod** [comment]
@ac51300696 

Your welcome. 

Thanks for your help :+1:

**Comment by myronliu347** [comment]
@ghprod  Excuse me, are you use div scroll or window scroll?

**Comment by ghprod** [comment]
Hi

I use window scroll

Thanks

**Comment by myronliu347** [comment]
You can write [jsfiddle](https://jsfiddle.net) , 
you can use 

https://unpkg.com/muse-ui@2.0.0-alpha.10/dist/muse-ui.js
https://unpkg.com/muse-ui@2.0.0-alpha.10/dist/muse-ui.css

**Comment by ghprod** [comment]
Do you have jsfiddle/codepen starter to fork?

Thanks

**Comment by myronliu347** [comment]
add resources

https://unpkg.com/muse-ui@2.0.0-alpha.10/dist/muse-ui.js
https://unpkg.com/muse-ui@2.0.0-alpha.10/dist/muse-ui.css

then write

**Comment by ghprod** [comment]
Ok

I'll try tonight .. Thanks

**Comment by myronliu347** [comment]
Because I don't have the problem, so trouble

**Comment by ghprod** [comment]
Hi do you any idea why its always ask for dataSource?

https://jsfiddle.net/ghprod/zfvo9j1e/

![image](https://cloud.githubusercontent.com/assets/1922652/20739937/b75d8926-b6f1-11e6-8247-7cba89ea91a5.png)

Thanks

**Comment by myronliu347** [comment]
dataSource to `data-source` in html，Because HTML is case-insensitive

**Comment by ghprod** [comment]
Here we go ..

https://jsfiddle.net/ghprod/zfvo9j1e/2/

Try to scroll ouside popover

**Comment by myronliu347** [comment]
[https://jsfiddle.net/zfvo9j1e/3/](https://jsfiddle.net/zfvo9j1e/3/)

you can use `scroller`

**Comment by ghprod** [comment]
when scrolled, then popup disappeared .. is it bug?

**Comment by myronliu347** [comment]
Because the input is not in the window
