### ISSUE TITLE
能否告知官网的模板在哪里可以找到？？？谢谢

### ISSUE THREAD

**Issue by s952787097** [museui/muse-ui#911]
能否告知官网的模板在哪里可以找到？？？谢谢

**Comment by carrymumu** [comment]
这个项目就是官网模板，你用IDE跑起来就行了

**Comment by s952787097** [comment]
@carrymumu  😢那个构建工具没用过

**Comment by carrymumu** [comment]
IDE是编译器的一种泛称，我用的是webstorm，npm install然后npm run dev就跑起来了啊

**Comment by s952787097** [comment]
@carrymumu  好的  我试一下 谢谢
