### ISSUE TITLE
adding ripple effect to other elements

### ISSUE THREAD

**Issue by NarimanMov** [museui/muse-ui#912]
hi there,
thanks for your perfect project
but there is a question

i have a ```<li>``` that has a ```<span>```
```
<li >
    <span >
          <i class="mu-icon material-icons">assignment</i> 
          biography
    </span>
</li>
```
i wanna add ripple effect to this <span>. how it can be possible?

**Comment by myronliu347** [comment]
use internal component https://github.com/museui/muse-ui/blob/master/ui/internal/AbstractButton.js

**Comment by NarimanMov** [comment]
sry but how can i use this AbstractButton ?
i can't find any documentation for it!!!
can u give me an example code?
