### ISSUE TITLE
Muse-UI单组件加载失败问题

### ISSUE THREAD

**Issue by Jude214** [museui/muse-ui#913]
按官方使用文档中的说明配置后引入MuseUI单组件，运行时报错：
![image](https://user-images.githubusercontent.com/13598600/40421185-85e320ca-5ebd-11e8-9729-dc061b6ab90b.png)
解决方式——官方使用文档中的下面这段代码：
const museUiThemePath = path.join(
  __dirname,
  'node_modules',
  'muse-ui',
  'src/styles/themes/variables/default.less'
)
改为
const museUiThemePath = path.join(
  __dirname,
  '..',
  'node_modules',
  'muse-ui',
  'src/styles/themes/variables/default.less'
)

**Comment by myronliu347** [comment]
按需引入的方式更改了哦， https://www.muse-ui.org/#/zh-CN/usage
