### ISSUE TITLE
一个页面同时存在 Popup 组件和 Modal 组件时， :overlay="false" 无法生效

### ISSUE THREAD

**Issue by charleslo1** [museui/muse-ui#914]
一个页面同时存在 Popup 组件和 Modal 组件时，关闭 modal 后遮罩层还继续存在，:overlay="false" 无法生效

<mu-popup :open="openPopup" :overlay="false"></mu-popup>
<mu-modal :open="openModal"></mu-modal>

**Comment by myronliu347** [comment]
fixed
