### ISSUE TITLE
波纹点击特效可以抽离出来作为一个特效组件

### ISSUE THREAD

**Issue by ShanaMaid** [museui/muse-ui#919]
波纹点击特效可以抽离出来作为一个特效组件-Ripple，为子代添加点击波纹特效，可以让开发者基于此进行二次开发。

**Comment by myronliu347** [comment]
那下个beta，我补下文档

**Comment by ShanaMaid** [comment]
@myronliu347 暴露的属性建议有波纹颜色、透明度、半径等

**Comment by myronliu347** [comment]
https://muse-ui.org/#/zh-CN/ripple
