### ISSUE TITLE
AutoComplete: make inner container able to scroll for long list

### ISSUE THREAD

**Issue by ghprod** [museui/muse-ui#92]
Hi

Container for auto complete result which used mu-popover get clipped from screen when having long list, maybe enable scroll inside this list would be better?

![image](https://cloud.githubusercontent.com/assets/1922652/20615941/c3fc3bd0-b310-11e6-8b93-ebee1d3ca679.png)

Thanks

**Comment by ac51300696** [comment]
did you hava some suggestion , ..because l think that is the error of design with width

**Comment by ghprod** [comment]
Maybe give parent `.mu-popover` some auto height depending limit of screen and makes `.mu-menu.mu-auto-complete-menu` overflow scroll ?

**Comment by ac51300696** [comment]
muse ui was design on material ui ...so ,l think it need more discussion , in next edition, we will consider this question

**Comment by myronliu347** [comment]
sorry，this is my negligence，i will be add `maxHeight` to solve

**Comment by myronliu347** [comment]
2.0.0-alpha.11 add `maxHeight`, please update, thanks!
