### ISSUE TITLE
官网报错了。

### ISSUE THREAD

**Issue by GalinaGao123** [museui/muse-ui#922]
![image](https://user-images.githubusercontent.com/16570238/40602015-d221becc-6289-11e8-9216-e6bc7c365837.png)

**Comment by myronliu347** [comment]
你环境可能存在缓存问题，清空下再看

**Comment by GalinaGao123** [comment]
看到其他人提的issue了。但是safari也是一样的。
这个地址能打开。 http://www.muse-ui.org/2.1.0/#/install
这个打不开。 http://www.muse-ui.org
