### ISSUE TITLE
支持服务端渲染吗

### ISSUE THREAD

**Issue by fantian007** [museui/muse-ui#932]
RT

**Comment by myronliu347** [comment]
暂时没有做这方面的测试，不过应该是支持的，目前所有的代码都没有直接使用浏览器环境全局变量

**Comment by DearAKuan** [comment]
大部分组件都支持，有一部分会获取body宽高等，例如 和搜索下拉、modal弹层相关的，服务端拼接html代码用到了document、window之类的属性，,整个程序就无响应或者崩溃了。 解决的过程很痛苦，都是翻源码一点一点修改的。。 现在算是没报错了。希望作者后续能完善一下。谢谢啦

**Comment by yutao331763646** [comment]
nuxt  测试可以

**Comment by myronliu347** [comment]
稍后会出nuxt 的项目模板

**Comment by myronliu347** [comment]
https://github.com/museui/nuxt-template
