### ISSUE TITLE
mu-list 或者mu-table、mu-grid-list下拉触发的方法有没有？

### ISSUE THREAD

**Issue by mrerhuo** [museui/muse-ui#939]
mu-list 或者mu-table、mu-grid-list 类似按住后下拉，然后分页数据就出来了。类似这样的功能。

**Comment by liu874396180** [comment]
同感啊~~~~更新3.x后，官方api少了好多方法实例。好多属性对应的方法没有写，好多效果官方api有，却没有说明如何实现，摸索的成本比2.x要高啊。。。。。。@作者，？

**Comment by yundGo** [comment]
+1。。下拉上拉事件好像没找到

**Comment by myronliu347** [comment]
https://muse-ui.org/#/zh-CN/load-more
