### ISSUE TITLE
這套ui是应用于桌面还是mobile的

### ISSUE THREAD

**Issue by LaiXuechao** [museui/muse-ui#94]
我看到有些组件像是给桌面用的，有些又是给mobile的

**Comment by piaohailin** [comment]
同问。。。。

**Comment by myronliu347** [comment]
Muse UI 所有组件都来源于 [material design components](https://material.google.com/components)  主要用于：

1. 移动端应用
2.基于 electron 的桌面应用
3.对浏览器兼容性要求不好的桌面应用
