### ISSUE TITLE
按需引入TextField webpack4报错

### ISSUE THREAD

**Issue by BeginsDuang** [museui/muse-ui#942]
`Can't resolve 'muse-ui/lib/text-field'`
路径解析不了，看了下node_modules 下面确实没有这个路径啊
我还测试了下2个单词名字的组件按需貌似路径都解析不了

**Comment by BeginsDuang** [comment]
还发现一个报错就是在webpack4中引入后会在控制台报一个
`Uncaught ReferenceError: MuseUI is not defined`
node里倒是没有报错。
最后解决办法是在webpack配置文件中添加如下代码：
`plugins: [
    new webpack.ProvidePlugin({
      MuseUI:"muse-ui"
    }),`
    ........
]

**Comment by myronliu347** [comment]
TextField

**Comment by BeginsDuang** [comment]
@myronliu347 没有我是按照文档了的按需添加的，一运行就会报这个错误

**Comment by BeginsDuang** [comment]
@myronliu347  我完全复制了你的文档按需引入的代码没做任何修改，一样全部2个单词的组件全报错
![qq 20180602150527](https://user-images.githubusercontent.com/25838823/40871864-905eaa40-6676-11e8-8067-45e1422a2abb.png)

**Comment by myronliu347** [comment]
babel-plugin-import 加上这个配置
"camel2DashComponentName": false,
