### ISSUE TITLE
Request/Ask: Please add english version of DatePicker

### ISSUE THREAD

**Issue by donnygunawan93** [museui/muse-ui#95]
How to change this from my component?
https://github.com/museui/muse-ui/blob/master/src/datePicker/dateUtils.js#L2-L5

**Comment by xiaoluoboding** [comment]
See also:
https://github.com/callemall/material-ui/blob/master/src/DatePicker/dateUtils.js#L3-L8

**Comment by myronliu347** [comment]
This seems to be a problem,  I will add internationalization solution

**Comment by myronliu347** [comment]
please update,  see last example [语言环境配置](https://museui.github.io/#/datePicker)

**Comment by yoh** [comment]
here is my muse-ui i18n datepicker (use `muse-ui/src/datePicker` mixin) using moment.js
https://gist.github.com/yoh/a36cf7c5706e52b901069be1b6e1e3b2
