### ISSUE TITLE
复选框checkbox,全选，反选如何实现？api 一点参考说明都没有

### ISSUE THREAD

**Issue by liu874396180** [museui/muse-ui#951]
复选框checkbox,全选，反选如何实现？api 一点参考说明都没有

**Comment by BeginsDuang** [comment]
这种逻辑你的自己实现啊，给你个链接吧[Vue全选和反选]https://www.cnblogs.com/yingzi1028/p/5602784.html)

**Comment by myronliu347** [comment]
下版本我在官网上加个例子吧

**Comment by myronliu347** [comment]
https://muse-ui.org/#/zh-CN/select-control
![image](https://user-images.githubusercontent.com/7897937/41187981-d23d7514-6be8-11e8-92f8-70e8e6bb618b.png)
