### ISSUE TITLE
text-field组件的v-model在使用中文输入法时，会监听每个拼音的输入。

### ISSUE THREAD

**Issue by diz39** [museui/muse-ui#954]
text-field组件的v-model在使用中文输入法时，会监听每个拼音的输入，因此watch该值时会无意义的触发，使用原生的input就没有这种问题。vue的v-model在文档中有以下描述：“_对于需要使用输入法 (如中文、日文、韩文等) 的语言，你会发现 v-model 不会在输入法组合文字过程中得到更新。如果你也想处理这个过程，请使用 input 事件。_”。

**Comment by myronliu347** [comment]
fixed
