### ISSUE TITLE
使用关闭水波纹动画配置报错

### ISSUE THREAD

**Issue by yyan** [museui/muse-ui#957]
由于在Android平板设备上，单选框和复选框感觉卡顿验证，想尝试下关闭动画效果。
查看issues说可以使用config关闭水波纹动画
MuseUI.config({
  disableTouchRipple: true,
  disableFocusRipple: true
})
但是加上这句代码后，程序报错
使用版本3.0.0-bata3

**Comment by myronliu347** [comment]
现在支持在组件上以 `ripple=false` 关掉波纹动画
