### ISSUE TITLE
建议：关于组件事件触发的机制

### ISSUE THREAD

**Issue by wh469012917** [museui/muse-ui#96]
根据文档以及具体在使用过程中发现，muse的组件事件的触发是基于数据的，比如一个checkbox组件，他的change事件是绑定在数据上的，只要数据的改变就会触发，**无论该数据是怎样改变的，用户行为改变以及api请求使得数据的改变，都会触发该change事件**
而vue默认的事件是基于用户行为的，checkbox的状态改变只要数据发生了变化，状态就会改变，但是checkbox的change事件触发必须是用户行为，而不是数据改变就会触发。

muse的事件机制在大部分情况下都是没问题的，但是在一个情况下就会有问题，那就是组件的状态是基于api请求的数据的。比如，我应用有一个switch的组件（假设该组件绑定了一个名称为toggle的数据，控制一个功能A的开或者关，当用户操作switch后，会发起api请求去设置功能A的开关），该组件的初始化状态是基于api请求的，而且该组件也绑定了一个change事件，做一个相应的操作。这时候组件初始化状态我会在created钩子里面去获取数据，然后去设置toggle，而这时候就会触发change事件。**（实际上该次事件并不应该触发，因为我要给用户展示该功能A目前是关闭还是开启状态，而不是修改该功能A的状态）**

所以我认为，muse的组件事件触发应该绑定在用户操作上，而不应该绑定在数据上。当然这个问题如果用服务端渲染就完全可以解决，但还是提出一下，不知道我的理解是否有出入，还请作者指点一下。

**Comment by s51983** [comment]
从我对vue的理解来看目前这样并无不妥之处。通常来讲类似switch这种控件一般用于表单，表单提交又通常由按钮点击收集数据后统一提交。
像你这个需求的话用法特殊，不过也只是需要再change事件里检测下change触发后的数据是否和初始值一致，有变化时再提交。

**Comment by wh469012917** [comment]
我觉得这个用法很普遍，特别在涉及到修改信息的时候，比如用户信息图书信息等修改页面，肯定要给表单元素一个初始值（初始值通过API获取），让用户知道该项是多少，而只要有设置初始值，那就会产生无意义的事件触发（假如表单元素有绑定事件）。
按你说的在事件里面检测值后再做业务逻辑处理，实际上是不可行的，举个简单的例子：
```javascript
<template>
    <mu-switch v-bind:label="toggle == true ? '开' : '关'" v-model="toggle" v-on:change="setStatus"/>
</template>

<script>
data(){
    return{
        toggle : false
    }
 },
methods: {
    created(){
        //通过api获取toggle的初始值,假设以下的userToggleSet是已经通过api获取到了的
        let userToggleSet = true;
        this.toggle = userToggleSet;
    },
    setStatus(value){
        if(this.toggle != value){
            //执行相关业务逻辑处理
        } 
    }
}
</script>
```
以上代码可以看到，toggle默认设置为false，而他的初始值是要通过api来获取的，这时api获取到的值不管是true还是false，其实都不应该去执行业务逻辑的处理，因为目的只是展示，而不是设置。

**Comment by s51983** [comment]
组件上为啥绑个v-model呢，按照文档用value代替v-model。
toggle的值变化并不会触发change和input事件

`<template>
    <mu-switch :label="toggle == true ? '开' : '关'" :value="toggle" @change="setStatus"/>
</template>

<script>
    import {Indicator} from '../../assets/function.js'
    export default{
        data(){
            return {
                toggle: false
            }
        },
        mounted: function () {
            this.created();
        },
        methods: {
            created()
            {
                //通过api获取toggle的初始值,假设以下的userToggleSet是已经通过api获取到了的
                let userToggleSet = true;
                this.toggle = userToggleSet;
            },
            setStatus(value)
            {
                console.log(this.toggle + ' / ' + value);
                if (this.toggle != value) {
                    this.toggle = value;
                    //执行相关业务逻辑处理

                }
            }
        }
    }
</script>`

**Comment by myronliu347** [comment]
@wh469012917  多谢，我会在近期改进

**Comment by myronliu347** [comment]
@wh469012917  已在新版本中更改所有表单类组件的change事件触发机制，请更新， 多谢！
