### ISSUE TITLE
mu-slide-picker 组件找不到

### ISSUE THREAD

**Issue by WX60666** [museui/muse-ui#960]
![image](https://user-images.githubusercontent.com/17688082/41223777-5438ecf0-6d9d-11e8-95af-4d4eaf426f18.png)

**Comment by WX60666** [comment]
全局引入之后, 使用这个组件报错

**Comment by myronliu347** [comment]
注意下版本号哦 3.0.0-beta.4 + 才有

**Comment by WX60666** [comment]
ok 已解决 我用的beta.3 使用npm安装目前默认是beta.3版本. 需要手动改成beta.4+

**Comment by myronliu347** [comment]
升级是 npm upgrade
