### ISSUE TITLE
Slide 过渡效果可以左右滑入滑出吗？

### ISSUE THREAD

**Issue by xuejianxianzun** [museui/muse-ui#962]
看到文档里有```<mu-slide-top-transition>```和```<mu-slide-bottom-transition>```组件，都是垂直方向的，没有水平方向的。

我用了 APP Bar，想在点击菜单按钮时，把菜单从左侧滑过来。试了试上下滑动很顺利，现在就差怎么改成左右了，请问现在 Muse-ui 有内置这个效果吗？还是得自己做动画？

**Comment by xuejianxianzun** [comment]
感谢您的及时回复，不过 ```<mu-slide-left-transition>``` 和 ```<mu-slide-right-transition>```都被报错未知元素了：

```[Vue warn]: Unknown custom element: <mu-slide-right-transition> - did you register the component correctly? For recursive components, make sure to provide the "name" option.```

其实昨天我就把 top、 bottom 改成 left、right 试过，也是一样的错误。top、 bottom 组件一直没问题。

**Comment by myronliu347** [comment]
还没发布

**Comment by xuejianxianzun** [comment]
原来如此，那就静候发布了，谢谢大大~
