### ISSUE TITLE
项目中并存3.0.0与2.1.0两个版本

### ISSUE THREAD

**Issue by yrfandrew** [museui/muse-ui#964]
项目采用2.1.0版本已稳定运行，计划采用3.0.0版本逐步替换旧版本的组件。不知道这样的设想有没有方法实现？

**Comment by myronliu347** [comment]
两个版本差距还挺大的，组件和使用方式都不一样

**Comment by myronliu347** [comment]
推荐是升级的， 2.1.0的问题比较多，如果使用的组件不是很多的话，可以考虑升级下
