### ISSUE TITLE
Data Table组件不能根据父元素宽度自动改变

### ISSUE THREAD

**Issue by adtkcn** [museui/muse-ui#967]

**Comment by adtkcn** [comment]
Data Table好像不兼容ie，radio组件好像也不兼容ie

**Comment by adtkcn** [comment]
this.$refs.form.validate();
表单验证 建议返回true or false

**Comment by myronliu347** [comment]
1. 是可以根据宽度自动计算， 也可以根据窗口大小改变重设宽度
2. Data Table没有用到不兼容的属性
3.验证函数返回的是 true/false

**Comment by adtkcn** [comment]
![image](https://user-images.githubusercontent.com/16753750/41346393-f5434c16-6f38-11e8-8ccd-233ae1ad5f7a.png);
Data Table的父元素被动态改变，Data Table就没有重新计算, 在ie里确实没显示出来table，radio的label在ie显示有点问题（不排除我的问题。。。）

console这个this.$refs.form.validate()一直是false,

然后，大哥，官网加个Promise吧，ie体验不成呀

**Comment by pgh147** [comment]
> 1. 根据宽度自动计算

具体要怎么做呢？
