### ISSUE TITLE
建议增强tab组件

### ISSUE THREAD

**Issue by slovebj** [museui/muse-ui#97]
参照b-jui使tab具有navtab功能。

**Comment by ZinCode** [comment]
tab组件确实得增强一下，一般情况下，tab下面的content用户自行设定就可以了，还有tab下面那条active的横杠弄得不好，具体参考youtube app中的tabs是怎么搞得，还有每一个tab上面放的应该是a标签链接，在vue中就是router-link，

**Comment by xiangle** [comment]
能排序就更好了

**Comment by guohuadeng** [comment]
Tab 看能不能加个开关，关闭 ripple动画
谢谢。
