### ISSUE TITLE
data-table 之 row-dblclick 的回调参数与文档有出入

### ISSUE THREAD

**Issue by yrfandrew** [museui/muse-ui#973]
以下为文档截图：

![image](https://user-images.githubusercontent.com/4082323/41386469-0b73bce8-6fb4-11e8-988b-4fdb37a6c134.png)

在项目中运用结果如下：

![image](https://user-images.githubusercontent.com/4082323/41386608-d07409d0-6fb4-11e8-8bea-ba9e0f1ccb92.png)

**Comment by myronliu347** [comment]
Thanks
