### ISSUE TITLE
希望 mu-auto-complete 的 change 事件返回选中项

### ISSUE THREAD

**Issue by yrfandrew** [museui/muse-ui#978]
目前 `mu-auto-complete` 组件的 `change` 事件只是返回了对象，如图所示：

![image](https://user-images.githubusercontent.com/4082323/41400827-c021bf78-6ff0-11e8-854f-b8f10c778a2e.png)

希望能返回选中项！

**Comment by myronliu347** [comment]
Thanks

**Comment by myronliu347** [comment]
跟原生事件监听一样是返回的 Event 对象哦
