### ISSUE TITLE
可否添加一个加载提示的组件

### ISSUE THREAD

**Issue by munimrwu** [museui/muse-ui#982]
需求：
1. 背景模态框禁止点击
2. 可以全局调用 `this.$loading()`

![uc 20180614182103](https://user-images.githubusercontent.com/33760888/41406919-69cf2c68-7000-11e8-89b4-842d470fd4f8.png)

感谢

**Comment by myronliu347** [comment]
后续会新开一个项目 muse-ui-toast 做这样的功能

**Comment by zangxx66** [comment]
这个好，我现在手动调用进度条很繁琐

**Comment by jlcool** [comment]
这种自己很好写吧

**Comment by myronliu347** [comment]
https://github.com/museui/muse-ui-toast
https://github.com/museui/muse-ui-loading
