### ISSUE TITLE
mu-select 无法触发click和change事件

### ISSUE THREAD

**Issue by rockeralx** [museui/muse-ui#983]
<mu-select label="select"  v-model="player.ethnicity" @change="roll">
               <mu-option v-for="option,index in ethnicity" :key="option.name" :label="option.name" :value="option.value"></mu-option>
           </mu-select>
我是用html引用js写的，没有用脚手架搭建vue工程

**Comment by myronliu347** [comment]
嗯，先用input 事件吧，这个bug 我会在下个版本修复

**Comment by myronliu347** [comment]
fixed
