### ISSUE TITLE
mu-text-field 输入的内容在文本框失去焦点后消失了

### ISSUE THREAD

**Issue by jlcool** [museui/muse-ui#984]
使用 vue 创建的默认项目里添加使用的
文本框里无法输入内容，一切换内容就消失了

**Comment by myronliu347** [comment]
先确认是否使用 `v-model`，如果仍有错误， 请给出在线的demo

**Comment by jlcool** [comment]
https://pan.baidu.com/s/1qWJkmc3xZjNuIMdor0hfUg 你看这样可以吗

**Comment by jlcool** [comment]
http://59.54.160.83:8184/ 在线地址

**Comment by jlcool** [comment]
http://wx.i234.me:8184/#/

**Comment by myronliu347** [comment]
https://jsfiddle.net/2bty6cq3/

**Comment by jlcool** [comment]
感谢 就是v-model
