### ISSUE TITLE
How I can use single Component without loading full in Nuxt

### ISSUE THREAD

**Issue by hasibul2363** [museui/muse-ui#987]
Thank you very much for awesome UI tool.
I am very new in vue and nuxt.
I am trying to load single element to Nuxt but failed. Can I get possible way to load single module in nuxt.

Nuxt is giving following error. It will be a great help you kindly suggest some way to work with nuxt with a single component approach.

`  nuxt:render Rendering url / +7m
{ H:\sourceControl\Git\hasibul2363\muse-ui\muse\node_modules\muse-ui\lib\styles\components\button.less:1
(function (exports, require, module, __filename, __dirname) { @import "../import.less";
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (H:\sourceControl\Git\hasibul2363\muse-ui\muse\node_modules\muse-ui\lib\Button\index.js:7:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17) statusCode: 500, name: 'SyntaxError' }
`

**Comment by myronliu347** [comment]
I think you should install less-loader

**Comment by hasibul2363** [comment]
Thank you very much for quick response and kind help.
Actually, I have installed less and less-loader
I can configure it in web-pack like following way (for VUE and it works),
`module: {
    rules: [
      {
        test: /\.less$/,
        use: [{
          loader: 'style-loader' // creates style nodes from JS strings
        }, {
          loader: 'css-loader' // translates CSS into CommonJS
        }, {
          loader: 'less-loader' // compiles Less to CSS
        }]
      }`
As I am using nuxt and I am new so i am not sure how to configure it to nuxt. But I have applied it like following way at nuxt.config.js but it produces above error what I already shared with you.
` build: {  
    extend(config, { isDev, isClient }) {
      config.module.rules.push({
        enforce: 'pre',
        test: /\.less$/,
        loader:  'less-loader'
      })
    }

  }`

Can you kindly help how I can configure it so that it works with nuxt

**Comment by hasibul2363** [comment]
@myronliu347 ,
Expecting your help

**Comment by myronliu347** [comment]
Please wait, I am enjoying the Dragon Boat Festival

**Comment by hasibul2363** [comment]
@myronliu347 
Thank you very much for your response. Have a great festival..

**Comment by myronliu347** [comment]
You need  `webpack-node-externals` 

first install 
```bash
npm install webpack-node-externals --save-dev
```

change nuxt.config.js

``` javascript
// nuxt.config.js
const nodeExternals = require('webpack-node-externals');

module.exports = {
    //....
    build: {
        extend(config, { isDev, isClient, isServer }) {
            if (isServer) {
                config.externals = [
                    nodeExternals({
                        whitelist: [/^muse-ui/]
                    })
                ];
            }                 
        }
    }
}
```

**Comment by hasibul2363** [comment]
@myronliu347,
Thank you very much. It is working now. :)
