### ISSUE TITLE
安卓设备 UC、自带浏览器 不兼容 渲染不出来 

### ISSUE THREAD

**Issue by jaweii** [museui/muse-ui#99]
安卓设备 UC、自带浏览器 不兼容 渲染不出来 （安卓5.0.2、UC 10.9.5.729）

谷歌字体、图标，墙内无法访问的，作者要是能传个到公共CDN库中，改成CDN的，对大陆人民就更友好了

**Comment by myronliu347** [comment]
实际项目中可以下载下来直接放在项目中使用。

* [icons 下载地址](https://github.com/google/material-design-icons/tree/master/iconfont)
* [roboto font 下载地址](https://material.google.com/resources/roboto-noto-fonts.html) **需要翻墙**
