### ISSUE TITLE
mu-text-field放到mu-appbar里时在ios手机版safari时样式错误

### ISSUE THREAD

**Issue by jlcool** [museui/muse-ui#991]
https://jsfiddle.net/74xs1onj/2/

**Comment by myronliu347** [comment]
具体使用方面还是需要一些自定义一些样式的，像这样：
https://jsfiddle.net/74xs1onj/15/

后续我也会考虑下关于这个组件嵌套使用的问题

**Comment by jlcool** [comment]
@myronliu347 您好，是错位的问题，问题还是存在
![_20180619084831](https://user-images.githubusercontent.com/381375/41569599-252d5368-739e-11e8-9927-805c582ff3ab.jpg)

**Comment by myronliu347** [comment]
https://jsfiddle.net/74xs1onj/18/
