### ISSUE TITLE
这个图标有问题add_photo_alternate

### ISSUE THREAD

**Issue by jlcool** [museui/muse-ui#995]
https://jsfiddle.net/08mobzy6/

**Comment by myronliu347** [comment]
最新版的 material icon 似乎已经解决了 ，

https://jsfiddle.net/08mobzy6/1/

https://github.com/google/material-design-icons

**Comment by suguoyao** [comment]
我也遇到这个问题，请问如何解决？
当前版本"muse-ui": "^3.0.1"
