### ISSUE TITLE
mu-carousel 组件没有吗？

### ISSUE THREAD

**Issue by kongyufei5039** [museui/muse-ui#997]
mu-carousel 这个组件有吗？如果有怎么使用？

**Comment by myronliu347** [comment]
https://muse-ui.org/#/zh-CN/carousel

v 3.0.0-beta.6 +

**Comment by kongyufei5039** [comment]
Carousel 组件好像不支持按需导入？

**Comment by myronliu347** [comment]
支持

**Comment by kongyufei5039** [comment]
"muse-ui": "^3.0.0-beta.5" 在node_modules/lib下没有 Carousel模块
